### ISSUE TITLE
工单的数据统计该如何做

### ISSUE THREAD

**Issue by AimeeGao** [blackholll/loonflow#10]
ticket_data = models.CharField('工单数据', max_length=10000, default='', blank=True, help_text='可以用于记录当前表单数据，json格式')

所有的工单产生的数据都存在json 字段中了， 那么字段统计的工作该怎么做 
**例如，定义了一个请假的流程，那么领导需要看本月总，平均，请假的时长该如何做？**

**Comment by blackholll** [comment]
1.这个表里面ticket_data记录的是历史状态下的所有数据。 用于排查每个人在不同状态处理工单的时候修改哪些工单信息。
2.你的需求可以这样：
请假天数是配置在自定义字段里面的，所以会保存到TicketCustomField表中。你可以去这个表里面找到每个请假单的请假天数。请假单的发起时间在TicketRecord表中。

**Comment by blackholll** [comment]
@AimeeGao 问题解决了么

**Comment by yslhzj** [comment]
![image](https://user-images.githubusercontent.com/29890756/56944463-0793d880-6b56-11e9-8781-69706460507e.png)

原始的流程图如上所示, 刚刚是假设未来的需求功能点

**Comment by blackholll** [comment]
@yslhzj 图贴错issue了吧 ，不是这个issue
