### ISSUE TITLE
请问建立流转时，条件表达式中可参与判断的字段有那些？

### ISSUE THREAD

**Issue by winvip8** [blackholll/loonflow#102]
![image](https://user-images.githubusercontent.com/10652628/77301422-9b503380-6d2a-11ea-946d-2dbec9795c75.png)

**Comment by blackholll** [comment]
支持的字段: 工单的基础字段(apps/ticket/models.py/TicketRecord 以及 apps.loon_base_model. BaseModel)+ 该工作流的所有自定义字段
支持的运算: datetime标准库的运算(因为loonflow在执行条件表达式计算之前import了datetime), time标准库的运算(因为loonflow在执行条件表达式计算之前import了time), 无需import库的内置运算(如+,-,*,/,==,!=,>,<等)
