### ISSUE TITLE
建议表单自定义字段新增“不允许重复值”（布尔值）属性

### ISSUE THREAD

**Issue by children1987** [blackholll/loonflow#103]
背景：
有一些字段，希望全局唯一，如：“回款单ID”，使其全局唯一目的是不希望一个“回款单”被用多次；再如“发票编号”，使其全局唯一目的是不希望一个发票被报销两次。

具体功能：
创建工单或执行某个流转后，loonflow后台检测所有“不允许重复值”的字段，如果DB中已有提交值，则返回一个错误码。

**Comment by blackholll** [comment]
说一下我们在用的一些类似的场景：
1.应用发布审批流程: 有些特殊应用是不需要测试审批的。我们的做法是这个配置是保存在发布系统的， 发布系统调用工单系统创建工单时传一个属性：是否需要测试审批， 然后流程里面通过这个属性来条件判断到哪个状态
2.服务器账号申请: 跨部门申请账号，需要应用所属部门的技术负责人审批。我们的做法是调用工单系统接口之前先计算是否跨部门， 作为一个自定义字段传进来新建工单， 然后条件流转里面通过这个属性来做条件流转
3.创建测试环境: 检测需求id是否合法，如果不合法，直接不调用工单系统的接口，直接返回错误
等等

总结来说，很多逻辑应该放到调用方中实现。你的场景，前端提交到调用方后端的时候可以做这个判断(如果自己保存了工单基础表，可以查自己的表，如果没有保存，可以直接操作loonflow的数据来判断)。 当然是否整合到loonflow中需要做权衡，针对这个需求，我认为应该做到调用方逻辑中

**Comment by children1987** [comment]
首先感谢如此耐心的回复，通过这几个例子，我深刻理解了你想表达的核心思路：loonflow只做共有逻辑，不做具体业务的特有逻辑。
同时，我也明白，这个功能放在调用方肯定是能实现的。
只是我仍然认为“不允许重复值”确实是一个公有逻辑。如果loonflow支持，那么很多场景下，只需要简单的配置即可，调用方就不用再做重复的开发。
再举一例：立项申请时，申请人需要命名一个全局唯一的“项目名称”以便于内部沟通时无二异性。这是只要对“项目名称”勾选“不允许重复值”即可

**Comment by blackholll** [comment]
在loonflow做的话能实现的逻辑有限，实际需要的可能并不只是不能重复，如果后续要这个字段做其他校验，必须得做在调用方， 那么两边分别写校验逻辑就不太合适了。
你举的“立项申请”，你的调用方应该是一个类似项目管理的系统，项目管理系统本身就应该保证项目名称和项目标识的唯一性，填写申请表单时候可以很方便的检查是否重复。此外项目管理系统中可能还会要求项目名称符合一定的规则如必须以业务线名称开头(这个逻辑肯定是做到项目管理系统中的)、如项目名称长度必须小于20个字符等等
对于“发票编号”，你的报销系统可能还得校验发票编号的合法性(如是否伪造的编号)
还有你可能需要校验发票的开票日期是在最近三个月内的。也就是说如果实际用户开始考虑不能重复时，可能他马上就需要开始做其他校验的功能。
不允许重复 确实会有需求，但是我觉得这个公有属性通用程度不够，将不是特别公用的功能写到loonflow会导致使用成本很高, 利大于弊.
非常欢迎继续讨论  😄

**Comment by children1987** [comment]
确实可能还有其它个性化的检验。到时就不得不在调用端做检验了。
可loonflow提供这个功能的话，因为“不允许重复”的默认值为“否”，所以并不会增加使用成本啊。

**Comment by children1987** [comment]
远程视频沟通结论：此功能暂不合入主干。
我们将在应用方系统实现此功能。
