### ISSUE TITLE
目前的流程配置好像并不支持并行流程的配置，是否考虑支持？

### ISSUE THREAD

**Issue by forevergao** [blackholll/loonflow#105]
比如有这样一类流程，目前貌似不能进行配置,流程图如下：
..     /B-E\  
A-C---G-END
..     \D-F/
是否考虑支持？如何支持比较好？

**Comment by blackholll** [comment]
使用子工作流 子工单的方式实现，如图:
![image](https://user-images.githubusercontent.com/6269605/77540462-17d74380-6ede-11ea-93a7-8bb89a1ad66f.png)

**Comment by yanxiaofei** [comment]
在“子工创建中”，如何设置参数呢？如何激活工作流B和工作流C？在哪个地方写父工单ID和状态ID？在“相关人员处理中”这一步，如何关联工作流B和C？工作流B和C结束后，如何与工作流A衔接呢？感谢！

**Comment by yanxiaofei** [comment]
@blackholll 能否给一个并行工作流的demo示例。感谢。

**Comment by blackholll** [comment]
> 在“子工创建中”，如何设置参数呢？如何激活工作流B和工作流C？在哪个地方写父工单ID和状态ID？在“相关人员处理中”这一步，如何关联工作流B和C？工作流B和C结束后，如何与工作流A衔接呢？感谢！

子工单创建中(hook/脚本)。 这个状态下配置一个hook或者脚本， 这个hook及脚本的左右就是调用loonflow的接口创建子工单(建见文档中的创建工单接口，传当前工单的id以及需要关联子工单的状态id).  
每个工单到达结束状态时候 loonflow都会检测当前工单是否是某个工单的子工单，如果是子工单则会检测其他子工单是否已经结束，如果全部子工单都结束，那么会自动触发父工单往下一步流转
