### ISSUE TITLE
请问要获取我审批过的记录，这个地方应该如何调用API？

### ISSUE THREAD

**Issue by winvip8** [blackholll/loonflow#106]
![image](https://user-images.githubusercontent.com/10652628/77719442-36ddee80-7020-11ea-8773-0129a64e03c3.png)

**Comment by winvip8** [comment]
我想在这里加个关键字获取我审批过的单，大家觉得如何 ！

**Comment by blackholll** [comment]
看文档：
0.1.x: https://loonflow.readthedocs.io/
0.3.x: https://github.com/blackholll/loonflow/wiki/0.3.x%E6%96%87%E6%A1%A3#%E5%B7%A5%E5%8D%95%E7%9B%B8%E5%85%B3%E6%8E%A5%E5%8F%A3

**Comment by blackholll** [comment]
r1.0.0正式版已支持
