### ISSUE TITLE
创建工作流创建人被默认为admin，并不是我自己的账号

### ISSUE THREAD

**Issue by hyperwd** [blackholll/loonflow#11]
![qq 20181031160049](https://user-images.githubusercontent.com/5171317/47773870-6521a680-dd26-11e8-859e-601a90152d7d.png)

**Comment by blackholll** [comment]
models中设置了default导致的。 小问题。准备发现其他问题后再一起修复

![image](https://user-images.githubusercontent.com/6269605/47774030-d8c3b380-dd26-11e8-96a7-a419ebd5bba7.png)

**Comment by blackholll** [comment]
fixed:
https://github.com/blackholll/loonflow/commit/4b2459da8029604d3fda3eb11ca1fe45ef4b8095
