### ISSUE TITLE
附件建议用“text_value”而非当前的“char_value”

### ISSUE THREAD

**Issue by children1987** [blackholll/loonflow#111]
![image](https://user-images.githubusercontent.com/9018733/78867739-2c861080-7a74-11ea-833a-273f2026fff6.png)
这里用 “char_value” 而非 “text_value”是出于什么考虑？
建议改为 “text_value” 以避免多个附件、url又长时，长度不够用的问题

**Comment by blackholll** [comment]
重复了   #113
