### ISSUE TITLE
为了方便定制（如，在评论中存多个图片的url），建议把如下2个字段改为 TextField

### ISSUE THREAD

**Issue by children1987** [blackholll/loonflow#113]
1.	TicketFlowLog().suggestion
由 CharField 改为 TextField
 
![image](https://user-images.githubusercontent.com/9018733/78958207-0450ed00-7b1a-11ea-9e9a-7afc6423ce6f.png)

2.	附件采用的存储字段变更
char_value -> text_value
 
![image](https://user-images.githubusercontent.com/9018733/78958217-087d0a80-7b1a-11ea-9530-2e44faa1536a.png)

**Comment by blackholll** [comment]
suggestion和附件正常情况也不会很长吧(目前是1000的， 按照一个图片或者附件url100个字符，也可以保存10个图片链接了)。  特殊情况自己改下长度是不是就可以了。  
改这个的话，旧版本升级还需要dml处理。 你觉得呢？

**Comment by children1987** [comment]
长度1000迟早是个隐患啊。。。。

**Comment by blackholll** [comment]
1.1版本中调整。  历史版本，如果大家遇到长度问题，自己修改数据库表结构中长度吧
