### ISSUE TITLE
“hook配置中wait为true时”--是不是写反了？是不是应该是wait为false时？

### ISSUE THREAD

**Issue by children1987** [blackholll/loonflow#114]
https://loonflow.readthedocs.io/zh_CN/r1.0.1/api_docs/ticket/#id17
“以触发loonflow中工单状态的流转(当hook配置中wait为true时，无需回调，hook发出后会立即触发流转)。”——是不是写反了？是不是应该是wait为false时？

**Comment by blackholll** [comment]
fixed in r1.0.2's doc
