### ISSUE TITLE
建议ticket创建、处理的全过程放到一个事务里

### ISSUE THREAD

**Issue by children1987** [blackholll/loonflow#121]
建议的原因：ticket创建、处理过程出错时，会产生脏数据，无法保证数据完整性。

另外，当前的返回 flag + result 的模式，建议修改为抛异常的处理方式，这样的好处：
1. 可方便的中断前述事务。
2. 把正常、异常的处理代码分离。

**Comment by blackholll** [comment]
事务的问题 下个大版本会考虑。  但是可能主要是工作流复制，工作流导入的功能会采用事务。
创建工单的话 逻辑比较多， 如果采用事务的话 写起来估计会比较麻烦，到时会权衡下
