### ISSUE TITLE
按照教程配置，出现前端VUE6061页面登录不上，账户密码正常

### ISSUE THREAD

**Issue by nicholas7464** [blackholll/loonflow#133]
教程地址：https://www.cnblogs.com/weavepub/p/11672305.html
问题图片：(https://img-blog.csdnimg.cn/20200611173150968.jpg?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L25pY2hvbGFzX0s=,size_16,color_FFFFFF,t_70)
环境：centos7，已完成守护进程配置，后端，后端后台，前端后台能登陆。
但前端登陆不上，前后端在一台centos7虚拟机上， obtain_token请求的状态码是failed，也看不到log

**Comment by blackholll** [comment]
是配置了ldap么  ldap这块配置去掉呢？

**Comment by nicholas7464** [comment]
配置了ldap，ldap配置去掉也是一样的问题，前端6061页面登录不上

**Comment by nicholas7464** [comment]
这个vue部署后，就出现图片的那个问题

**Comment by blackholll** [comment]
shutongflow后端是否正常启动的？   检查下fronted/config/index.js中 指向的shuongflow后端ip 及端口是否正确
