### ISSUE TITLE
在流转阶段不显示提交人的字段

### ISSUE THREAD

**Issue by wiliiwin** [blackholll/loonflow#134]
工单提交人这里可以看到相关的字段，但是流转到下一个阶段的时候，相关的人看不到相关的字段，但是我这里已经在状态里面加入了展示字段的配置了，现在不知道为什么会不显示。
![8A063A724F1DEE5646A7A2D085533D7A](https://user-images.githubusercontent.com/20533148/85985124-d6928a80-ba1c-11ea-8de4-86f2fced45db.jpg)
<img width="1582" alt="WX20200629-152613@2x" src="https://user-images.githubusercontent.com/20533148/85985144-e4e0a680-ba1c-11ea-8062-4cc076a61a61.png">

**Comment by blackholll** [comment]
属性类型 1、2、3 没有引号
![image](https://user-images.githubusercontent.com/6269605/86005451-43227f00-ba47-11ea-9cf1-3d07a92c0ad7.png)

**Comment by wiliiwin** [comment]
<img width="1407" alt="WX20200629-222027@2x" src="https://user-images.githubusercontent.com/20533148/86017575-c4354280-ba56-11ea-96f1-ae70ceef2d63.png">
现在是显示了字段了，但是字段的内容却没有显示，但是发起人确实是添加了相关的内容的

**Comment by blackholll** [comment]
loonflow的管理后台  工单干预 里面打开工单详情看下

**Comment by wiliiwin** [comment]
工单干预 是在哪里 没有找到

**Comment by blackholll** [comment]
![image](https://user-images.githubusercontent.com/6269605/86064396-88729b00-ba9f-11ea-8803-4341eea969f6.png)

**Comment by wiliiwin** [comment]
<img width="1395" alt="WX20200630-092909@2x" src="https://user-images.githubusercontent.com/20533148/86072452-2c664180-bab4-11ea-9fe2-b393d9918490.png">
什么都没有显示，这个是啥原因了

**Comment by blackholll** [comment]
1.工单管理中没显示字段是因为管理员登录的管理后台，管理员不是工单的当前处理人， 展示的字段是根据工作流编辑中的展现表单来显示的。你把工作流编辑记录里面的展现表单配置下
![image](https://user-images.githubusercontent.com/6269605/86073606-ad263d00-bab6-11ea-89ae-c7b3bd1e2c4c.png)

2.如果步骤1配置后，展示了字段但是字段的值是空， 说明提交的时候字段就没保存。 那么检查下初始状态(状态属性为初始状态的那个状态) 里面的表单字段是否配置错了，导致loonflow并不会保存提交上了的值

**Comment by wiliiwin** [comment]
我检查了下 字段是没有问题的，这些字段我都是复制粘贴过来的，就怕出现错误。
["shopping_name","appid","work_type","discover_system","launch_dep","question_module","comment"]
<img width="978" alt="WX20200630-095930@2x" src="https://user-images.githubusercontent.com/20533148/86074483-a8fb1f00-bab8-11ea-8287-a76e80d5c6f4.png">


{"shopping_name":1,"appid":1,"work_type":1,"discover_system":1,"launch_dep":1,"question_module":1,"comment":1}
<img width="988" alt="WX20200630-100039@2x" src="https://user-images.githubusercontent.com/20533148/86074493-b0222d00-bab8-11ea-92d5-ad7c1ecaf0d7.png">

**Comment by blackholll** [comment]
1是只读啊。 后端不保存的。  需要用2必填 或者3可选

**Comment by wiliiwin** [comment]
已经解决谢谢大佬的恢复
