### ISSUE TITLE
loonflow是否可以实现下拉菜单的级联操作

### ISSUE THREAD

**Issue by wiliiwin** [blackholll/loonflow#135]
<img width="1538" alt="WX20200701-092804@2x" src="https://user-images.githubusercontent.com/20533148/86192892-330cbb80-bb7d-11ea-8ff5-fe5bdb51704d.png">

1、是否可以实现通过选择1，然后级联展示出2 对应的选项。

2、是否可以实现通过1 选择不同的选项，提交给不同的人员，其他人员不会收到相关的工单

3、还有一个就是是否可以实现流转到下一个阶段之后，如果处理人发现这个订单不是自己的，他是否可以进行把工单流转到指定的用户的

**Comment by blackholll** [comment]
1. 这种属于个性化需求， 管理后台配置字段时候加个标签(和前端约定好格式)，然后前端展示表单的时候 根据这个标签特殊处理
2.使用条件流转，不同的条件达到不同的状态，每个状态设置不同的处理人。 target_state_id是你配置的状态，需要到哪个状态就是哪个状态的id
3.直接转交就行

**Comment by wiliiwin** [comment]
<img width="1078" alt="WX20200701-095751@2x" src="https://user-images.githubusercontent.com/20533148/86194563-5f2a3b80-bb81-11ea-98b3-73f00f253c07.png">
<img width="983" alt="WX20200701-095734@2x" src="https://user-images.githubusercontent.com/20533148/86194574-6c472a80-bb81-11ea-8559-b7cc7be91e2e.png">
[{"expression":"{question_module} = 1", "target_state_id":14},{"expression":"{question_module} = 2", "target_state_id":15}] 
我指定了条件，但是并没有实现不同的模块不同的开发人员看到，不是这个模块的人也一样可以看到

**Comment by wiliiwin** [comment]
[{"expression":"{question_module} == 1", "target_state_id":14},{"expression":"{question_module} == 2", "target_state_id":15}]

问下这个question_module 这里的等号后面的值 ，是根据自定义字段的
{"1":"商品","2":"订单、支付","3":"活动","4":"ERP 推单","5":"门店助手","6":"店铺、模板、提审","7":"用户、优惠券","8":"企业微信(内购、社群)"}
这里的key吗？

**Comment by blackholll** [comment]
key。 另外因为是字符串 所以条件表达式中你也需要[{"expression":"{question_module} == '1'", "target_state_id":14},{"expression":"{question_module} == '2'", "target_state_id":15}]

**Comment by wiliiwin** [comment]
![image](https://user-images.githubusercontent.com/20533148/86219612-0aa0b380-bbb5-11ea-9a1e-dd1b1f2ad1e2.png)
在后端的工单管理可以看到是分配对应的人员了，但是相关人员在前端登录之后看不到工单
![image](https://user-images.githubusercontent.com/20533148/86219763-358b0780-bbb5-11ea-8422-b8fbb95c3507.png)
并且在所有工单里面看到的如下图，显示流程走到的是商品研发处理，并不是活动研发人员处理，所有的处理都显示出来了，这个好像不太符合实际情况
![image](https://user-images.githubusercontent.com/20533148/86219862-5e130180-bbb5-11ea-9ce2-995f910596ee.png)

**Comment by blackholll** [comment]
shutongflow 和workflowdemo  分别是vue及bootstrap版本。 会有些问题，需要靠大家一起改进(我暂时没时间去改这两个demo, 我主要精力会放在改进loonflow)。  
shutongflow 和workflowdemo在某些情况下会出现step图中状态显示不一样。 
有问题的时候 多看看loonflow的管理后台， 管理后台中工单数据会比较准确。
当前处理人类型是7的问题 ，请检查下状态的处理人设置是否正确， 可以贴出你现在的流程图以及下个状态的参与人设置

**Comment by wiliiwin** [comment]
感谢大佬的回复
