### ISSUE TITLE
后台报错，流程显示不出来了

### ISSUE THREAD

**Issue by 397334469** [blackholll/loonflow#136]
![image](https://user-images.githubusercontent.com/51410244/86419472-cffa6080-bd05-11ea-9a41-277f0a8fcc47.png)
![image](https://user-images.githubusercontent.com/51410244/86419496-e7d1e480-bd05-11ea-8ab7-1f9e958286c6.png)

**Comment by blackholll** [comment]
1.查看loonflow日志，看是否有报错
2.查看浏览器控制台network中workflow列表的请求返回的内容是啥
3.”用户及权限“ -”调用权限“中的配置看下

**Comment by 397334469** [comment]
![image](https://user-images.githubusercontent.com/51410244/86431288-03011c00-bd27-11ea-9e33-214db844430b.png)

![image](https://user-images.githubusercontent.com/51410244/86431195-b4538200-bd26-11ea-879c-ef6c6711380b.png)

**Comment by 397334469** [comment]
上周是正常的，昨天打开想编辑就不行了。

**Comment by 397334469** [comment]
找到问题，注释了这行，就显示不出来。
![image](https://user-images.githubusercontent.com/51410244/86432642-08606580-bd2b-11ea-9207-fa0417023c9c.png)
