### ISSUE TITLE
shutongflow  显示页面不正常

### ISSUE THREAD

**Issue by kyriefly** [blackholll/loonflow#137]
![image](https://user-images.githubusercontent.com/66997396/86510013-dfb99800-be1e-11ea-816f-5c2f2f2f54ef.png)
cd /opt/shutongflow/fronted
npm install . 
老是报错 
npm 版本高于5.6  源码安装的

![image](https://user-images.githubusercontent.com/66997396/86510071-4b036a00-be1f-11ea-9da8-c0092dacb018.png)

npm dudit fix 之后 还是报错
![image](https://user-images.githubusercontent.com/66997396/86510140-bea57700-be1f-11ea-9a56-dae8cc3ae8d5.png)

**Comment by blackholll** [comment]
shutogflow的前端默认启动端口是6061， 后端6062端口。 
前端npm run dev启动后通过6061端口访问
记得shutongflow前后端，  loonflow都需要启动
