### ISSUE TITLE
shutongflow 输入用户登录进去之后  页面显示403 如下

### ISSUE THREAD

**Issue by kyriefly** [blackholll/loonflow#138]
![image](https://user-images.githubusercontent.com/66997396/86516197-17d9ce80-be51-11ea-83a1-43646c970fdd.png)

**Comment by blackholll** [comment]
shutongflow的配置了DEFAULT_AUTHENTICATION_CLASSES，不会检验csrf的。 你改过代码么

**Comment by kyriefly** [comment]
没有改配置文件   就按照文档做的 改了 settings里面的数据库名称， 还有调用权限  代码 是没动的。

**Comment by blackholll** [comment]
你登录的确实是shutongflow么？  shutongflow和loonflow分别是如何启动的， 端口、ip分别是什么，访问的是什么ip、什么端口

**Comment by kyriefly** [comment]
确定是啊&nbsp;&nbsp;
&nbsp;进入虚拟环境之后 启动的啊。&nbsp;
loonflow启动命令是 python manger.py runserver 0.0.0.0:6060
shutongflow 是上面命令加6062端口
访问的是虚拟机自己配的ip 端口6060
前端是没有问题的&nbsp; 工作流也创建了。
shutongflow 登录页面都出来了&nbsp; 输入用户跟密码就抱那个错



---原始邮件---
发件人: "blackholll"<notifications@github.com&gt;
发送时间: 2020年7月8日(周三) 晚上6:47
收件人: "blackholll/loonflow"<loonflow@noreply.github.com&gt;;
抄送: "kyriefly"<676893124@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [blackholll/loonflow] shutongflow 输入用户登录进去之后  页面显示403 如下 (#138)




 
你登录的确实是shutongflow么？  shutongflow和loonflow分别是如何启动的， 端口、ip分别是什么，访问的是什么ip、什么端口

**Comment by blackholll** [comment]
登录界面截图，  浏览器控制台中 点击登录后 发起的请求的请求参数以及返回值截图看下

**Comment by kyriefly** [comment]
> 登录界面截图，浏览器控制台中单击登录后发起的请求的请求参数以及返回值截图看下
![image](https://user-images.githubusercontent.com/66997396/87029095-3b669580-c212-11ea-9e3f-d5c90f15cbe2.png)
![image](https://user-images.githubusercontent.com/66997396/87029362-a1531d00-c212-11ea-9bd9-d365c6937908.png)
![image](https://user-images.githubusercontent.com/66997396/87029480-cfd0f800-c212-11ea-8ad8-1e01dc3f9112.png)

**Comment by blackholll** [comment]
shutongflow分为前端(vue.js)和 后端两部分（django）， 仔细看shutongflow的文档。  
分别启动前后端后，访问前端的入口地址，默认是6061端口

**Comment by kyriefly** [comment]
已经解决  谢谢
