### ISSUE TITLE
是否有支持子表单的计划？若有，我们团队可贡献代码，若无，我们只能自己维护独立分支了。

### ISSUE THREAD

**Issue by children1987** [blackholll/loonflow#139]

**Comment by blackholll** [comment]
通过一个自定义字段+标签(标签中可以定义有哪些字段)，然后前端根据这个字段特殊处理

**Comment by forevergao** [comment]
标签字段长度太短了，才100字节，建议弄长一些。否则稍微复杂点的标签就装不下了。

**Comment by blackholll** [comment]
> 标签字段长度太短了，才100字节，建议弄长一些。否则稍微复杂点的标签就装不下了。

1.1.0版本中修改。 你先自己直接修改数据中长度吧
