### ISSUE TITLE
loonflow登录 失败

### ISSUE THREAD

**Issue by kyriefly** [blackholll/loonflow#140]
![image](https://user-images.githubusercontent.com/66997396/87110675-2fbeb180-c29a-11ea-8b4e-92c418b544b2.png)
![image](https://user-images.githubusercontent.com/66997396/87110724-49f88f80-c29a-11ea-93f3-d6da8fc5fa3b.png)

![image](https://user-images.githubusercontent.com/66997396/87110786-6e546c00-c29a-11ea-969e-098ece69e22e.png)

最后一步  其他组件都装好了  跨域 包括数据库都有数据， 就是登录不了

**Comment by blackholll** [comment]
这个登录的是shutongflow. 检查下shutongflow的后端是否有启动， 
使用shutongflow你需要启动：shutongflow前端，shutongflow后端， loonflow
详见https://github.com/youshutong2080/shutongFlow

**Comment by liangey** [comment]
同样遇到登录失败问题。前后端都已经启动，端口正常

**Comment by blackholll** [comment]
> 同样遇到登录失败问题。前后端都已经启动，端口正常

初始数据是否有导入？

**Comment by kyriefly** [comment]
肯定导入了啊



---原始邮件---
发件人: "blackholll"<notifications@github.com&gt;
发送时间: 2020年7月13日(周一) 下午5:33
收件人: "blackholll/loonflow"<loonflow@noreply.github.com&gt;;
抄送: "kyriefly"<676893124@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [blackholll/loonflow] loonflow登录 失败 (#140)




  
同样遇到登录失败问题。前后端都已经启动，端口正常
  
初始数据是否有导入？

**Comment by blackholll** [comment]
> 肯定导入了啊
> […](#)
> ---原始邮件--- 发件人: "blackholll"<notifications@github.com&gt; 发送时间: 2020年7月13日(周一) 下午5:33 收件人: "blackholll/loonflow"<loonflow@noreply.github.com&gt;; 抄送: "kyriefly"<676893124@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [blackholll/loonflow] loonflow登录 失败 (#140) 同样遇到登录失败问题。前后端都已经启动，端口正常 初始数据是否有导入？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

检查是否导入成功， 查看下shutongflow的数据库

**Comment by kyriefly** [comment]
数据库早查了 能导进去&nbsp; 看群里大家说&nbsp; 已经好几人遇到这种问题了吧



---原始邮件---
发件人: "blackholll"<notifications@github.com&gt;
发送时间: 2020年7月13日(周一) 下午5:36
收件人: "blackholll/loonflow"<loonflow@noreply.github.com&gt;;
抄送: "kyriefly"<676893124@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [blackholll/loonflow] loonflow登录 失败 (#140)




  
肯定导入了啊
 …
 ---原始邮件--- 发件人: "blackholll"<notifications@github.com&gt; 发送时间: 2020年7月13日(周一) 下午5:33 收件人: "blackholll/loonflow"<loonflow@noreply.github.com&gt;; 抄送: "kyriefly"<676893124@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [blackholll/loonflow] loonflow登录 失败 (#140) 同样遇到登录失败问题。前后端都已经启动，端口正常 初始数据是否有导入？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
检查是否导入成功， 查看下shutongflow的数据库

**Comment by blackholll** [comment]
信息给全点：

**Comment by kyriefly** [comment]
对啊&nbsp; 你要是解决告诉我一声



---原始邮件---
发件人: "liangey"<notifications@github.com&gt;
发送时间: 2020年7月13日(周一) 下午5:14
收件人: "blackholll/loonflow"<loonflow@noreply.github.com&gt;;
抄送: "kyriefly"<676893124@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [blackholll/loonflow] loonflow登录 失败 (#140)




 
同样遇到登录失败问题。前后端都已经启动，端口正常

**Comment by blackholll** [comment]
部署视频先看下：   https://www.ixigua.com/6756220859498627588?id=6760302462663393800&logTag=KYmrre0GUHP7ylhcqUhSK

**Comment by kyriefly** [comment]
好的&nbsp; 感谢。&nbsp; 晚上回去研究一下。



---原始邮件---
发件人: "blackholll"<notifications@github.com&gt;
发送时间: 2020年7月13日(周一) 下午5:45
收件人: "blackholll/loonflow"<loonflow@noreply.github.com&gt;;
抄送: "kyriefly"<676893124@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [blackholll/loonflow] loonflow登录 失败 (#140)




 
部署视频先看下：   https://www.ixigua.com/6756220859498627588?id=6760302462663393800&amp;logTag=KYmrre0GUHP7ylhcqUhSK
