### ISSUE TITLE
工单创建问题

### ISSUE THREAD

**Issue by zzgxgit** [blackholll/loonflow#141]
创建一次工单成功之后，再创建第二个工单，显示创建成功但是工单不显示

访问我的创建还有报错如下：

TypeError: Cannot read property 'workflow_name' of undefined

**Comment by blackholll** [comment]
使用的那个调用方，shutongflow还是workflowdemo?   loonflow的运行日志截图也贴下

**Comment by zzgxgit** [comment]
![image](https://user-images.githubusercontent.com/24837575/87372077-46764880-c5b9-11ea-8d94-d1d4baaa2098.png)

shutongflow

**Comment by zzgxgit** [comment]
![image](https://user-images.githubusercontent.com/24837575/87372248-aa990c80-c5b9-11ea-87c4-1a2d9d023d57.png)

永远都是这一个工单，怎么创建都创建不出来，下面报错 console报错 'workflow_name' undefined

**Comment by blackholll** [comment]
这里两个问题：
1.创建失败，见loonflow的错误日志，是因为条件表达式中配置了days字段, 实际自定义字段中不存在days这个字段，导致流转失败
2.console报错 'workflow_name' undefined(也就是为何工单列表中 业务流转列为空)： shutongflow的前端bug,  自己跟进返回的工单列表中的数据格式，改下
