### ISSUE TITLE
用户权限问题

### ISSUE THREAD

**Issue by zzgxgit** [blackholll/loonflow#142]
shutongflow创建的用户无法管理loonflow的工单
![image](https://user-images.githubusercontent.com/24837575/87380799-d3bf9a00-c5c5-11ea-8584-5c59856788cc.png)
![image](https://user-images.githubusercontent.com/24837575/87380814-dcb06b80-c5c5-11ea-8cd3-7bacc09b382e.png)
所有工单中可以查看到工单，但是我的待办里没有，权限根本不通用呀，shutongflow创建的用户，loonflow里也不会创建，导致无法审批工单。

**Comment by blackholll** [comment]
shutongflow是loonflow的调用方demo. 你可以将shutongflow理解为你自己的运维系统、客服系统、oa系统。 
loonflow只是工作流引擎， 当然两套系统需要各自的用户系统。
你可以根据自己公司的情况将loonflow和shutongflow的用户模块统一成一套(如果你们公司有一套统一的用户认证系统的话)。
loonflow本身之所以单独维护用户系统，是因为工单流转过程中需要知道用户信息(如获取用户所在部门、用户的TL等等)，而  每个公司的使用的用户体系不一样(如用ldap、自研的用户系统、直接使用钉钉用户体系、直接使用企业微信的用户体系、北森的用户体系)。 所以需要loonflow的管理员写个脚本定时自动从自己公司的用户系统中将用户同步过来

**Comment by zzgxgit** [comment]
公司用户体系和loonflow的用户的表结构不一样，如何同步？如何接入ldap？

**Comment by blackholll** [comment]
![image](https://user-images.githubusercontent.com/6269605/87389748-eb088280-c5d9-11ea-903c-18c9cbce3980.png)
表结构不一样就找到对应关系来操作数据库。
关于ldap，qq群文件中有示例。   
不过很多公司ldap中只保存了用户基础信息， 而没有部门，部门审批人等信息。所以接入后还是需要其他方式维护其他信息
