### ISSUE TITLE
流转创建问题

### ISSUE THREAD

**Issue by zzgxgit** [blackholll/loonflow#143]
![image](https://user-images.githubusercontent.com/24837575/87402685-7ee44980-c5ee-11ea-8065-928cf9b6a196.png)
弹窗gou勾选上之后，但是页面还是显示false

**Comment by blackholll** [comment]
确实是个bug, 我周末修复下。
目前这个属性， 两个调用方demo：shutongflow和workflowdemo均未支持。需要自己在前端实现

**Comment by blackholll** [comment]
fixed in r1.0.10
