### ISSUE TITLE
流程配置问题

### ISSUE THREAD

**Issue by zzgxgit** [blackholll/loonflow#144]
问题1：大佬，可不可以给我一套配置好的流程，sql，包括部门及用户的配置，我这边用shutongflow，前后数据库的用户同步了，但是我使用开发账号审批不了我的工单，我设置的审批人就是开发账号的。
![image](https://user-images.githubusercontent.com/24837575/87496902-0c737800-c687-11ea-8a82-e990067cea21.png)
![image](https://user-images.githubusercontent.com/24837575/87496937-1bf2c100-c687-11ea-9fca-0284b7b8dc38.png)
![image](https://user-images.githubusercontent.com/24837575/87497035-4cd2f600-c687-11ea-8436-60f10b2ebf86.png)
![image](https://user-images.githubusercontent.com/24837575/87497091-6f650f00-c687-11ea-9616-3e755faadf3c.png)
问题2：流水号，没有前缀。

**Comment by YuZongYangHi** [comment]
Please watch the document carefully, the document is very clear

**Comment by blackholll** [comment]
1.点开后无法操作就说明当前处理人不是他了，  看下loonflow管理后台中的工作流配置。另外也可以看下loonflow管理后台的工单管理下打开工单详情看下当前状态是否正确
2.调用权限这里配置下工单前缀
![image](https://user-images.githubusercontent.com/6269605/87559932-7c1c4e00-c6ed-11ea-8b05-622445daa2e1.png)
