### ISSUE TITLE
工单审批过程如何显示上一步提交的内容

### ISSUE THREAD

**Issue by zzgxgit** [blackholll/loonflow#145]
工单审批过程如何显示上一步提交的内容

![image](https://user-images.githubusercontent.com/24837575/87624379-3ba6e980-c75a-11ea-9b30-cfcd57159f4d.png)

页面设置了，但是如何获取到前面提交信息的字段的值呢？
![image](https://user-images.githubusercontent.com/24837575/87624310-0b5f4b00-c75a-11ea-90cc-b1496de368fc.png)

**Comment by blackholll** [comment]
看起来是 工单创建的时候 这两个字段没有实际保存成功。
使用loonflow管理后台中工单管理打开工大详情看下是否有内容，  如果没有的话在工单创建页面打开浏览器控制台看下创建工单的时候这两个字段是否作为请求参数来请求后端了

**Comment by zzgxgit** [comment]
工单详情中没有内容。
![image](https://user-images.githubusercontent.com/24837575/87634029-1670a600-c76f-11ea-8019-bbc68c0ed3d0.png)
这种情况，应该如何处理？

**Comment by blackholll** [comment]
这里没有显示详情是因为：
1.工作流配置里面没有配置展现表单 或 当前状态的表单字段配置(如果当前用户没有处理权限则展现字段已工作流配置中为准，是当前处理人则以当)。  先配置下
2.怀疑是shutongflow是不是有问题，   你可以吧初始状态中的表单字段设置将 这两个字段改成必填再试下是否会报错。

另外创建工单页面  打开浏览器控制台  看下点击提交时，ajax请求中传给后端的参数

**Comment by zzgxgit** [comment]
我的配置如下，您看下是我配置上的问题吗？
![image](https://user-images.githubusercontent.com/24837575/87634862-af53f100-c770-11ea-950a-2fac25e57e7c.png)
![image](https://user-images.githubusercontent.com/24837575/87634959-dd393580-c770-11ea-9742-bf11789f9e92.png)
![image](https://user-images.githubusercontent.com/24837575/87635049-04900280-c771-11ea-9c3f-800801556e70.png)

**Comment by blackholll** [comment]
> 这里没有显示详情是因为：
> 1.工作流配置里面没有配置展现表单 或 当前状态的表单字段配置(如果当前用户没有处理权限则展现字段已工作流配置中为准，是当前处理人则以当)。 先配置下
> 2.怀疑是shutongflow是不是有问题， 你可以吧初始状态中的表单字段设置将 这两个字段改成必填再试下是否会报错。
> 
> 另外创建工单页面 打开浏览器控制台 看下点击提交时，ajax请求中传给后端的参数



"""创建工单页面 打开浏览器控制台 看下点击提交时，ajax请求中传给后端的参数"""

**Comment by zzgxgit** [comment]
这里是请求
![image](https://user-images.githubusercontent.com/24837575/87635543-d4952f00-c771-11ea-896a-e94d656e3c47.png)

**Comment by blackholll** [comment]
shutongflow 工单详情页面，看下浏览器控制台中请求工单详情的那个请求 中返回内容中data.field_list中全量数据截图看下。

**Comment by zzgxgit** [comment]
工单详情页面的数据只有这些
![image](https://user-images.githubusercontent.com/24837575/87636639-a31d6300-c773-11ea-98e3-d2e628a4c294.png)

**Comment by blackholll** [comment]
看工单详情的那个请求，不是工作流的

**Comment by zzgxgit** [comment]
看到了，总共三个数据，就第一个时间的数据有，其他的数据都是null，这个是什么原因呢？
![image](https://user-images.githubusercontent.com/24837575/87638328-2770e580-c776-11ea-993b-da0aff3d946d.png)

**Comment by zzgxgit** [comment]
看到了，总共三个数据，就第一个时间的数据有，其他的数据都是null，这个是什么原因呢？
![image](https://user-images.githubusercontent.com/24837575/87638328-2770e580-c776-11ea-993b-da0aff3d946d.png)

**Comment by blackholll** [comment]
![image](https://user-images.githubusercontent.com/6269605/87730562-bb849080-c7fa-11ea-9b4f-dfcc27c75624.png)
配置错误了。 “2”改成2
