### ISSUE TITLE
提一个shutongflow代码中的小问题

### ISSUE THREAD

**Issue by zzgxgit** [blackholll/loonflow#147]
浏览器中一直报错"workflow_name" undefined
![image](https://user-images.githubusercontent.com/24837575/87639954-92bbb700-c778-11ea-828a-c1d7eedb4c9d.png)
原因是(ALL.vue\Audit.vue\Myself.vue\Todo.vue)几个组件的代码中内容如下：
![image](https://user-images.githubusercontent.com/24837575/87640183-ed551300-c778-11ea-982a-5d544bc66b15.png)
在提交请求时，发现，workflow_name不在workflow中，所以代码改成params.row.workflow_info.workflow_name即可
![image](https://user-images.githubusercontent.com/24837575/87640242-05c52d80-c779-11ea-8d57-dabe2f2bcdd7.png)

**Comment by blackholll** [comment]
是的 我一直没时间改。 你可以提个pr
