### ISSUE TITLE
拉取工单详情时--用户不存在--报错

### ISSUE THREAD

**Issue by pygodnet** [blackholll/loonflow#148]
![image](https://user-images.githubusercontent.com/43093645/87742016-6fe0df80-c818-11ea-8012-6a14662804f8.png)
![image](https://user-images.githubusercontent.com/43093645/87742035-7d966500-c818-11ea-8d77-56912a8afa75.png)

**Comment by blackholll** [comment]
抱歉 这个issue遗漏了。       
创建工单的用户需要在loonflow中存在， 你可以写个定时任务同步用户信息到loonflow
