### ISSUE TITLE
新建工单时未对--username 做校验

### ISSUE THREAD

**Issue by pygodnet** [blackholll/loonflow#149]
使用系统未注册的用户（随意用户名）可发起工单

**Comment by blackholll** [comment]
loonflow只校验调用源应用是否合法(通过应用的授权，签名算法)，而且也限制了该应用可以创建或者操作的工作流。 
调用应用自己负责用户的有效性

**Comment by pygodnet** [comment]
此方式可能存在问题：用户手动修改headers 中  username 参数，可越权操作

**Comment by blackholll** [comment]
调用关系是：
调用方前端--->调用方后端-->loonflow
用户在调用方前端操作， 所有请求经过你的调用方后端的时候，你的后端需要验证用户的登录状态，识别到用户身份后， 再向loonflow发送请求。
你的后端保障用户身份， loonflow通过签名机制保证了来源调用方的身份
