### ISSUE TITLE
上传附件功能问题

### ISSUE THREAD

**Issue by zzgxgit** [blackholll/loonflow#150]
配置如下：
![image](https://user-images.githubusercontent.com/24837575/87751530-c65a1800-c830-11ea-9860-eb07657f1ab6.png)
我这边配置了上传附件的字段。
但是在状态中，我设置了上传附件的关键字，2的时候是必填
![image](https://user-images.githubusercontent.com/24837575/87751902-ac6d0500-c831-11ea-9749-7fe26d85c28c.png)
但是页面中并没有显示
![image](https://user-images.githubusercontent.com/24837575/87751710-3d8fac00-c831-11ea-87c6-a77fae03c666.png)
当我设置为1，只读的时候，可以看到，但是无任何内容也没有上传的按钮
![image](https://user-images.githubusercontent.com/24837575/87751935-c0186b80-c831-11ea-9e15-d29a993945c9.png)
![image](https://user-images.githubusercontent.com/24837575/87751793-72036800-c831-11ea-8070-00e3a62d0667.png)

**Comment by blackholll** [comment]
shutongflow前端未支持附件类型， 需要自己改下。
实现思路：  前端检测字段类型为附件 则显示一个文件上传的组件， 点击上传选择文件后，上传到自己的后端。 然后提交工单的时候将附件的路径作为这个字段的value 传给后端
