### ISSUE TITLE
loonflow接入LDAP

### ISSUE THREAD

**Issue by zzgxgit** [blackholll/loonflow#152]
大佬，我这边需要接入公司的LDAP，我应该配置在shutongflow还是在loonflow中？我两边都配置了一下，但是发现并没有走ldap，大概是什么原因呢？或者您这边有没有配置的demo，因为我用python写了个脚本获取ldap的数据是没有问题的。

**Comment by blackholll** [comment]
loonflow管理后台目前不支持工单处理， 只是给管理员配置工作流用的。 管理员就个别几个人，没必要配置ldap
shutongflow的话   qq群文件中有人上传了样例，可以参考下
