### ISSUE TITLE
接单功能问题

### ISSUE THREAD

**Issue by zzgxgit** [blackholll/loonflow#153]
想问一下，流程配置好了之后，选择接单，不继续往下走了是什么原因呢？
![image](https://user-images.githubusercontent.com/24837575/88010403-61136900-cb47-11ea-878e-99fe19ff3f99.png)

**Comment by blackholll** [comment]
接单的含义是， 当前是多个，且处理方式设置的是主动接单。 那么需要其中一个人接单后 再进行正常的操作逻辑。
当工单当前需要接单时候， 获取工单可以执行的操作接口会返回“接单”这个操作。 前端在处理这个操作时 不同于正常的操作（同意、拒绝、完成等这些）。 用户点击接单后需要调用loonflow的接单接口。 详情loonflow文档 http://loonflow.readthedocs.io/
当前shutongflow应该没有支持“接单”的功能。你可以自己修改下shutongflow，然后提交pr
