### ISSUE TITLE
工单结束后无法看到工单详情

### ISSUE THREAD

**Issue by zzgxgit** [blackholll/loonflow#154]
shutongflow工单审批结束后，不管是在我的创建，所有工单，还是我相关的里面，点开工单详情，都无法看到内容。
![image](https://user-images.githubusercontent.com/24837575/88018583-9bd2cc80-cb5a-11ea-83d4-5fc1a67cfb57.png)
报错如下:
![image](https://user-images.githubusercontent.com/24837575/88018621-b016c980-cb5a-11ea-8eaa-f0ae45267b96.png)

**Comment by blackholll** [comment]
1. 先检查下字段配置。 字段展示逻辑见  #37  
2. 检查浏览器中打开详情页面时  各ajax请求返回的内容。

**Comment by zzgxgit** [comment]
工单的内容可以显示出来了，但是操作日志无法显示，一直有一个报错。
![image](https://user-images.githubusercontent.com/24837575/88023723-1fdd8200-cb64-11ea-9e3e-25f4d5f1f4ab.png)

**Comment by blackholll** [comment]
看下loonflow的日志， 看是否有报错       https://loonflow.readthedocs.io/zh_CN/r1.0.9/q&a/  搜索“如何查看日志”

**Comment by pyang30** [comment]
这个问题是因为shutongflow会判断transation的长度是否>0， 然后根据是否大于0显示相应的按钮。但是用户第一步创建工单后，自己是没有任何操作权限，loonflow没有返回transation这个变量，前端拿到的就是null。

改动措施：
    loonflow的app/ticket/view.py文件中   class TicketTransition(LoonBaseView): 中的get函数中倒数第二行，value=result.get('transition_dict_list')), ''  改成value=result.get('transition_dict_list', [])), '' 即可，设置返回一个transation长度为空的数组。

@blackholll @zzgxgit

**Comment by blackholll** [comment]
该这里合适点， 下个版本我改下
![image](https://user-images.githubusercontent.com/6269605/89432448-b8365200-d773-11ea-9796-020a825e3e38.png)

**Comment by blackholll** [comment]
fixed in [r1.0.11](https://github.com/blackholll/loonflow/releases/tag/r1.0.11)
