### ISSUE TITLE
上级部门作为参与人

### ISSUE THREAD

**Issue by sleeper99** [blackholll/loonflow#155]
如果参与人类型为 "部门", 我想让工单处理人的上级部门作为参与人, 怎样在工作流配置时写参与人字段?

**Comment by blackholll** [comment]
当前不支持直接设置处理人为  创建人的上级部门
你可以添加一个自定义字段，类型为用户。  下个节点的处理人类型设置为工单字段，处理人设置为字段的标识
配置这个字段为初始状态的必填字段
创建工单的时候获取用户上级部门的所有人员，将人员的username逗号隔开作为这个工单字段的值 传给loonflow

**Comment by sleeper99** [comment]
希望工单字段类型可以支持部门而不只是个人, 或者有个接口可以根据部门id获取到部门下所有人
