### ISSUE TITLE
多部门BUG

### ISSUE THREAD

**Issue by sleeper99** [blackholll/loonflow#156]
由于 ticket_base_service 中 "参与人去重复+类型修正" 部分将部门参与人类型改为多人, 部门参与人不支持多个部门

**Comment by blackholll** [comment]
参与人类型设置为部门， 参与人以逗号隔开多个部门的id。在工单流转过程中会获取多个部门下的所有人，将工单处理人类型替换为多人，参与人为部门下所有人。
替换具体的人是为了 提高待办工单列表查询效率

**Comment by sleeper99** [comment]
> 参与人类型设置为部门， 参与人以逗号隔开多个部门的id。在工单流转过程中会获取多个部门下的所有人，将工单处理人类型替换为多人，参与人为部门下所有人。
> 替换具体的人是为了 提高待办工单列表查询效率

![WeChat Screenshot_20200724111320](https://user-images.githubusercontent.com/33992792/88358185-8ea71f00-cda0-11ea-9698-2d7bc71ff922.png)
![WeChat Image_20200724112551](https://user-images.githubusercontent.com/33992792/88358187-91097900-cda0-11ea-89e1-0bb0e8bb882c.png)

**Comment by blackholll** [comment]
fixed in r1.0.10
