### ISSUE TITLE
shutongflow的build后使用nginx访问问题

### ISSUE THREAD

**Issue by zzgxgit** [blackholll/loonflow#157]
shutongflow使用npm build之后出现的dist目录，部署在nginx目录下，正常访问是OK的，一旦刷新页面就会404，这是什么原因呢？
![image](https://user-images.githubusercontent.com/24837575/88264394-42a39e00-ccfe-11ea-8103-148bf8686ade.png)
正常点击都没问题，只要一刷新页面就崩，404，URL和正常访问的URL都是一样的。

**Comment by blackholll** [comment]
试下这个： https://www.google.com/search?q=nginx%E5%88%B7%E6%96%B0%E5%90%8E404&oq=nginx%E5%88%B7%E6%96%B0%E5%90%8E404&aqs=chrome..69i57.5991j0j4&sourceid=chrome&ie=UTF-8
