### ISSUE TITLE
工单列表查询

### ISSUE THREAD

**Issue by tjcaxl** [blackholll/loonflow#158]
建议支持工单列表查询时返回结果能支持带上自定义字段信息，有时需要批量获取工单的自定字段信息，目前得查了工单列表后再逐单查工单详情获取字段信息，来回网络API速度太慢，可以设个类似流转log查询一样的标识，为1时返回自定义字段信息，为0时返回不带

**Comment by blackholll** [comment]
列表接口返回自定义字段的话  性能会非常差，因为自定义字段是单独另外一张表以纵表的形式保存的。
如果列表也需要一些关键信息的话，有以下方法：
1.创建工单的时候将一些字段的信息组合为标题字段，然后调用loonflow创建工单的接口时作为title参数的value。这样就可以根据标题来查询了
2.自己的后端，每个类型的工单建一个张表， 和loonflow的工单id关联， 自己的表 保存工单的所有字段的值。然后自己的后端提供查询列表接口
