### ISSUE TITLE
建议修改支持django3.1的版本

### ISSUE THREAD

**Issue by dkddkk** [blackholll/loonflow#160]
（1）{% load staticfiles%}替换为{% load static%}即可
（2）hook_call_back的by_hook应该设置为True，原函数遗漏。同时希望hook时也能支持超时默认通过的选择

如有可能，请简介一下工作流中，变量是什么作用，能否支持动态的人员审批（比如专家审批，哪些专家，早期是不知道的）

附注：shutong要做如下settings:
JWT_AUTH = { 

     'JWT_ALLOW_REFRESH':  True, 

     'JWT_EXPIRATION_DELTA': datetime.timedelta( hours= 12), #这个可以不要

     'JWT_AUTH_COOKIE': 'token', #这个要

}

**Comment by blackholll** [comment]
1. django3 我看了下除了ASGI支持异步，没啥其他特别的地方。 最近在写loonflow1.1.0版本, 后期深入看下，确定要不要升级django3
2.第二个问题可以说的具体点， 没太明白的意思

关于变量： 
目前支持了创建人，创建人tl。  这两种变量根据工单来确定处理人的(不同的工单创建人、创建人tl是不同的)。
当前需要支持其他变量类型需要自己扩展二次开发。 后续会考虑支持通过hook请求的方式获取处理人(即到达某个状态时候触发hook，根据返回的信息设置工单的处理人)

**Comment by dkddkk** [comment]
（1）支持3.1是为了更多人的方便。比如我现在没用env，安装django到了3.08。改起来也很容易；
（2）hook_call_back是有问题的，by_hook一直为false，执行不下去，无法把流程走到下一步。hook_call_back的参数，不知道如何使用时间节点（比如3天后自动视作审核通过等）

最后，你说了，以后考虑hook请求方式获取处理人。（可以考虑一个特定的hook接口还要同时支持by_time，目前的hook和hook_call_back都不是很合适。）

**Comment by blackholll** [comment]
1. 个人开发多个python项目，每个项目中依赖的包版本(除了django 还有有其他的包)都是不同的，肯定是需要虚拟环境的
2. hook是从celery任务中触发的，见tasks.py中flow_hook_task方法
3.当前支持定时器流转。如果某个流转一直没有触发，超过定时器时间后会自动触发流转
![image](https://user-images.githubusercontent.com/6269605/88683887-e1793180-d126-11ea-830a-fc2a335aad6c.png)
