### ISSUE TITLE
工单详情页bug

### ISSUE THREAD

**Issue by zzgxgit** [blackholll/loonflow#163]
前端使用的shutongflow，点击进入工单详情之后，应该会显示如下三部分内容：
1.业务流程
2.自定义的审批流程
3.操作日志
但是，有时候点击进去，只显示自定义审批流程，业务流程和操作日志都不显示，有的时候不显示操作日志，有的时候不显示业务流程，后端每次都会返回数据，但是前端不显示。
下面几张图所示：
1.全部都能正常显示
![image](https://user-images.githubusercontent.com/24837575/89007606-a0a63600-d33b-11ea-82f5-4811dbdaff23.png)
2.只显示自定义的审批流程，另外两个不显示
![image](https://user-images.githubusercontent.com/24837575/89007645-b4519c80-d33b-11ea-8ec1-808ebcf6960a.png)
3.操作日志不显示
![image](https://user-images.githubusercontent.com/24837575/89007664-c0d5f500-d33b-11ea-89e0-d93a00265d66.png)

报错内容如下：
![image](https://user-images.githubusercontent.com/24837575/89007684-cdf2e400-d33b-11ea-8dd0-ed56de1a015d.png)

数据返回都正常：
![image](https://user-images.githubusercontent.com/24837575/89007768-f8dd3800-d33b-11ea-92e0-d1f44ad34c00.png)

**Comment by pyang30** [comment]
https://github.com/blackholll/loonflow/issues/154#issuecomment-667844756

**Comment by blackholll** [comment]
fixed in [r1.0.11](https://github.com/blackholll/loonflow/releases/tag/r1.0.11)
