### ISSUE TITLE
工单状态字段act_state_id错误

### ISSUE THREAD

**Issue by tjcaxl** [blackholll/loonflow#165]
在执行retreat撤回操作后act_state_id还是1，按帮助说明应该是被撤回状态3

**Comment by blackholll** [comment]
下周末修复。 欢迎提交pr。 

当前pr分支为v1.0.11。

**Comment by blackholll** [comment]
fixed in [r1.0.11](https://github.com/blackholll/loonflow/releases/tag/r1.0.11)
