### ISSUE TITLE
后台管理页面工作流配置页的标题模板和内容模板不能更新

### ISSUE THREAD

**Issue by tjcaxl** [blackholll/loonflow#166]
标题模板和内容模板在变更内容后，再次进入还是显示的默认值，数据库底层已更改。
调试发现在service\workflow\workflow_base_service.py的get_workflow_list函数中，读取工作流配置信息时漏了两个字段信息，补上以下两行后，页面可正常显示变更后的值

title_template = workflow_result_object.title_template,
content_template=workflow_result_object.content_template)

**Comment by blackholll** [comment]
是有问题。  下次发新版本的时候修复

**Comment by blackholll** [comment]
fixed in [r1.0.11](https://github.com/blackholll/loonflow/releases/tag/r1.0.11)
