### ISSUE TITLE
一个流程问题，提交用户的 需要上级领导审批

### ISSUE THREAD

**Issue by net592** [blackholll/loonflow#172]
每个用户提交流程，需要他上级领导审批，这种情况老大建议如何实现？
我可以每次获取提交用户的上级账号，我想的是提交事后，修改改审批，通过接单接口，api/v1.0/tickets/{ticket_id}/accept  设置为上级领导

**Comment by pyang30** [comment]
你多看看文档
https://loonflow.readthedocs.io/zh_CN/r1.0.9/manage/workflow_config/

处理人类型选变量，值是creator_tl，审批人会自动设置成用户所在部门的leader。
前提是你在用户表/部门表中设置正确的部门teamleader关系，这个要你自己用脚本导入。

**Comment by net592** [comment]
感谢感谢，看到有个部门leader ,主要公司组织结构有点庞大，20W多万人数据，关系导入太麻烦，我打算用/api/v1.0/tickets/｛id｝/deliver 每次去指定下提交账号的上级用户，来去操作。

**Comment by blackholll** [comment]
方案一:
将accout_base_service中里面的方法全部改一遍，改成调用公司的接口来获取
方案二:
1.新建一个字段比如创建人TL。 在初始状态配置时候将这个字段设置为必填。
2.调用端前端特殊处理下字段隐藏掉。前端提交工单时，你的后端获取创建人TL信息，作为参数一起调用loonflow的创建工单接口。
3.将下个状态的处理人类型设置为工单字段， 处理人设置为这个字段的字段标识
