### ISSUE TITLE
如何实现子工单循环？

### ISSUE THREAD

**Issue by dkddkk** [blackholll/loonflow#175]
以代码管理为例，假设现在是维护阶段，state_id=4，现在进入子循环：（1）提交bug；（2）代码修改；（3）发布补丁；（4）结束修改。当选择项目维护结束，才能进入下一步。

# 如图
[如图](http://59.53.216.140/images/a.png)

http://59.53.216.140/images/a.png

运维==》子工单循环[（1）提交bug；（2）代码修改；（3）发布补丁；（4）结束修改 ] ==>运维结束

这种循环要怎么做才能利用loonflow的流程的详情功能呢（查看主工单的时候，能看到所有的子工单）

**Comment by blackholll** [comment]
工单列表接口 传父工单id和 状态id，即可以查询到此状态下的所有子工单的列表
