### ISSUE TITLE
撤回操作

### ISSUE THREAD

**Issue by tjcaxl** [blackholll/loonflow#177]
撤回工单后，搜索duty我的处理工单时，还停留在撤回前的状态参与人名下

**Comment by blackholll** [comment]
哪个版本

**Comment by tjcaxl** [comment]
1.0.11发自我的华为手机-------- 原始邮件 --------发件人： blackholll <notifications@github.com>日期： 2020年9月1日周二 23:59收件人： blackholll/loonflow <loonflow@noreply.github.com>抄送： tjcaxl <tjcaxl@163.com>, Author <author@noreply.github.com>主    题： Re: [blackholll/loonflow] 撤回操作 (#177)

哪个版本

**Comment by blackholll** [comment]
撤回工单的逻辑是会将状态回到工单的初始状态，处理人设置为工单的创建人。代码见:
https://github.com/blackholll/loonflow/blob/r1.0.11/service/ticket/ticket_base_service.py#L2413

**Comment by tjcaxl** [comment]
工单详情的参与人信息没错，是做了变更，但有个用户表快速搜索待办工单的，那个里面没改，搜索个人待办时出错发自我的华为手机-------- 原始邮件 --------发件人： blackholll <notifications@github.com>日期： 2020年9月3日周四 23:04收件人： blackholll/loonflow <loonflow@noreply.github.com>抄送： tjcaxl <tjcaxl@163.com>, Author <author@noreply.github.com>主    题： Re: [blackholll/loonflow] 撤回操作 (#177)

撤回工单的逻辑是会将状态回到工单的初始状态，处理人设置为工单的创建人。代码见:

https://github.com/blackholll/loonflow/blob/r1.0.11/service/ticket/ticket_base_service.py#L2413

**Comment by blackholll** [comment]
是的，TicketUser表没改， 我周末抽空修复下

**Comment by blackholll** [comment]
fixed in https://github.com/blackholll/loonflow/releases/tag/r1.0.12
