### ISSUE TITLE
客户端调研获取工单详情接口时，不时会出现Connection reset by peer

### ISSUE THREAD

**Issue by forevergao** [blackholll/loonflow#178]
我在使用流程引擎的时候，由于某个流程配置了一个富文本字段，里面会保存有一些图片信息。（整个字段保存的数据量也不大，大约100K左右。）
当前端调用获取获取工单详情接口 /ticket/<int:ticket_id> 时，会经常性的返回 Connection reset by peer 的错误。

不知道是什么原因，麻烦帮核查一下？

**Comment by blackholll** [comment]
你是python manage.py runserver启动的吧， 这种方式仅供开发调试用的。 生产环境建议用uwsgi+nginx部署
