### ISSUE TITLE
工单查询接口，要对自定义字段值做筛选，要怎么做比较好

### ISSUE THREAD

**Issue by ningyinchuan** [blackholll/loonflow#179]

**Comment by blackholll** [comment]
可以支持 用户选择工单类型后， 允许用户选择自定义字段及字段的值
1.1.0版本将支持

![image](https://user-images.githubusercontent.com/6269605/92388926-a5d07f00-f14a-11ea-8ac0-3f603b21de56.png)


![image](https://user-images.githubusercontent.com/6269605/92388866-8df8fb00-f14a-11ea-8b59-f669ba73a818.png)

**Comment by blackholll** [comment]
对于后端接口来说，就是工单列表接口，新增支持两个参数：custom_field、custom_field_value。 且传了workflow_id参数时这两个参数才有效。
因为不同类型工作流中的自定义字段类型是不同的， 需要根据workflow_id来确定custom_field的字段的类型， 然后去ticket_custom_field表中对应列来搜索

**Comment by ningyinchuan** [comment]
1.1.0版本预计在什么时候更新呢？

**Comment by blackholll** [comment]
争取10月底发布。   你可以在现有接口的基础上修改， 当传了custom_field、custom_field_value、workflow_id参数时， 与ticket_custom_field表做连表查询
