### ISSUE TITLE
负责人  hook

### ISSUE THREAD

**Issue by tjcaxl** [blackholll/loonflow#181]
节点负责人不固定，有逻辑需求，大概就是根据填写表单中的某些字段来判断，指定某一节点的不同的负责人。请问如何实现

**Comment by blackholll** [comment]
方案一:
loonflow的参与人类型支持hook， 当某个状态的参与人设置为hook时，工单到达状态 发起hook请求获取到参与人信息
该方案loonflow尚不支持。 1.1.0版本将支持
方案二:
新建一个自定义字段。如流程为: 发起人创建中--获取处理人中(类型为hook,wait为true. 状态可设置为隐藏【step图中不会显示】，此hook请求的你的后端，这个后端计算出处理人后， 调用loonflow的修改工单字段的接口，前面定义的字段)---负责人处理中(处理人类型为工单字段， 处理人为自定义字段的field_key)。 状态触发hook当前版本已经支持

**Comment by tjcaxl** [comment]
现在采用的是，建了一个自定义字段作为状态处理人提取信息字段，在创建工单时根据已填工单字段信息再填充此新建字段，将改字段在创建时作为工单创建参数一并提交

**Comment by blackholll** [comment]
如果是后端调用loonflow接口直接创建工单(而不是用户在界面上发起的)，这是个不错的办法。    如果是用户在界面提交工单， 那么界面上需要对这个字段做隐藏处理了，不然提交人可以直接制定下个节点的处理人
