### ISSUE TITLE
已建流程上修改字段类型的问题

### ISSUE THREAD

**Issue by tjcaxl** [blackholll/loonflow#182]
![Uploading 2020-09-11_095051.jpg…]()
有这样一种情况，就是流程建好后，实际工单数据也产生了一些后，可能字段属性又会做改变，如单选字段改为多选，但数据库存储不同的值不同类型是放在不同字段的，将单选改为多选后就会造成之前的工单获取该字段数据时为空，值在单选那，多选值是空的。这种改字段属性的可能改动大的是很难兼容，不过如果小改是否可以考虑底层兼容下，如字符类的字段值都放在同一个数据库字段里，不用把字段值类型分得太细，获取时可以再由前端去做这种变更后的兼容处理。
可能您有其它考虑，这里只是我碰到的片面问题的一点需求，看能否解决

**Comment by blackholll** [comment]
分开存的原因见:  #184 

修改字段类型后 自己写个sql操作下吧
