### ISSUE TITLE
celery 运行失败，Redis和Mysql用的不是本地的，是阿里云的RDS是否有影响部署运行？

### ISSUE THREAD

**Issue by wuzheng0709** [blackholll/loonflow#187]
不知道是哪里的问题
celery multi start -A tasks worker -l info -c 8 -Q loonflow –logfile=/localhost/log/logfile.log –pidfile=/localhost/log/pidfile.pid
![image](https://user-images.githubusercontent.com/16788717/94353234-32fb5980-00a1-11eb-9278-a9c1d25a9da9.png)
![image](https://user-images.githubusercontent.com/16788717/94353241-45759300-00a1-11eb-830c-ed965639db33.png)

![image](https://user-images.githubusercontent.com/16788717/94353239-3ee71b80-00a1-11eb-8ecf-2ca70305a427.png)

**Comment by wuzheng0709** [comment]
![image](https://user-images.githubusercontent.com/16788717/94353257-866da780-00a1-11eb-9c92-6b79a24ff88b.png)

**Comment by blackholll** [comment]
cd到代码根目录下执行命令

**Comment by wuzheng0709** [comment]
解决了
