### ISSUE TITLE
按照文档安装成功以后，账号密码不对，登录失败啊

### ISSUE THREAD

**Issue by wuzheng0709** [blackholll/loonflow#188]
因为 我只是想接入一下不打算二次开发，但一直没找到登录密码。 本来想尝试改一下源码密码验证、 、make_password(password, None, 'pbkdf2_sha256')  我看代码里的密码是这样生成的？那岂不是每次生成的密码都不一样？所以到底是怎么验证的呢？

**Comment by blackholll** [comment]
用户/密码：   admin/ loonflow123
我也记不太清楚了。  如果不对的话，可以通过命令创建下：
修改manage.py中配置文件为你正在使用的配置文件， 然后python manage.py createsuperuser来创建超级管理员账号和密码

**Comment by wuzheng0709** [comment]
就是你写的这个密码
