### ISSUE TITLE
destination_participant_list为空

### ISSUE THREAD

**Issue by yutao668** [blackholll/loonflow#189]
![image](https://user-images.githubusercontent.com/58452208/94507812-231b7b00-0243-11eb-80d3-b6acc5d61fd7.png)

**Comment by blackholll** [comment]
是bug. 你方便的话  可以提交个pr到分支 v1.0.12

**Comment by yutao668** [comment]
我们马上上线要用， 什么时候会发布v1.0.12

**Comment by blackholll** [comment]
国庆期间，之前有几个小问题，一起改下。
你可以提交pr到v1.0.12分支，  然后你直接用v1.0.12分支的代码部署

**Comment by yutao668** [comment]
能不能给我帐号赋下权限提交

**Comment by blackholll** [comment]
fork到自己账户下， 然后提交pr. 具体操作google下

**Comment by blackholll** [comment]
fixed in https://github.com/blackholll/loonflow/releases/tag/r1.0.12
