### ISSUE TITLE
代码中id没有定义

### ISSUE THREAD

**Issue by JakLiao** [blackholll/loonflow#19]
https://github.com/blackholll/loonflow/blob/a10b9a8605622a31cd01418f86f77cabd291f6f4/service/workflow/workflow_state_service.py#L59

这里应该是workflow_states_object的id字段

**Comment by cdz620** [comment]
这个已经反馈过了，不懂作者处理了没有

**Comment by blackholll** [comment]
我现在处理下

**Comment by blackholll** [comment]
[fixed](https://github.com/blackholll/loonflow/releases/tag/r0.2.7)
