### ISSUE TITLE
调用接口时报错 app_name in request header is unauthorized

### ISSUE THREAD

**Issue by uzi6666666** [blackholll/loonflow#190]
你好，我在调用API时，报了如下错误
{"code": -1, "msg": "permission check fail\uff1aAppname:app_name in request header is unauthorized, please contact
administrator to add authorization for appname:app_name in loonflow", "data": []}
请问这个app_name 代表什么，需要如何更改，感谢~~

**Comment by blackholll** [comment]
https://loonflow.readthedocs.io/zh_CN/r1.0.11/api_docs/authentication/

![image](https://user-images.githubusercontent.com/6269605/95316631-a9c8fb80-08c6-11eb-81a9-55cc766a6adc.png)

**Comment by uzi6666666** [comment]
谢谢，工作流权限是什么呢，填1的话说  参数不合法

**Comment by uzi6666666** [comment]
谢谢！
