### ISSUE TITLE
工作流配置导出

### ISSUE THREAD

**Issue by sleeper99** [blackholll/loonflow#191]
有没有办法可以导出/导入工作流的配置，在不同服务器都要手动配一次

**Comment by yutao668** [comment]
你也在用loonflow吗？  能不能留个qq联系方式，方便交流

**Comment by blackholll** [comment]
1.1.0版本开发中。 目前来看应该是要11月份以后发布，计划会有导出，导入功能

**Comment by blackholll** [comment]
> 你也在用loonflow吗？ 能不能留个qq联系方式，方便交流

有个qq群： 558788490， 可以在群里交流

**Comment by yutao668** [comment]
已经加了这个群，只是想挖一些python和loonflow人才！！！ ：）

**Comment by sleeper99** [comment]
> 1.1.0版本开发中。 目前来看应该是要11月份以后发布，计划会有导出，导入功能

thank you, sir
