### ISSUE TITLE
为什么这个要限制??? 使用中出现大于1000而前端无法显示

### ISSUE THREAD

**Issue by yutao668** [blackholll/loonflow#192]
![image](https://user-images.githubusercontent.com/58452208/95723594-e3737b00-0ca7-11eb-9e55-5edbecc02de5.png)

**Comment by blackholll** [comment]
这里主要是保存处理意见的。 1000还不够么？  你啥场景 处理意见会超过1000

**Comment by yutao668** [comment]
因为存了（图片、附件）名称、路径、大小等信息，需求是处理意见可以上传图片和附件！！！如果传多几个就爆了！！！

**Comment by blackholll** [comment]
其实我起初的设计是希望这个字段只是处理意见的。   如果有复杂的内容是可以新建一个自定义字段，让处理人在新增的自定义字段中填写复杂内容的。 
你把这段逻辑去掉， 然后修改下数据库中这个字段的长度吧
