### ISSUE TITLE
multi_all_person 是不是取值取错了！！！

### ISSUE THREAD

**Issue by yutao668** [blackholll/loonflow#193]
![image](https://user-images.githubusercontent.com/58452208/95855878-b39da380-0d8b-11eb-95a5-5d56aedbe8eb.png)

是不是应该改为  multi_all_person = str(participant_info.get('multi_all_person', '{}')).replace("'", '"')

**Comment by blackholll** [comment]
if has_all_save_value ==True表示，当前状态需要多人全部处理，且所有人都已经处理过了而且处理操作是一致的。
这时候就应该流转到下个状态了， 工单基础信息中的multi_all_person 重置为"{}"

**Comment by yutao668** [comment]
前后节点都是会签，会有问题； 如果下一个节点也是会签，multi_all_person 还赋值‘｛｝’，就无法实现下一个节点会签

**Comment by blackholll** [comment]
对的。  你提个pr到v1.0.13分支吧。
另外 应该用replace吧
multi_all_person = participant_info.get('multi_all_person', '{}')

**Comment by yutao668** [comment]
恩恩

还有，就是保存进去是单引号，会转圈报错；是不是要转义双引号，你在看看:)
