### ISSUE TITLE
又发现multi_all_person 在一个地方写死了！！！

### ISSUE THREAD

**Issue by yutao668** [blackholll/loonflow#194]
![image](https://user-images.githubusercontent.com/58452208/95948963-40943b80-0e24-11eb-960d-78d20249cb2a.png)

**Comment by blackholll** [comment]
后面有重新赋值
https://github.com/blackholll/loonflow/blob/master/service/ticket/ticket_base_service.py#L2023

**Comment by yutao668** [comment]
没看到哪里有赋值，或者有赋值，但是都是带条件的，如果条件不满足还不是没有赋值！！！

能不能截下图，Thx!!!

**Comment by yutao668** [comment]
确认了，不满足这些条件后将无法重新赋值！！！

![image](https://user-images.githubusercontent.com/58452208/95963929-daff7980-0e3a-11eb-8996-9fdd71ddb1c5.png)

**Comment by blackholll** [comment]
抱歉，漏回复了。刚看到
直接处理的意思是： 当某个状态为多人时，随便一个人处理就好了。  这种情况下 不需要记录mult_all_person
