### ISSUE TITLE
为什么我在获取tickets信息的时候，filed_list数据是空的

### ISSUE THREAD

**Issue by yanxiaofei** [blackholll/loonflow#195]
API接口的url为：api/v1.0/tickets/{ticket_id}，其他字段数据获取正常，唯独field_list数据是空，后台代码部分没有做任何修改，所有的tickets得field_list都是空，是不是触发了系统的一个bug了？跪求大神解答。

**Comment by yanxiaofei** [comment]
![Uploading 2020-10-19_093319.png…]()
![Uploading 2020-10-19_093400.png…]()

**Comment by yanxiaofei** [comment]
![2020-10-19_093319](https://user-images.githubusercontent.com/13655257/96392676-6daf6800-11ef-11eb-9b37-9c2faf4e6f11.png)
![2020-10-19_093400](https://user-images.githubusercontent.com/13655257/96392686-74d67600-11ef-11eb-857f-3e8759c6299b.png)

**Comment by blackholll** [comment]
提issue之前先搜索下   
Duplicate of #37

**Comment by yanxiaofei** [comment]
> 提issue之前先搜索下
> Duplicate of #37

多谢作者及时回复，非常感谢。以后一定注意查看历史问题。
