### ISSUE TITLE
如何在自己的系统中嵌入loonflow

### ISSUE THREAD

**Issue by lixiaorui2000** [blackholll/loonflow#196]
自己的系统保存了关于业务方面的数据，希望在系统中嵌入流程管理，看了帮助中的demo，发现这些demo的参数数据都是直接调用loonflow，并没有在自己的系统中保存。如何在一个流程运行到某个环节时，触发之前自己系统的相关逻辑。例如：如何在loonflow审核通过时，修改原系统中的数据。
希望大神指导一下。

**Comment by blackholll** [comment]
新增一个状态(可以放在审批通过后)， 状态的参与人类型是hook. hook地址配置为自己提供的一个接口。  当工单状态到达这个状态时候opsflow会触发post请求。   请求会带上工单的所有信息。      你的系统接收到请求后可以执行自己的逻辑

**Comment by zjfansu** [comment]
同求，有没有实例可以参考的。

**Comment by caoqianming** [comment]
> 同求，有没有实例可以参考的。

我目前用django的信号进行处理的

**Comment by Alvin-Frank** [comment]
不知道怎样可以不通过http调用，直接用后端部分的代码直接改

**Comment by caoqianming** [comment]
> 不知道怎样可以不通过http调用，直接用后端部分的代码直接改

可以看看我改的，做成一个app放到系统里

**Comment by blackholll** [comment]
> 不知道怎样可以不通过http调用，直接用后端部分的代码直接改

不建议这么用。 这样用的话loonflow只为你这个系统服务了。  loonflow的初衷是企业统一的工作流引擎。每个系统都通过api调用使用loonflow的引擎功能，而不是每个系统吧loonflow的代码拷贝过去一份
