### ISSUE TITLE
hook形式的工单状态流转，当code返回非0是存在异常

### ISSUE THREAD

**Issue by SmallJune** [blackholll/loonflow#197]
@app.task
def flow_hook_task(ticket_id):
    """
    hook 任务
    :param ticket_id:
    :return:
    """
    # 查询工单状态
    ticket_obj = TicketRecord.objects.filter(id=ticket_id, is_deleted=0).first()
    state_id = ticket_obj.state_id
    state_obj = State.objects.filter(id=state_id, is_deleted=0).first()

    participant_type_id = state_obj.participant_type_id
    if participant_type_id != constant_service_ins.PARTICIPANT_TYPE_HOOK:
        return False, ''
    hook_config = state_obj.participant
    hook_config_dict= json.loads(hook_config)
    hook_url = hook_config_dict.get('hook_url')
    hook_token = hook_config_dict.get('hook_token')
    wait = hook_config_dict.get('wait')
    extra_info = hook_config_dict.get('extra_info')

    flag, msg = common_service_ins.gen_hook_signature(hook_token)
    if not flag:
        return False, msg
    flag, all_ticket_data = ticket_base_service_ins.get_ticket_all_field_value(ticket_id)
    if extra_info is not None:
        all_ticket_data.update(dict(extra_info=extra_info))
    try:
        r = requests.post(hook_url, headers=msg, json=all_ticket_data, timeout=10)
        result = r.json()
    except Exception as e:
        result = dict(code=-1, msg=e.__str__())
    if result.get('code') == 0:
        # 调用成功
        if wait:
            # date等格式需要转换为str
            for key, value in all_ticket_data.items():
                if type(value) not in [int, str, bool, float]:
                    all_ticket_data[key] = str(all_ticket_data[key])

            all_ticket_data_json = json.dumps(all_ticket_data)
            TicketBaseService().add_ticket_flow_log(dict(ticket_id=ticket_id, transition_id=0,
                                                         suggestion=result.get('msg'),
                                                         participant_type_id=constant_service_ins.PARTICIPANT_TYPE_HOOK,
                                                         participant='hook', state_id=state_id,
                                                         ticket_data=all_ticket_data_json,
                                                         creator='loonrobot'
                                                      ))
            return True, ''
        else:
            # 不等待hook目标回调，直接流转
            flag, transition_queryset = workflow_transition_service_ins.get_state_transition_queryset(state_id)
            transition_id = transition_queryset[0].id  # hook状态只支持一个流转

            new_request_dict = {}
            new_request_dict.update({'transition_id': transition_id, 'suggestion': msg, 'username': 'loonrobot'})
            # 执行流转
            flag, msg = ticket_base_service_ins.handle_ticket(ticket_id, new_request_dict, by_hook=True)
            if not flag:
                return False, msg

    else:
        ticket_base_service_ins.update_ticket_field_value(ticket_id,{'script_run_last_result': False})

        flag, result = ticket_base_service_ins.get_ticket_all_field_value_json(ticket_id)

        all_ticket_data_json = result.get('all_field_value_json')
        ticket_base_service_ins.add_ticket_flow_log(
            dict(ticket_id=ticket_id, transition_id=0, suggestion=result.get('msg'),
                 participant_type_id=constant_service_ins.PARTICIPANT_TYPE_HOOK,
                 participant='hook', state_id=state_id, ticket_data=all_ticket_data_json, creator='loonrobot' ))

其中 suggestion=result.get('msg')  应该为 result = r.json() 的数据返回数据吧
但是 这个result取的是 flag, result = ticket_base_service_ins.get_ticket_all_field_value_json(ticket_id) 
不存在 msg字段 内容

**Comment by blackholll** [comment]
是的，这里处理的有问题。 你可以提个pr到v1.0.13分支，然后使用v.1.0.13分支的代码。
最近在写r1.1.0的版本，bug修复的会不太及时。欢迎大家提交pr

**Comment by SmallJune** [comment]
我看到v1.0.13 已经修改了当前问提
