### ISSUE TITLE
docker-compose deployment problem [unsuccessful]

### ISSUE THREAD

**Issue by huskier** [blackholll/loonflow#198]
I follow the steps of the file loonflow/docker-compose_deploy/README.md to deploy the loonflow service.

1. The database "loonflow" is OK, and I can access it through "mysql -h 192.168.5.2 -uloonflow -p" command.
2. The DB info in the run.py is completed with the following text.
    db_host = '192.168.5.2'  # loonflow使用的数据库的ip
    db_port = '3306'  # loonflow使用的数据库的端口
    db_name = 'loonflow'  # loonflow使用的数据库的名称
    db_user = 'loonflow'  # loonflow使用的数据库的用户
    db_password = '123456'  # loonflow使用的数据库的用户密码
    ddl_db_user = 'loonflow'  # 可以执行ddl(拥有修改表结构权限)的用户
    ddl_db_password = '123456'  # 可以执行ddl(拥有修改表结构权限)的用户的密码

When I run the following command:
[root@homemachine loonflow_only]# /opt/anaconda3/bin/python run.py install

I've got the following output:
开始导入初始化sql，需要下载镜像arey/mysql-client, 请耐心等候
docker run -i arey/mysql-client -h192.168.5.2 -p123456 -uloonflow loonflow < /opt/loonflow/loonflow_init.sql
Unable to find image 'arey/mysql-client:latest' locally
latest: Pulling from arey/mysql-client
fe2a0d033fc4: Pull complete 
a3ed95caeb02: Pull complete 
9bad46d163e2: Pull complete 
Digest: sha256:782328de0b97194751c68b276a651f40c69f7777b029370c9ce22076d0e31786
Status: Downloaded newer image for arey/mysql-client:latest
_**ERROR 1067 (42000) at line 28: Invalid default value for 'gmt_created'**_

完成初始化sql导入

开始更新数据库配置
完成数据库配置
Starting loonflow_only_loonflow-task_1  ... done
Starting loonflow_only_loonflow-redis_1 ... done
Starting loonflow_only_loonflow-web_1   ... done

启动成功，你可以直接通过http://hostip来访问loonflow的管理后台,其中hostip为你宿主机的ip

The problem is that:
1. There is an error during the service startup: 
_**ERROR 1067 (42000) at line 28: Invalid default value for 'gmt_created'**_
2. When I access the IP address 192.168.5.2, I could see the login page, but when I use the user name "admin" and password "loonflow123" to login the system, an error occured:
**_(2005, "Unknown MySQL server host 'loonflow-db' (2)")_**

Besides, the master version now is 1.0.12, but the docker version is till 1.0.2 (the login page). It is not up to date.

Thanks for your help.

Youbao

**Comment by blackholll** [comment]
What is the version of your mysql server?
the default value of 'gmt_created' in the loonflow_init.sql   is CURRENT_TIMESTAMP.  
check you mysql version whether support this syntax

**Comment by huskier** [comment]
It is a MariaDB 5.5, equivalent to MySql 5.5 from the internet info..  Since it is the default DB for the RHEL 7.x, so I tried it for loonflow. So, I have to install MySql 5.7.x instead?

How about the other error? Is it triggered by the first problem?

MariaDB [(none)]> status
--------------
mysql  Ver 15.1 Distrib 5.5.56-MariaDB, for Linux (x86_64) using readline 5.1

Connection id:		15
Current database:	
Current user:		root@localhost
SSL:			Not in use
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server:			MariaDB
Server version:		5.5.56-MariaDB MariaDB Server
Protocol version:	10
Connection:		Localhost via UNIX socket
Server characterset:	latin1
Db     characterset:	latin1
Client characterset:	utf8
Conn.  characterset:	utf8
UNIX socket:		/var/lib/mysql/mysql.sock
Uptime:			6 hours 54 min 38 sec

**Comment by blackholll** [comment]
1. same problem:  https://dba.stackexchange.com/questions/132951/cant-default-date-to-current-timestamp-in-mysql-5-5
.update you db to 5.7

2. 
alter docker docker_compose_deploy/loonflow_only/loonflow-task/Dockerfile. change redis and db config to the same as it in run.py.
alter docker docker_compose_deploy/loonflow_only/loonflow-web/Dockerfile. change redis and db config to the same as it in run.py.
then, rm docker images for loonflow-task and loonflow-web. rerun run.py

it's my fault

**Comment by huskier** [comment]
Thanks for your help. Two more questions:
1. Is it possible to make the current MariaDB workable with minimal changes? For example, we change the 'datetime' to 'TIMESTAMP'.
2. Is it still a problem for "docker + database" approach? I think maybe it is feasible with extra "volume" option.
    """
    在宿主机安装 mysql5.7
    为什么不以docker安装database？
    测试时发现了很多问题。最终放弃了以docker方式安装 mysql5.7
    """

Besides, Is it better to change the content in run.py instead of in the Dockerfile?

Youbao

**Comment by blackholll** [comment]
1. change the  column 'datetime' to TIMESTAMP , then the code should modify,  otherwise may raise exception when handle this filed 

2. after r1.1.0 release,  i will optimize deployment。  r1.1.0 support handle ticket（before that, You should user shutongflow or workflowdemo or realize by yourself ）

3. change run.py or dockerfile is all

**Comment by huskier** [comment]
By the code, do you mean the loonflow's source code? That's too much. That way, I prefer to update the DB.
> 1. change the  column 'datetime' to TIMESTAMP , then the code should modify,  otherwise may raise exception when handle this filed

Do you have a rough timeline for r1.1.0? I have seen the tag in the Github's tags.
> 2. after r1.1.0 release,  i will optimize deployment。  r1.1.0 support handle ticket（before that, You should user shutongflow or workflowdemo or realize by yourself ）

**Comment by blackholll** [comment]
1. yes, source code. 

2.
The latest code in https://github.com/blackholll/loonflow/tree/v1.1.0   . I will commit my code some time。 The original release plan is At the end of October。  but it will be delayed because  other members have not According to the plan.  new plan is The end of December。

**Comment by huskier** [comment]
I updated my DB from MariaDB to Mysql 5.7.21 following the URL (http://blog.itpub.net/31015730/viewspace-2152272/).

Then, I remove the previous docker images, and re-run the run.py. I have not changed run.py and Dockerfiles. Maybe they are already consistent for my first change.

After that, I could login into the loonflow website.

Thanks.

Youbao
