### ISSUE TITLE
关于子任务

### ISSUE THREAD

**Issue by sleeper99** [blackholll/loonflow#199]
1. 有没有什么配置项, 可以让工单列表接口不返回子任务
2. 根据主任务查询相关的子任务

**Comment by blackholll** [comment]
1.子工单么？ 默认是不返回对应子工单的。 子工单对应的工作流是另外的id。查询的时候如果制定了工作流类型 是不会子工单的
2. 刚检查了下代码和接口文档， 忘了支持了。   可以在查询工单的列表接口上支持个参数 parent_ticket_id,  然后接口返回对应的子工单列表。 这个我下周末如果有时间的话支持下 发个版本。

**Comment by sleeper99** [comment]
创建子工单的时候工作流id不用主工单工作流id, 然后查询的时候只传主工单工作流id子工单就不会显示了是吧

**Comment by blackholll** [comment]
创建工单时候，可以指定父工单id，可以产生子工单的状态id。
https://loonflow.readthedocs.io/zh_CN/r1.0.12/api_docs/ticket/

![image](https://user-images.githubusercontent.com/6269605/97127146-d2c90780-1773-11eb-92cf-ceda71e7ad57.png)

**Comment by blackholll** [comment]
a example contains  sub ticket

![image](https://user-images.githubusercontent.com/6269605/97127256-102d9500-1774-11eb-945b-7158d44e667e.png)

**Comment by sleeper99** [comment]
明白，谢谢啦
