### ISSUE TITLE
本来想做一次代码合并

### ISSUE THREAD

**Issue by SmallJune** [blackholll/loonflow#200]
本来想做一次代码合并
发现v1.0.13 已经修改了当前问提

但是在v1.1.0上没有做修改

_Originally posted by @SmallJune in https://github.com/blackholll/loonflow/issues/197#issuecomment-716363093_

**Comment by blackholll** [comment]
v1.1.0发布前   会将1.0.13代码merge过来。 
1.1.0还在开发中，改动比较大。 目前还不能使用
