### ISSUE TITLE
Problem to deploy with loonflow_shutongflow

### ISSUE THREAD

**Issue by huskier** [blackholll/loonflow#201]
When I deply the demo with loonflow_shutongflow, I've almost gotten done except the following error:
    shutongflow_1    | _mysql_exceptions.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
    shutongflow_1    | 
    shutongflow_1    | The above exception was the direct cause of the following exception:

I only modified the IP part in the config.json file, and others are "as is".

After deployment:
I can access http://192.168.5.2:6061, but when I use the user "admin" and passwd "yxuqtr", nothing happens.
I cannot access http://192.168.5.2:6060.

The solution on the following website can not help.
https://stackoverflow.com/questions/10181344/mysql-exceptions-operationalerror-1045-access-denied-for-user-rootlocalh

Youbao

**Comment by blackholll** [comment]
is mysql install successfully? 
when install mysql, there are some info display in you terminal。

![image](https://user-images.githubusercontent.com/6269605/97372623-054b3f80-18ef-11eb-9422-381cfeddd675.png)

**Comment by huskier** [comment]
For the deployment of loonflow_only, we use the mysql 5.7 installed on the host machine, not the docker installed mysql. We can successfully run the loonflow_only  service with the host-installed mysql 5.7.

For the deployment of loonflow_shutongflow, do we have to use the docker-installed mysql?

We've tried the docker-installed mysql, and we've gotten the following error:
[root@homemachine loonflow]# /opt/anaconda3/bin/python ./docker_compose_deploy/loonflow_shutongflow/setup_all.py 
安装 docker版 mysql5.7
docker安装 mysql5.7 开始
998e979e5f96ac0de25f70b5481c30170a1d76477fcc84bf9caec2d802a74477
docker安装 mysql5.7 完成
睡眠10秒，确保mysql启动完成
创建 loonflow 数据库
Error response from daemon: Container 998e979e5f96ac0de25f70b5481c30170a1d76477fcc84bf9caec2d802a74477 is not running
Traceback (most recent call last):
  File "./docker_compose_deploy/loonflow_shutongflow/setup_all.py", line 105, in <module>
    main()
  File "./docker_compose_deploy/loonflow_shutongflow/setup_all.py", line 98, in main
    setup_mysql57()
  File "./docker_compose_deploy/loonflow_shutongflow/setup_all.py", line 79, in setup_mysql57
    sql_to_docker_mysql(root_pwd, db_name, sql_file)
  File "./docker_compose_deploy/loonflow_shutongflow/setup_all.py", line 33, in sql_to_docker_mysql
    root_pwd, db_name))
  File "/opt/loonflow/docker_compose_deploy/loonflow_shutongflow/utils.py", line 24, in cmd
    raise Exception("{} 执行失败".format(cmd_str))
Exception: docker exec -itd mysql mysqladmin -uroot -p'mySql12#4,.De' create loonflow 执行失败

We've also tried the following command, no success.
docker start 998e979e5f96ac0de25f70b5481c30170a1d76477fcc84bf9caec2d802a74477

Where were we wrong?

Thanks.

Youbao

**Comment by blackholll** [comment]
whether your server configuration is too low?  sleep 10s is not enough.  then create database is fail because "Error response from daemon: Container 998e979e5f96ac0de25f70b5481c30170a1d76477fcc84bf9caec2d802a74477 is not running"?

alter sleep time(docker_compose_deploy/loonflow_shutongflow/setup_all.py), and re-try

![image](https://user-images.githubusercontent.com/6269605/97516454-18810c80-19ce-11eb-8eec-2189fe44d630.png)

**Comment by huskier** [comment]
But even I mannully start the container，I can not see the running container with cmd "docker ps".

docker start 998e979e5f96ac0de25f70b5481c30170a1d76477fcc84bf9caec2d802a74477

**Comment by blackholll** [comment]
use cmd：docker images to find image about mysql, and run the image， maybe some error info about start

**Comment by huskier** [comment]
The root reason is that my host-installed mysql is running. After killed the host-installed mysqld service, I could start the service. It's all my fault. I forgot the host-installed mysql occupied the port 3306, and the docker start container give no clue about that. I suggest that a tip "make sure the port 3306 is available" is added after "睡眠10秒，确保mysql启动完成".

Now, I can access http://192.168.5.2:6060 (user: admin; passwd: loonflow123) without problem.

But for the site http://192.168.5.2:6061, when I input the user "admin" and passwd "yxuqtr", the login page gives no response at all. The command line window has no any output information.

Any clues? Thanks.

Youbao

**Comment by blackholll** [comment]
It seem like an error occurred when import shutongflow_demo_init.sql to mysql。
connect the mysql user command or client, check table record in db "shutongflow"
or you can delete table in db "shutongflow" and import sql by mannual.
