### ISSUE TITLE
定时器流转的使用方法？

### ISSUE THREAD

**Issue by a5467021** [blackholll/loonflow#202]
作者您好，我在基于loonflow进行二次开发的时候，需要实现这么一个功能：在步骤为`A->B`的流转过程中，完成A状态后，冻结一段时间（比如5分钟），再进入B状态。对此我的实现方法是，添加中间状态`C`，先从`A`状态无条件跳转到`C`，再在`C`状态使用定时器流转跳转到`B`，即`A->C->B`。

但是在使用过程中，我发现定时器似乎并没有生效，为了测试我设置了一个30秒跳转的定时器，可以成功从A主动进入C状态，等了几分钟状态也没有自动流转到B。起初我对中间状态`C`的设置没做更改，默认参与人类型是个人，参与人留空。后来尝试了“角色+（自定义）管理员”、“无+留空”、“无+loonrobot”的组合，都不起作用，检查`loonflow.log`没有发现任何异常之处，都是HTTP日志；查阅wiki也没有发现对该功能使用的详细叙述。因此想请教作者，是我的配置有误，还是loonflow出现了bug？

**Comment by blackholll** [comment]
celery有没启动？ 定时器流转， 会触发一个celery的延时任务， 需要启动celery，至于如何启动celery请看下文档

**Comment by a5467021** [comment]
感谢作者的回复！如您所言，是我的celery没有配置好，按照文档配置后就工作正常了。
