### ISSUE TITLE
工单问题询问

### ISSUE THREAD

**Issue by wangxuanwx** [blackholll/loonflow#206]
你好，工单数据在Excel文件上，如何实现批量导入工单数据

**Comment by blackholll** [comment]
1.自己写脚本操作数据库写入数据
2.自己写脚本 调用创建工单接口来创建工单

**Comment by wangxuanwx** [comment]
脚本执行不了是什么原因

**Comment by blackholll** [comment]
celery任务没正常启动吧 
https://loonflow.readthedocs.io/zh_CN/r1.0.12/about/start/
