### ISSUE TITLE
初始状态的工单，创建人关闭时的问题

### ISSUE THREAD

**Issue by pyang30** [blackholll/loonflow#210]
# 强制关闭工单需要对应工作流的管理员或者超级管理员 或者处于初始状态的工单由创建人直接关闭

```python
flag, start_state_result = workflow_state_service_ins.get_workflow_start_state(ticket_result.workflow_id)
if ticket_result.creator == username and ticket_result.state_id == start_state_result.id:
               return True, "ticket's creator can close ticket in start state"

```

这里看代码应该是判断创建人，并处于初始状态时，可以关闭，但是有个问题，一旦工单创建了，他的状态就不是初始状态了，就是初始状态的下一个状态了。

所以这个判断永远为false。

那如何简单的判断creator是否可以关闭工单？

**Comment by blackholll** [comment]
有个撤回功能， 状态配置的时候支持配置该状态是否允许创建人撤回工单。 撤回工单后工单状态就处于初始状态了。 
撤回工单的接口见 https://loonflow.readthedocs.io/
