### ISSUE TITLE
请问工单管理中，点击某工单详情，为什么不显示单选框的字段信息

### ISSUE THREAD

**Issue by MetO940743** [blackholll/loonflow#211]
自定义字段中有设置单选框类型的字段，工作流中也配置了，但是在工单管理详情中并不显示，shutongflow中显示正常，请问这里应该如何填写
![1](https://user-images.githubusercontent.com/48880518/100844473-e3794580-34b6-11eb-8ecd-f0b3978c4b3e.png)
![2](https://user-images.githubusercontent.com/48880518/100844478-e4aa7280-34b6-11eb-8519-d02613e4861f.png)
![3](https://user-images.githubusercontent.com/48880518/100844486-e6743600-34b6-11eb-93f3-4928247b4dea.png)

**Comment by blackholll** [comment]
查看下浏览器控制台中的网络请求，检查tickets/:id这个接口返回的数据中field_list中是否有这个字段

**Comment by MetO940743** [comment]
找到原因了，是因为前端工单详情的js中，并没有处理单选、多选等字段，所以页面并不显示，接口是有返回该字段数据的
![1](https://user-images.githubusercontent.com/48880518/100954714-115e9880-3550-11eb-8f64-32b77491b8e0.png)
