### ISSUE TITLE
参与人设置为多人直接或全部处理引发的问题

### ISSUE THREAD

**Issue by MetO940743** [blackholll/loonflow#212]
请教一下，当设置参与人为多人全部处理时，如果有人不同意，状态会停留，那么应当如何处理或者重新配置，如果转交给拒绝的人再次审批会报错，状态无变化
![xxx](https://user-images.githubusercontent.com/48880518/100988222-720ac700-358a-11eb-9045-1ddc35f3c217.png)
另外就是工作流配置中工单查看权限校验按钮设置无效

**Comment by blackholll** [comment]
1.工单查看权限校验，  这个需要前端适配。
2.当前的设计是希望其中有人拒绝的后停留在此状态， 然后管理员在管理后台可以干预处理(转交、 强制关闭等)。  如果出现上面的情况，那么应该是bug。 看下loonflow的日志，看是哪段代码报错的

**Comment by MetO940743** [comment]
![x](https://user-images.githubusercontent.com/48880518/101112219-ca3bda80-3617-11eb-8db7-d02e16261639.png)
看了下应该是没有匹配到上图中某个条件选项，导致没有destination_participant_list，然后运行到下图中红圈处抛出错误"local variable 'destination_participant_list' referenced before assignment"
![y](https://user-images.githubusercontent.com/48880518/101112369-14bd5700-3618-11eb-8381-c053f9ca2502.png)
多人全部处理的状态中转交给拒绝过的人重新同意会报该错，状态不变更，强制改变到下一状态后审批仍然是该问题，不知道怎么解决

**Comment by blackholll** [comment]
该问题已经修复， 更新到r1.0.x最新版本。https://github.com/blackholll/loonflow/releases/tag/r1.0.12
