### ISSUE TITLE
请问动态的获取部门怎么做？

### ISSUE THREAD

**Issue by SelfDown** [blackholll/loonflow#214]
有这么个场景，员工>**运维部门**>产品中心>领导>财务。比如这个**运维部门**它是动态的，和它并排的有技术部门，测试部门，实施部门
我这里需要建立几个流程？

**Comment by blackholll** [comment]
什么规则来确定不同部门的？   可以用条件流转 然后不同条件 到达不同的状态(运维部门处理中、技术部门处理中等)
