### ISSUE TITLE
可以作为企业微信审批流的后端吗

### ISSUE THREAD

**Issue by fuzhuojun1** [blackholll/loonflow#217]
有个需求，通过企业微信里面的内部应用达到审批目的，loonflow能否作为后端，我再写一个vue作为前端调用loonflow的审批逻辑，请问企业微信里面的组织架构和用户信息如何导到loonflow中？

**Comment by blackholll** [comment]
1,使用后端调用loonflow接口，  如果不会后端语言，你可以在vue的node层来调用(前端请求node， node调用loonflow)
2.自己写个脚本直接插入到loonflow的数据库，定时运行
