### ISSUE TITLE
关于人员多部门

### ISSUE THREAD

**Issue by fuzhuojun1** [blackholll/loonflow#220]
麻烦问下 人员多部门怎么处理 在企业微信架构中  好多人兼职在多个部门 但是在loonflow里面的人员表中 部门id只能填一个 如何处理呢

**Comment by blackholll** [comment]
当前不支持一个用户  属于多部门。  我理解的一个人处于多部门一般是在作为其他部门的负责人。这种情况不应该放到各个部门中。
不过考虑到实际情况，v1.1版本将支持属于多部门， 目前开发中，发布时间暂未确定
