### ISSUE TITLE
确认子工作流功能是否被移除

### ISSUE THREAD

**Issue by zjkyz8** [blackholll/loonflow#222]
请问子工作流是否已被移除，目前文档中还有少量提及，但是代码中未找到相关实现，是移除这个功能了吗？

**Comment by blackholll** [comment]
子工作流在配置的时候 无需选择。  创建子工单的时候传对应父工单的id,以及父工单需要创建子工单节点的状态id即可。

工单在流转的过程中，当工单状态结束的时候， 会检查当前工单是否存在兄弟工单(相同的父工单 和相同的父工单状态id)，就检测所有兄弟工单是否都结束 ,  如果所有兄弟工单状态都已经结束，就触发父工单的自动流转到下个节点

**Comment by zjkyz8** [comment]
感谢回复，子工作流是否可以考虑通过配置方式实现呢，如果父工单的某个状态需要创建子工单，则由流程引擎根据配置自动发起指定流程的工单，这样通过流程引擎配置的方式实现了低耦合 高内聚

**Comment by blackholll** [comment]
引擎自动发起的话， 有些问题需要处理：
1.父工单与子工单的字段的关联。  因为父子工作流是单独配置的， 自定义字段也是单独配置的
2.配置的时候 需要选择子工作流， 同时需要指定创建多少子工单。 比如有些场景是需要根据父工单的某个字段的内容来确定 创建多少子工单。  这个配置层面比较难配置

**Comment by zjkyz8** [comment]
关于问题1：
可以在引擎层面约定，子工单的字段需要从父工单的同名字段获取，可以在文档中进行明确。只要保证在创建子工单时，父工单对应的字段已经被设值即可。
关于问题2：
之前0.X版本在子工单的对应状态上是可以指定子流程ID的，不知何原因后续版本配置消失了。关于子工单的数量，这个需求不是很清楚，我的理解是当父工单到达某个状态时，此状态对应了另一个流程，所以此时需要发起一个新的工单，即子工单，流程转入子工单，父工单停留在当前状态，等待子工单处理完成后，继续父工单。所以不是很清楚为什么会需要多个子工单，望指正。
谢谢

**Comment by blackholll** [comment]
关于问题2：
举例场景： 父工单是项目开发流程，  子工单是应用的生命周期流程。  父工单中指定了本项目涉及哪些应用的改动， 当项目的流程进入到开发中的时候， 创建指定应用的子工单(父工单中制定了多少应用，就创建多少子工单。工单的流程包括静态扫描、单元测试、安全扫描等等)
