### ISSUE TITLE
工作流节点问题

### ISSUE THREAD

**Issue by fuzhuojun1** [blackholll/loonflow#223]
新建工单之后hookurl接受的信息里面当前处理人是工单发起人而不是第一个节点的审核人，正常发起人是不用审核的，直接流转到第一个节点审核人。
设置成定时流转也不好用，到时间仍然不流转到下一个审核人。
下面是收到的hook信息，请问哪个字段是当前处理人，
{'title_result': '赵六的MIS权限新增申请单', 'content_result': '沈阳新玛特中街店百货赵六的混子MIS权限新增申请单, 创建时间:2021-01-26 14:00:04', 'participant': '', 'participant_type_id': 1, 'multi_all_person': '{}', 'ticket_value_info': {'id': 27, 'creator': 'fzj', 'gmt_created': '2021-01-26 14:00:04', 'gmt_modified': '2021-01-26 14:00:04', 'is_deleted': False, 'title': '', 'workflow_id': 1, 'sn': '_202101260018', 'state_id': 10, 'parent_ticket_id': 0, 'parent_ticket_state_id': 0, 'participant_type_id': 1, 'participant': '', 'relation': 'fzj', 'in_add_node': False, 'add_node_man': '', 'script_run_last_result': True, 'act_state_id': 1, 'multi_all_person': '{}', 'store_name': '沈阳新玛特中街店百货', 'person_name': '赵六', 'ID_NUM': '210221', 'post_NUM': '0006', 'post_name': '混子', 'LOCD_userId': 'fzj', 'LOS_userId': 'wdp', 'store_NUM': '0009', 'LOS_name': '王德鹏', 'LOCD_name': '付卓君'}, 'last_flow_log': {'id': 54, 'ticket_id': 27, 'state': {'state_id': 9, 'state_name': '申请单发起'}, 'transition': {'transition_id': 1, 'transition_name': '发起人-电脑部', 'attribute_type_id': 3}, 'intervene_type_id': 0, 'participant_type_id': 1, 'participant': 'fzj', 'participant_info': {'participant_type_id': 1, 'participant': 'fzj', 'participant_alias': '付卓君', 'participant_email': 'fuzhuojun@dsjt.com', 'participant_phone': '18640888832'}, 'suggestion': '', 'gmt_created': '2021-01-26 14:00:04'}, 'participant_info_list': []}
106.12.50.107 - - [26/Jan/2021 14:00:04] "POST /hookapi HTTP/1.1" 200 -

**Comment by blackholll** [comment]
hook的时候当前处理人  是当前节点的处理人，也就是hook。
当前处理人是participant(字典根节点， 非last_flow_log下面的)字段
