### ISSUE TITLE
关于流转分支表达式

### ISSUE THREAD

**Issue by fuzhuojun1** [blackholll/loonflow#224]
流转分支表达式说明如下[{"expression":"{days} > 3 and {days} ≤10", "target_state_id":11},{"expression":"{days} >10", "target_state_id":12}]
1、我应该把days换成我的工单字段，expression和target_state_id都不变是吗？
2、表达式是以列表形式呈现，是要把所有分支的条件写在一个分支钟吗，还是各分支写各自条件。
3、可以由中间审批人手动选择后面走向哪个流程分支吗？
![1611737836](https://user-images.githubusercontent.com/51150492/105967413-c3ce5a00-60c0-11eb-95af-9f3f62879e31.png)

**Comment by blackholll** [comment]
1. expression是表达式，你根据自己的需要来写， python预发，支持内置运算(+、-、*、/)以及datetime. time运算， {xxx}表示xxx字段的值。target_state_id指的是符合这个条件后 目标状态id是多少
2.所有分支写到一个流转记录里面。 这是个列表， 列表中列举所有的条件。 [{"expression":"{days} > 3 and {days} ≤10", "target_state_id":11},{"expression":"{days} >10", "target_state_id":12}]
3.手动选择到哪个节点，那就配置多个流转，每个流转的目标状态不一样， 然后流转的名字有区分，用户处理的时候 根据名字来区分

**Comment by blackholll** [comment]
1. expression是表达式，你根据自己的需要来写， python预发，支持内置运算(+、-、*、/)以及datetime. time运算， {xxx}表示xxx字段的值。target_state_id指的是符合这个条件后 目标状态id是多少
2.所有分支写到一个流转记录里面。 这是个列表， 列表中列举所有的条件。 [{"expression":"{days} > 3 and {days} ≤10", "target_state_id":11},{"expression":"{days} >10", "target_state_id":12}]
3.手动选择到哪个节点，那就配置多个流转，每个流转的目标状态不一样， 然后流转的名字有区分，用户处理的时候 根据名字来区分

**Comment by fuzhuojun1** [comment]
分支表达式还是没搞懂什么意思
[{"expression":"{post_NUM} = 80065 or {post_NUM }= 80066 or {post_NUM} = 80067 or {post_NUM}=80068 or {post_NUM}=80069 or {post_NUM}=80070", "target_state_id":13},{"expression":"{post_NUM} = 80197", "target_state_id":14}]
比如我这个审批流，根据岗位编号走不同的审批人，一共三个状态，三个流转，“post_NUM”字段等于多少就走哪个target_state_id，那不是上面那些编号的岗位怎么表达，可以用！=吗，上面的表达式写的对吗，三个流转每个都这么写吗，github上传不图总失败。。。

**Comment by blackholll** [comment]
[{"expression":"{post_NUM} >= 80065 and {post_NUM} <= 80070", "target_state_id":13},{"expression":"{post_NUM} = 80197", "target_state_id":14}].  建一个流转就可以了， 需要条件表达式的流转，目标状态可以随便点，系统会以符合条件的条件分支的目标状态为准

**Comment by fuzhuojun1** [comment]
表达式如下：
[{"expression":"{post_NUM} >=80065 and {post_NUM }<= 80070", "target_state_id":13},{"expression":"{post_NUM} = 80197", "target_state_id":14},{"expression":"{post_NUM} != 80197 and ({post_NUM} <80065 or {post_NUM}>80070) ", "target_state_id":15}]
每次走到表达式前一布就不自动往下走了，表达式是否有问题，表单提交的{post_NUM}是string类型吗，{post_NUM}全改成int({post_NUM})仍然不好用，望指点

**Comment by blackholll** [comment]
表达式流转的是需要人为触发的。 是某个流转配置了条件流转， 所以是人为点击了这个流转的按钮， 然后系统执行流转， 流转的过程中根据这个条件表达式来流转到对应的状态。 
比如请假申请的流程。  提交----TL审批----HR审批(请假天使小于3)/总监审批(请假天数大于3)。   那么TL审批阶段TL点了同意后出发条件

**Comment by fuzhuojun1** [comment]
现在所有流转都设置的定时器流转我想测试一下表单流程，每次到条件表达式前面就不自动往下走了，定时器流转和人为点击同意流转道理应该是一样的吧

**Comment by blackholll** [comment]
定时器不一样。 如果A-B-C .  B-C之间的流转配置了定时器，那么当工单状态到达B后  会自动流转到C

**Comment by fuzhuojun1** [comment]
我是想测试流转分支表达式是否好用，目前没做到处理工单的接口。如果A-B-C和D两个分支，最后到流程结束（B到C和D有条件表达式），每个都设置定时器流转 ，整个流程会不会走完。现在我这里每次走到B 不往下走了。按道理B设置成定时器流转应该按照条件自动到C或者D吧 然后再继续往下走。条件表达式如下：[{"expression":"{post_NUM} >=80065 and {post_NUM }<= 80070", "target_state_id":13},{"expression":"{post_NUM} = 80197", "target_state_id":14},{"expression":"{post_NUM} != 80197 and ({post_NUM} <80065 or {post_NUM}>80070) ", "target_state_id":15}] ，还是一定需要B手动点击同意不能B定时器流转。

**Comment by blackholll** [comment]
定时器依赖task任务，检查下celery是否启动并且使用了相同的redis配置(task.py中配置)

**Comment by fuzhuojun1** [comment]
定时器是好用的，所有节点定时器都是可以自动执行，只有条件表达式前面的定时器无法自动同意

**Comment by blackholll** [comment]
那可能是 定时器+条件流转 这个场景有问题。 说下你的实际场景，看下是否可以规避下

**Comment by fuzhuojun1** [comment]
岗位审批，按照岗位编号走不同的审批人，实际场景是需要人为点同意继续往下走的，但是我的处理工单接口还没写，只写了创建工单接口，想先试试这个工单表达式如何配置，整个流程测试一下。

**Comment by blackholll** [comment]
那就可以shutongflow或者workflowdemo部署下， 在shutongflow或者workflowdemo中处理工单
1.1.0版本将支持直接在loonflow中处理工单，尚在开发中，发布时间暂不确定

**Comment by fuzhuojun1** [comment]
表单中的数据需要转化成int格式再做条件计算吗,例如是否需要int{post_NUM}>80197。

**Comment by blackholll** [comment]
看你自定义字段类型，如果是整形，那么可以直接比较， 如果是字符串就需要先转换   int({post_NUM})>80197. 你少了个括号

**Comment by fuzhuojun1** [comment]
处理工单接口里面没找到哪个是同意字段，哪个是拒绝字段，怎么发送请求代表同意呢

**Comment by blackholll** [comment]
同意、拒绝、等等这些在loonflow中就是流转。 所以传流转的id就可以了

**Comment by fuzhuojun1** [comment]
{"code": 0, "data": {"value": []}, "msg": ""} 获得可操作信息是这个，我在流转中配置同意了呀

**Comment by blackholll** [comment]
调用获取可以执行操作接口的 用户用的是谁？  这个状态的处理人是否配置了这个人

**Comment by fuzhuojun1** [comment]
嗯 调整了审批用户就可以了 ，到分支前一步提示这个信息{'code': -1, 'data': {}, 'msg': "'post_NUM '"}，是不是还是分支表达式写的不对

**Comment by blackholll** [comment]
'post_NUM '    NUM后面多了个空格
