### ISSUE TITLE
关于hook信息

### ISSUE THREAD

**Issue by fuzhuojun1** [blackholll/loonflow#226]
工单到指定节点会发出hook信息，如何根据hook内容记录每个节点的审批结果和编号，因为要调用企业微信的接口，每个节点编号不能重复，应该使用ticket_id+transition_id还是ticket_id+state_id，但是如果一个工单回退再重新走审批流程，无论transition_id还是state_id都会出现重复。

**Comment by blackholll** [comment]
新建个表用户保存消息记录，字段包括 ticket_id，task_id(企业微信消息卡片id),receiver（消息接收人），handled(是否已处理)、以及创建时间、修改时间、是否已删除
task_id生成规则： 公司前缀+ '-' +  ticket_id  + '-'+ state_id+ '-' + 一个随机字符串。 如zx-19222-33-xeNXe
