### ISSUE TITLE
flowlogs接口返回的ticket_data，不是字典是字符串

### ISSUE THREAD

**Issue by 397334469** [blackholll/loonflow#227]
第一个节点（发起人-新建中）是正常的

![image](https://user-images.githubusercontent.com/51410244/106682816-4180f100-65fe-11eb-82d1-85544b4318f1.png)

后续的都变成了字符串

![image](https://user-images.githubusercontent.com/51410244/106682630-e5b66800-65fd-11eb-83ab-40470f0c5b5d.png)

**Comment by blackholll** [comment]
非常抱歉，这个issue忘记回复了。 
你这个字段有在用么？ 我在1.1版本中修复吧。 大概2月底或者3月份发布
