### ISSUE TITLE
关于获取工单详情接口

### ISSUE THREAD

**Issue by fuzhuojun1** [blackholll/loonflow#228]
1、使用查询工单详情接口时，只有待审批状态下才能查看工单详情吗，为什么审批之后该用户再想看看已审批的历史工单调不出来工单详情了。
2、工单流转记录和工单处理步骤记录这两个接口在什么场景下会用到，工单进度条是调用这两个接口中的哪个？

**Comment by blackholll** [comment]
问题1：  见 https://github.com/blackholll/loonflow/issues/37 

问题2：
![image](https://user-images.githubusercontent.com/6269605/108199846-92452d80-7158-11eb-9d4b-4b588a0da0d0.png)
