### ISSUE TITLE
关于工单操作按钮

### ISSUE THREAD

**Issue by fuzhuojun1** [blackholll/loonflow#229]
从api/v1.0/tickets/{ticket_id}/transitions 接口可以得到工单流转信息，但是没有加签和转审的信息，每个审批人都可以对工单进行加签和转审的操作吗，能否在管理端控制每个审批人是否有加签及转审的功能？

**Comment by blackholll** [comment]
加签和 转交  前端根据用户有处理权限 就显示(transitions接口返回非空)
