### ISSUE TITLE
通知脚本模板

### ISSUE THREAD

**Issue by Becker345** [blackholll/loonflow#23]
请问通知的脚本，也是demo_script那个样子么？没有提供模板

**Comment by blackholll** [comment]
这个脚本和工作流状态脚本写法一样，tasks.py里面调用通知脚本的时候会将以下参数传过来，通知脚本直接使用就可以
`
globals = {'title_result': title_result, 'content_result': content_result,
                   'participant': ticket_obj.participant, 'participant_type_id': ticket_obj.participant_type_id,
                   'multi_all_person': ticket_obj.multi_all_person, 'ticket_value_info': ticket_value_info,
                   'last_flow_log': last_flow_log, 'participant_info_list': participant_info_list}
`
以下是demo
`
# demo_notice_script.py
def demo_script_call():
    phone_list = []
    email_list = []
    for participant_info in participant_info_list:
        phone_list.append(participant_info['phone'])
        email_list.append(participant_info['email'])
    r = requests.post('http://xxxxx.com/sendsms', {'phone':phone_list, 'context':content_result}) #发送短信，需要你的企业内有提供发送短信的接口
    r = requests.post('http://xxxxx.com/sendemail', {'phone':email_list, 'context':content_result,'title':title_result}) #发送短信，需要你的企业内有提供发送短信的接口
    return True, ''


demo_script_call()`

**Comment by Becker345** [comment]
好的， 谢谢～

**Comment by yslhzj** [comment]
### 工作流流转通知操作如下:

**一.在本地完成了企业微信的通知脚本 和邮件通知脚本的编写**

**二.将自定义通知脚本通过管理后台上传到工作流后台**

![image](https://user-images.githubusercontent.com/29890756/56267780-656dfc80-6122-11e9-9c52-604614a32238.png)

 **三.在工作流设置中进行脚本绑定**

![image](https://user-images.githubusercontent.com/29890756/56268031-0957a800-6123-11e9-8c9d-016b4756cca5.png)
 完成上述操作后,当状态变化时,系统会自动通知下一个节点.

**四,其它补充**

4.1 向通知脚本传递参数
![image](https://user-images.githubusercontent.com/29890756/56268335-a74b7280-6123-11e9-92d7-a68af6775b8e.png)

4.2 源码处理逻辑
![image](https://user-images.githubusercontent.com/29890756/56268181-52a7f780-6123-11e9-94aa-d71b13107563.png)
![image](https://user-images.githubusercontent.com/29890756/56268226-5d628c80-6123-11e9-9d02-6a97d5672eb7.png)

**Comment by blackholll** [comment]
v0.3版本已经重写了管理后台，配置界面更加简单了
![793527721CB9F736C66609B9F92EBEF4](https://user-images.githubusercontent.com/6269605/56268677-820b3400-6124-11e9-82cf-b6d45f6bed19.jpg)
![8AEADB31DF820BA409BA66986692C727](https://user-images.githubusercontent.com/6269605/56268678-820b3400-6124-11e9-8766-09a5c036ecc9.jpg)
