### ISSUE TITLE
r1.0.12版本：python3 run.py install出现如下报错

### ISSUE THREAD

**Issue by MarsLyn** [blackholll/loonflow#230]
![image](https://user-images.githubusercontent.com/40854628/108588759-c9ece900-7395-11eb-8c31-8f3d2fe2b70e.png)
你好请问那个环节出错了么？

**Comment by blackholll** [comment]
错误很明显， could not resolve host nginx.org.  你服务器无法连接外网？

**Comment by MarsLyn** [comment]
> 错误很明显，无法解析主机nginx.org。您服务器无法连接外网？
浏览器测试是可以正常访问外网的
并且直接使用这条命令的话rpm -Uvh http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
也是能正常安装的

**Comment by blackholll** [comment]
这个是容器里面无法访问外网。你网络环境是怎样的

**Comment by MarsLyn** [comment]
> 这个是容器里面无法访问外网。你网络环境是怎样的

![image](https://user-images.githubusercontent.com/40854628/108589361-e63e5500-7398-11eb-8e4c-f5898dc1ab9f.png)
无法访问外网，是这个原因么？

**Comment by blackholll** [comment]
https://blog.csdn.net/weiguang1017/article/details/76212203

**Comment by MarsLyn** [comment]
> https://blog.csdn.net/weiguang1017/article/details/76212203

感谢你，帮我把问题解决了，赞
