### ISSUE TITLE
关于显示流程图

### ISSUE THREAD

**Issue by fuzhuojun1** [blackholll/loonflow#233]
loonflow查看流程图用的哪个接口，前端能使用loonflow里面的流程图吗

**Comment by blackholll** [comment]
三个接口(分别是工作流基础信息、状态列表，流转列表)获取工作流相关信息，然后前端组合生成流程图的。 你的前端可以使用iframe嵌入流程图的页面。   不过建议自己写， 可以写的好看点
![image](https://user-images.githubusercontent.com/6269605/109372334-ef24ae80-78e3-11eb-8771-40f04430ab9d.png)
