### ISSUE TITLE
api调用时出现编码问题

### ISSUE THREAD

**Issue by MarsLyn** [blackholll/loonflow#234]
import requests,time,hashlib,json

timestamp = str(time.time())[:10]
ori_str = timestamp + 'b1386a30-7bef-11eb-b7cf-0242ac120004'
signature = hashlib.md5(ori_str.encode(encoding='utf-8')).hexdigest()
print(signature)

headers = dict(signature=signature, timestamp=timestamp, appname='intention', username='李四')
data = dict(workflow_id=1, transition_id=2)
r = requests.post('http://192.168.0.198/api/v1.0/tickets',headers=headers,data=json.dumps(data).encode('utf-8'))
print(r.json())

![image](https://user-images.githubusercontent.com/40854628/109778524-e1eb2500-7c3f-11eb-84c2-de5afe93696e.png)

**Comment by blackholll** [comment]
python2么？ 
在脚本第一行加上# coding=utf-8

**Comment by MarsLyn** [comment]
python3.8

**Comment by blackholll** [comment]
看起来像是header不支持中文。 username不要用中文。    
另外本身这个地方是传username的。你的用户同步到loonflow中 username是用中文的？

**Comment by MarsLyn** [comment]
的确是头部不能使用中文，我随便改成一个英文就解决了
![image](https://user-images.githubusercontent.com/40854628/109779874-5d010b00-7c41-11eb-80b4-76a40625f3f2.png)
username是需要使用：xs_zhangsan么？

**Comment by blackholll** [comment]
是的

**Comment by MarsLyn** [comment]
![image](https://user-images.githubusercontent.com/40854628/109781841-3512a700-7c43-11eb-82f8-eec3b289a393.png)
这个响应信息有点看不懂了

**Comment by MarsLyn** [comment]
![image](https://user-images.githubusercontent.com/40854628/109782157-86bb3180-7c43-11eb-8547-dc9e451e8ef4.png)
![image](https://user-images.githubusercontent.com/40854628/109782181-8c187c00-7c43-11eb-8ca4-b4e63e242974.png)
![image](https://user-images.githubusercontent.com/40854628/109782193-90449980-7c43-11eb-9230-4fb25c5c9ec6.png)
这个是我后台的基本配置

**Comment by blackholll** [comment]
看下loonflow的日志。 默认是在启动用户的家目录下  loonflow.log

**Comment by MarsLyn** [comment]
里面没有数据信息
![image](https://user-images.githubusercontent.com/40854628/109784983-97b97200-7c46-11eb-80bf-b177bdc63d32.png)

**Comment by blackholll** [comment]
docker componse启动的么？ 日志不应该为空的， 路径查看的对么？

**Comment by MarsLyn** [comment]
{address space usage: 261378048 bytes/249MB} {rss usage: 40849408 bytes/38MB} [pid: 17|app: 0|req: 67/242] 192.168.0.201 () {48 vars in 659 bytes} [Wed Mar  3 17:51:14 2021] POST /api/v1.0/tickets => generated 35 bytes in 134 msecs (HTTP/1.1 200) 4 headers in 114 bytes (1 switches on core 0) 这个是uwsgi的log

notice_manage" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36"
192.168.0.201 - - [03/Mar/2021:09:51:14 +0000] "POST /api/v1.0/tickets HTTP/1.1" 200 35 "-" "python-requests/2.23.0"这个是nginx的log

**Comment by MarsLyn** [comment]
![image](https://user-images.githubusercontent.com/40854628/109788077-ddc40500-7c49-11eb-895f-9a2473035c15.png)
数据库是正常的

**Comment by blackholll** [comment]
我说的是redis。 loonflow也会依赖redis。 你用docker启动的话，看下redis-server有没起来

**Comment by blackholll** [comment]
你这信息是提示redis端口已经被占用了，应该已经启动了。   你直接进到loonflowweb的容器里面去看下日志吧。 进程启动用户的家目录下

**Comment by MarsLyn** [comment]
选项：用于指定单选、多选、下拉框、多选下拉框字段的可选项目，格式为json如:{“1”:”中国”, “2”:”美国”},{“ch”:”中国”, “us”:”美国”}注意数字也需要引号

请问多选下拉框字段是那种级连字段，可以有多级选项的么，例如：
![image](https://user-images.githubusercontent.com/40854628/109937883-58545980-7d0a-11eb-871b-8b4c69861ed9.png)

**Comment by blackholll** [comment]
目前不支持级联，你可以配置在选项中，  然后给字段加个标签(和前端部分约定好规则)。前端根据这个标签特殊处理下这个字段的显示逻辑

**Comment by MarsLyn** [comment]
好的，谢谢

**Comment by MarsLyn** [comment]
请问docker部署的项目，如何解决前端请求的跨域问题？

**Comment by blackholll** [comment]
> 请问docker部署的项目，如何解决前端请求的跨域问题？

网上搜索下有很多解决方案
