### ISSUE TITLE
关于上一级部门（可不存在）审核问题

### ISSUE THREAD

**Issue by Seven7jr** [blackholll/loonflow#236]
状态： 申报（用户X，当前部门A）——上级部门审批（用户Y，部门B）——下一个状态S；
用户X（属于部门A）；
用户Y（可设置为审核员，属于部门B）；
部门B是部门A的上级部门。（部门B可能不存在，即部门A无上级部门）
如何实现：
1、如果部门B存在，用户X 提交了工单，由其部门的上级部门人员（例如用户Y）审批，审批后流转到S状态。
2、如果部门B不存在，用户X 提交工单后， 那么直接流转到下一个状态S。
3、如果用户Y， 提交工单， 工单直接流转到下一个状态S。

简而言之， 某个部门用户提交工单后，如果该用户所属部门存在上级部门，则上级部门审批；否则无需上一级部门审批，直接流转到状态S。另外，上级部门提交，则直接流转到S状态。

之前询问过，类似的问题，只不过那是一个部门情况，现在是设计成两个部门。

是不是也只能是：用hook来获取，当前部门的上一级部门的审核人，根据是否存在，来作为条件判断控制下一个状态，且处理人为工单字段？？有没有其他方式可参考？

**Comment by blackholll** [comment]
目前来说需要用hook方式。
后续loonflow会支持配置：  
1.如果节点的处理人计算为空时，是否直接跳过审批的设置。 计划在1.2.0版本支持
2.支持设置多级leader， 即审批人支持1级tl,2级tl,3级tl。 计划在1.2.0版本支持
