### ISSUE TITLE
启动后网页显示500报错

### ISSUE THREAD

**Issue by fuzhuojun1** [blackholll/loonflow#239]
## ISSUE TEMPLATE

使用的版本:1.0.13

问题详细描述:python manage.py runserver 0.0.0.0:8888 启动后 访问管理端显示500报错

是否查看了系统日志(默认在启动用户家目录下loonflow.log):未找到log文件

是否搜索过历史issue:是

做过哪些尝试:

**Comment by blackholll** [comment]
1.管理端指的是哪里？ 访问地址和截图看下
2.用什么用户启动的？ 去哪个目录没有发现日志文件
3.控制台也没有异常信息输出么

**Comment by fuzhuojun1** [comment]
1.就是访问loonflow的页面
2.用管理员用户启动的，找到loonflow.log文件了 里面是空日志
3.控制台没有任何输出
![1](https://user-images.githubusercontent.com/51150492/111937130-0ed57e00-8b02-11eb-8d36-bf00a35c949e.JPG)

**Comment by blackholll** [comment]
在当前服务器上 新建个终端，在命令行中curl http://127.0.0.1:8000看下两个终端的输出

**Comment by fuzhuojun1** [comment]
都没有输出。。。
![3](https://user-images.githubusercontent.com/51150492/111937867-af786d80-8b03-11eb-9e74-5fe65dd2eb8d.JPG)
