### ISSUE TITLE
脚本执行完成后如何流转到下一个节点

### ISSUE THREAD

**Issue by Becker345** [blackholll/loonflow#24]
当有个节点是执行脚本的时候，脚本执行完了，如何流转到下一个节点，在脚本里写调接口的代码么？

**Comment by blackholll** [comment]
目前的逻辑是脚本执行完成后，如果脚本执行成功了，就去查询以这个状态为起始状态的transtion记录，然后来将工单状态设置为目标状态。 这个逻辑已经实现了。你的脚本只需要处理你的逻辑，如果你的逻辑失败了就抛个异常，便于loonflow将这个异常捕捉到并记录到工单处理记录中取。。  其实这里最好是直接调用 TicketBaseService.handle_ticket方法。后续我会优化下

![1555644075840](https://user-images.githubusercontent.com/6269605/56403713-4348bb80-6295-11e9-8b02-f2b22132c809.jpg)

**Comment by blackholll** [comment]
Has been optimized： **https://github.com/blackholll/loonflow/releases/tag/v0.3.5**
