### ISSUE TITLE
Do you have any plan to make a tutorial?

### ISSUE THREAD

**Issue by huskier** [blackholll/loonflow#243]
Hi, do you have any plans to make a paid tutorial (in Shanghai) for grasping the loonflow in a short time? Thanks.

**Comment by blackholll** [comment]
If the price is attractive, I can consider it

**Comment by huskier** [comment]
You can arrange a workshop (or a training course) for a number of people. In this way, anybody could afford the class, and you will get an attractive offer.

Or, you coud arrange the workshop online, and anybody who is interested in the class has to register to participate the course.

BTW, where are you living?

**Comment by blackholll** [comment]
I live in Hangzhou, Zhejiang Province

Online course need a lot of time for prepare. 
Last year, I have made a course in www.toutiao.com。But just six class, then I  begin to  develop r2.0.0。
now r2.0 have  release a short time, and r2.1 will start soon。

maybe I will continue In the second half of the year

**Comment by huskier** [comment]
We're looking forward to the courses.

Maybe, there would be loonflowCon (or LFCon), just like PyCon, JuliaCon, and KiCon etc. The workflow is the crucial middleware for many application suits.

**Comment by blackholll** [comment]
I will  speed up optimize r2.0.x and r2.1.x recently. then online course maybe come soon

**Comment by huskier** [comment]
Thanks for your continuous efforts for developing loonflow!
