### ISSUE TITLE
关于表单字段不定数量工单问题

### ISSUE THREAD

**Issue by fuzhuojun1** [blackholll/loonflow#245]
## ISSUE TEMPLATE

使用的版本:1.0.12

问题详细描述: 审批表单中有不定数量字段的需求，申请单内有可能是一个人的信息，有可能是多人信息，这种情况怎么存到loonflow的表单字段中。
![1](https://user-images.githubusercontent.com/51150492/113383158-e0835880-93b5-11eb-8dfa-f1f88d5102a3.JPG)
![2](https://user-images.githubusercontent.com/51150492/113383162-e24d1c00-93b5-11eb-9cf5-883be24e0ece.JPG)

**Comment by blackholll** [comment]
新建一个自定义字段， 字段指定个标签， 前后端约定好，针对具有这个标签的字段做这种特殊的定制的显示和编辑逻辑。   用户填写后提交的时候，前端将这些信息组合成一个json格式 当做这个参数的值传给工单的接口
