### ISSUE TITLE
多人审批无效

### ISSUE THREAD

**Issue by hrLee340** [blackholll/loonflow#246]
## ISSUE TEMPLATE

使用的版本: 1.0.0

问题详细描述:对人审批不是根据状态中设置的全部处理做判断的吗？为何要根据 multi_all_person 判断是否是多人审批？

是否查看了系统日志(默认在启动用户家目录下loonflow.log):否

是否搜索过历史issue:是

做过哪些尝试:测试多人审批无效

**Comment by blackholll** [comment]
1.0.x的最新版本是1.0.13    https://github.com/blackholll/loonflow/releases/tag/r1.0.13
请使用1.0.13版本验证下
多人处理因为需要记录当前状态下所有人的处理操作是否相同，所有通过multi_all_person来记录每个人的操作

**Comment by hrLee340** [comment]
收到，感谢
