### ISSUE TITLE
结束流程无邮件发送

### ISSUE THREAD

**Issue by hrLee340** [blackholll/loonflow#247]
## ISSUE TEMPLATE

使用的版本:V1.0.0

问题详细描述: 流程进入到结束状态无邮件发送

是否查看了系统日志(默认在启动用户家目录下loonflow.log):否

是否搜索过历史issue:是

做过哪些尝试: 自己尝试新建流程到审批结束之后没有邮件发送提示流程已经结束

**Comment by blackholll** [comment]
1. 工单系统本身不提供发邮件的功能， 消息通知是通过hook，由hook的服务方自己实现通知逻辑
2. hook任务执行需要启动celery 任务，见 https://loonflow.readthedocs.io/zh_CN/r1.0.13/about/start/

另外1.0.x的最新版本为1.0.13请使用最新版本 https://github.com/blackholll/loonflow/releases/tag/r1.0.13
如果是新用户可以直接使用2.0.x的当前最新版本2.0.1
