### ISSUE TITLE
自定义字段是否可以动态设置选项？

### ISSUE THREAD

**Issue by yunweigo** [blackholll/loonflow#249]
## ISSUE TEMPLATE

使用的版本:  v1.0.11

问题详细描述: 自定义字段是否可以动态设置？
比如我申请阿里云的资源， 实例类型字段  我需要获取阿里云的接口获取实例类型  动态的展示到我的系统当中。 

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue: 是

**Comment by blackholll** [comment]
两中方案: 
1. 添加自定义字段的时候加个标签(和前端约定好)， 然后前端针对这种待标签的字段特殊处理(请求你的后端接口将返回值作为选项来展示)
2.loonflow的选项类型支持通过http请求获取(计划2.1.0版本支持， 近期开发中，发布时间待定)

**Comment by yunweigo** [comment]
http请求的设计思路怎样设计？

**Comment by blackholll** [comment]
自己的前端请求你的后端， 你的后端返回可选项
