### ISSUE TITLE
节点变化的时候，如何通知三方调用系统

### ISSUE THREAD

**Issue by Becker345** [blackholll/loonflow#25]
当节点流转的时候，如何通知三方调用系统，是在‘通知脚本’里写调用三方系统接口的代码, 然后三方系统收到调用后，再主动调loonflow的查询接口一次，以此来获取最新的状态流转。

**Comment by blackholll** [comment]
目前通知脚本的逻辑时：

**Comment by blackholll** [comment]
tasks.py-->send_ticket_notice

**Comment by Becker345** [comment]
嗯 其实我想请教的问题是如何让三方系统能及时收到状态的变化，而不需要三方系统定时轮询，那现在看来，办法就是把通知三方系统的逻辑，写到通知脚本里，以前我想的比较狭义，以为通知脚本里只写一些通知具体人的操作，比如发送钉钉通知这种逻辑。那我的需求来看，通知脚本里还是要加上通知三方系统的操作： 比如调一下三方系统的获取状态更新的接口。是这样不？

**Comment by blackholll** [comment]
三方系统需要知道状态变化的场景是什么？ 我的理解应该只是特定状态下需要知道状态。 比如用户发起了一个服务器权限申请的工单，然后当工单审批通过后，调用方需要执行具体的授权任务。
这种场景应该是通过状态设置处理人类型为脚本实现，状态脚本中调用三方系统，然后三方系统开始执行授权任务，状态脚本中轮询获取结果等执行完成后return。 这种流程节点大致为：发起人新建中-tl审批中- 授权脚本执行中-结束。
当然目前通过脚本来完成任务会存在一个问题，就是如果需要等任务执行完成后才将工单状态变为结束的话，需要在授权脚本中轮询获取任务执行的结果。 这种方式比较耗费loonflow的任务执行资源，当任务执行非常耗时时，可能会导致loonfow的其他任务阻塞。 

目前我在公司使用的版本已经改进了这种方式，而且也以及大范围使用。即通过hook的方式。 这种近期将移植到loonflow中。 具体逻辑如下：
状态的处理人类型新增一个hook的类型，处理人中填写hook_url, token(用于鉴权)，wait(是否等待hook目标执行完任务后回调后才变更工单的状态到下个节点)等信息。 当工单状态到此节点时，loonflow会调用hook_url，通过token签名，并将工单的一些信息作为参数。  这样你的系统收的这个hook请求后 就可以开始执行任务了，当你的任务执行完成后，再调用loonflow的一个接口，loonflow收到你的请求再触发工单的状态流转(如果wait配置为否，则不需要你回调)
此种方式的优点是：不需要在loonflow中管理很多的脚本。 具体的逻辑由业务方自己实现。 loonflow也不会有很多任务执行压力

**Comment by Becker345** [comment]
我这边的需求是，三方系统需要知道每个状态的流转情况，并发到群里，因为我要做一个问题反馈的流程，每一个节点的状态都需要及时反馈到群里，您刚提的新hook方式，也可以满足我的需求，现在在通知脚本里手动调三方系统的hook接口，也可以满足我的需求。显然新hook方式更好，新hook方式就不需要在有维护通知脚本了，希望尽快更新哈～

**Comment by blackholll** [comment]
每个节点都需要的话  还是建议写在通知脚本里面吧。不然你每个正常状态之间都需要加一个hook的状态。
本来：发起人新建中-tl审批中- 授权脚本执行中-结束 
要变成
发起人新建中--新建hook--tl审批中--tl审批hook- 授权脚本执行中--授权执行完成hook--结束.
这样显然流程太臃肿了

**Comment by Becker345** [comment]
嗯 是的
