### ISSUE TITLE
关于展现表单内置特殊字段显示中文名字

### ISSUE THREAD

**Issue by fuzhuojun1** [blackholll/loonflow#251]
## ISSUE TEMPLATE

使用的版本:V1.0.12

问题详细描述:工作流配置-编辑-展现表单的内置特殊字段 哪个字段是显示人员姓名,我选的participant_info.participant_name 显示的是用户名,全都是导入的英文名,如何显示用户姓名一栏的汉字名字.

**Comment by blackholll** [comment]
participant_info.participant_alias
