### ISSUE TITLE
管理端页面查看工单信息 带有空格数据显示不完整

### ISSUE THREAD

**Issue by fuzhuojun1** [blackholll/loonflow#253]
## ISSUE TEMPLATE

使用的版本:1.0.12

问题详细描述:管理端页面查看工单信息 带有空格数据显示不完整
![捕获2](https://user-images.githubusercontent.com/51150492/115804132-eef0ed00-a414-11eb-97a7-3a01aa98a06a.JPG)
![捕获1](https://user-images.githubusercontent.com/51150492/115804143-f57f6480-a414-11eb-8be4-f144bdee2ee1.JPG)
正常数据应该是图一 但是通过管理端查看工单数据“ - ”后面数据都不显示

**Comment by blackholll** [comment]
fixed https://github.com/blackholll/loonflow/releases/tag/r1.0.14
