### ISSUE TITLE
关于版本更新数据库字段报错

### ISSUE THREAD

**Issue by fuzhuojun1** [blackholll/loonflow#254]
## ISSUE TEMPLATE

使用的版本:r1.0.14

问题详细描述:由于1.0.12数据中包含空格 将版本升级到了1.0.14。数据库还是用的1.0.12的原数据库，运行loonflow时候报错
(1054, "Unknown column 'account_loonuser.type_id' in 'field list'"），是不是新版本中数据库增加了新字段，我如何使用原数据情况下增加这些字段。
![报错1](https://user-images.githubusercontent.com/51150492/115977103-52128900-a5a7-11eb-9725-951356b30673.JPG)

**Comment by blackholll** [comment]
r1.0.14版本有问题， 是基于r2.0.x checkout的分支。。 
回到r1.0.13吧。
等我重新发布1.0.14后再升级，或者看下当前1.0.14中的修改记录，本地临时先改下

**Comment by fuzhuojun1** [comment]
r1.0.13修复数据中有空格 显示不完整的bug了吗

**Comment by blackholll** [comment]
1.0.13未修复。可以看下更新日志
https://loonflow.readthedocs.io/zh_CN/r1.0.13/others/release_note/

**Comment by blackholll** [comment]
重新发布了1.0.14
