### ISSUE TITLE
【多人审批】

### ISSUE THREAD

**Issue by hrLee340** [blackholll/loonflow#255]
## ISSUE TEMPLATE

使用的版本: V1.0.13

问题详细描述: 多人审批中审批人审批之后打开界面后仍然有审批的权限（同一人可多次审批）

是否查看了系统日志(默认在启动用户家目录下loonflow.log): 否

是否搜索过历史issue: 是

做过哪些尝试: 测试

**Comment by blackholll** [comment]
提供相关信息
1.审批界面的截图
2.ticketrecord表中此工单的记录信息
3. 审批界面控制台中， transition接口返回的数据截图

**Comment by hrLee340** [comment]
基于目前的业务已对 loonflow 做较大改动，对于此问题现有处理方式是在 ticket_handle_permission_check 加限制条件，不知道有没有更好的办法

**Comment by blackholll** [comment]
你对工单处理相关有改动么？
说下你做了哪些改动？ 你你的改动导致的这个问题？  标准版本应该不存在这个问题的
