### ISSUE TITLE
docker-compose遇到多次部署失败，初始账号密码如何查询？

### ISSUE THREAD

**Issue by LazySongQ** [blackholll/loonflow#256]
## ISSUE TEMPLATE

使用的版本:
2.0.2
问题详细描述:
docker-compose遇到多次部署失败，初始账号密码如何查询？
是否查看了系统日志(默认在启动用户家目录下loonflow.log):
日志为空
是否搜索过历史issue:
只有5个，没有相关
做过哪些尝试:
查看Docker 日志 连接Redis异常

**Comment by LazySongQ** [comment]
loonflow-task_1   | [2021-04-27 18:00:49,480: ERROR/MainProcess] consumer: Cannot connect to redis://:**@loonflow-redis:6379/0: Error -2 connecting to loonflow-redis:6379. Name or service not known..
loonflow-task_1   | Trying again in 14.00 seconds...

**Comment by LazySongQ** [comment]
数据库为空

**Comment by blackholll** [comment]
docker -ps 查看下 redis是否正常启动了

**Comment by blackholll** [comment]
你这应该是部署过程失败了。 
检查下步骤
https://loonflow.readthedocs.io/zh_CN/r2.0.2/about/start/#docker-compose

**Comment by LazySongQ** [comment]
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2 "No such file or directory")

**Comment by LazySongQ** [comment]
> 你这应该是部署过程失败了。
> 检查下步骤
> https://loonflow.readthedocs.io/zh_CN/r2.0.2/about/start/#docker-compose

docker_compose_deploy_loonflow-redis_1   docker-entrypoint.sh redis ...   Up      0.0.0.0:6379->6379/tcp,:::6379->6379/tcp
docker_compose_deploy_loonflow-task_1    /bin/sh -c cd /opt/loonflo ...   Up                                              
docker_compose_deploy_loonflow-web_1     /bin/sh -c uwsgi /opt/loon ...   Up      0.0.0.0:80->80/tcp,:::80->80/tcp  
服务正常，登录web容器也能Telnet本机端口，
启动服务的时候碰到MySQL无法连接

**Comment by blackholll** [comment]
这是你授权有问题吧， 可以尝试用mysql客户端或者直接命令行看是否可以正常连接mysql
