### ISSUE TITLE
MySQL初始化失败，程序依然进行下一步

### ISSUE THREAD

**Issue by LazySongQ** [blackholll/loonflow#257]
## ISSUE TEMPLATE

使用的版本:
2.0.2
问题详细描述:
[root@iZbp1fyiki4t9twrn1v9cnZ docker_compose_deploy]#   python3 run.py install
------------------------------
开始导入初始化sql，需要下载镜像arey/mysql-client, 请耐心等候
docker run -i arey/mysql-client -hxxxxx -pxxxx -uloonflow loonflow < /data/loonflow/loonflow2.0.0_init.sql
ERROR 2003 (HY000): Can't connect to MySQL server on '192.168.100.63' (111 "Connection refused")

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:
![image](https://user-images.githubusercontent.com/83281049/116244566-9f0a8100-a79a-11eb-9fc3-6191632f600f.png)

做过哪些尝试:
修改MySQL-client镜像
手动导入MySQL数据

**Comment by LazySongQ** [comment]
MySQL端口有修改，最好修改一下run.py 对应添加端口参数-P

**Comment by blackholll** [comment]
初始化失败 还继续执行这个问题，后面优化下。

run.py 中不是有db_port参数么？

**Comment by LazySongQ** [comment]
> 初始化失败 还继续执行这个问题，后面优化下。
> 
> run.py 中不是有db_port参数么？

有参数，在初始化是没有生效的，因为没有写，默认就是3306

**Comment by blackholll** [comment]
你指的是这行，没有指定端口吧？  下个版本修复下
https://github.com/blackholll/loonflow/blob/master/docker_compose_deploy/run.py#L133

**Comment by blackholll** [comment]
已优化: https://github.com/blackholll/loonflow/releases/tag/r2.0.3
