### ISSUE TITLE
初始化之后使用默认admin账号密码登录没有反应

### ISSUE THREAD

**Issue by LazySongQ** [blackholll/loonflow#258]
## ISSUE TEMPLATE

使用的版本:
2.0.2
问题详细描述:
初始化之后使用默认admin账号密码登录没有反应
是否查看了系统日志(默认在启动用户家目录下loonflow.log):
日志为空，没有任何显示
是否搜索过历史issue:
没有相关
做过哪些尝试:

**Comment by LazySongQ** [comment]
![Uploading image.png…]()

**Comment by LazySongQ** [comment]
> 图片没上传成功。
> 是使用根目录下的loonflow2.0.0_init.sql导入的么？
> 前后后端是如何启动的？
> 登录时打开浏览器的控制台查看是否有网络请求，请求的返回结果是什么？
> 查看loonflow的日志是否有异常

使用的Docker-compose 启动的，是在初始化的时候自动导入的，日志就没有提示。。。

**Comment by blackholll** [comment]
登录时打开浏览器的控制台查看是否有网络请求，网络请求的地址是什么，请求的返回结果是什么？
