### ISSUE TITLE
为啥创建工作流时管理员，干预人，授权应用等不存数据库，而要等到修改工作流时才存

### ISSUE THREAD

**Issue by xiaodaidai9404** [blackholll/loonflow#259]
## ISSUE TEMPLATE

使用的版本: 2.0.2

问题详细描述: 为啥设置的时候创建工作流时管理员，干预人，授权应用等不存数据库，而要等到修改的时候再存，和前端web的话也对应不上

是否查看了系统日志(默认在启动用户家目录下loonflow.log): 是

是否搜索过历史issue: 是

做过哪些尝试: 理代码逻辑

**Comment by blackholll** [comment]
如果事实如你描述的话， 就是代码bug。  我晚上确认下

**Comment by blackholll** [comment]
已修复: https://github.com/blackholll/loonflow/releases/tag/r2.0.3
