### ISSUE TITLE
关于系统的几个疑问

### ISSUE THREAD

**Issue by Becker345** [blackholll/loonflow#26]
1. 节点的主动接单和直接处理和随机分配，是不是都是节点如果需要多人审批的情况下，只需要一个人审批，即发生节点流转？主动节点和直接处理的区别在哪里？都不接单和都不处理，结果不是一样的？
  2. 对子工作流的概念和用法不是很清楚。
  3. 考虑这样一个应用场景：三方系统有四个节点，A，B,  C，D。 要求每个点对点的流转后都要求不同的处理方式，例如：要求从A到B，和从C到B，要采用不同的处理方式。这样不同的处理，是不是就是要在通知脚本里，写if else来判断不同的流转采用不同的处理？因为同样也要保证三方系统的拓展性，而不能将这些不同的流转方式，在三方系统里写死。
感谢！
  4. 节点配置的’状态标签‘：
<img width="840" alt="image" src="https://user-images.githubusercontent.com/19348733/56457417-38814a00-63ad-11e9-9df3-21b5c2ab3304.png">
不很清楚它的应用场景和使用方法。

**Comment by blackholll** [comment]
1.主动接单、直接处理、随机处理主要是为了区分当前处理人实际为多个人的情况(状态的处理人类型为多人、处理人为角色且这个角色对应了多个人、处理人为部门且该部门下有多个人)。主动接单：当工单处理这个状态下，当前的处理人a,b,c需要其中一个人先接单(也就是将处理人设置为自己一个人，loonflow提供了接单的接口，当需要接单时transitions接口返回的是接单操作，调用方需要根据这个transiton的类型来确定用户点击时应该调用接单的接口，接单后工单处理人为a,其他人都不可以再处理)，先接单是为了避免a,b,c同时都在处理这个事情。 直接处理：a,b,c随便一个人直接按照正常的逻辑来处理，处理后工单状态发生变化。随机分配：loonflow会在工单到达此状态时将工单的处理人随机分配给a,b,c其中的一个人，这种场景可以是比如这类工单任务每天非常多，通过随机处理的方式将任务平均分配给a,b,c
2.关于子工作流，我这边用的比较多的是项目流程和应用流程。 一个项目的生命周期可以包括立项、开发中、测试中、预发中、上线中、完成等等状态。 而项目处于开发中时 可以是多个应用同时在开发，而每个应用的状态可能不一致，a应用在编码中 b应用在静态扫描中、c应用在单元测试中、d应用已经完成开发。如果需要a、b、c、d应用都开发完成后项目的状态自动变为测试中。那么可以在项目的开发中这个状态设置关联一个应用的工作流(也就是子工作流)
3.通知脚本建议只作为通知来用。 不同的流转到不同状态。你可以在相应的状态设置不同的执行脚本(处理人类型是脚本，处理人填写脚本id)
4.状态标签用户满足定制化需求。比如一个请假流程，状态有发起人创建中-tl审批中-hr审批中-财务处理中-结束。 你需要当tl审批时显示创建人历史假期余额以及请假详细记录。那么你可以在tl审批中这个状态配置个状态标签:{"commpents":["leave_history","vacation_balance"]}。那你前端定制处理的时候发现有这个标签就在工单详情界面展示请假信息的组件：leave_history， vacation_balance。 这两块代码你可以实现准备好，需要显示的时候才将这两块代码加载进来。
 
不知道我说清楚了没？

**Comment by Becker345** [comment]
感谢，还是有点疑惑，直接处理，不会发生a, b, c同时处理一件事情的情况么？我理解也是会的，只是假如三个人同时提交了意见，只有第一个提交的那个会提交成功，其他人不会提交成功；而接单的方式，我不清楚有什么用，我理解是不需要接单，也是只有一个会提交成功，需要接单，也是只有一个会提交成功，那还需要接单做什么呢？

**Comment by blackholll** [comment]
一个工作流:发起人新建中--[提交]--TL审批中--[同意]--运维人员处理中--[处理完成]--结束 (其中中括号内为可以做的操作)   。 主动接单这种形式， 当a、b、c同时打开工单详情界面时，操作都只有”接单“这个按钮。  a点击接单后，工单详情界面会出现”处理完成“的这个操作。这时如果b,c 再点击”接单“时 会接单失败。那么b,c就知道该工单已经有人在处理人。 a接单成功后开始处理，等待处理完成后，可以点击”处理完成“按钮。
直接处理是用于明确不会同时处理的情况，这里说的同时处理指的是比如安装一个操作系统、更换一块硬盘等等至少需要1分钟以上的操作，当a准备去做的时候，不需要b也重复去做。 而比如需要某人审批这种操作点击下同意或者拒绝就可以了，不用担心a和b同时重复在做一件事情。

**Comment by Becker345** [comment]
好的，明白了，感谢。
