### ISSUE TITLE
处理人类型常量前后端不一致

### ISSUE THREAD

**Issue by andy263** [blackholll/loonflow#260]
## ISSUE TEMPLATE

使用的版本: 2.0/2

问题详细描述:

后端定义的hook是10,PARTICIPANT_TYPE_HOOK = 10。前端配置成hook，保存后写进数据库的是19。

**Comment by blackholll** [comment]
是的，写错了，下个版本改下

**Comment by blackholll** [comment]
已修复： https://github.com/blackholll/loonflow/releases/tag/r2.0.3
