### ISSUE TITLE
点击工作流系统内部显示获取工作流基础信息失败:

### ISSUE THREAD

**Issue by LazySongQ** [blackholll/loonflow#263]
## ISSUE TEMPLATE

使用的版本:
2.0.2
问题详细描述:
获取工作流基础信息失败: (1054, "Unknown column 'workflow_workflowuserpermission.workflow_id' in 'field list'")
是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:

做过哪些尝试:

**Comment by LazySongQ** [comment]
附带出来的问题就是用户无法关联角色

**Comment by blackholll** [comment]
检查下sql导入是否成功：
https://github.com/blackholll/loonflow/blob/master/loonflow2.0.0_init.sql

**Comment by LazySongQ** [comment]
点击

> 检查下sql导入是否成功：
> https://github.com/blackholll/loonflow/blob/master/loonflow2.0.0_init.sql

因为改成手动部署了，所以确认数据是导入成功的

**Comment by andy263** [comment]
`CREATE TABLE `workflow_workflowuserpermission` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `creator` varchar(50) NOT NULL,
  `gmt_created` datetime(6) NOT NULL,
  `gmt_modified` datetime(6) NOT NULL,
  `is_deleted` tinyint(1) NOT NULL,
  `permission` varchar(100) DEFAULT NULL,
  `user_type` varchar(100) DEFAULT NULL,
  `user` varchar(100) DEFAULT NULL,
  `workflow_id_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `workflow_workflowuserpermission_workflow_id_id_0221212d` (`workflow_id_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;`

这个语句最后一个字段名写错了，需要手动改一下。应该是workflow_id

**Comment by blackholll** [comment]
是的，下个版本修复

**Comment by blackholll** [comment]
已修复: https://github.com/blackholll/loonflow/releases/tag/r2.0.3
