### ISSUE TITLE
流转中配置条件表达式在2.0版本中流程图不正常显示

### ISSUE THREAD

**Issue by Li-dacheng** [blackholll/loonflow#264]
## ISSUE TEMPLATE

使用的版本:r2.0.2

问题详细描述:在配置流转时，输入了条件表达式，目标状态需必填这是bug1，配置了条件表达式后，在流程图中显示了几个object Object，存在一个单独的条件表达式节点

是否查看了系统日志(默认在启动用户家目录下loonflow.log):否

是否搜索过历史issue:是

做过哪些尝试:在loonflow管理端看流程图是正常显示的

**Comment by blackholll** [comment]
提供下相关的截图、 条件表达式、 状态列表

**Comment by Li-dacheng** [comment]
> 提供下相关的截图、 条件表达式、 状态列表

- 流程图
<img width="441" alt="截屏2021-05-07 14 10 52" src="https://user-images.githubusercontent.com/46306557/117405446-38c1f300-af3e-11eb-9444-822902525f84.png">

- 条件表达式
<img width="677" alt="截屏2021-05-07 14 14 05" src="https://user-images.githubusercontent.com/46306557/117405662-8b9baa80-af3e-11eb-9395-b68a1817b40a.png">

- 状态列表
<img width="798" alt="截屏2021-05-07 14 16 34" src="https://user-images.githubusercontent.com/46306557/117405868-dfa68f00-af3e-11eb-8556-c8b18e14720e.png">

另外还测出一个bug：编辑流转的时候属性类型不回显，点击保存后新增了一条流转而非流转

**Comment by blackholll** [comment]
已修复: https://github.com/blackholll/loonflow/releases/tag/r2.0.3
不过流程图显示的不是太美观，后面抽空再优化下
