### ISSUE TITLE
打开所有流程速度过慢问题

### ISSUE THREAD

**Issue by hrLee340** [blackholll/loonflow#268]
## ISSUE TEMPLATE

使用的版本: V1.4

问题详细描述: 流程过多的时候打开界面很慢，有没有更好的优化方式？

是否查看了系统日志(默认在启动用户家目录下loonflow.log): 否

是否搜索过历史issue: 否

做过哪些尝试: 创建主键索引，修改orm查询方式效果不明显

**Comment by blackholll** [comment]
版本没有1.4。  是1.0.4版本么？

工单列表页可以尝试以下优化方法：
1. 查看数据库的慢查记录，找到慢查sql。针对性优化索引
2. 查询页面对查询时间限制，比如设置默认的查询时间范围为最近6个月
