### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by Baoanxia** [blackholll/loonflow#269]
File "C:\Desktop\shutongFlow-master\apps\service\views.py", line 32, in get
    if resp['code'] == 0:
TypeError: string indices must be integers
尝试网上各种方法 无果

**Comment by blackholll** [comment]
这是调用loonflow接口异常了 导致这里无法解析。 下面加个打印看下resp的内容。 或者你调试到这一步看下resp的值，里面有错误原因
![image](https://user-images.githubusercontent.com/6269605/118752293-62134500-b895-11eb-8e02-742fe225a71e.png)

**Comment by Baoanxia** [comment]
> 这是调用loonflow接口异常了 导致这里无法解析。 下面加个打印看下resp的内容。 或者你调试到这一步看下resp的值，里面有错误原因
> ![image](https://user-images.githubusercontent.com/6269605/118752293-62134500-b895-11eb-8e02-742fe225a71e.png)

感谢回复
