### ISSUE TITLE
关于上传功能

### ISSUE THREAD

**Issue by YuZongYangHi** [blackholll/loonflow#27]
是否考虑增加一个上传功能，比如我需要上传一个log文件， 到当前处理人后，可以点击下载之后，下载到本地

**Comment by blackholll** [comment]
loonflow不通过直接上传文件的功能，你可以通过自定义字段+ 字段标识来实现。 字段标识中标明是附件，前端处理的时候根据这个标识 实现一个单独的文件上传输入框，将文件上传到你自己后端。 然后提交工单的时候将文件路径传给loonflow。 loonflow只保存上传后文件的路径。 然后前端再次展示的时候可以支持根据文件路径来下载
