### ISSUE TITLE
给loonfow增加一个创建工单的时候去重的功能

### ISSUE THREAD

**Issue by zengshuaishuai** [blackholll/loonflow#270]
工单去重功能是根据创建字段做判断还是有其他方法？

**Comment by blackholll** [comment]
你的场景是：前端用户连续点击多次导致创建了重复的工单  还是比如不希望相关的订单号提交多条工单

**Comment by zengshuaishuai** [comment]
我的场景是用户创建工单点击提交完成后 不小心又创建了一条同样的工单 我希望当用户创建工单的时候如果有相同的工单前端会弹出一个提示框 提示工单重复创建

**Comment by blackholll** [comment]
这个不小心是怎么触发的？   提交后 窗口没关闭， 用户又点击了一次提交？---- 这种情况应该你的前段来解决， 点击提交后，按钮disable掉

如果是比较业务属性的去重， 你可以在你自己的后端查询去重，  如果重复直接返回，不去调用loonflow的接口。

**Comment by zengshuaishuai** [comment]
我这边的场景是与前端没多大关系，用户创建一条工单后，又不小心创建了一条相同的工单，属于后者吧发自我的华为手机-------- 原始邮件 --------发件人： blackholll ***@***.***>日期： 2021年5月19日周三 11:37收件人： blackholll/loonflow ***@***.***>抄送： Petrus ***@***.***>, Author ***@***.***>主    题： Re: [blackholll/loonflow] 给loonfow增加一个创建工单的时候去重的功能 (#270)

你的场景是：前端用户连续点击多次导致创建了重复的工单  还是比如不希望相关的订单号提交多条工单

**Comment by zengshuaishuai** [comment]
点击提交工单后，如果再创建一条一摸一样的工单,想在前端进行一个提示，这个我后端是需要根据提交的工单数据去loonflow数据库查重？

**Comment by blackholll** [comment]
是的
