### ISSUE TITLE
数据库导入失败

### ISSUE THREAD

**Issue by johntoms** [blackholll/loonflow#271]
## ISSUE TEMPLATE

使用的版本:r2.0.3

问题详细描述:mysql5.7.34 导入失败
![image](https://user-images.githubusercontent.com/33974450/119457581-6a282480-bd6e-11eb-9705-010eb56d18da.png)

是否查看了系统日志(默认在启动用户家目录下loonflow.log):是

是否搜索过历史issue:是

做过哪些尝试:更换系统 MAC 切换到 linux

**Comment by johntoms** [comment]
at line 1475: `workflow_id` 修改为 `id`后，成功导入。

**Comment by blackholll** [comment]
这里上次修bug,  误操作了。  吧workf  改回workflow_id
![image](https://user-images.githubusercontent.com/6269605/119462600-76fb4700-bd73-11eb-81ab-16361dda2277.png)

**Comment by johntoms** [comment]
谢谢，收到
