### ISSUE TITLE
pip 安装依赖包时，总是连接超时

### ISSUE THREAD

**Issue by johntoms** [blackholll/loonflow#272]
## ISSUE TEMPLATE

使用的版本:r2.0.3

问题详细描述: pypi.tuna.tsinghua.edu.cn 总是连接超时

是否查看了系统日志(默认在启动用户家目录下loonflow.log):是

是否搜索过历史issue:是

**Comment by blackholll** [comment]
可以临时换个源  https://pypi.douban.com/simple

**Comment by johntoms** [comment]
更改两个文件的依赖源可以解决
docker_compose_deploy/loonflow-web/Dockerfile
at 15 line: RUN pip3 install -r pro.txt -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host=mirrors.aliyun.com

docker_compose_deploy/loonflow-task/Dockerfile
at 11 line: RUN pip3 install -r pro.txt -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host=mirrors.aliyun.com

**Comment by johntoms** [comment]
> 可以临时换个源 https://pypi.douban.com/simple

**Comment by johntoms** [comment]
@blackholll 嗯嗯，这个问题解决了，我怕有人没发现所以提个 issue,以防有人再提这个问题！
