### ISSUE TITLE
frontend/src/pages/Ticket/TicketDetail/index.tsx fetchTicketDetailInfo函数缺乏对多选框的判断

### ISSUE THREAD

**Issue by lixiangzzz2017** [blackholll/loonflow#276]
## ISSUE TEMPLATE

使用的版本:r2.0.3

问题详细描述: frontend/src/pages/Ticket/TicketDetail/index.tsx fetchTicketDetailInfo函数缺乏对多选框的判断，当选择多个选项时，数据库会以","为分隔显示，但是处理的时候没有处理到"," 导致页面同意流程时报错 Unhandled Rejection (TypeError): values[key].join is not a function (handleTicket的多选框，多选下拉) 并且显示值错误(带上了",")。

是否查看了系统日志(默认在启动用户家目录下loonflow.log):是

是否搜索过历史issue:否

做过哪些尝试: fetchTicketDetailInfo函数添加上 else if (result.field_type_id === 50) {
            var values = result.field_value.split(",")
            formInitValues[result.field_key] = values;
          } 正常显示，但是没有考虑到值里面存在","的情况，建议以数组的形式存放

**Comment by blackholll** [comment]
我周末处理下， 或者你你可以提交个pr到v2.0.4分支

**Comment by lixiangzzz2017** [comment]
还有个问题:布尔类型在处理工单的时候时会遇到没有自动选中的问题。建议布尔类型使用switch 虽然我自己沿用了这个radiogroup 下面这个不是最好的解法
fetchTicketDetailInfo函数里面 else if (result.field_type_id === 20) {
            if (result.field_value) {
              formInitValues[result.field_key] = "true";
            } else {
              formInitValues[result.field_key] = "false";
            }
          }
看起来还有很多种情况没有处理。。

**Comment by blackholll** [comment]
是的 详情页完成度较低。 详情页比较复杂，  你有时间吧详情页给优化下么

**Comment by lixiangzzz2017** [comment]
可以。不过我主要写后端的 前端只是个半吊子。

**Comment by blackholll** [comment]
多选问题，改了下。  
https://github.com/blackholll/loonflow/releases/tag/r2.0.4
详情页比较复杂，暂时不继续该了，等有缘人帮忙修改
