### ISSUE TITLE
工单的子工单如何创建和正常使用

### ISSUE THREAD

**Issue by Lin-KFou** [blackholll/loonflow#280]
## ISSUE TEMPLATE

使用的版本: 2.0.2

问题详细描述: 在使用文档说明进行创建自动单，设置了参与人类型为个人，参与人设置为了loonrobot，当处理到此工作状态的时候，没有正确跳转到子工单的创建中，而是直接就完结了此工单，请问此工单下的自动单该如何进行创建呢。

是否查看了系统日志(默认在启动用户家目录下loonflow.log): 看过

是否搜索过历史issue: 搜索过，没有找到相关信息

做过哪些尝试:  没有做其他的尝试

**Comment by blackholll** [comment]
参见 #199

**Comment by Lin-KFou** [comment]
我看了Issues #199 可以理解为：是只能通过hook接口创建，不能直接在web页面端创建？

**Comment by blackholll** [comment]
如果你你自己写前端，就可以在前端新增一个如: 创建子工单的  按钮。 用户点击后，请求到你自己的后端，然后你后端调用loonflow的接口来创建子工单
