### ISSUE TITLE
如何用Python代码实现一个创建工单的例子？

### ISSUE THREAD

**Issue by huskier** [blackholll/loonflow#281]
## ISSUE TEMPLATE

使用的版本: r2.0.0

问题详细描述:
想用如下代码实现创建工单，但目前token不知如何获取，如下界面设置token不成功，返回错误如下：
{'code': -1, 'msg': 'permission check fail：The signature you provide in request header is invalid', 'data': {}}
![image](https://user-images.githubusercontent.com/5828575/122432243-bbbb7c00-cfc7-11eb-8966-aa7a54f230a7.png)

```
import requests
import json
import time
import hashlib

timestamp = str(time.time())[:10]
token = '069b4418-08a8-11eb-902e-acde48001122'
ori_str = timestamp + token
signature = hashlib.md5(ori_str.encode(encoding='utf-8')).hexdigest()
username = 'admin'
app_name = 'test'
headers = dict(signature=signature, timestamp=timestamp, appname=app_name, username=username)

post_url = "http://192.168.5.4/api/v1.0/tickets"
request_param = dict(title='测试工单0001', leave_start='2018-10-14 09:00:00', leave_end='2018-10-15 09:00:00',
              leave_proxy='lisi', leave_type='2', leave_reason='请假原因', workflow_id=1,
              username='guiji', transition_id=1)

r = requests.post('http://192.168.5.4/api/v1.0/tickets', headers=headers, json=request_param)
result = r.json()

print(result)
```

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:

做过哪些尝试:

**Comment by blackholll** [comment]
用v2.0.4分支吧。   当前已发布版本 sql有问题，导致这里无法添加记录。  
或者你把v2.0.4的分支中的初始化sql下载下来重新初始化数据库

**Comment by huskier** [comment]
用v2.0.4分支和把v2.0.4的分支中的初始化sql重新初始化数据库均出现错误：ERROR 1072 (42000) at line 1475: Key column 'workflow_id' doesn't exist in table

**Comment by huskier** [comment]
解决了正确初始化sql的问题后，python程序调用的创建新工单的例子仍然不能正常运行，提示如下错误。
{'code': -1, 'data': {}, 'msg': '此工单的必填字段为:attachment_field,multi_user_field,user_fleld,text_field,multi_select_field,select_field,leave_start,leave_end,leave_type,leave_reason,bool_field,checkbox_field,multi_checkbox_field'}

事实上，request_param 的参数我是从tests/test_views/test_ticket_view.py参考过来的。
```
import requests
import json
import time
import hashlib

timestamp = str(time.time())[:10]
token = '069b4418-08a8-11eb-902e-acde48001122'
ori_str = timestamp + token
signature = hashlib.md5(ori_str.encode(encoding='utf-8')).hexdigest()
username = 'admin'
app_name = 'test'
headers = dict(signature=signature, timestamp=timestamp, appname=app_name, username=username)

post_url = "http://192.168.5.4/api/v1.0/tickets"
request_param = dict(title='测试工单0001', leave_start='2018-10-14 09:00:00', leave_end='2018-10-15 09:00:00',
              leave_proxy='lisi', leave_type='2', leave_reason='请假原因', workflow_id=1,
              username='guiji', transition_id=1)

r = requests.post('http://192.168.5.4/api/v1.0/tickets', headers=headers, json=request_param)
result = r.json()

print(result)
```

**Comment by blackholll** [comment]
添加调用权限记录后 会生成你添加的appname 对应的token(如下图所示).  将代码中的token和app_name替换掉
![image](https://user-images.githubusercontent.com/6269605/122643220-34921380-d141-11eb-85d4-e45db3aaacb4.png)

**Comment by huskier** [comment]
您好，这一步我是做了的了，已经替换了app_name和token。我现在的问题应该是request_param参数可能不匹配，但这个参数我是从tests/test_views/test_ticket_view.py参考过来的，能否请您帮忙看下，如何填写好符合的完整参数，或者参考您代码中的哪句？

python程序调用的创建新工单的例子仍然不能正常运行，提示如下错误。
{'code': -1, 'data': {}, 'msg': '此工单的必填字段为:attachment_field,multi_user_field,user_fleld,text_field,multi_select_field,select_field,leave_start,leave_end,leave_type,leave_reason,bool_field,checkbox_field,multi_checkbox_field'}

**Comment by blackholll** [comment]
根据初始状态配置的表单字段， 对于必填属性的字段   需要传参

**Comment by huskier** [comment]
测试成功的单独Python文件的调用API的代码如下，若要成功运行，有一步需要做：在“用户及权限”的“调用权限”的“调用应用名”下的“ops”应用需要增加“工作流权限”的“请假申请”权限。

当然，r2.0.4版本中，“请假申请”流程中的自定义字段中的开始时间字段标识需要修改为"leave_start"，当前为“leave_start12”。

```
import requests
import json
import time
import hashlib

timestamp = str(time.time())[:10]
token = '4e57d414-c6aa-11ea-9ed0-784f437daad6'
ori_str = timestamp + token
signature = hashlib.md5(ori_str.encode(encoding='utf-8')).hexdigest()
username = 'admin'
app_name = 'ops'
headers = dict(signature=signature, timestamp=timestamp, appname=app_name, username=username)

post_url = "http://192.168.5.4/api/v1.0/tickets"
request_param = dict(title='测试工单20210620', bool_field=1, checkbox_field='1', multi_checkbox_field='1', select_field='1', multi_select_field='1,2', text_field='123456', user_fleld='dsfsffsdf', multi_user_field='dsfsffsdf', attachment_field='', leave_start='2018-10-14 09:00:00', leave_end='2018-10-15 09:00:00',
              leave_proxy='aaaa', leave_type='1', leave_reason=2, workflow_id=1, transition_id=1, username='guiji',)

r = requests.post('http://192.168.5.4/api/v1.0/tickets', headers=headers, json=request_param)
result = r.json()

print(result)
```
