### ISSUE TITLE
关于工单的“回退”功能

### ISSUE THREAD

**Issue by huskier** [blackholll/loonflow#282]
**使用的版本:** r2.0.0

**问题详细描述:**
[当前工单审批是否有“回退”功能？希望能有(https://github.com/blackholll/loonflow/issues/98)提到的“回退”功能，比如说退到发起人，发起人根据“回退意见”修改后再次进入审批流程。

**是否搜索过历史issue:** 是的！

**Comment by huskier** [comment]
您好，所提到的“回退”功能如下图所示，只有文档发起人可以修改文档，修改后再次按照审批流的顺序进入审批流。

![审批流程回退](https://user-images.githubusercontent.com/5828575/122786945-68a73900-d2e7-11eb-9316-8925814f1701.png)

**Comment by blackholll** [comment]
因为https://github.com/blackholll/loonflow/issues/98中提到一系列原因， 暂时不会加入这种自由选择目标状态的回退功能。 
当前的版本是支持回退到非初始状态的，取决于你配置流转时选择的目标状态，你可以配置的时候将回退流转的目标状态到任意状态

**Comment by huskier** [comment]
通过自己实际操作工作流，好像能明白什么意思了。多谢！
