### ISSUE TITLE
新建通知管理失败

### ISSUE THREAD

**Issue by luozhijunroy18** [blackholll/loonflow#283]
## ISSUE TEMPLATE

使用的版本: 2.0.4

问题详细描述: 在loonflow管理后台新建通知， 页面显示成功， 实际接口报错， 只是status_code返回200
![image](https://user-images.githubusercontent.com/42432108/123032575-ba9bac00-d418-11eb-9d2e-6d4f00684910.png)
![image](https://user-images.githubusercontent.com/42432108/123032619-d43cf380-d418-11eb-9bdd-9919d05f67d1.png)
![image](https://user-images.githubusercontent.com/42432108/123032706-fdf61a80-d418-11eb-9565-d71f6cf93d57.png)

是否查看了系统日志(默认在启动用户家目录下loonflow.log): 是

是否搜索过历史issue: 是

做过哪些尝试:

**Comment by blackholll** [comment]
2.x版本以后 bootstrap的管理后台已经弃用，后续将移除代码。
直接访问ant desgin的管理后台(路径不带manage)， 参见：https://loonflow.readthedocs.io/zh_CN/r2.0.4/about/start/
