### ISSUE TITLE
前端设定了proxy dev 地址无效

### ISSUE THREAD

**Issue by a-bo** [blackholll/loonflow#284]
## ISSUE TEMPLATE

使用的版本:
v2.0.4
问题详细描述:
前端设定了proxy dev 地址无效，登录操作时的接口地址任然是localhost:xxx，而不是我配置的proxy地址

是否查看了系统日志(默认在启动用户家目录下loonflow.log):
是
是否搜索过历史issue:
是
做过哪些尝试:

**Comment by blackholll** [comment]
你如何设置的  修改的哪个文件？
另外，你为何需要该这个地址？ npm run dev开发模式下的，如果生产环境使用， 可以使用nginx代理。  文档中有部署方式
https://loonflow.readthedocs.io/zh_CN/r2.0.4/about/start/#id3

**Comment by a-bo** [comment]
修改路径是：fronted/config/proxy.ts

**Comment by blackholll** [comment]
后端有通过这个地址启动么？ 后端默认是127.0.0.1下启动的。 python manage.py runserver 0.0.0.0:8000
