### ISSUE TITLE
编辑工作流【状态】不断地出现json转义

### ISSUE THREAD

**Issue by luozhijunroy18** [blackholll/loonflow#286]
## ISSUE TEMPLATE

使用的版本:  r2.0.4

问题详细描述:
![image](https://user-images.githubusercontent.com/42432108/123416772-9216dc00-d5e9-11eb-88cb-fe0989ade569.png)
![image](https://user-images.githubusercontent.com/42432108/123416835-a35fe880-d5e9-11eb-9fc2-e7f53438b4da.png)

尤其是第一条【状态】出现频率更高

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:

做过哪些尝试:

**Comment by blackholll** [comment]
目前的现象是 点击编辑后， 关闭，再次编辑会出现这个问题， 下个版本修复下

**Comment by blackholll** [comment]
修复代码已经提交到分支: v2.0.5

**Comment by blackholll** [comment]
fixed: https://github.com/blackholll/loonflow/releases/tag/r2.0.5
