### ISSUE TITLE
On transition_id

### ISSUE THREAD

**Issue by huskier** [blackholll/loonflow#287]
## ISSUE TEMPLATE

**使用的版本:** r2.0.4

**问题详细描述:**
假如有一个流程：
部门经理：同意(transition_id=28), 回退(transition_id=29)
       总监：同意(transition_id=30), 回退(transition_id=31)
   总经理：同意(transition_id=32), 回退(transition_id=33)

在写工单处理程序的时候，request.POST得到的是泛泛的request.user，并不知道该用户的角色，但可以查到request.user的待处理工单，这个时候有什么办法来确定当前用户“同意”或者是“回退”的transition_id呢？因为要处理工单必须得有这个transition_id。

**是否查看了系统日志(默认在启动用户家目录下loonflow.log):** Yes

**是否搜索过历史issue:** Yes

做过哪些尝试:

**Comment by blackholll** [comment]
用户打开工单详情的时候调用loonflow的工单详情接口，详情接口中会返回用户在当前状态下可以做的操作(transition列表)，前端显示对应的按钮。 
用户点击按钮（对应的transition）后，后端请求loonflow的处理工单接口，参数中包含transition_id

**Comment by huskier** [comment]
应该是如下操作，还得多读文档啊，多谢！

获取工单可以做的操作
api/v1.0/tickets/{ticket_id}/transitions

**Comment by huskier** [comment]
应该是如下操作，还得多读文档啊，多谢！

获取工单可以做的操作
api/v1.0/tickets/{ticket_id}/transitions
