### ISSUE TITLE
建议将“获取工单列表”返回数据中的ticket_id字段（当前字符串为"id"）修改为字符串"ticket_id"

### ISSUE THREAD

**Issue by huskier** [blackholll/loonflow#288]
## ISSUE TEMPLATE
**使用的版本:** r2.0.4

**问题详细描述:**
当前通过“获取工单列表”返回数据中的ticket_id字段的字符串为“id”，建议修改为“ticket_id”，这样在写程序的时候比较清晰。因为涉及到id的有transition_id, workflow_id, ticket_id等。

**是否查看了系统日志(默认在启动用户家目录下loonflow.log):** 是

**是否搜索过历史issue:** 是

**Comment by blackholll** [comment]
下个大版本的的时候可以考虑下，小版本改动可能影响比较大

**Comment by huskier** [comment]
OK, Thanks.
