### ISSUE TITLE
About is_staff property of class LoonUser(AbstractBaseUser):

### ISSUE THREAD

**Issue by huskier** [blackholll/loonflow#292]
其中属性is_staff返回is_active是明确的吧？
![image](https://user-images.githubusercontent.com/5828575/126906178-036169d3-0f1a-4489-b413-4561f41e96ef.png)

**Comment by blackholll** [comment]
啥叫 是明确的？
这个地方加上is_staff 印象中是因为django自定义user必须定义is_staff属性，否则会报错。 实际我是没有用到这个属性的

**Comment by huskier** [comment]
关键是定义的是is_staff，但是返回值是is_acitve，明确的意思是确定是要这样吗？

**Comment by blackholll** [comment]
这里因为不想加个is_staff字段， 也不想改django本身的逻辑。  所以直接返回的is_active。 
is_active本来设计是用来标识用户是否在职的

**Comment by huskier** [comment]
Thanks for your explanation.
