### ISSUE TITLE
新版管理后台 删除工作流按钮无效

### ISSUE THREAD

**Issue by luozhijunroy18** [blackholll/loonflow#295]
## ISSUE TEMPLATE

使用的版本:r2.0.5

问题详细描述: 新版管理后台， 点击删除工作流按钮无效
![image](https://user-images.githubusercontent.com/42432108/128112581-8d73959c-9d3e-47c7-a52e-8160f9ae6026.png)

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue: 是

做过哪些尝试: 查看控制台， 应该是前端没有触发相关删除工作流接口

**Comment by blackholll** [comment]
确实是的， 我周末发个版本修复下

**Comment by blackholll** [comment]
fixed in v2.0.6 分支，
因为临时发现另外一个bug： 多人全部处理时， 一个人处理后，另外一个人无法处理。    这周来不及修复，所以先不发布了

**Comment by blackholll** [comment]
fixed in  r2.0.6 release
