### ISSUE TITLE
工作流 -基础信息-  API授权应用  增加授权应用 无效

### ISSUE THREAD

**Issue by luozhijunroy18** [blackholll/loonflow#296]
## ISSUE TEMPLATE

使用的版本:r2.0.5

问题详细描述: 新版管理后台，工作流 -基础信息-  API授权应用  增加授权应用 无效。  但是可以删除授权应用
必须到 用户及权限 - 调用权限 中增加才行
![image](https://user-images.githubusercontent.com/42432108/128153017-e8ec92bb-489a-4115-b85c-e78669cc48e5.png)

是否查看了系统日志(默认在启动用户家目录下loonflow.log): 

是否搜索过历史issue:

做过哪些尝试:

**Comment by blackholll** [comment]
我这边没有复现，  你操作的时候打开浏览器控制台， 提交后，看下网络请求中中的参数截个图贴出来

**Comment by luozhijunroy18** [comment]
https://user-images.githubusercontent.com/42432108/128290753-d0ee8b9e-c6d4-4290-a027-b9eeacaa6a33.mov
如果在这个页面新增， 是把id传进去了
![image](https://user-images.githubusercontent.com/42432108/128290921-5872162f-42f4-4e0e-ac76-6cea2784b8ca.png)
如果更新， 是把值穿进去了
![image](https://user-images.githubusercontent.com/42432108/128291234-2080a096-691c-4cec-9953-1e08771dbbac.png)

**Comment by blackholll** [comment]
你确定是r2.0.5的代码？  你怎么获取代码的
![image](https://user-images.githubusercontent.com/6269605/128619043-9d77a89e-337a-463a-9c27-316c34cf9fbf.png)

**Comment by luozhijunroy18** [comment]
我可能没说清楚步骤， 你在工作流详情页面， 先把所有【API授权应用】全部删除， 保存， 然后再在这个页面添加权限，就复现了。 应该是【API授权应用】从无到有 这种情况下才会出现， 应该是前端的问题

**Comment by blackholll** [comment]
确实有问题， 我周末修下

**Comment by blackholll** [comment]
实际现象是：
删除工作流中配置的api授权应用后，无法再次添加回来

fixed : r2.0.6
