### ISSUE TITLE
关于流程图dagre d3的问题

### ISSUE THREAD

**Issue by caoqianming** [blackholll/loonflow#297]
## ISSUE TEMPLATE

使用的版本:最新

问题详细描述:dagre d3不更新了，有其他可选的么，不过感觉d3挺简单好用的

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:

做过哪些尝试:

**Comment by blackholll** [comment]
纯流程图展示 当前dagred3支持的功能足够了。 
近期打算将流程设计这块支持拖拽配置，计划采用logicflow。
另外x6 也是不错的流程编辑器

**Comment by caoqianming** [comment]
嗯，谢谢。确实展示够用了挺好的
