### ISSUE TITLE
角色新增用户, 前端搜索不展示, 但是搜索接口是正常返回的

### ISSUE THREAD

**Issue by luozhijunroy18** [blackholll/loonflow#298]
## ISSUE TEMPLATE

使用的版本: r2.0.6

问题详细描述:
![image](https://user-images.githubusercontent.com/42432108/130412945-b99a7950-cc1b-43df-8ae7-29b095fa1234.png)
![image](https://user-images.githubusercontent.com/42432108/130413584-1c8f36e8-edc7-4de7-8969-b505291636c5.png)

![image](https://user-images.githubusercontent.com/42432108/130413447-1045c995-af64-4dd1-bd39-53e91990db8b.png)

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:

做过哪些尝试:

**Comment by blackholll** [comment]
问题将于 r2.0.7 修复

**Comment by blackholll** [comment]
fixed in https://github.com/blackholll/loonflow/releases/tag/r2.0.7
