### ISSUE TITLE
删除工作流中配置的api授权应用后，无法再次添加回来, 这个问题在r2.0.6中仍然存在

### ISSUE THREAD

**Issue by luozhijunroy18** [blackholll/loonflow#299]
实际现象是：
删除工作流中配置的api授权应用后，无法再次添加回来
![image](https://user-images.githubusercontent.com/42432108/130421798-12ec915b-1b8c-413c-9d93-8ea4666bbd95.png)
页面显示样子正常， 但是传给后端的数据有问题。

fixed : r2.0.6

_Originally posted by @blackholll in https://github.com/blackholll/loonflow/issues/296#issuecomment-903118406_

**Comment by blackholll** [comment]
我复现不了。。。  你调试解决下 提个pr呗

**Comment by luozhijunroy18** [comment]
在这个页面全部删除权限， 然后添加，
![image](https://user-images.githubusercontent.com/42432108/130722033-8fb94186-d87e-4f96-980e-a56fc5e49bc2.png)

然后在这个页面查看结果， 是没有出现已添加的权限
![image](https://user-images.githubusercontent.com/42432108/130722012-ca071d97-6206-4c37-914d-b12c479130c9.png)

**Comment by blackholll** [comment]
fixed in https://github.com/blackholll/loonflow/releases/tag/r2.0.7
