### ISSUE TITLE
条件流转

### ISSUE THREAD

**Issue by Becker345** [blackholll/loonflow#30]
1. 请问怎么实现一个条件流转，拿请假流程为例，当请假天数小于等于三天时，只需要直属上级审批->结束；当请假天数大于三天时，就需要直属上级->hr部门审批->结束。
2. 一开始我想在transition上配条件表达式,形如： {'expression':'{leave_days} > 3', 'target_state_id':4}， {'expression':'{leave_days} <= 3', 'target_state_id':3}，分别配这样两条transition： 提交到hr和提交到直属上级，但是那样前端拿到的操作是这两个，让用户选择提交到哪个，不符合要求。

**Comment by blackholll** [comment]
[{"expression": "{leave_days} > 3", "target_state_id": 4}, {"expression": "{leave_days} <= 3","target_state_id": 3}]
json格式

**Comment by Becker345** [comment]
我可能没说清楚，在直属上级这个节点之后，写条件表达式的话，像这样：
![image](https://user-images.githubusercontent.com/19348733/56561852-9f377b00-65da-11e9-8643-0e7d953d3092.png)
就会出现这样的情况：
![image](https://user-images.githubusercontent.com/19348733/56561660-3b14b700-65da-11e9-8bc3-f2c348e2d026.png)
到了直属上级审批的节点，前端出现两个transition，不符合要求，要三方调用的前端根据返回的transition，来自己判断显示哪些transition么？

**Comment by Becker345** [comment]
在这个流转里配条件表达式：
![image](https://user-images.githubusercontent.com/19348733/56566960-74ebba80-65e6-11e9-8562-6ff54c0dcd81.png)
应该可以做到根据条件直接走结束节点，或者走hr这个节点，但是流程图上，就没有直属上级到结束节点这条流转，导致流程图和真实的流程不一致，流程图不完整。

**Comment by Becker345** [comment]
已解决。
如图：
![image](https://user-images.githubusercontent.com/19348733/56569163-107f2a00-65eb-11e9-84e6-8528a6ab23a3.png)
将TL审批到结束这条流转的属性类型设为拒绝或其他，前端可以据此不展示这个操作，并在TL审批到hr审批这个流转上设条件表达式，即可。

**Comment by blackholll** [comment]
你这个流程设计有两个问题：
1. 保存操作不可以目标状态是初始状态，你可以有“发起人-创建中”，“发起人-编辑中”， “TL审批中”，“人事部门-处理”，“结束”。可以在“发起人-编辑中”这个状态设置保存(目标状态也发起人编辑中)。初始状态只在创建的时候有效。退回也应该只退回到如“发起人编辑中”这样的状态。
2.条件表达式这里，应该是配置个流转(初始状态是TL审批， 然后设置上面的那个条件表达式。loonflow中当设置了条件表达式后，将以条件表达式中指定的目标为准)

**Comment by blackholll** [comment]
另外目前v0.3中，查看流程图中显示的流程图没考虑条件流转的情况，也就设置了条件流转，但是这个自动生成的流程图中没有体现条件的逻辑。 这个我后续会优化下
