### ISSUE TITLE
【需求】在工作流状态列表展示ID, 以便写条件表达式target_state_id

### ISSUE THREAD

**Issue by luozhijunroy18** [blackholll/loonflow#300]
## ISSUE TEMPLATE

使用的版本: 2.0.6
问题详细描述:
【需求】希望在工作流状态列表展示ID, 以便写条件表达式target_state_id

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:

做过哪些尝试:

**Comment by blackholll** [comment]
将于 r2.0.7 支持

**Comment by blackholll** [comment]
optimize in https://github.com/blackholll/loonflow/releases/tag/r2.0.7
