### ISSUE TITLE
r2.0.6版本如何新建工单？

### ISSUE THREAD

**Issue by seasonhallym** [blackholll/loonflow#303]
## ISSUE TEMPLATE

使用的版本:r2.0.6

问题详细描述:没有新建工单按钮

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:是

做过哪些尝试:其他三方demo部署，未成功
![image](https://user-images.githubusercontent.com/8360436/134308545-35938c85-8220-4356-a4cd-458f84eda59d.png)

**Comment by blackholll** [comment]
看文档：   https://loonflow.readthedocs.io/zh_CN/r2.0.6/about/start/

2.0.x版本提供了新的前端页面。 你截图中的页面已废弃

**Comment by seasonhallym** [comment]
老师，介绍文档中的端口信息错了。
![image](https://user-images.githubusercontent.com/8360436/134447594-1179897d-7eb7-4e7f-b5c6-c0e1677f2467.png)
老师，是参照您这个启动过程执行，刚接触这一块内容，是个小白，还是不得要领，麻烦老师再给俺指导下，您这个前端页面在哪里启动，在哪里登录？

如下截图的界面在哪里？
![image](https://user-images.githubusercontent.com/8360436/134447993-55a04f2f-683a-48f6-ae43-6b8108d0ab1f.png)
麻烦老师指导一下
