### ISSUE TITLE
account_base_service.py 中 188 行代码是否有点小问题？

### ISSUE THREAD

**Issue by simonzhang98** [blackholll/loonflow#306]
account_base_service.py 中 188 行代码是否有点小问题？       

user_dept_queryset = LoonUserDept.objects.filter(user_id=user_obj.id, is_deleted=0).all()
user_dept_id_list = [user_dept.dept_id for user_dept in user_dept_queryset]
for user_dept_id in user_dept_id_list:
       iter_dept(user_obj.dept_id)

**Comment by blackholll** [comment]
fixed in https://github.com/blackholll/loonflow/releases/tag/r2.0.7
