### ISSUE TITLE
删除节点后， 获取工单列表报错

### ISSUE THREAD

**Issue by luozhijunroy18** [blackholll/loonflow#307]
optimize in https://github.com/blackholll/loonflow/releases/tag/r2.0.7

_Originally posted by @blackholll in https://github.com/blackholll/loonflow/issues/304#issuecomment-932882512_

**Comment by luozhijunroy18** [comment]
版本：r2.0.8

操作步骤：工单管理/所有工单

错误日志： 
File "/opt/loonflow/service/ticket/ticket_base_service.py", line 182, in get_ticket_list
    state_name = state_obj.name
AttributeError: 'str' object has no attribute 'name'

![image](https://user-images.githubusercontent.com/42432108/137454865-cbe33744-fd19-4477-b0d7-3ea1bbe060e5.png)

**Comment by blackholll** [comment]
这里可以简单优化下， state_name = state_obj.name if state_obj else '未知'
你可以自行改下，或者等我下个版本优化下

**Comment by blackholll** [comment]
更正下， 应该是 state_name = state_obj.name if flag else '未知'
v2.0.9分支已优化， 近几天会发布r2.0.9版本

**Comment by blackholll** [comment]
已优化: https://github.com/blackholll/loonflow/releases/tag/r2.0.9
