### ISSUE TITLE
如何从角色中选取审批人

### ISSUE THREAD

**Issue by caoqianming** [blackholll/loonflow#308]
## ISSUE TEMPLATE

使用的版本:最新

问题详细描述:
比如有一个合同审批，开始之后下一个节点是部门法律专员审批，这个应该是个角色，但这个角色下可能有多个人员(A部门，B部门都可能有这类人员)，而实际审批人应该是创建的该审批归属部门(一般就是创建人所属部门)的法律专员。这种情况应该如何处理呢

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:

做过哪些尝试:尝试用变量来解决，但感觉不太合适。想着用脚本来实现，自定义脚本用于返回执行人

**Comment by caoqianming** [comment]
嗯。我也倾向于方案4，我看现在hook和脚本都是执行某项操作。可以多加一个字段标记该脚本或hook是用来返回实际处理人，然后继续原工单处理流程，如果是这样的话那么当前的变量即create_TL也可以用这种方法实现。不知这种想法有没有什么问题

**Comment by blackholll** [comment]
区分下类型 比较好， 新增一个类型。外部获取。  填写url、token信息，约定一个返回格式， 如{"code":0, data:"zhangsan,lisi,wangwu", msg:"获取处理人成功"}
你可以实现下这个功能， 然后提交PR到v2.0.9分支

**Comment by caoqianming** [comment]
我又想了一个解决办法，我始终觉得能不用hook就不用，毕竟也是一种常见需求。我现在想的是这样做，增加一个参与人过滤策略字段，目前有这几个值
`state_filter_choices=(
        (0, '无'),
        (1, '和工单同属一部门'),
        (2, '和创建人同属一部门'),
        (3, '和当前处理人同属一部门'),
        (4, '和工单同属一上级部门'),
        (5, '和创建人同属一上级部门'),
        (6, '和当前处理人同属一上级部门'),
    )`

然后在获取下一步处理人时再多一步处理，您觉得呢

**Comment by caoqianming** [comment]
当然肯定不能满足所有，fromhook还是需要的

**Comment by blackholll** [comment]
这里做成通用功能，就是需要类似下图所示， 支持直接发写代码计算处理人。 吧简单的逻辑直接写在配置中， 支持执行。
![image](https://user-images.githubusercontent.com/6269605/138200495-9b8b23ce-dae8-4895-b09b-2219f172ce80.png)
