### ISSUE TITLE
附件上传异常

### ISSUE THREAD

**Issue by seasonhallym** [blackholll/loonflow#309]
![image](https://user-images.githubusercontent.com/8360436/138009052-368bfcab-d237-47c0-9304-03f9b10848fd.png)
附件上传的时候提示找不到文件夹或者路径，请教下是如何添加这个路径。

**Comment by blackholll** [comment]
配置文件中改下media路径  MEDIA_URL。  或者创建下这个目录/opt/loonflow/medis/ticket_file

**Comment by blackholll** [comment]
生产环境方式启动的么？  生产环境用nginx的话需要将这个目录配置到反向代理里面去。 docker_compose_deploy目录下有nginx的配置文件，可以参考下
