### ISSUE TITLE
流转配置的属性类型的疑问

### ISSUE THREAD

**Issue by Becker345** [blackholll/loonflow#31]
对流转配置中这个字段：
![image](https://user-images.githubusercontent.com/19348733/56565724-98613600-65e3-11e9-96d6-f447bfc35efd.png)
感觉不太明白。
这个流转在业务上是个退回操作，但是这里也要配同意，这里配拒绝和其他的场景是什么呢?这个字段配置的意义是什么?

**Comment by blackholll** [comment]
1.因为loonflow在使用过程中 可能会需要和别的工单系统交互。 有些工单系统操作只有同意和拒绝。 当在loonflow中有个操作后，调用别的工单系统时 需要有这个操作的对应关系。所以这里有同意和拒绝以及其他
2.设置同意拒绝后，当工单处理后可以给工单设置一个标识：是否被拒绝。 这样查询工单列表的时候就可以查询被拒绝的工单了
