### ISSUE TITLE
操作记录状态栏中的HTTPConnectionPool

### ISSUE THREAD

**Issue by Lin-KFou** [blackholll/loonflow#312]
在使用hook进行工单流转后，操作记录中的hook状态栏显示下面的问题：
HTTPConnectionPool(host='xx.xx.xx.xx', port=4000): Read timed out. (read timeout=10)
请问这个地方该如何进行解决呢?

![image](https://user-images.githubusercontent.com/39783009/139225705-a987223d-b668-49cf-b713-e223a6a77636.png)

> 备注：
> 整个工单调用hook正常，可以完成整个工单

**Comment by Lin-KFou** [comment]
wait配置的是：true
hook主要做一些任务的采集，数据的写入等，有些快的可能3-15s，慢的差不多3-5min，请求任务执行完成后才进行工单的回调

**Comment by blackholll** [comment]
两个问题：

**Comment by blackholll** [comment]
未知操作   问题已修复:https://github.com/blackholll/loonflow/releases/tag/r2.0.9

**Comment by blackholll** [comment]
未知操作   问题已修复:https://github.com/blackholll/loonflow/releases/tag/r2.0.9
