### ISSUE TITLE
加签点击“完成”报错：参数不合法,请提供username，transition_id

### ISSUE THREAD

**Issue by seasonhallym** [blackholll/loonflow#313]
## ISSUE TEMPLATE

使用的版本:V2.0.6

问题详细描述:
![image](https://user-images.githubusercontent.com/8360436/140268726-ec8fee72-8dcf-47b3-b6ea-ff5e0c00da70.png)

是否查看了系统日志(默认在启动用户家目录下loonflow.log):日志内只显示启动日志

是否搜索过历史issue:是

做过哪些尝试: 初学者，未能找出哪里有逻辑异常，麻烦大神指导一下。
class TicketAddNodeEnd(LoonBaseView):
    post_schema = Schema({
        Optional('suggestion'): str,
    })

    def post(self, request, *args, **kwargs):
        """
        加签处理完成,加签完成操作后工单处理人回回到之前加签发起人
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        json_str = request.body.decode('utf-8')
        if not json_str:
            return api_response(-1, 'post参数为空', {})
        request_data_dict = json.loads(json_str)
        ticket_id = kwargs.get('ticket_id')
        username = request.META.get('HTTP_USERNAME')
        suggestion = request_data_dict.get('suggestion', '')

        app_name = request.META.get('HTTP_APPNAME')
        app_permission_check, msg = account_base_service_ins.app_ticket_permission_check(app_name, ticket_id)
        if not app_permission_check:
            return api_response(-1, msg, '')

        result, msg = ticket_base_service_ins.add_node_ticket_end(ticket_id, username, suggestion)
        if result:
            code, msg, data = 0, msg, {}
        else:
            code, msg, data = -1, msg, ''
        return api_response(code, msg, data)

**Comment by blackholll** [comment]
打开页面详情的时候看下， transitions接口返回的结果。 贴出来 
点击“完成”的时候看下请求的是哪个接口，贴出来

**Comment by blackholll** [comment]
之前未支持加签完成 这个功能。  v2.0.9分支上已经支持， 这几天会发布r2.0.9版本

**Comment by seasonhallym** [comment]
好的，谢谢解答



致此
&nbsp; &nbsp; &nbsp;敬礼
越努力 越幸运 做最好的自己

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "blackholll/loonflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月16日(星期二) 上午6:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [blackholll/loonflow] 加签点击“完成”报错：参数不合法,请提供username，transition_id (Issue #313)





 
之前未支持加签完成 这个功能。  v2.0.9分支上已经支持， 这几天会发布r2.0.9版本
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by blackholll** [comment]
已支持   https://github.com/blackholll/loonflow/releases/tag/r2.0.9
