### ISSUE TITLE
脚本不会执行，流转到脚本执行就不往下流转了。

### ISSUE THREAD

**Issue by ganxuwei** [blackholll/loonflow#314]
## ISSUE TEMPLATE

使用的版本:2.0.6

问题详细描述: 配置了脚本执行，但流转到脚本那一步，就不会继续了，脚本也未运行，不会用hook方式，请大神指教，感谢！

是否查看了系统日志(默认在启动用户家目录下loonflow.log):看过，没有相关记录。

是否搜索过历史issue:是

做过哪些尝试:修改过审批流，也是不行。

**Comment by blackholll** [comment]
脚本执行和hook 需要依赖celery.  启动下celery任务   https://loonflow.readthedocs.io/

**Comment by ganxuwei** [comment]
感谢大神，已经可以了。
