### ISSUE TITLE
新建工单时出错

### ISSUE THREAD

**Issue by Code-SkyWalker** [blackholll/loonflow#315]
## ISSUE TEMPLATE

使用的版本:
v1.0
问题详细描述:
调用接口: api/v1.0/tickets
创建工单时参数: {"workflow_id":26,"title":"崔齐的来访登记","suggestion":"as","transition_id":103}
返回错误: {
  code: -1,
  data: {},
  msg: `(1406, "Data too long for column 'participant' at row 1")`
}
是否查看了系统日志(默认在启动用户家目录下loonflow.log):
否
是否搜索过历史issue:
是, 没有类似问题
做过哪些尝试: 无

**Comment by blackholll** [comment]
看错误是更新处理人信息时 字段长度不够了。  你这个工作流下个状态的处理人配置的是什么？ 一个大部门？ 包含很多人么？

**Comment by Code-SkyWalker** [comment]
> 看错误是更新处理人信息时 字段长度不够了。 你这个工作流下个状态的处理人配置的是什么？ 一个大部门？ 包含很多人么？
这是该工作流的初始状态信息
workflows/id/init_state  == > data: {
  code: 0,
  data: {
    id: 274,
    creator: 'admin',
    gmt_created: '2021-11-11 18:02:04',
    gmt_modified: '2021-11-11 18:02:04',
    is_deleted: false,
    name: '残疾人',
    workflow_id: 58,
    is_hidden: false,
    order_id: 0,
    type_id: 1,
    enable_retreat: false,
    remember_last_man_enable: false,
    participant_type_id: 3,
    **participant: '13,59,20',**
    distribute_type_id: 2,
    label: {},
    field_list: [],
    transition: [ [Object] ]
  },
  msg: ''
}

三个部门, 总人数101
每个 节点 处理人都与该participate所持有的三个部门相同,
participate的字段长度不是1000吗, 怎么还会超出长度

**Comment by blackholll** [comment]
这是提交后的节点  处理人超过长度了。 也就是初始节点的下个节点。participant的长度是1000.   但是保存的是username， 每个人的username长度可能都超过10了， 总的就超过1000了

**Comment by Code-SkyWalker** [comment]
原来保存的是username, 十分感谢
