### ISSUE TITLE
通过hook推送消息

### ISSUE THREAD

**Issue by jacoblann** [blackholll/loonflow#316]
## ISSUE TEMPLATE

使用的版本: r2.0.8

问题详细描述: 我想通过hook向企业微信推送消息，尝试配置了一下，最终在celery里面可以看到接收了任务tasks.send_ticket_notice并成功的记录（如下截图），但是查看微信还是没有收到消息。我想知道是不是我的配置还有什么问题，可以麻烦帮忙查看下吗？特别想确认下“自定义通知”里的hook token就是应该填调用应用的token吗？
Workflow配置:
![Workflow setting](https://user-images.githubusercontent.com/36351236/144785409-f41d93a5-c1e2-4904-8750-18ff22566942.png)
调用应用配置：
![Configure setting](https://user-images.githubusercontent.com/36351236/144785441-81ca7d65-e0d8-4bbf-af43-b951efe86f06.png)
自定义通知配置：
<img width="269" alt="Notification setting" src="https://user-images.githubusercontent.com/36351236/144785452-b730f896-2410-4e54-85f6-55b001364cda.png">

是否查看了系统日志(默认在启动用户家目录下loonflow.log): celery相关，celery log如下。
![Celery log](https://user-images.githubusercontent.com/36351236/144784551-9d0e990c-53ab-422f-942a-98e8dd113acb.png)

是否搜索过历史issue: 搜索过

做过哪些尝试: 微信webhook确定能够工作，尝试过更改各种配置但还是不行

**Comment by blackholll** [comment]
1.这里的token是为了做鉴权用的。 loonflow请求你的hook url的时候会根据这个token做签名。 hook接收方收到请求后可以根据这个签名做验证，以保证是loonflow发送过来的请求。 这个token你自己生成，写到你的服务方配置里面。  和调用应用那边没有关系，只是签名生成算法是一样的
2. 看celery日志是执行成功了，你可以在你的hook服务方新增一些日志 来排查： 是否收到了请求，请求的参数是怎样的 这些

**Comment by jacoblann** [comment]
谢谢及时的回复！我修改了一下设置，让token不是必填的一项。然后找到一个叫做Zapier的webhook服务，设置了URL成功自动发出一份邮件了！
![email setting](https://user-images.githubusercontent.com/36351236/144821969-1dbd9c1b-0421-4062-9a76-e8fd89eeb80b.png)

还想请问下如果我想要推送消息到微信上面，有什么比较好的hook服务选择呢？或者有办法自己配置实现发送消息到微信吗？谢谢！

**Comment by blackholll** [comment]
loonflow触发hook的时候是 按照loonflow的格式来请求的。   其他系统提供的的hook服务是需要请求方按照约定的格式来请求。
所以你需要做一层转换
