### ISSUE TITLE
显示流程图报错

### ISSUE THREAD

**Issue by znznz** [blackholll/loonflow#317]
## ISSUE TEMPLATE

使用的版本:当前master

问题详细描述:进入并点击工作流管理-请假申请-详情-流程图时报错

![image](https://user-images.githubusercontent.com/15881284/145380269-178c21f8-15fb-471c-8ff5-f3b5400d5e60.png)

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:是

做过哪些尝试:不了解前端

**Comment by blackholll** [comment]
重新进到工作流管理，   然后打开浏览器的控制台，  然后点击“请假申请”的详情。   然后把控制台-网络里面所有xhr请求的结果截图发出来

**Comment by znznz** [comment]
这里是详情：
![image](https://user-images.githubusercontent.com/15881284/145401629-52588346-ea49-46c0-babf-e570e80f459d.png)
![image](https://user-images.githubusercontent.com/15881284/145401679-4a2c61b3-da15-4ea4-9fea-1aa26d12db2f.png)
![image](https://user-images.githubusercontent.com/15881284/145401701-cc6fbf6b-1c5e-4c06-b699-3c02b00ab9f5.png)
![image](https://user-images.githubusercontent.com/15881284/145401760-05e85ba7-5e05-4b61-9a44-100405d32e4b.png)
点流程图之后就成下面这样了：
![image](https://user-images.githubusercontent.com/15881284/145401430-b3c473d2-6553-4903-8a07-4b75d906704f.png)

**Comment by blackholll** [comment]
状态列表 和流转列表 的记录 截图看下， 怀疑是 你删除了某个状态，但是流转里面的源或者目标状态配置的还是这个被删除的状态 导致的

**Comment by znznz** [comment]
按说明的方法部署之后就这样了，没有进行删除操作，就是创建数据库是直接用的sql脚本，因为执行python manage.py migrate的时候会报数据库字段长度的问题。
![image](https://user-images.githubusercontent.com/15881284/145403167-b5ad7cf5-ef35-489c-a9c6-f184b71f3807.png)
![image](https://user-images.githubusercontent.com/15881284/145403289-fc40c988-6241-44ae-b9ad-60353da87b06.png)

**Comment by SwallowJ** [comment]
> +1，希望解决一下

看我提的issue，有解决方案

**Comment by SwallowJ** [comment]
看我提的issue，有解决方案

**Comment by znznz** [comment]
参考https://github.com/blackholll/loonflow/issues/318解决了，谢谢 @SwallowJ @blackholll
