### ISSUE TITLE
v0.3.4版本，后台页面，部门管理页面报错

### ISSUE THREAD

**Issue by tymagic** [blackholll/loonflow#32]
报错信息：
DataTables warning: table id=dept_table - Requested unknown parameter 'creator_info' for row 0, column 6. For more information about this error, please see http://datatables.net/tn/4

**Comment by blackholll** [comment]
部门列表请求返回的数据贴出来下, 这个接口
/api/v1.0/accounts/depts?per_page=10&page=1

**Comment by tymagic** [comment]
{"data": [], "msg": "\u6743\u9650\u6821\u9a8c\u5931\u8d25\uff1aunsupported operand type(s) for +: 'NoneType' and 'str'", "code": -1}

**Comment by blackholll** [comment]
检查下loonflow的日志。  settings/pro.py 或则 settings/dev.py（根据你实际使用的配置文件而定）中有日志文件的路径

**Comment by tymagic** [comment]
之前的报错是因为我调用没有加时间戳，加了以后没有报错了，返回如下
{"msg": "\u6743\u9650\u6821\u9a8c\u5931\u8d25\uff1a\u7b7e\u540d\u6821\u9a8c\u5931\u8d25", "data": [], "code": -1}

**Comment by blackholll** [comment]
你是没登陆么？ 不然请求这个接口不应该会报签名校验失败

**Comment by tymagic** [comment]
尴尬了，我没用网页访问，下面是内容
{"msg": "", "data": {"value": [{"label": "", "leader": "", "leader_info": {"leader_alias": "", "leader_username": ""}, "parent_dept_info": {"parent_dept_id": 192768, "parent_dept_name": "\u7528\u6237\u7814\u53d1\u90e8"}, "parent_dept_id": 192768, "id": 38, "creator": "admin", "approver": "", "approver_info": [], "is_deleted": false, "gmt_modified": null, "gmt_created": "2019-04-23 17:54:34", "creator_info": {"creator_alias": "", "creator_id": 15396}, "name": "\u8fd0\u8425\u5e73\u53f0\u7ec4"}, {"label": "", "leader": "", "leader_info": {"leader_alias": "", "leader_username": ""}, "parent_dept_info": {"parent_dept_id": 583, "parent_dept_name": "\u672a\u77e5"}, "parent_dept_id": 583, "id": 45, "creator": "admin", "approver": "", "approver_info": [], "is_deleted": false, "gmt_modified": null, "gmt_created": null, "creator_info": {"creator_alias": "", "creator_id": 15396}, "name": "\u7814\u53d1\u8fd0\u7ef4\u90e8"}, {"label": "", "leader": "", "leader_info": {"leader_alias": "", "leader_username": ""}, "parent_dept_info": {"parent_dept_id": 583, "parent_dept_name": "\u672a\u77e5"}, "parent_dept_id": 583, "id": 231, "creator": "admin", "approver": "", "approver_info": [], "is_deleted": false, "gmt_modified": null, "gmt_created": null, "creator_info": {"creator_alias": "", "creator_id": 15396}, "name": "IT\u8fd0\u7ef4\u7ec4"}, {"label": "", "leader": "", "leader_info": {"leader_alias": "", "leader_username": ""}, "parent_dept_info": {"parent_dept_id": 192764, "parent_dept_name": "\u88c5\u4f01\u7814\u53d1\u90e8"}, "parent_dept_id": 192764, "id": 233, "creator": "admin", "approver": "", "approver_info": [], "is_deleted": false, "gmt_modified": null, "gmt_created": null, "creator_info": {"creator_alias": "", "creator_id": 15396}, "name": "iOS\u7814\u53d1\u7ec4"}, {"label": "", "leader": "", "leader_info": {"leader_alias": "", "leader_username": ""}, "parent_dept_info": {"parent_dept_id": 192764, "parent_dept_name": "\u88c5\u4f01\u7814\u53d1\u90e8"}, "parent_dept_id": 192764, "id": 234, "creator": "admin", "approver": "", "approver_info": [], "is_deleted": false, "gmt_modified": null, "gmt_created": null, "creator_info": {"creator_alias": "", "creator_id": 15396}, "name": "Android\u7814\u53d1\u7ec4"}, {"label": "", "leader": "", "leader_info": {"leader_alias": "", "leader_username": ""}, "parent_dept_info": {"parent_dept_id": 448589, "parent_dept_name": "Tumax\u7814\u53d1\u90e8"}, "parent_dept_id": 448589, "id": 597, "creator": "admin", "approver": "", "approver_info": [], "is_deleted": false, "gmt_modified": null, "gmt_created": null, "creator_info": {"creator_alias": "", "creator_id": 15396}, "name": "\u5546\u5bb6\u4e0e\u540e\u53f0\u7ec4"}, {"label": "", "leader": "", "leader_info": {"leader_alias": "", "leader_username": ""}, "parent_dept_info": {"parent_dept_id": 448589, "parent_dept_name": "Tumax\u7814\u53d1\u90e8"}, "parent_dept_id": 448589, "id": 598, "creator": "admin", "approver": "", "approver_info": [], "is_deleted": false, "gmt_modified": null, "gmt_created": null, "creator_info": {"creator_alias": "", "creator_id": 15396}, "name": "\u4ea4\u4e92\u4e0e\u573a\u666f\u7ec4"}, {"label": "", "leader": "", "leader_info": {"leader_alias": "", "leader_username": ""}, "parent_dept_info": {"parent_dept_id": 192764, "parent_dept_name": "\u88c5\u4f01\u7814\u53d1\u90e8"}, "parent_dept_id": 192764, "id": 600, "creator": "admin", "approver": "", "approver_info": [], "is_deleted": false, "gmt_modified": null, "gmt_created": null, "creator_info": {"creator_alias": "", "creator_id": 15396}, "name": "\u88c5\u4f01\u5e73\u53f0\u7ec4"}, {"label": "", "leader": "", "leader_info": {"leader_alias": "", "leader_username": ""}, "parent_dept_info": {"parent_dept_id": 45, "parent_dept_name": "\u7814\u53d1\u8fd0\u7ef4\u90e8"}, "parent_dept_id": 45, "id": 643, "creator": "admin", "approver": "", "approver_info": [], "is_deleted": false, "gmt_modified": null, "gmt_created": null, "creator_info": {"creator_alias": "", "creator_id": 15396}, "name": "\u5b89\u5168\u5e73\u53f0\u7ec4"}, {"label": "", "leader": "", "leader_info": {"leader_alias": "", "leader_username": ""}, "parent_dept_info": {"parent_dept_id": 2141, "parent_dept_name": "\u5927\u6570\u636e\u90e8"}, "parent_dept_id": 2141, "id": 912, "creator": "admin", "approver": "", "approver_info": [], "is_deleted": false, "gmt_modified": null, "gmt_created": null, "creator_info": {"creator_alias": "", "creator_id": 15396}, "name": "\u57fa\u7840\u5e73\u53f0\u7ec4"}], "page": 1, "per_page": 10, "total": 87}, "code": 0}




------------------ 原始邮件 ------------------
发件人: "blackholll"<notifications@github.com>;
发送时间: 2019年4月24日(星期三) 下午2:36
收件人: "blackholll/loonflow"<loonflow@noreply.github.com>;
抄送: "vision"<576786031@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [blackholll/loonflow] v0.3.4版本，后台页面，部门管理页面报错 (#32)




你是没登陆么？ 不然请求这个接口不应该会报签名校验失败

**Comment by blackholll** [comment]
看了下你返回的数据 都么有creator_info。 这个报错后列表页是否正常显示？ 如果正常显示 可能是我请求没没处理好，结果还没返回就开始渲染table导致这个报错

**Comment by tymagic** [comment]
嗯，正常显示的，那也没啥大问题




------------------ 原始邮件 ------------------
发件人: "blackholll"<notifications@github.com>;
发送时间: 2019年4月24日(星期三) 下午3:27
收件人: "blackholll/loonflow"<loonflow@noreply.github.com>;
抄送: "vision"<576786031@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [blackholll/loonflow] v0.3.4版本，后台页面，部门管理页面报错 (#32)




看了下你返回的数据 都么有creator_info。 这个报错后列表页是否正常显示？ 如果正常显示 可能是我请求没没处理好，结果还没返回就开始渲染table导致这个报错
