### ISSUE TITLE
工作流程管理，点击流程图报错，错误如下

### ISSUE THREAD

**Issue by bergkamp2008999** [blackholll/loonflow#322]
## ISSUE TEMPLATE

使用的版本:最新

问题详细描述:工作流程图报错

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:没有

做过哪些尝试:没有尝试

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `WorkflowGraph`.

**Comment by blackholll** [comment]
是否搜索过历史issue: 没有 [惊讶]

https://github.com/blackholll/loonflow/issues/318

原因： antd的chart库新版本不兼容导致的， 可以按照上面issue先改下。 后面我发个版本限制下版本

**Comment by blackholll** [comment]
fixed: https://github.com/blackholll/loonflow/releases/tag/r2.0.10
