### ISSUE TITLE
流程处置过程中，管理员点击流程查看报错

### ISSUE THREAD

**Issue by bergkamp2008999** [blackholll/loonflow#324]
## ISSUE TEMPLATE

使用的版本:最新版本

问题详细描述:流程处置过程中，管理员点击流程查看报错

是否查看了系统日志(默认在启动用户家目录下loonflow.log):未查看

是否搜索过历史issue:搜索过，没有

做过哪些尝试:未尝试

×
Unhandled Rejection (ReferenceError): message is not defined
_callee$
./src/pages/Workflow/WorkflowGraph/index.tsx:59
  56 | 
  57 | 
  58 |    } else {
> 59 |      message.error(result.msg);
     | ^  60 |    };
  61 |  };
  62 |

**Comment by blackholll** [comment]
浏览器控制台下，看下states、 transition接口的返回内容贴出来

**Comment by SuperLeilia** [comment]
> 浏览器控制台下，看下states、 transition接口的返回内容贴出来

你好，我遇到了相同的问题，存在以下两个问题：
1. 当点击工单详情时，console报出Warning: Each child in a list should have a unique "key" prop.
并且页面上出现以下error：
![截屏2022-01-07 下午10 08 08](https://user-images.githubusercontent.com/23026219/148555465-de1fe4d7-ab4b-44ef-b552-b424ca011cce.png)
2. 当点击流程图时，页面直接跳转到下图页面，console报错：
Uncaught (in promise) ReferenceError: message is not defined
    at _callee$ (index.tsx:59)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
![截屏2022-01-07 下午10 10 25](https://user-images.githubusercontent.com/23026219/148555757-ebd05b30-c1ac-45a6-aa09-dabb0f58925e.png)

transition的返回内容为{"code": 0, "data": {"value": []}, "msg": ""}
states我没有找到

**Comment by blackholll** [comment]
这个是  获取工作流基础信息报错 code!=0导致代码执行到message.error。 因为这个文件忘记imort message了导致出错。
你可以看下页面上/api/v1.0/workflows/${workflowId}/simple_description这个接口返回的什么内容， 里面有错误信息
