### ISSUE TITLE
工作流管理-基础信息中，如果展现表单字段里面不填入[]直接为空会出错，建议里面为空字符串时，前端传入[]

### ISSUE THREAD

**Issue by Jayden-he** [blackholll/loonflow#326]
![image](https://user-images.githubusercontent.com/31341179/147735469-c1e4aa94-39ed-417f-baa5-07c7747ecce1.png)
![image](https://user-images.githubusercontent.com/31341179/147735496-1dc523c3-5896-4ed2-8136-5ab95b049ba6.png)

**Comment by blackholll** [comment]
这个后续会优化成 下拉选择
