### ISSUE TITLE
容器部署登陆后Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185

### ISSUE THREAD

**Issue by EricHan-XL** [blackholll/loonflow#328]
## ISSUE TEMPLATE

使用的版本:2.0.9

问题详细描述:使用容器方式部署后，使用admin用户登录，页面显示something went wrong，Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:是，未找到

做过哪些尝试:2.0.10 optimize: wget nodejs cert for docker compose，升级是否可以解决？

**Comment by blackholll** [comment]
2.0.10主要解决两个问题：
1.因为ant design charts最新版本不向下兼容，导致流程图界面展示有问题，所以我固定了charts的版本
2.docker compose部署的时候会下载nodejs。因为清华源的证书问题导致无法下载，所以加了个参数

你的这个问题我没复现。  你是登录后就直接报错么？还是某个固定的页面报错 或者是做了上面操作的时候报错？

**Comment by EricHan-XL** [comment]
![29c27f207ecb05ddf688dfa226e4808](https://user-images.githubusercontent.com/97075688/148312880-16c94dad-bdeb-4a18-99dc-bb38b26fbdf1.png)
用2.0.9的时候，除了系统配置其他界面都会显示这个，后面重新构建了2.0.10的镜像，这个问题目前没有了
