### ISSUE TITLE
工作流创建完成后无法正常使用

### ISSUE THREAD

**Issue by binhoul** [blackholll/loonflow#331]
## ISSUE TEMPLATE

使用的版本:  master分支，loonflow 2.0.10

问题详细描述: 
使用docker-compose运行。
使用系统启动时默认自带的工作流可以创建工单，但是使用自己创建的工作流是，不显示自定义的选项。

![image](https://user-images.githubusercontent.com/5045366/149894902-41921754-92e6-460d-930e-de24ee665b1c.png)

是否查看了系统日志(默认在启动用户家目录下loonflow.log):是

是否搜索过历史issue: 是

做过哪些尝试: 切换到2.0.9版本依然存在。

**Comment by blackholll** [comment]
字段展示逻辑见: https://github.com/blackholll/loonflow/issues/37
新建的时候没显示字段  需要在状态列表中找到 属性为”初始状态“的状态，在这个状态的设置里面有 要展示哪些字段

**Comment by binhoul** [comment]
> 字段展示逻辑见: #37 新建的时候没显示字段 需要在状态列表中找到 属性为”初始状态“的状态，在这个状态的设置里面有 要展示哪些字段

多谢解释。
