### ISSUE TITLE
初始状态的新建工单可以撤销掉吗

### ISSUE THREAD

**Issue by tkzca** [blackholll/loonflow#333]
## ISSUE TEMPLATE

使用的版本: master   v2.0.10
问题详细描述:  新建工单可以自行撤销吗？
![1](https://user-images.githubusercontent.com/86900913/150457953-3babe2da-d12b-49e4-91a0-493409e6974c.png)

是否查看了系统日志(默认在启动用户家目录下loonflow.log):
是否搜索过历史issue:  有，没搜到相关问题
做过哪些尝试:

**Comment by blackholll** [comment]
后端接口有提供撤回接口 api/v1.0/tickets/<int:ticket_id>/retreat，前端页面暂未支持
