### ISSUE TITLE
工单分配审批人可见的问题

### ISSUE THREAD

**Issue by tkzca** [blackholll/loonflow#334]
使用的版本:master分支，loonflow 2.0.10
安装环境:docker-compose
问题详细描述:  
是否查看了系统日志(默认在启动用户家目录下loonflow.log):未查看
是否搜索过历史issue:搜索过，没有
做过哪些尝试:未尝试

当工单审批配置是"参与人类型是部门或者多人并且分配方式是随机分配"时候, 从提单人或者干预者或管理员角度看，这个单子到底在谁手上，工单上没有处理人相关信息，无法做催单动作。
![1](https://user-images.githubusercontent.com/86900913/150460880-cf4b1135-7721-41c2-95ed-2d7dbb12ce9e.png)

![2](https://user-images.githubusercontent.com/86900913/150461409-b91ff892-5d28-4961-909d-fe0da99ec933.png)

**Comment by blackholll** [comment]
可以将当前处理人配置显示出来， 工作流的展现表单和状态的里面表单配置有说明

**Comment by tkzca** [comment]
试了下，是可以配置出来的。
