### ISSUE TITLE
服务启动后点击pycharm终端的蓝色链接打开并没有看到登录页面

### ISSUE THREAD

**Issue by Alvin-Frank** [blackholll/loonflow#335]
## ISSUE TEMPLATE

使用的版本:2.0.10

问题详细描述:虽然严格的按照说明书的5.1安装流程安装，但服务启动后点击pycharm终端的蓝色链接打开并没有看到登录页面，而是page not found 404的黄色背景bebug画面，请问如何解决

![屏幕截图 2022-01-21 113548](https://user-images.githubusercontent.com/61074629/150461856-a51faf5e-aa11-438e-ba9d-2a64a94886eb.png)

是否查看了系统日志(默认在启动用户家目录下loonflow.log):查看了

是否搜索过历史issue:搜过

做过哪些尝试:暂时没有

**Comment by blackholll** [comment]
看文档 https://loonflow.readthedocs.io。 前端页面需要编译， python只提供接口

**Comment by Alvin-Frank** [comment]
您好，请问，我现在的node.js现在有一些依赖包一直安装不上，没办法渲染前端的内容，如果我直接调用http api的接口去给odoo后端引用，在odoo中可以用吗？在调用时，我需要让loonflow保持服务开启的状态吗？

**Comment by blackholll** [comment]
erp那个odoo么？  不太了解。
注意node版本要14以上
这里有调用方式说明： https://loonflow.readthedocs.io/zh_CN/r2.0.9/api_docs/authentication/
调用接口当然服务要启动

**Comment by Alvin-Frank** [comment]
看不到登录画面的问题已解决

我的pycharm在win系统中，然后会遇到按文档操作后的尴尬
原初始化数据库指令：
python manage.py makemigrations
python manage.py migrate

解决方法：
在win系统下在初始化数据库的这一步骤时与文档操作不同
WIN操作系统中：
在pycharm中执行命令
python  manage_test.py  makemigrations
python  manage_test.py  migrate
然后安装nodeV14，然后再在前端目录下进行npm指令操作

**Comment by Alvin-Frank** [comment]
> erp那个odoo么？ 不太了解。 注意node版本要14以上 这里有调用方式说明： https://loonflow.readthedocs.io/zh_CN/r2.0.9/api_docs/authentication/ 调用接口当然服务要启动

感谢您的回复，我已经知晓，感谢您的帮助

**Comment by blackholll** [comment]
> 看不到登录画面的问题已解决
> 
> 我的pycharm在win系统中，然后会遇到按文档操作后的尴尬 原初始化数据库指令： python manage.py makemigrations python manage.py migrate
> 
> 解决方法： 在win系统下在初始化数据库的这一步骤时与文档操作不同 WIN操作系统中： 在pycharm中执行命令 python manage_test.py makemigrations python manage_test.py migrate 然后安装nodeV14，然后再在前端目录下进行npm指令操作

manage_test.py是用于跑单测的。 里面用的是sqlite数据库，不是mysql。  你用manage.py执行migare失败 应该找找报错原因。是否是你没有配置mysql的地址

**Comment by Alvin-Frank** [comment]
> > 看不到登录画面的问题已解决
> > 我的pycharm在win系统中，然后会遇到按文档操作后的尴尬 原初始化数据库指令： python manage.py makemigrations python manage.py migrate
> > 解决方法： 在win系统下在初始化数据库的这一步骤时与文档操作不同 WIN操作系统中： 在pycharm中执行命令 python manage_test.py makemigrations python manage_test.py migrate 然后安装nodeV14，然后再在前端目录下进行npm指令操作
> 
> manage_test.py是用于跑单测的。 里面用的是sqlite数据库，不是mysql。 你用manage.py执行migare失败 应该找找报错原因。是否是你没有配置mysql的地址

作者您好，我之前的操作是使用您以前gitee上的旧版本，新版本r2.0.10的，我就是在python manage.py runserver 6060这一步，我是在编辑配置的形参里用了127.0.0.1：8000了，相当于跳步了，并没能开启后端服务，后来老老实实按文档一步一步走，在开启后端服务后，再浏览器访问127.0.0.1：8000就直接来到首页可以登录了，就能正常使用了。这几天感谢您的回复，您的帮助
