### ISSUE TITLE
loonflow的api端口支持odoo框架调用吗？

### ISSUE THREAD

**Issue by Alvin-Frank** [blackholll/loonflow#336]
## ISSUE TEMPLATE

使用的版本:2.0.10

问题详细描述:loonflow的api端口支持odoo框架调用吗？

是否查看了系统日志(默认在启动用户家目录下loonflow.log):是

是否搜索过历史issue:是

做过哪些尝试:未尝试

**Comment by blackholll** [comment]
http调用就行

**Comment by Alvin-Frank** [comment]
已知晓，odoo可以使用loon flow的api，具体操作还待我个人研究，问题已解决，感谢制作者的回复与帮助
