### ISSUE TITLE
工单查看权限问题

### ISSUE THREAD

**Issue by tkzca** [blackholll/loonflow#337]
使用的版本:master分支，loonflow 2.0.10
安装环境:docker-compose
是否查看了系统日志(默认在启动用户家目录下loonflow.log):未查看
是否搜索过历史issue:搜索过，没有
做过哪些尝试:未尝试

问题详细描述:   这个工单类型只仅配置了bl用户的查看权限，但是fl用户确能看到工单列表?
![1](https://user-images.githubusercontent.com/86900913/150495454-fb28791e-9b9b-4a0a-a64f-6ef74bcfb200.png)
![2](https://user-images.githubusercontent.com/86900913/150495469-e7211c29-91ac-49e8-bbd7-88418a26fe24.png)
![3](https://user-images.githubusercontent.com/86900913/150495489-1d179870-f93f-45e3-9415-934ca8171fcc.png)

**Comment by blackholll** [comment]
简单看了下代码 好像查看工单权限代码部分有点问题，下个版本我修复下

**Comment by blackholll** [comment]
fixed https://github.com/blackholll/loonflow/releases/tag/r2.0.11
