### ISSUE TITLE
docker-compose安装方式sql导入失败

### ISSUE THREAD

**Issue by tkzca** [blackholll/loonflow#339]
使用的版本:master分支，loonflow 2.0.10
安装环境:docker-compose
是否查看了系统日志(默认在启动用户家目录下loonflow.log):未查看
是否搜索过历史issue:搜索过，没有
做过哪些尝试:未尝试

问题详细描述:  docker安装在导入sql是失败
1.主机IP、网络环境配置：
![1](https://user-images.githubusercontent.com/86900913/150623891-7f47a562-645d-4df8-8bf4-54b71607480f.png)

2. run.py数据库信息：
![2](https://user-images.githubusercontent.com/86900913/150623915-429cd8e4-76c8-40a1-888b-e8adaf83590e.png)

3. 数据端口是通的：
![4](https://user-images.githubusercontent.com/86900913/150624067-6a02ee06-c128-4ce5-9336-23f213a4d9c2.png)

4. iptables的相关配置：
![5](https://user-images.githubusercontent.com/86900913/150627541-9ee78878-ce9b-486b-9d18-a02304aabc28.png)

5. 安装报错：
![3](https://user-images.githubusercontent.com/86900913/150623994-f9ab6b1f-0c3c-47db-9c79-c8827f781b6c.png)

**Comment by tkzca** [comment]
已解决了，是我机器本身就开了iptables,是filter表的INPUT链给drop了，添加如下规则就好了。
iptables -i br-4e42f14075c8  -A INPUT -s 0.0.0.0/0  -p tcp --dport 3306 -j ACCEPT
4e42f14075c8是容器附着在docker0网桥的网卡

**Comment by blackholll** [comment]
另一种方法：
数据地址用服务器的真实ip地址，不要用127
