### ISSUE TITLE
审批流中有“字段类型”为"日期"的字段，在提交审批时会报错

### ISSUE THREAD

**Issue by tkzca** [blackholll/loonflow#341]
使用的版本:master分支，loonflow 2.0.10
安装环境:docker-compose
是否查看了系统日志(默认在启动用户家目录下loonflow.log):未查看
是否搜索过历史issue:搜索过，没有
做过哪些尝试:未尝试

问题描述：审批流中带有"日期"le类型字段，提交审批报错，可能是个bug?
1.  自定义字段里有“字段类型”为"日期"的字段
![aaa](https://user-images.githubusercontent.com/86900913/150754177-2386010f-d8af-40e5-af0f-66098090b994.png)

2. 审批表单里设置一个"日期"类型字段：
![2](https://user-images.githubusercontent.com/86900913/150753561-79e4677b-8d76-4391-9783-1860708409e1.png)

3. 审批人操作"同意"或"拒绝"时，报错
![bbb](https://user-images.githubusercontent.com/86900913/150754253-0977c68f-91dd-4a52-9551-0ecbd7400790.png)

**Comment by blackholll** [comment]
fixed https://github.com/blackholll/loonflow/releases/tag/r2.0.11
