### ISSUE TITLE
[内置字段页面展示优化] 正常工单状态下的内置字段说明显示屏蔽掉

### ISSUE THREAD

**Issue by tkzca** [blackholll/loonflow#342]
使用的版本:master分支，loonflow 2.0.10
安装环境:docker-compose
是否查看了系统日志(默认在启动用户家目录下loonflow.log):未查看
是否搜索过历史issue:搜索过，没有
做过哪些尝试:未尝试

需求描述：正式环境可否把这个"内置字段"的说明去掉，感觉这部信息审批人不需要看到。
![1234](https://user-images.githubusercontent.com/86900913/150754914-d722b7fb-3db0-4a3e-bfe0-75700097e2e7.png)

**Comment by blackholll** [comment]
可以， 我下个版本移除下

**Comment by blackholll** [comment]
done  https://github.com/blackholll/loonflow/releases/tag/r2.0.11
