### ISSUE TITLE
[自定义字段前端页面优化] 自定义字段的"用户"和"多选用户"字段前端页面拉取优化

### ISSUE THREAD

**Issue by tkzca** [blackholll/loonflow#343]
使用的版本:master分支，loonflow 2.0.10
安装环境:docker-compose
是否查看了系统日志(默认在启动用户家目录下loonflow.log):未查看
是否搜索过历史issue:搜索过，没有
做过哪些尝试:未尝试

优化点描述:  "用户"和"多选用户"字段在前端页面拉取列表逻辑上可以优化下。
![abc](https://user-images.githubusercontent.com/86900913/150758901-3ef9dac4-e7d7-4438-b513-73a670942717.png)

**Comment by blackholll** [comment]
用户字段是要求用户输入关键词搜索的。 单多选下拉一般数据量比较少，所以是直接选择的。  
当然用户选择字段里面可以加下提示信息
