### ISSUE TITLE
关于条件表达式

### ISSUE THREAD

**Issue by Alvin-Frank** [blackholll/loonflow#345]
## ISSUE TEMPLATE

使用的版本:r2.0.10

问题详细描述:不知道怎样去写条件表达式，只看懂了格式，如果我想写一个关于金额条件的表达式应该怎么写
![屏幕截图 2022-01-27 140734](https://user-images.githubusercontent.com/61074629/151301547-10cb3ba5-8c41-4dbb-9ad0-fb577bdb67ea.png)
您帮忙给看看怎么写才好

是否查看了系统日志(默认在启动用户家目录下loonflow.log):是

是否搜索过历史issue:是

做过哪些尝试:尝试过自行书写

**Comment by blackholll** [comment]
如果你的采购金额这个字段是 purchase。  总经理 这个状态的id是5， 采购单这个状态的id是6
那么你新建一个流转，流转的的目标状态留空，条件表达式里面填写 [{"expression":{purchase}>1000, "target_id":5}, {"expression":{purchase}<=1000, "target_id":6}]

**Comment by Alvin-Frank** [comment]
> 

感谢作者的回复，我已经懂了，那么这个条件表达式的作用是什么，我即使没有加这个条件也能完成流程，那么是不是加了这个之后，同意的按钮就会从2个变成一个了

**Comment by Alvin-Frank** [comment]
> 感谢作者的回复，我已经懂了，那么这个条件表达式的作用是什么，我即使没有加这个条件也能完成流程，那么是不是加了这个之后，同意的按钮就会从2个变成一个了

感谢作者的回复，我已经懂了，那么这个条件表达式的作用是什么，我即使没有加这个条件也能完成流程，那么是不是加了这个之后，同意的按钮就会从2个变成一个了

**Comment by blackholll** [comment]
不加条件  那就需要处理人自己判断点哪个按钮。
通过条件， 处理人之需要点击”同意“，系统会自动判断下个节点应该到哪里

**Comment by Alvin-Frank** [comment]
> 不加条件 那就需要处理人自己判断点哪个按钮。 通过条件， 处理人之需要点击”同意“，系统会自动判断下个节点应该到哪里

![image](https://user-images.githubusercontent.com/61074629/151642017-ea837c6b-f97e-40b4-a124-ba7d409fe992.png)
貌似不太对，这一部分对应代码的那一部分啊

**Comment by Alvin-Frank** [comment]
> 不加条件 那就需要处理人自己判断点哪个按钮。 通过条件， 处理人之需要点击”同意“，系统会自动判断下个节点应该到哪里

![image](https://user-images.githubusercontent.com/61074629/151643244-6233beaa-aa8c-4bdc-91ba-2abe741fa4ee.png)
表达式：[{"expression":"int({purchase})>1000", "target_state_id":5}, {"expression":"int({purchase})<=1000", "target_state_id":6}]

**Comment by blackholll** [comment]
目标状态随便选一个吧， 后端必填校验有点问题

**Comment by blackholll** [comment]
已优化： https://github.com/blackholll/loonflow/releases/tag/r2.0.11
