### ISSUE TITLE
希望添加复制流程的功能

### ISSUE THREAD

**Issue by sun515yt** [blackholll/loonflow#347]
## ISSUE TEMPLATE

使用的版本:2.0.10

问题详细描述:实际工作中有很多流程是类似的，只需修改部分节点和字段即可，通过复制流程项目可以极大简化开发过程，建议添加复制流程功能。

是否查看了系统日志(默认在启动用户家目录下loonflow.log):否

是否搜索过历史issue:是

做过哪些尝试:无

**Comment by blackholll** [comment]
2.1.0版本考虑支持，计划2022年10月底之前发布
