### ISSUE TITLE
推荐作者修改requirements/common.txt中mysqlclient为mysqlclient==2.1.0

### ISSUE THREAD

**Issue by Alvin-Frank** [blackholll/loonflow#348]
## ISSUE TEMPLATE

使用的版本:R2.0.11

问题详细描述:推荐作者修改requirements/common.txt中mysqlclient为mysqlclient==2.1.0，因为1点几版本从我用r2.0.10就一直存在找不到库用问题，下图是重装前后的效果
![mysqlclient问题](https://user-images.githubusercontent.com/61074629/153325302-e43d41e3-b794-4c52-8ead-fd5477a22804.png)

**Comment by Alvin-Frank** [comment]
> 这是install 成功了， 但是这里提示没有安装么？ 还是install的时候就失败了？ 可以pip freeze 看下

是的，虽然用-r已经安装了，但那个1点几的版本即使是安装了也是得手动再安一次2.1.0版本，不如直接最开始就安装2的版本，也就是您猜想的第一种结果，可能是版本的问题导致pycharm读不到这个库

**Comment by blackholll** [comment]
判断是否是版本导致pycharm无法识别库，可以在命令行下进到虚拟环境执行命令试下
我这边mac centos都没遇到这个问题，难道是window不支持这个版本的mysqlclient？

**Comment by Alvin-Frank** [comment]
> 判断是否是版本导致pycharm无法识别库，可以在命令行下进到虚拟环境执行命令试下 我这边mac centos都没遇到这个问题，难道是window不支持这个版本的mysqlclient？

这个库win用2.1.0就行了
