### ISSUE TITLE
希望作者可以在超级用户账户下，在所有工单中每条流水后增加删除工单键

### ISSUE THREAD

**Issue by Alvin-Frank** [blackholll/loonflow#349]
## ISSUE TEMPLATE

使用的版本:r2.0.11

问题详细描述:希望作者可以在超级用户账户下，在所有工单中每条流水后增加删除工单键
![QQ截图20220210114209](https://user-images.githubusercontent.com/61074629/153333009-86a85837-3ee8-4309-ac27-9d5382c606e9.png)

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:

做过哪些尝试:

**Comment by blackholll** [comment]
下个版本加上
