### ISSUE TITLE
工作流数据获取不全

### ISSUE THREAD

**Issue by Bright-z** [blackholll/loonflow#35]
在loonflow添加了多个工作流，但是前端获取数据时，只获取到了一条数据
![image](https://user-images.githubusercontent.com/13827789/57218873-074d7e80-7029-11e9-8f08-c19c6df2a564.png)
![image](https://user-images.githubusercontent.com/13827789/57218886-13394080-7029-11e9-906f-feeedaa6d58c.png)

**Comment by blackholll** [comment]
调用loonflow接口的时候会传app_name信息过来， loonflow会根据这个app_name判断其有权限的工作流， 然后只返回有权限的工作流的相关信息。
![image](https://user-images.githubusercontent.com/6269605/57219020-6e6b3300-7029-11e9-9f72-6598fd2bbc33.png)
