### ISSUE TITLE
工单流转的条件表达式依旧出现了问题

### ISSUE THREAD

**Issue by Alvin-Frank** [blackholll/loonflow#350]
## ISSUE TEMPLATE

使用的版本:r2.0.11

问题详细描述:问题延续自r2.0.10

工单流转的条件表达式依旧出现了问题
![image](https://user-images.githubusercontent.com/61074629/153334147-4ba4132e-2117-4d14-8e59-a307beb4fc19.png)
然后流图这边直接就崩掉了
![image](https://user-images.githubusercontent.com/61074629/153334285-4bd30208-30b9-450f-884c-2bebcc4a6f15.png)
条件表达式依旧没有达到通过“采购经理”一个同意按键，后台自动判断金额递送给不同人的效果

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:是

做过哪些尝试:恢复数据库

**Comment by blackholll** [comment]
target_state_id

![image](https://user-images.githubusercontent.com/6269605/153511718-4b7da844-6ca2-4e53-a8c0-8448a02fcdd6.png)

**Comment by Alvin-Frank** [comment]
> target_state_id
> 
> ![image](https://user-images.githubusercontent.com/6269605/153511718-4b7da844-6ca2-4e53-a8c0-8448a02fcdd6.png)

已解决，感谢作者
![推导式1](https://user-images.githubusercontent.com/61074629/153533181-5a366b85-3088-48f6-bbd8-370b6ca4dc31.png)
![推导式2](https://user-images.githubusercontent.com/61074629/153533194-a8cd4957-1ded-4037-a891-1ab9be4afa0d.png)
