### ISSUE TITLE
eventlet库我个人认为并不重要，celery4还是可以在win下运行

### ISSUE THREAD

**Issue by Alvin-Frank** [blackholll/loonflow#352]
## ISSUE TEMPLATE

使用的版本:r2.0.11，win10系统

问题详细描述:关于celery
![异步1](https://user-images.githubusercontent.com/61074629/153534080-bf1fcaff-baab-4ddf-9f2f-6e104a8e1e5d.png)
文档说是win10需要一个eventlet库
然后执行两个指令
celery -A tasks worker -l info -Q loonflow
和
celery -A tasks worker -l info -P eventlet

但我实际上不执行第二个eventlet指令项目依旧可以使用
这一库和这一指令到底对于win10系统重要么，我个人认为并不重要，celery4还是可以在win下运行的

是否查看了系统日志(默认在启动用户家目录下loonflow.log):是

是否搜索过历史issue:是

做过哪些尝试:

**Comment by blackholll** [comment]
windows很久没用了，stackoverflow上有个讨论，可以了解下。 https://stackoverflow.com/questions/37255548/how-to-run-celery-on-windows
按照这里的讨论 不用eventlet 执行task的时候应该会报错的。 你这里正常是可以正常执行任务么？

**Comment by Alvin-Frank** [comment]
> windows很久没用了，stackoverflow上有个讨论，可以了解下。 https://stackoverflow.com/questions/37255548/how-to-run-celery-on-windows 按照这里的讨论 不用eventlet 执行task的时候应该会报错的。 你这里正常是可以正常执行任务么？

试过下载了库但不执行eventlet的指令，可以正常用，不过异步能支撑多少就不清楚了

**Comment by blackholll** [comment]
如果只是本地开发环境，用windows没问题。 线上环境还是用linux吧
