### ISSUE TITLE
在工作台中查看工单详情的时候，提示 TypeError: date.clone is not a function

### ISSUE THREAD

**Issue by fanandli** [blackholll/loonflow#353]
## ISSUE TEMPLATE

使用的版本:2.0.11

问题详细描述:
![image](https://user-images.githubusercontent.com/37018548/153556050-5c6fdc1c-045f-4d0a-aa6b-8a60ae5ef748.png)

是否查看了系统日志(默认在启动用户家目录下loonflow.log):没看。。

是否搜索过历史issue:是

做过哪些尝试:前端不太懂。。

**Comment by fanandli** [comment]
![image](https://user-images.githubusercontent.com/37018548/153556486-666147d3-5863-41f3-99ce-5fcebfbd3433.png)

**Comment by fanandli** [comment]
> 确定下什么场景会出现： 1.当前用户是否有该工单的处理权限，即这个工单是否是自己的代办列表中的工单 2.这个工单这个状态下是否有显示时间/日期类型的字段，这个字段当前属性是怎样的？ 只读、必填、可选？ 3.这个工单的这个时间日期类型字段的实际的值是怎样的。 去ticket_custom_field表中根据field_key找到这个字段的值
1.是自己的代表列表工单，有处理的权限的
2.有时间/日期类型的字段，是必填字段，且已经填了
3.实际值是2022-2-14

**Comment by fanandli** [comment]
> 确定下什么场景会出现： 1.当前用户是否有该工单的处理权限，即这个工单是否是自己的代办列表中的工单 2.这个工单这个状态下是否有显示时间/日期类型的字段，这个字段当前属性是怎样的？ 只读、必填、可选？ 3.这个工单的这个时间日期类型字段的实际的值是怎样的。 去ticket_custom_field表中根据field_key找到这个字段的值

1.是自己的代表列表工单，有处理的权限的
2.有时间/日期类型的字段，是必填字段，且已经填了
3.实际值是2022-2-14

**Comment by fanandli** [comment]
> 确定下什么场景会出现： 1.当前用户是否有该工单的处理权限，即这个工单是否是自己的代办列表中的工单 2.这个工单这个状态下是否有显示时间/日期类型的字段，这个字段当前属性是怎样的？ 只读、必填、可选？ 3.这个工单的这个时间日期类型字段的实际的值是怎样的。 去ticket_custom_field表中根据field_key找到这个字段的值

1.是自己的代办列表工单，有处理的权限的
2.有时间/日期类型的字段，是必填字段，且已经填了
3.实际值是2022-2-14

**Comment by fanandli** [comment]
![image](https://user-images.githubusercontent.com/37018548/153819191-06366b5c-7837-4c6f-bacb-f5da29b41259.png)
这里也会有一个报错...

**Comment by blackholll** [comment]
这个错误应该是 配置了这个状态的表单按配置了days字段笔谈， 但是实际days字段已经被删除了

**Comment by fanandli** [comment]
> 这个错误应该是 配置了这个状态的表单按配置了days字段笔谈， 但是实际days字段已经被删除了

不好意思啊，笔谈？没听懂。。我没有字段是days呀。。。

**Comment by fanandli** [comment]
> 确定下什么场景会出现： 1.当前用户是否有该工单的处理权限，即这个工单是否是自己的代办列表中的工单 2.这个工单这个状态下是否有显示时间/日期类型的字段，这个字段当前属性是怎样的？ 只读、必填、可选？ 3.这个工单的这个时间日期类型字段的实际的值是怎样的。 去ticket_custom_field表中根据field_key找到这个字段的值

这个错误，我将“时间类型的字段”在 非初始状态 下，改为了只读状态，就好了，不知道具体什么原因

**Comment by blackholll** [comment]
> > 这个错误应该是 配置了这个状态的表单按配置了days字段笔谈， 但是实际days字段已经被删除了
> 
> 不好意思啊，笔谈？没听懂。。我没有字段是days呀。。。

检查下“部门负责人审批中” 这个状态的配置，  有个表单配置，里面是不是配置了days字段

**Comment by blackholll** [comment]
> 



> > 确定下什么场景会出现： 1.当前用户是否有该工单的处理权限，即这个工单是否是自己的代办列表中的工单 2.这个工单这个状态下是否有显示时间/日期类型的字段，这个字段当前属性是怎样的？ 只读、必填、可选？ 3.这个工单的这个时间日期类型字段的实际的值是怎样的。 去ticket_custom_field表中根据field_key找到这个字段的值
> 
> 这个错误，我将“时间类型的字段”在 非初始状态 下，改为了只读状态，就好了，不知道具体什么原因

从现象来看，就是时间类型有值，且可编辑状态下会有问题。  这个我周末验证下

**Comment by fanandli** [comment]
> 

![image](https://user-images.githubusercontent.com/37018548/153973119-cb49e0ef-a753-47d5-a138-c099a6b51a03.png)
是这里吗？这个类型工作流我没有配置days字段

**Comment by fanandli** [comment]
> > 
> 
> > > 确定下什么场景会出现： 1.当前用户是否有该工单的处理权限，即这个工单是否是自己的代办列表中的工单 2.这个工单这个状态下是否有显示时间/日期类型的字段，这个字段当前属性是怎样的？ 只读、必填、可选？ 3.这个工单的这个时间日期类型字段的实际的值是怎样的。 去ticket_custom_field表中根据field_key找到这个字段的值
> > 
> > 
> > 这个错误，我将“时间类型的字段”在 非初始状态 下，改为了只读状态，就好了，不知道具体什么原因
> 
> 从现象来看，就是时间类型有值，且可编辑状态下会有问题。 这个我周末验证下

好滴，谢谢啦~

**Comment by fanandli** [comment]
> > > 这个错误应该是 配置了这个状态的表单按配置了days字段笔谈， 但是实际days字段已经被删除了
> > 
> > 
> > 不好意思啊，笔谈？没听懂。。我没有字段是days呀。。。
> 
> 检查下“部门负责人审批中” 这个状态的配置， 有个表单配置，里面是不是配置了days字段

![image](https://user-images.githubusercontent.com/37018548/153973269-ca291d80-20cd-4550-be1d-4e4ba7669e3d.png)
是这里吗？这个类型工作流我没有配置days字段

**Comment by fanandli** [comment]
> > > 这个错误应该是 配置了这个状态的表单按配置了days字段笔谈， 但是实际days字段已经被删除了
> > 
> > 
> > 不好意思啊，笔谈？没听懂。。我没有字段是days呀。。。
> 
> 检查下“部门负责人审批中” 这个状态的配置， 有个表单配置，里面是不是配置了days字段

![image](https://user-images.githubusercontent.com/37018548/153973539-b34a040c-f477-43ec-bca4-dccd12eda288.png)

是这里吗？这个类型工作流我没有配置days字段。我这里的start_data和end_data用的是日期类型。我估计是日期类型在逻辑上处理有些问题。我重新配置了一个没有使用日期类型的工作流时，就不会有这些问题。

**Comment by blackholll** [comment]
> 



> > > > 这个错误应该是 配置了这个状态的表单按配置了days字段笔谈， 但是实际days字段已经被删除了
> > > 
> > > 
> > > 不好意思啊，笔谈？没听懂。。我没有字段是days呀。。。
> > 
> > 
> > 检查下“部门负责人审批中” 这个状态的配置， 有个表单配置，里面是不是配置了days字段
> 
> ![image](https://user-images.githubusercontent.com/37018548/153973539-b34a040c-f477-43ec-bca4-dccd12eda288.png)
> 
> 是这里吗？这个类型工作流我没有配置days字段。我这里的start_data和end_data用的是日期类型。我估计是日期类型在逻辑上处理有些问题。我重新配置了一个没有使用日期类型的工作流时，就不会有这些问题。

从错误来看应该就是哪个地方配置了days字段。   可以可以下后端的日志会有详细的 错误提示

**Comment by fanandli** [comment]
> > 
> 
> > > > > 这个错误应该是 配置了这个状态的表单按配置了days字段笔谈， 但是实际days字段已经被删除了
> > > > 
> > > > 
> > > > 不好意思啊，笔谈？没听懂。。我没有字段是days呀。。。
> > > 
> > > 
> > > 检查下“部门负责人审批中” 这个状态的配置， 有个表单配置，里面是不是配置了days字段
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/37018548/153973539-b34a040c-f477-43ec-bca4-dccd12eda288.png)
> > 是这里吗？这个类型工作流我没有配置days字段。我这里的start_data和end_data用的是日期类型。我估计是日期类型在逻辑上处理有些问题。我重新配置了一个没有使用日期类型的工作流时，就不会有这些问题。
> 
> 从错误来看应该就是哪个地方配置了days字段。 可以可以下后端的日志会有详细的 错误提示

![image](https://user-images.githubusercontent.com/37018548/154005568-785e39a4-8d63-47fe-a8ea-3e617f300523.png)
日志报的是这个错误😯

**Comment by blackholll** [comment]
条件表达式里面用了days。 检查下流转的配置

**Comment by fanandli** [comment]
> 条件表达式里面用了days。 检查下流转的配置

感谢~~已解决~果然是这个问题，谢谢😄
