### ISSUE TITLE
推荐再增加一个公司部门结构的结构图的功能

### ISSUE THREAD

**Issue by Alvin-Frank** [blackholll/loonflow#354]
## ISSUE TEMPLATE

使用的版本:R2.0.11

问题详细描述:
这里的上级部门，既然已经有上级部门的功能了，推荐再增加一个公司部门结构的结构图的功能，然后流程图配置中选择是否开启工单是否展示部门结构图，然后在每个部门名旁加一个（部门负责人）
![image](https://user-images.githubusercontent.com/61074629/153986651-584f2a70-4b9f-4086-9159-01d57bb3140c.png)

是否查看了系统日志(默认在启动用户家目录下loonflow.log):是

是否搜索过历史issue:是

**Comment by blackholll** [comment]
就是树形组织架构的显示吧？  这个有计划，不过因为重前端，我前端不熟，所以没这么快支持
