### ISSUE TITLE
HOOK请求无参数

### ISSUE THREAD

**Issue by gavine199** [blackholll/loonflow#357]
## ISSUE TEMPLATE

使用的版本:r2.0.11

问题详细描述:HOOK触发后，POST请求成功，但无工单数据传输过来，查看数据库日志
![L3N P4ZH6OGKU7D)NO_NB_N](https://user-images.githubusercontent.com/42564385/154406860-d0a598c3-ec7c-4570-9706-00db12bda01e.png)
Expecting value: line 1 column 1 (char 0)

这是HOOK配置
![~$9U{)J@DJ6@F31XP8KY_OU](https://user-images.githubusercontent.com/42564385/154406970-39459ac1-4cd0-4704-b6a6-1ca4f6c01883.png)

是否查看了系统日志(默认在启动用户家目录下loonflow.log):看过
这个是celery 的日志：这个是celery 的日志
![8K)@{G% VHJU$)T7HIG}{7M](https://user-images.githubusercontent.com/42564385/154406939-acf88703-ac68-445a-a8e3-b76732b182e7.png)

是否搜索过历史issue:是

做过哪些尝试:修改配置仍然无效

**Comment by blackholll** [comment]
运行日志也看下，  celery日志里面是通知hook，没有执行hook.    你配置的是运行hook.  应该是触发hook的时候就报错了。

**Comment by gavine199** [comment]
系统日志没看到生成呀，我的是WINDOWS运行的

**Comment by gavine199** [comment]
![image](https://user-images.githubusercontent.com/42564385/154413715-94fd7354-768e-4607-ac82-9e1de60b67f8.png)
这是操作完后loonflow.log流转的工作日志

**Comment by blackholll** [comment]
数据库中完整的错误信息发下：
![image](https://user-images.githubusercontent.com/6269605/154413974-b1f5c8c6-cef5-4752-95dc-831693504c54.png)

**Comment by gavine199** [comment]
![image](https://user-images.githubusercontent.com/42564385/154414012-f7cb286f-2c9e-438c-9ddf-18ad7eb4fcb6.png)
这是执行hook部分的日志

**Comment by gavine199** [comment]
> 数据库中完整的错误信息发下： ![image](https://user-images.githubusercontent.com/6269605/154413974-b1f5c8c6-cef5-4752-95dc-831693504c54.png)
Expecting value: line 1 column 1 (char 0)

**Comment by gavine199** [comment]
![image](https://user-images.githubusercontent.com/42564385/154479126-d14a9ad5-fd14-4cc3-a973-e12cc3331cbb.png)
这是traceback打印的错误信息

**Comment by gavine199** [comment]
已解决，请求的数据发送的 hook 函数为 r = requests.post(hook_url, headers=msg, json=json.dumps(all_ticket_data), timeout=10)
post服务器应该读取request.body
