### ISSUE TITLE
【需求】功能建议--为状态添加特定操作逻辑

### ISSUE THREAD

**Issue by fanandli** [blackholll/loonflow#358]
## ISSUE TEMPLATE
使用的版本: r2.0.11

问题详细描述:
📌1. 想请问一下，现在 "流转"只是改变状态。如何实现，在一次流转的同时，再执行一些特定的操作呢。 比如，在“运维人员审批中”这个状态时，运维人员可以选择执行“入网”的操作后，状态也流转到下一个状态了。
(简单来讲就是说，为流转增加特定的操作逻辑，而不仅仅是状态的改变。）
📌2. 是否可以在流转中 再加一个“执行逻辑”属性填入某个api，比如点“同意”流转到下一个状态的同时，也将数据传给这个api执行，如果返回成功就流转到下一个状态。这样就能达到状态流转的同时也执行了特定的操作。

是否查看了系统日志(默认在启动用户家目录下loonflow.log):否

是否搜索过历史issue:否

做过哪些尝试:否

**Comment by blackholll** [comment]
1.在这个状态后面加个状态， 新的状态的处理人是hook.   工单到达hook状态时，会触发post请求，你的hook服务方可以做一些自动化的动作
2.处理人类型hook，支持参数wait：true/false. 如果设置为true, 工单触发hook后会停在当前状态，需要hook服务方处理好后回调工单接口， 然后工单状态继续流转。 如果设置为false，工单触发hook后 如果服务方response中code=0 ,则就直接进入下个状态

**Comment by fanandli** [comment]
> 1.在这个状态后面加个状态， 新的状态的处理人是hook. 工单到达hook状态时，会触发post请求，你的hook服务方可以做一些自动化的动作 2.处理人类型hook，支持参数wait：true/false. 如果设置为true, 工单触发hook后会停在当前状态，需要hook服务方处理好后回调工单接口， 然后工单状态继续流转。 如果设置为false，工单触发hook后 如果服务方response中code=0 ,则就直接进入下个状态

好滴~非常感谢~😆😆

**Comment by fanandli** [comment]
1.我设置状态为隐藏状态，但是还是显示了
2.我已经到hook状态了，但是没有发起post请求呀。。

**Comment by blackholll** [comment]
异步任务走的celery。 需要启动celery进程. 详见文档的如何运行部分   https://loonflow.readthedocs.io/zh_CN/r2.0.11/about/start/#id2

**Comment by fanandli** [comment]
> 异步任务走的celery。 需要启动celery进程. 详见文档的如何运行部分 https://loonflow.readthedocs.io/zh_CN/r2.0.11/about/start/#id2

了解了~  感谢~
