### ISSUE TITLE
hook发不了post请求，celery日志显示No module named 'django.db.backends.mysql.compiler'

### ISSUE THREAD

**Issue by labmemW** [blackholll/loonflow#359]
## ISSUE TEMPLATE

使用的版本:2.0.11

问题详细描述:
自己配置了一个hook,向自己的服务器发送post请求，但是工单流转到hook节点时无法触发hook，也无法进入到下一阶段。查看celery日志和loonflow提示报错：ModuleNotFoundError: No module named 'django.db.backends.mysql.compiler'
是否查看了系统日志(默认在启动用户家目录下loonflow.log):
![image](https://user-images.githubusercontent.com/83324318/155504635-39afa9ec-4d05-42d2-b141-199cecb83b31.png)
/home/loonflow/loonflow_env/lib/python3.6/site-packages/下面有django.db.backends.mysql.compiler
![image](https://user-images.githubusercontent.com/83324318/155505342-c62ef6ce-4cd0-4b5f-8af4-17751fee3265.png)

是否搜索过历史issue:搜索过，但是没有解决

做过哪些尝试:新建了虚拟环境重新部署过也不行，其他的不太懂就没试过

**Comment by blackholll** [comment]
有目录不一定是安装成功了。 
1. 你的django版本是 requirement里面要求的版本么？
2. 可以进虚拟环境 import试下  from django.db.backends.mysql import compiler
3. 如果2不成功  尝试重新安装下虚拟环境

**Comment by labmemW** [comment]
![image](https://user-images.githubusercontent.com/83324318/155669166-b9bd7022-3ee3-488c-ae86-3feeaf0405b3.png)
- 1 是要求版本
- 2 虚拟环境命令行可以import成功

**Comment by blackholll** [comment]
代码运行的环境 和你这个截图里面的虚拟环境不一直吧。 loonflow_env 和 loonflow_dev

**Comment by labmemW** [comment]
这个问题我暂时解决了，写一下解决思路给后来人看。同时想问大佬一个和这个解决方案有关的问题
- ## 解决方案
参考了这篇文章解决了https://blog.csdn.net/qq_42839596/article/details/105945519
代码是先检测了我的虚拟环境`/home/loonflow/loonflow_dev/lib/python3.6/site-packages`发现` “str” object has no attribute “decode”`然后去找`/home/loonflow/loonflow_env/lib/python3.6/site-packages/`发现不存在这个模块。因此我的报错和我设置的环境不一致。
修改方案是两个地方都放了这些库，然后把其中`decode`注释掉
```
    query = getattr(cursor, '_executed', None)
    # if query is not None:
    #     query = query.decode(errors='replace')
    return query
```
这时只有部分hook任务可以执行
可能是因为任务队列里已经有很多无法完成的hook任务，我是把全部工单都从表里删掉之后再测试就都可以触发了
- ## 问题
请问一下，大佬的`\lib64\python3.6\site-packages\django\db\backends\mysql\operations.py`里的`last_executed_query`函数是怎么处理的。只是好奇我的解决方案对不对

**Comment by blackholll** [comment]
你环境错了，难道不应该是去查为何用的环境不对么？ 搜索下vscode 如何设置虚拟环境。 或者你直接在console里面命令运行
