### ISSUE TITLE
支持执行脚本报错后走另一分支吗？

### ISSUE THREAD

**Issue by jjhongpeng** [blackholll/loonflow#36]

**Comment by blackholll** [comment]
脚本执行报错会工单会停留在此状态，且工单有个标识会标记工单是脚本执行失败了。前端可以根据这个字段显示个按钮如:"重试"，用户点击重试按钮会调用loonflow的重试接口再次执行脚本。
如果需要根据脚本执行结果来走不同的分支，可以这样:
给工作流定义一个自定义字段。脚本状态的流转配置一个条件流转，这个条件表达式根据该字段确定不同的走向，脚本执行过程中根据执行结果给这个字段赋予不同的值。可以参考下https://github.com/blackholll/loonflow/issues/33
