### ISSUE TITLE
服务启动后没看到登录首页

### ISSUE THREAD

**Issue by tanxinglinux** [blackholll/loonflow#360]
## ISSUE TEMPLATE

使用的版本:r2.0.12

问题详细描述:服务启动后，页面如下图，没有跳转登录页
![image](https://user-images.githubusercontent.com/26711695/157214390-8896da47-8800-455d-8574-a64d5b664690.png)

是否查看了系统日志(默认在启动用户家目录下loonflow.log):是

是否搜索过历史issue:是

做过哪些尝试:无

**Comment by blackholll** [comment]
英文看不懂么？ https://loonflow.readthedocs.io/

**Comment by tanxinglinux** [comment]
抱歉，原因是Nginx的配置文件问题，配置文件搬运错了。
