### ISSUE TITLE
【需求】增加调用其他应用api且显示相关数据

### ISSUE THREAD

**Issue by fanandli** [blackholll/loonflow#363]
## ISSUE TEMPLATE

使用的版本:2.0.11

问题详细描述:
📌是否可以增加一个需求：
在某一个工单 执行到某一个状态时， 该状态下 调用 外部 api 显示该api返回的数据。
📌举例：
某用户申请机器。当工单执行到仓库管理员审批状态时， 仓库管理员可以在此时不仅可以看到自定义字段中申请者填写的信息，还可以看到调用外部api获取到的数据。（比如，显示了仓库中库存机器的剩余量）
📌总结：
希望工作流系统 不仅可以发送api 还可以发送api后 在某一状态时展示发送api返回的数据。

谢谢😄
是否查看了系统日志(默认在启动用户家目录下loonflow.log):否

是否搜索过历史issue:否

做过哪些尝试:看源码

**Comment by blackholll** [comment]
这个需求后续会考虑支持。但是没这么快。 
当前我们公司在用的版本实现如下:
支持了外部数据源类型。实现就是原有的字符串、整形、选项这些类型新增一个外部数据源的类型。这个类型会去请求一个地址，然后从这个地址获取数据。数据的格式分为三种: 表格、键值对、字符串。 前端会根据这三种类型做相应的展示形式。 

当前的方案:
1.自己先实现
2.变通的方式
提交工单后， 下个节点是个hook， 此hook获取需要展示的数据，然后调用工单的修改工单字段值的接口将需要展示的信息填写到工单中去， 这样后面的节点就可以展示了

**Comment by fanandli** [comment]
> 这个需求后续会考虑支持。但是没这么快。 当前我们公司在用的版本实现如下: 支持了外部数据源类型。实现就是原有的字符串、整形、选项这些类型新增一个外部数据源的类型。这个类型会去请求一个地址，然后从这个地址获取数据。数据的格式分为三种: 表格、键值对、字符串。 前端会根据这三种类型做相应的展示形式。
> 
> 当前的方案: 1.自己先实现 2.变通的方式 提交工单后， 下个节点是个hook， 此hook获取需要展示的数据，然后调用工单的修改工单字段值的接口将需要展示的信息填写到工单中去， 这样后面的节点就可以展示了

是update_ticket_field_value这个函数吗，谢谢啦

**Comment by blackholll** [comment]
不要直接调用方法。 通过api调用:  https://loonflow.readthedocs.io/zh_CN/r2.0.12/api_docs/ticket/#id15

**Comment by fanandli** [comment]
> 不要直接调用方法。 通过api调用: https://loonflow.readthedocs.io/zh_CN/r2.0.12/api_docs/ticket/#id15

好滴，谢谢~
