### ISSUE TITLE
子流程配置问题

### ISSUE THREAD

**Issue by Baoanxia** [blackholll/loonflow#364]
## ISSUE TEMPLATE

使用的版本:2.0.12

问题详细描述:
子工单配置问题。
A到B之后无法继续流程了
是否搜索过历史issue:

做过哪些尝试:
![父工作流](https://user-images.githubusercontent.com/70136571/159669412-904280b3-99c1-4927-9910-f9fa3960112d.jpg)
![子工作流](https://user-images.githubusercontent.com/70136571/159669941-68b905d3-6178-4701-beea-3a9fdee33140.jpg)
![数据库](https://user-images.githubusercontent.com/70136571/159669991-10606c43-2c82-4352-b883-1269e364064e.jpg)

**Comment by Baoanxia** [comment]
![数据库](https://user-images.githubusercontent.com/70136571/159670335-c2fc9f32-3b84-4a4b-9506-4bce4f73581c.jpg)

**Comment by blackholll** [comment]
子工作流无需配置， 需要自己实现创建子工单的的逻辑，创建时传递父工单的id和父工单需要关联子工单的状态的id。 父工单的相同状态下可以创建多个类型(工作流)的子工单。 当所有子工单状态都结束时，将触发父工单的状态流转。  
子工作流参考：https://github.com/blackholll/loonflow/issues/199
