### ISSUE TITLE
有个接口调用有疑问

### ISSUE THREAD

**Issue by fanandli** [blackholll/loonflow#368]
## ISSUE TEMPLATE

使用的版本:2.0.11

问题详细描述:
127.0.0.1:6060/api/v1.0/workflows/{workflow_id}这个接口 使用有问题。传入数据库中存在的username提示
username:  is not existed or has been deleted"。传入不存在的username则正确判断此username不存在。
是否查看了系统日志(默认在启动用户家目录下loonflow.log):
![image](https://user-images.githubusercontent.com/37018548/164393544-4e17395f-6c31-4d70-8f09-13b84a3a30b2.png)

是否搜索过历史issue:

做过哪些尝试:
自己看了下代码，是@auto_log的原因，调用了两次get_user_by_username函数。第二次传的是默认的空值。
（弱弱的问一下，可以加微信不，已捐助呀）

**Comment by blackholll** [comment]
api请求的处理逻辑会经过: 
1.中间件 service.permission.api_permission.ApiPermissionCheck 
2. view方法的装饰器,如本接口的是manage_permission_check('workflow_admin')

调用get_user_by_username分别是在中间件中 和view方法体中。  中间件中是根据header中获取username， view方法体中是根据request.user.username获取用户的，应该是你通过api调用的方式， loonflow没处理好，到最后用request.user.username获取不到用户。 

manage_permission_check装饰的接口，本意是不准备对外开放的。  你可以说下你的场景，为什么需要用这个接口

捐助后，可以qq私聊，截图发我。

**Comment by fanandli** [comment]
> api请求的处理逻辑会经过: 1.中间件 service.permission.api_permission.ApiPermissionCheck 2. view方法的装饰器,如本接口的是manage_permission_check('workflow_admin')
> 
> 调用get_user_by_username分别是在中间件中 和view方法体中。 中间件中是根据header中获取username， view方法体中是根据request.user.username获取用户的，应该是你通过api调用的方式， loonflow没处理好，到最后用request.user.username获取不到用户。
> 
> manage_permission_check装饰的接口，本意是不准备对外开放的。 你可以说下你的场景，为什么需要用这个接口
> 
> 捐助后，可以qq私聊，截图发我。

已解决，谢谢~

**Comment by sendtion** [comment]
我也遇到了这个问题，请问是怎么解决的呢 @fanandli

**Comment by blackholll** [comment]
> 我也遇到了这个问题，请问是怎么解决的呢 @fanandli
manage_permission_check装饰的接口本意是不准备提供应用调用的。如果你是自己写前端，可以参考当前loonflow前端的方式，先登录，然后带上jwt访问

**Comment by sendtion** [comment]
可以登录后获取jwt，然后放置到cookie中，但是好像不行，貌似还需要sessionid，但是加上sessionid后我们自己的接口不行了，为什么获取工作流列表就可以，获取详情不行了呢？还有别的方式吗？ @blackholl

**Comment by blackholll** [comment]
@sendtion 为什么你需要调用workflow接口，配置界面也要自己写么？ 如果需要后端调用的话可以吧这个地方改下。 因为登录或者直接api调用这个header中的user都会被替换为实际的用户 
![image](https://user-images.githubusercontent.com/6269605/165894837-45b82d0f-893b-4708-8e5d-88cfedc9c5e7.png)

**Comment by sendtion** [comment]
@blackholll 这么修改后可以访问了，谢谢拉
