### ISSUE TITLE
重置或撤回流程后 发起人再次发起报错

### ISSUE THREAD

**Issue by Hanppytiger** [blackholll/loonflow#369]
## ISSUE TEMPLATE

使用的版本:
r2.0.12

问题详细描述:
我搭建了一个流程，有发起人 预审节点 部门负责人节点 结束节点  ，预审节点是多个人且全部处理设置。当预审节点的多个人意见不一致的时候，由于流程状态停止在预审节点，并未往下一个节点执行，于是我写了逻辑把该流程重置到发起人节点或者后台模拟发起人撤回。总之流程由回到了发起人，但是此时发起人再次提交的时候，调用工单处理接口，返回错误为：
{'code': -1, 'data': {}, 'msg': "local variable 'destination_participant_type_id' referenced before assignment"}
是否查看了系统日志(默认在启动用户家目录下loonflow.log):
看了日志，日志大小为0
-rw-r--r--  1 root root    0 Mar 18 20:07 loonflow.log

是否搜索过历史issue:
没有，我先提交吧，写了半天了
做过哪些尝试:
打开loonflow源码 看了下 apps ticket views 下的handle_ticket，没看出啥问题
不过由于我只是想使用 不想修改loonflow所以没搭建loonflow的开发环境

**Comment by Hanppytiger** [comment]
然后使用管理员去工作流平台  强制修改状态 到发起人  之后发起人发起还是报这个错误
{'code': -1, 'data': {}, 'msg': "local variable 'destination_participant_type_id' referenced before assignment"}

**Comment by blackholll** [comment]
uwsgi日志看下这个错误是哪段代码出错的。

**Comment by Hanppytiger** [comment]
是不是因为我配置uwsgi 没有做好配置，我的uwsgi.log 只有我调用了什么形如：
![image](https://user-images.githubusercontent.com/104182244/164648094-1c8e85e5-0980-49e6-bddd-b1392051f16f.png)

**Comment by Hanppytiger** [comment]
是不是因为我配置uwsgi 没有做好配置，我的uwsgi.log 只有我调用了什么形如：
![image](https://user-images.githubusercontent.com/104182244/164648305-d024030a-e8ef-43a6-8b60-4d44ffba8f05.png)

**Comment by Hanppytiger** [comment]
这些配置都是原来没动的
![image](https://user-images.githubusercontent.com/104182244/164649973-9fd51f4b-ee26-4ceb-8cb1-df34ef9e5d40.png)

**Comment by blackholll** [comment]
你再次提交的时候怎么传参的

**Comment by Hanppytiger** [comment]
> 你再次提交的时候怎么传参的

和普通处理工单一样：三个参数形如：'transition_id': 27, 'suggestion': '两点上课进来多少看链接', 'title': '测试全部处理一个先同意一个再拒绝042204'。再加上作为发起人必填的页面字段一起传参的。

普通的正常被退回的单据，发起人发起是不报错的。

**Comment by blackholll** [comment]
好像用uwsgi后日志是有会有问题。 你可以python manage.py runserver启动下(注意配置)， 然后再调用下，看下日志

**Comment by Hanppytiger** [comment]
> 好像用uwsgi后日志是有会有问题。 你可以python manage.py runserver启动下(注意配置)， 然后再调用下，看下日志

![image](https://user-images.githubusercontent.com/104182244/164677901-aea0ae2a-a62c-4b5c-8963-b72d26a984b2.png)
22-04-22 17:24:31,131 /website/wwwroot/loonflow/service/common/log_service.py process-2972368 thread-140306271938304 20 [ERROR]: Traceback (most recent call last):
  File "/website/wwwroot/loonflow/service/common/log_service.py", line 17, in _deco
    real_func = func(*args, **kwargs)
  File "/website/wwwroot/loonflow/service/ticket/ticket_base_service.py", line 1188, in handle_ticket
    ticket_obj.participant_type_id = destination_participant_type_id
UnboundLocalError: local variable 'destination_participant_type_id' referenced before assignment

**Comment by Hanppytiger** [comment]
我看了下，貌似是在多人审批，出现不一致意见导致节点的状态停留在那个节点的时候，强制修改状态还是后台撤回，表单详情中的是否是multi_all_person，没有被修改回去。我再试一个正常的。
下面第一个图是报错的 表单信息，第二个图是正常的表单信息
![image](https://user-images.githubusercontent.com/104182244/164681549-19d6eaf5-4318-4420-8132-8604b88da243.png)
![image](https://user-images.githubusercontent.com/104182244/164682926-5c13cda0-55ed-4e29-bad6-fc8eb9d715a0.png)

**Comment by Hanppytiger** [comment]
![image](https://user-images.githubusercontent.com/104182244/164684762-5aeea163-dddf-4e68-9e3e-b5cab9f09de6.png)

接上：
然后走了 这两个if 以外的分支，这两个以外的分支都没有写逻辑，所以没有提前分配或者定义他destination_participant_type_id
在1188行的时候  把他赋值给别人的时候 就报错了

**Comment by blackholll** [comment]
对的。 强制修改状态应该将multi_all_person重置为"{}"的。
针对全部处理，处理操作不同时， 比较合理的做法应该是将状态流转到 拒绝属性的操作去的。 但是如果多个分支都没设置拒绝属性 也还是会导致没有后续处理人。 

针对被退回导致无法重新提交的问题，你可以先这么改下代码。  因为非重要bug， 我这边等有其他问题的时候，再发布新版本
![image](https://user-images.githubusercontent.com/6269605/164688193-e4fef893-864e-41a6-96aa-dc5a5c9ff965.png)

**Comment by Hanppytiger** [comment]
是的  因为我设置的流程是发起人提交后到多人节点，所以多人审批不一致的时候，强行回到拒绝属性 刚好是发起人。
当然 我准备做的工作流 比较简单 不允许退回到其他节点，只能退回到发起人

以上，多谢了，我先处理下  辛苦啦

**Comment by blackholll** [comment]
fixed in r2.0.13
