### ISSUE TITLE
创建工作流设置展现表单字段, 接口返回的file_list字段中没有设置的字段

### ISSUE THREAD

**Issue by smilesmall** [blackholll/loonflow#37]

**Comment by blackholll** [comment]
表单字段设置有两个地方：
1.工作流的设置中
工作流的设置中设定的展现字段用于，当用户无处理权限，但是有查看权限(是工单的关系人，或者工作流未开启查看权限校验时)时候需要显示的字段。这里的设置是一个字段标识组成的list的json格式
2.工作流状态的设置中
此处的设置是针对用户有该工单处理权限时，当请求工单详情接口时，会根据工单当前状态设置的字段以及字段的属性(只读，可选，必填)来返回字段信息

为何要如此设计:
1.工单在不同处理状态下，需要处理人填写不同的表单信息，所有当有处理权限时返回的表单字段信息不同
2.当用户在查看工单时， 需要查看工单的所有信息。所以在工作流设置下定义这些字段

**Comment by wys523310** [comment]
您好 我想问一下 状态配置里 这个参与人是创建人 这块具体该怎么写？创建人的TL我在哪获取？

**Comment by wys523310** [comment]
您好 我想问一下 状态配置里 这个参与人是创建人 这块具体该怎么写？创建人的TL我在哪获取？
![微信图片_20240611095458](https://github.com/blackholll/loonflow/assets/111214241/ac90388f-0210-42a8-8d2b-7c0032962847)

**Comment by blackholll** [comment]
如果是需要 这个状态的处理人是工单创建人本人： 参与人类型选“变量”， 参与人填写 creator
如果是需要这个状态的处理人是工单创建人的tl: 参与人类型选“变量”， 参与人填写 creator_tl

loonflow获取创建人tl的逻辑是先找到这个人所在部门， 然后找到部门记录的的审批人字段中的信息，如果审批人字段内容为空，则取部门的leader字段

**Comment by wys523310** [comment]
> 如果是需要 这个状态的处理人是工单创建人本人： 参与人类型选“变量”， 参与人填写 creator 如果是需要这个状态的处理人是工单创建人的tl: 参与人类型选“变量”， 参与人填写 creator_tl
> 
> loonflow获取创建人tl的逻辑是先找到这个人所在部门， 然后找到部门记录的的审批人字段中的信息，如果审批人字段内容为空，则取部门的leader字段

好的 非常感谢
