### ISSUE TITLE
内容模板中，可用的工单字段都有哪些，在哪里可以查到

### ISSUE THREAD

**Issue by agclqq** [blackholll/loonflow#373]
## ISSUE TEMPLATE

使用的版本: r2.0.13

问题详细描述:
  在使用hook通知状态时，内容模板中，除了默认的『工单字段的值可以作为参数写到模板中，格式如：标题:{title}, 创建时间:{gmt_created}』，还有哪些可用的值？
  **想根据当前通知，来判断当前流程是否结束**
是否查看了系统日志(默认在启动用户家目录下loonflow.log):与log无关
 
是否搜索过历史issue:是

做过哪些尝试:  工单其他字段，尝试过 state_id成功，state_type,state_type_id,type_id,state_info,state_info均失败。

文档中未找到对应内容，希望能得到帮助，谢谢

**Comment by blackholll** [comment]
代码是在：service.ticket.ticket_base_service.get_ticket_all_field_value中。
包含TicketRecord 对象中的所有字段+ 工单的自定义字段的值。
工单当前状态的详细信息当前是没有的。如果需要工单当前状态的名称，可以调用api/v1.0/tickets/states接口来获取

**Comment by agclqq** [comment]
多谢
