### ISSUE TITLE
复杂表单该怎么处理比较好

### ISSUE THREAD

**Issue by caoqianming** [blackholll/loonflow#378]
## ISSUE TEMPLATE

使用的版本:最新

问题详细描述:审批开始创建的时候填写信息比较复杂，关联好几个表，比如说需要表格选择功能或者就是新建表格等等；这种情况该怎么处理，或者还有一个方案就是能否只用流程审批，不用loonflow的自定义表单功能呢

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:是

做过哪些尝试:

**Comment by blackholll** [comment]
你自己写前端的话 当然可以不用loonflow的表单功能。
你也可以自定义字段，设置一下标签，表单展示的时候可以这个标签来显示你的个性化表单

**Comment by caoqianming** [comment]
那条件流转以及选择审批人。这块需要用到自己创建出来的信息，这块怎么配置。有什么好的思路呢；我刚想了一下，可以把需要用到的字段设成工作流自定义字段，这样创建的时候走自己的接口，然后提交审批的时候后端创建审批流把需要的字段填进去，应该是可行的吧

**Comment by blackholll** [comment]
可行。不过更推荐的做法是:
给loonflow新增一个处理人类型: "从外部获取"(到达给状态时，发送请求，由hook服务方告知处理人)。这个功能是后续计划支持的。 你有时间的话可以提交pr

**Comment by caoqianming** [comment]
嗯，谢谢。获取处理人可以用hook，条件流转估计还是得需要字段信息。还有个问题，如果我创建工单后不立即流转，而是统一流转，比如创建几个工单后统一提交，该怎么处理比较好。是不是后台强制更改工单状态?

**Comment by blackholll** [comment]
说下具体场景， 为什么需要几个工单填写后  再提交

**Comment by caoqianming** [comment]
不用了。。我又思考了一下，改了逻辑。我先按前面说的实现一下试试
