### ISSUE TITLE
建议能否将说明文档在详细些，尽可能面对小白~感谢开发者

### ISSUE THREAD

**Issue by niujinkai** [blackholll/loonflow#379]
## ISSUE TEMPLATE

使用的版本:2.0.13

问题详细描述:对于这个项目的部署还是不是特别理解，能否完整的提供下教程呢 ？例如

是否查看了系统日志(默认在启动用户家目录下loonflow.log):无

是否搜索过历史issue:是

做过哪些尝试:自己尝试看过多次文档，但是确实还是没透彻理解

**Comment by blackholll** [comment]
需要详细到什么程度？ 有哪里不理解的  指出来

**Comment by niujinkai** [comment]
就是，需要准备哪些环境，这些环境的配置，我看了网络上关于这个项目的所有文档，几乎和你的一模一样，所以，有没有，从0搭建的教程

**Comment by niujinkai** [comment]
> 需要详细到什么程度？ 有哪里不理解的  指出来

就是，需要准备哪些环境，这些环境的配置，我看了网络上关于这个项目的所有文档，几乎和你的一模一样，所以，有没有，从0搭建的教程

**Comment by niujinkai** [comment]
> 需要详细到什么程度？ 有哪里不理解的  指出来

您好，首先并不是说不好，确实很喜欢这个项目，但是我看文档，部署的时候，不知道事先需要准备哪些环境，或者不知道从哪开始，还望开发者指导，谢谢

**Comment by blackholll** [comment]
你看的是这个文档么？ https://loonflow.readthedocs.io/zh_CN/r2.0.13/about/start/

**Comment by niujinkai** [comment]
> 你看的是这个文档么？ https://loonflow.readthedocs.io/zh_CN/r2.0.13/about/start/

您好 是的

**Comment by blackholll** [comment]
这个已经够详细了啊，  另外这里有一些之前录制的免费视频（录的比较早，和最新版本有些差异），可以参考下
https://www.ixigua.com/6756220859498627588

**Comment by niujinkai** [comment]
> 这个已经够详细了啊， 另外这里有一些之前录制的免费视频（录的比较早，和最新版本有些差异），可以参考下 https://www.ixigua.com/6756220859498627588

好的 谢谢
