### ISSUE TITLE
部门领导提交的请假审批过滤掉部门审批的环节

### ISSUE THREAD

**Issue by bmw66990** [blackholll/loonflow#380]
## ISSUE TEMPLATE

使用的版本:2.0.14

问题详细描述:
![894E1A7E9ECDD17092324FF74CF37AD5](https://user-images.githubusercontent.com/18702033/175197522-acf68675-e23f-446a-b6de-8f41651c00e2.jpg)
如图所示，这是我创建的关于请假流程的流程图，面临的问题是，当前如果是部门的部长提交的话，需要通过表达式的判断来过滤掉部长审批环节，直接到人事审批环节，当前的这个表达式该咋写啊
![4CEEE6242641ED43426D1225AF978E23](https://user-images.githubusercontent.com/18702033/175197545-d8cadf9c-bb55-490e-ac01-f1e2cf386f54.jpg)
![6D818D94D7C0E50011419990556B8AF2](https://user-images.githubusercontent.com/18702033/175197567-f8ecf4b8-1c3b-4fa8-99d1-9fcc4a5821ad.jpg)

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:

做过哪些尝试:

**Comment by blackholll** [comment]
提交 这个流转里面 加个条件表达式 [{"expression":"{creator}  in ('zhangsan', 'lisi')", "target_id":3},{"expression":"{creator} not in ('zhangsan','lisi')","target_id":4}]
creator为创建人的用户名。  这里的3指的是人事审批的状态的id(你根据实际情况自己改下)

另外一种方案，创建个自定字段，用于表示是否是部门领导， 调用工单接口创建工单的时候传下这个字段。 然后后面流转根据这个字段来做条件判断

**Comment by bmw66990** [comment]
感谢，感谢

**Comment by bmw66990** [comment]
<img width="863" alt="image" src="https://user-images.githubusercontent.com/18702033/175450562-81d22f2d-aecc-47af-acbe-6fe21fb051f1.png">
<img width="579" alt="image" src="https://user-images.githubusercontent.com/18702033/175450741-80f837ef-58ca-48f8-8be6-fd436370963f.png">
表达式中支持时间变量的相加，相减的基础运算吗？或者其他整型、浮点型的基础运算吗？

**Comment by bmw66990** [comment]
当一个流程已经创建好了，并且已经有个工单正在运转，这时候对流程进行修改的话，当前运转的工单还能正常的流转下去吗

**Comment by blackholll** [comment]
每次流转都会拿最新的配置。 如流程是a-b-c。 当工单处于b状态  你改了c状态的属性。 b流向c时就会拿到c最新的配置

**Comment by bmw66990** [comment]
> <img alt="image" width="863" src="https://user-images.githubusercontent.com/18702033/175450562-81d22f2d-aecc-47af-acbe-6fe21fb051f1.png">
> 
> <img alt="image" width="579" src="https://user-images.githubusercontent.com/18702033/175450741-80f837ef-58ca-48f8-8be6-fd436370963f.png">
> 
> 表达式中支持时间变量的相加，相减的基础运算吗？或者其他整型、浮点型的基础运算吗？

经过测试发现支持整型、浮点型的运算，但是这里如果是时间变量的话，除了增加额外的字段外，能不能通过写表达式的方式进行时间的运算

**Comment by blackholll** [comment]
time 和datetime支持的

**Comment by bmw66990** [comment]
> 

<img width="649" alt="image" src="https://user-images.githubusercontent.com/18702033/175454663-b3b2881b-2a76-4cb6-888c-9d914b421a4a.png">
![image](https://user-images.githubusercontent.com/18702033/175454786-560f1ab9-48b4-4352-9617-e46cac710583.png)
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/18702033/175454847-3eb8100f-146d-405f-9808-f77df06456ca.png">
点击提交后提示这个问题

**Comment by blackholll** [comment]
你需要先用datetime转成时间格式在比较  因为条件表达式运算赋值的时候都当作字符串或整形了

**Comment by bmw66990** [comment]
我在表达式中修改吗？您有没有这个表达式的写法规则啊

**Comment by bmw66990** [comment]
> 我在表达式中修改吗？您有没有这个表达式的写法规则啊

 通过写复杂的表达式，可以在不修改代码的情况下，完美的实现逻辑

**Comment by bmw66990** [comment]
> > 我在表达式中修改吗？您有没有这个表达式的写法规则啊
> 
> 通过写复杂的表达式，可以在不修改代码的情况下，完美的实现逻辑

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/18702033/175459071-033a2659-890e-47fb-8ec7-4028c9b7ac0b.png">
通过研究发现得出来，流转中的表达式的说明和运算规则

**Comment by blackholll** [comment]
对的  就类似这样。因为是json 注意下引号问题

**Comment by blackholll** [comment]
表达式规则   你都找到代码所在了， 看代码应该可以理解的出来

**Comment by bmw66990** [comment]
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/18702033/175505821-531fc7cb-e075-453d-880e-35be50fbbdd6.png">
<img width="705" alt="image" src="https://user-images.githubusercontent.com/18702033/175505622-926d4f17-ef55-4680-8b33-e7db72efd66b.png">
这个选择通知和通知模版内容该如何配置和使用？我配置之后怎么验证是否配置成功？

**Comment by blackholll** [comment]
节点hook和通知都是通过celery执行的。  需要启动celery。   通知是在工单状态发生变化都会调用。  你可以在你配置的hook服务端打印日志来校验
