### ISSUE TITLE
图中的静态资源，能否改成本地加载

### ISSUE THREAD

**Issue by ghost** [blackholll/loonflow#382]
如图，这个静态资源，能否本地加载，因为内网环境下，无法访问公网，会导致页面加载时间较长。

![092261C4-6C35-45fa-96A3-71D9603BAFCD.png](https://user-images.githubusercontent.com/97371434/176410755-c7965be5-636e-49d0-bc70-9dca061bd66e.png)

**Comment by niujinkai** [comment]
查看了下，是项目logo

**Comment by blackholll** [comment]
你可以先全局搜索 然后改下。  这边等下个版本一起改下

**Comment by niujinkai** [comment]
> 你可以先全局搜索 然后改下。  这边等下个版本一起改下
这边儿看了一下，引用的地方还比较多。所以建议下一个版本优化一下，谢谢了。
![mmexport1656559678459.png](https://user-images.githubusercontent.com/97371434/176586684-dddd9383-c612-4910-aeee-a3824168909f.png)

**Comment by blackholll** [comment]
changed in https://github.com/blackholll/loonflow/releases/tag/r2.0.14
