### ISSUE TITLE
一个工单里面有办法填写多条记录吗？

### ISSUE THREAD

**Issue by ammimi** [blackholll/loonflow#385]
比如请假申请， 是否可以在一个工单里面填写多条请假记录，然后再提交申请

**Comment by blackholll** [comment]
两种方案:
1. 新增一个自定义字段，设置一个标签， 你的前端根据这个标签来支持插入多条记录， 展示的时候也根据这个标签来特殊展示
2. loonflow新增一个字段类型， 如“明细”，明细中支持多个子字段。 填写的时候可以成组添加。 目前暂不支持， 欢迎提交pr
