### ISSUE TITLE
获取工单详情creator_info中id和name会出现多个逗号

### ISSUE THREAD

**Issue by Jayden-he** [blackholll/loonflow#386]
获取工单详情creator_info中id和name会出现多个逗号
![S3V9M{J(43AG}C81{FP%@0B](https://user-images.githubusercontent.com/31341179/184057851-3554e9ce-0392-4d18-8219-7e4365187aae.png)

**Comment by blackholll** [comment]
user_dept_info.id吧， 2.0.14修复。 2.0.14要吧docker 部署部分优化下，需要点时间，预计8月底发布
<img width="708" alt="image" src="https://user-images.githubusercontent.com/6269605/184134972-0c62dad4-c0a4-45a3-893e-f44f71031c58.png">

**Comment by blackholll** [comment]
fixed in https://github.com/blackholll/loonflow/releases/tag/r2.0.14
