### ISSUE TITLE
多层级审批

### ISSUE THREAD

**Issue by Jayden-he** [blackholll/loonflow#389]
假如我在当前流程选择了creator_tl审批，下一个流程节点我想tl的上级审批，这个要怎么做呢？

**Comment by blackholll** [comment]
方案一:
定制loonflow,新支持一种变量：二级leader,  需要自己写下逻辑。 前端比较好找，直接全文搜索下，后端需要改这个方法：
https://github.com/blackholll/loonflow/blob/294fcc51449c6fcfbac7974e6685109d60c68059/service/ticket/ticket_base_service.py#L1940

方案二: 
新增一个自定字段，比如叫二级leader.  创建工单的时候获取这个值提交， 下个状态的处理人用这个工单字段

方案三: 
新增一个自定义字段，比如叫二级leader,   在creatortl审批节点后面  新增一节点处理人类型用hook,  你的hook服务端收到hook请求后 获取工单创建人的二级leader,  调用修改工单字段的接口，将这个字段的值修改为二级leader.   下个节点的处理人用这个工单字段
