### ISSUE TITLE
celery

### ISSUE THREAD

**Issue by Qianzujin** [blackholll/loonflow#39]
请问这个redis是给celery用的嘛，可以换mysql嘛

**Comment by blackholll** [comment]
redis的作用有:
1.创建工单的时候生成自增的流水号，利用了redis的自增特性
2.通知脚本、状态脚本使用了celery执行异步任务，redis作为消息队列使用。 celery支持的消息队列有RabbitMQ, redis,Amazon SQS, Zookeeper. 不支持mysql
