### ISSUE TITLE
流程流转的问题

### ISSUE THREAD

**Issue by bmw66990** [blackholll/loonflow#391]
## ISSUE TEMPLATE

使用的版本:
2.0.14
问题详细描述:
假设当前有5个流程，A，B，C，D，E
A流程流转完之后，可以流转到B，C，D任意流程，没有先后顺序，E流程在操作的时候，必须判断B，C，D流程是否都操作了之后，才能进行E流程的操作
是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:

做过哪些尝试:

**Comment by blackholll** [comment]
这里的A B C D E 是节点吧。   你将BCD合并成一个节点， 然后处理人是之前BCD的处理人一起。 并将这个节点的流转类型设置为全部处理
