### ISSUE TITLE
docker部署报错问题

### ISSUE THREAD

**Issue by moeik** [blackholll/loonflow#392]
## ISSUE TEMPLATE

使用的版本:
Latest
问题详细描述:
使用docker部署报错
是否查看了系统日志(默认在启动用户家目录下loonflow.log):
直接打印出来了
是否搜索过历史issue:
没有相关解答
做过哪些尝试:
![image](https://user-images.githubusercontent.com/49871008/200500216-808105f6-5ddc-48fc-87fd-4ae622ac6a48.png)

**Comment by micro-stone** [comment]
centos docker 部署报同样的错误。

**Comment by blackholll** [comment]
这是docker buildimage的时候使用的源 没有指定版本的依赖包。 可能是有些包的依赖版本变更 导致需要了这个版本。 可以换个pypi源试下

**Comment by iksyz** [comment]
依赖的包都是python3.10.x的，但是centos7下安装的python是3.6.x的，得换基础镜像

**Comment by blackholll** [comment]
也可能是因为docker_compose_deploy目录下下dockerfile里面不是使用的python3.10.   requirements/common.txt里面是注明了使用python3.10.    dockerfile里面忘了改了

**Comment by blackholll** [comment]
fixed in r2.0.15
