### ISSUE TITLE
接单相关

### ISSUE THREAD

**Issue by Sunny-SKY-S** [blackholll/loonflow#393]
当前状态为 多选用户名的工单字段 作为处理人时, 且此状态需要接单时, 执行保存操作(重新流转回当前状态)有些问题.
比如此状态有ABC三个处理人, A进行接单, 然后A就可以处理工单, 但是当A执行保存操作后, 此工单又需要ABC重新执行接单操作了
逻辑上这样是没啥问题, 但是怎样实现A保存完, 还是A处理, 不用接单?(在不考虑保存完进入脚本状态的情况下)

**Comment by blackholll** [comment]
编辑状态节点是有个配置：记忆最后处理人， 把这个状态的这个配置勾选上

**Comment by Sunny-SKY-S** [comment]
> 编辑状态节点是有个配置：记忆最后处理人， 把这个状态的这个配置勾选上

好的, 感谢

**Comment by Sunny-SKY-S** [comment]
> 编辑状态节点是有个配置：记忆最后处理人， 把这个状态的这个配置勾选上

但是打开这个功能后, 该状态不能执行转单的操作了(即修改字段为其它人), 当前状态处理人被锁死为接单的人了

**Comment by blackholll** [comment]
转交不会考虑这个配置。 a接单后可以转给b，  b再保存后处理人还会是b
