### ISSUE TITLE
外部获取,工单创建前执行get_ticket_all_field_value，报错

### ISSUE THREAD

**Issue by tuiche** [blackholll/loonflow#396]
File "/home/hui/loonflow-r2.0.14/service/common/log_service.py", line 17, in _deco
    real_func = func(*args, **kwargs)
  File "/home/hui/loonflow-r2.0.14/service/ticket/ticket_base_service.py", line 2101, in get_ticket_state_participant_info
    all_ticket_data.update(dict(extra_info=extra_info))
AttributeError: 'str' object has no attribute 'update'

**Comment by blackholll** [comment]
你改过代码吧?  https://github.com/blackholll/loonflow/blob/r2.0.14/service/ticket/ticket_base_service.py#L2101   这个版本的2101行代码不是这样的。
应该是在2076行。  这里确实有问题 你可以临时把这行修改下， 我近期出个版本修复下
flag, all_ticket_data = ticket_base_service_ins.get_ticket_all_field_value(ticket_id)改成

`
if ticket:
    flag, all_ticket_data = ticket_base_service_ins.get_ticket_all_field_value(ticket_id)
else:
    all_ticket_data = ticket_req_dict
`

**Comment by blackholll** [comment]
2082是说的这个错误吧 
https://github.com/blackholll/loonflow/issues/395

**Comment by tuiche** [comment]
嗯，是这个,能把destination_state_id（放外层好取一点）默认也传进去更好，然后根据workflow_id，destination_state_id和一些其它字段信息来生成参与人

**Comment by blackholll** [comment]
这些信息你可以在配置的时候放在extra_info里面
