### ISSUE TITLE
自定义api中get请求参数丢失

### ISSUE THREAD

**Issue by sakeri1** [blackholll/loonflow#397]
## ISSUE TEMPLATE

使用的版本:
loonflow-r2.0.14
问题详细描述:
自定义的api接口中使用get请求带参数时，参数丢失
export async function getDetailDetailUserRequest(ticketId: number,params: getDetailDetailUserRequestType) {
  return request<API.CommonResponse> (`/api/v1.0/tickets/${ticketId}`,{
    method: 'get',
    data:params
  })
}
此时查看json_str = request.body.decode('utf-8')中json_str为空

是否查看了系统日志(默认在启动用户家目录下loonflow.log):
是
是否搜索过历史issue:
是
做过哪些尝试:
使用post可以带参数

**Comment by blackholll** [comment]
get请求 前端用params:params  不用data：params
后端用request_data = request.GET获取参数

**Comment by sakeri1** [comment]
谢谢，非常感谢

**Comment by sakeri1** [comment]
再请教您一个问题，我想可以通过点击工单进度中的节点，实时刷新工单信息中的内容，我现在可以获取到每个节点中工单信息的内容，我不知道怎么去刷新工单信息中显示，我不太会前端，感谢万分

**Comment by blackholll** [comment]
实时刷新工单信息内容指的是 需要查看工单在对应状态时刻的信息么? 这个信息目前是存在flowlog表中的.
至于刷新工单信息显示, 要注意不同状态下显示的字段数量也是不一样的，如果你用react的话将内容更新到state中去 就会自动重新渲染前端的

**Comment by sakeri1** [comment]
我在工单进度的Steps中添加了onchange方法，重写了您代码中的getDetailDetailRequest方法，新增个一个参数state_id:value，其余内容都是和原方法一样的，getDetailDetailUserRequest中直接返回state_id（当前点击到的进度的id）,返回值也是和您getDetailDetailRequest返回值一样，我现在不知道怎么把这个返回的result，传递给工单信息，我需要传递到那个state中才可以？感谢
  const onChange = async (value) => {
    const result = await getDetailDetailUserRequest(props.ticketId,{state_id:value});
    if (result.code === 0) {
      message.success('修改状态成功');
    } else {
      message.error(`修改状态失败`)
    }
  };

**Comment by blackholll** [comment]
你的step onchange 是在 src/pages/Ticket/TicketDetail/index.tsx中  TicketStep 组件中. 需要更新的是其父组件中的 ticketInfo这个status  也就是 子组件与父组件通信. 你晚上搜索下react 父子组件通信.
另外不同状态下需要显示的字段是不一样的， 你这种需要显示每个状态的所有字段的信息， 详情中的表单这块逻辑也需要调整下

**Comment by sakeri1** [comment]
嗯嗯，这个已经搞定了，感谢，不过我还有一个小问题不知道是不是bug，在上传附件的时候，上传按钮请求的api是api/v1.0/tickets/upload_file，有的时候点击上传请求的api里面多了一个tickets，导致上传文件失败，这个大概可能时那块的问题呢？
页面是：
        // 附件import BraftEditor from 'braft-editor'
        child = <Upload action="api/v1.0/tickets/upload_file" listType="text" onChange={(info)=>this.fileChange(item.field_key, info)} fileList={this.state.fileList[item.field_key]}>
        {/*child = <Upload action="api/v1.0/tickets/upload_file" listType="text" onChange={(info)=>this.fileChange(item.field_key, info)}>*/}
          <Button icon={<UploadOutlined />}>Click to upload</Button>
        </Upload>
实际上请求的url是Request URL: http://127.0.0.1:8000/tickets/api/v1.0/tickets/upload_file，我上传图片一直失败，麻烦帮忙看一下可能是那块有问题，我排查一下

**Comment by blackholll** [comment]
action="api/v1.0/tickets/upload_file"  改成 action="/api/v1.0/tickets/upload_file"
