### ISSUE TITLE
工作流分类如何处理, 需要自己新加字段吗?

### ISSUE THREAD

**Issue by smilesmall** [blackholll/loonflow#40]

**Comment by blackholll** [comment]
两种方式:
1.修改loonflow 的model。给Workflow新增字段， 然后工作流列表接口支持这个字段的查询
2.在你自己的应用的后端新建一个表，用于保存分类与loonflow中工作流id的映射关系。自己封装一个支持分类的工作流列表接口

推荐第二种方式
