### ISSUE TITLE
新建工单接口报错

### ISSUE THREAD

**Issue by tc-wlm** [blackholll/loonflow#405]
只有两个必填项
![image](https://user-images.githubusercontent.com/70578294/218257312-2bb43e1b-e74b-4d9e-8caf-1de4bab77066.png)
但是结果报错，是还缺少什么吗
![image](https://user-images.githubusercontent.com/70578294/218257363-5aac899e-ab0f-4a94-bc53-19d7d3aa9774.png)

是还缺少什么吗

**Comment by blackholll** [comment]
看错误可能是你穿的transition_id=57不存在. 
详细信息可以去看下loonflow的日志，里面可以看出来是哪行代码报错的

**Comment by tc-wlm** [comment]
邮件已收到，尽快给您回复。

**Comment by tc-wlm** [comment]
是的 我给理解错误了 确实是transition_id不存在

**Comment by tc-wlm** [comment]
问题也解决 感谢！！！

**Comment by tc-wlm** [comment]
问题解决了
