### ISSUE TITLE
请教一个部署时出现的问题

### ISSUE THREAD

**Issue by tc-wlm** [blackholll/loonflow#406]
我用的2.0.15 本地开发环境测试没问题想部署一下试试，结果出现 为啥会去请求8000端口呢
![Snipaste_2023-02-13_21-55-19](https://user-images.githubusercontent.com/70578294/218477429-86d2fab9-439b-4620-be44-a21d6b535ebb.png)
我的uwsgi里配置的是6060端口
![image](https://user-images.githubusercontent.com/70578294/218477574-e49385e6-7523-4091-9565-f856b7a2c999.png)

**Comment by blackholll** [comment]
你的前端没有build，以开发模式启动的，所有请求后由前端转发到后端。当请求地址是/api开头的会转发到后端的http://127.0.0.1:6060, 转发规则见: https://github.com/blackholll/loonflow/blob/master/frontend/config/proxy.ts

如果你的后端和前端在同一机器上，那应该实际可以请求到， 但是后端500了，检查下后端的日志。 uwsgi日志、loonflow运行日志.

生产环境部署文档： https://loonflow.readthedocs.io/zh_CN/r2.0.15/about/start/#id3

**Comment by tc-wlm** [comment]
我就是按照你的那个文件上描述的试着部署的。我的流程是在Windows系统进入frontend目录下，依次执行npm i 和npm run build ，之后将打包的dist文件啥的放到了服务器上，然后配置nginx和uwsgi。不知道这个流程对不对



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月13日(周一) 晚上10:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [blackholll/loonflow] 请教一个部署时出现的问题 (Issue #406)




 
你的前端没有build，以开发模式启动的，所有请求后由前端转发到后端。当请求地址是/api开头的会转发到后端的http://127.0.0.1:6060, 转发规则见: https://github.com/blackholll/loonflow/blob/master/frontend/config/proxy.ts
 
如果你的后端和前端在同一机器上，那应该实际可以请求到， 但是后端500了，检查下后端的日志。 uwsgi日志、loonflow运行日志.
 
生产环境部署文档： https://loonflow.readthedocs.io/zh_CN/r2.0.15/about/start/#id3

**Comment by blackholll** [comment]
的nginx配置文件里面监听的哪个端口?  浏览器当前访问的是哪个端口？ 然后检查下uwsgi日志、loonflow运行日志中的错误

**Comment by blackholll** [comment]
pip都安装成功了么？  换python3.10试试， python3.9未测试过
<img width="976" alt="image" src="https://user-images.githubusercontent.com/6269605/218493626-dbd25bd1-c125-4e58-b876-685bbb7c39b8.png">

**Comment by blackholll** [comment]
另外 loonflow日志中请求login的日志呢？  截图中没有，  这个请求floonflon日志中是否有记录 和错误信息？

**Comment by tc-wlm** [comment]
pip都安装成功了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月13日(周一) 晚上11:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [blackholll/loonflow] 请教一个部署时出现的问题 (Issue #406)




 
pip都安装成功了么？  换python3.10试试， python3.9未测试过
