### ISSUE TITLE
请教工单类型的权限设置问题

### ISSUE THREAD

**Issue by tc-wlm** [blackholll/loonflow#407]
![image](https://user-images.githubusercontent.com/70578294/218964222-e1702626-b754-4e7a-9d47-1031732cce27.png)
现在2.0.15版本 前端能否根据限制表达式 展示不同权限 不同的工单显示

**Comment by blackholll** [comment]
当前不支持

**Comment by tc-wlm** [comment]
好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月16日(周四) 上午7:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [blackholll/loonflow] 请教工单类型的权限设置问题 (Issue #407)




 
当前不支持
