### ISSUE TITLE
我有一个flask的项目希望有一个工作流引擎。loonflow能整合到flask系统么？

### ISSUE THREAD

**Issue by lovefox666** [blackholll/loonflow#41]
审批流程里，有一种审批。
比如：有两种类型的审批流程A和B，B流程的发起，依赖A流程的审批完成。

**Comment by blackholll** [comment]
1.loonflow是通过http api提供服务，而且是django写的的。强烈建议你和自己的应用分开部署，自己的应用后端来调用loonflow接口实现功能。  这样loonflow的工作流引擎功能还可以供其他系统使用
2.loonflow提供子工作流的功能，对应的子工单和父工单。 父工单在某一个状态下，可以发起子工单，子工单完成后，父工单从当前状态继续流转。  你这里b流程 a流程每个对应多个工单 还是只一个工单？如果只是一个工单的话 直接合并到一个工单就好了

**Comment by lovefox666** [comment]
1、是不是理解为loonflow是一个引擎，定义工作流审批等流程。我创建工作流实例，通过api创建、流转？审批的相关数据是保存在我的项目的数据库，还是你的引擎数据库呢？
2、我的审批流程不是完全的父子关系，有点像两个阶段审批的关系。比如一个是项目的立项审批，一个是招标审批，一个是合同签订审批。每个审批都是独立的，但下一个审批是依赖和关联上一个审批的结果。




------------------ 原始邮件 ------------------
发件人: "blackholll"<notifications@github.com>;
发送时间: 2019年6月7日(星期五) 上午9:49
收件人: "blackholll/loonflow"<loonflow@noreply.github.com>;
抄送: "夜凉如水"<540085660@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [blackholll/loonflow] 我有一个flask的项目希望有一个工作流引擎。loonflow能整合到flask系统么？ (#41)




1.loonflow是通过http api提供服务，而且是django写的的。强烈建议你和自己的应用分开部署，自己的应用后端来调用loonflow接口实现功能。  这样loonflow的工作流引擎功能还可以供其他系统使用
 2.loonflow提供子工作流的功能，对应的子工单和父工单。 父工单在某一个状态下，可以发起子工单，子工单完成后，父工单从当前状态继续流转。  你这里b流程 a流程每个对应多个工单 还是只一个工单？如果只是一个工单的话 直接合并到一个工单就好了

**Comment by blackholll** [comment]
1. 是的。 文档中有说明https://github.com/blackholll/loonflow/blob/master/docs/index.md。 loonflow中会保存审批过程数据及工单的基本信息。如果调用方在显示工单数据的时候需要显示更多相关信息，可以本地保存一份附属信息与loonflow中对应关系。针对本地保存的情况，如果涉及工单流转的字段(如参与人等)，在本地修改时需要同时调用loonflow修改loonflow中保存的字段的值

2.这种情况其实就是多个工作流，那么你可以在定义工作流的时候，一个工作流审批都通过后，加个状态比如: 创建xx工单，这个状态的处理人类型是脚本，通过脚本来自动创建下个一个工单。 如果你需要保存这几个工单之间的关系，可以将这信息保存在你自己的应用的数据库中。如项目表中有个字段是立项审批工单id,招标审批工单id, 合同签订工单id.

**Comment by lovefox666** [comment]
1、如果需要认为手工根据审批A，创建审批B呢。也可以吧？
2、我的开发环境是Windows，部署环境也可能是Windows，能使用么？有每月docker的部署模式？

**Comment by blackholll** [comment]
1.你在A类型工单的某个状态下 显示一个按钮。 用户点击这个按钮的时候你的后端调用loonflow来创建一个新的类型的工单
2.windows系统支持，文档中有说明
3.docker有个问题。 因为执行脚本和通知脚本是上传文件的。所以如果需要用docker,需要将这个media目录挂载到宿主机上(或者使用分布式存储)保证每次发布或者重写调度后文件不丢失
