### ISSUE TITLE
流转未设置默认destination_state_id,条件也未匹配到destination_state_id，报的错不好调试

### ISSUE THREAD

**Issue by tuiche** [blackholll/loonflow#410]
https://github.com/blackholll/loonflow/blob/r2.0.15/service/ticket/ticket_base_service.py#L2204

**Comment by blackholll** [comment]
可以说的详细点么？  如果是调试的话其实看日志报错的哪一行就应该好判断了。 
你是希望配置的时候界面有提示么

**Comment by tuiche** [comment]
![捕获](https://user-images.githubusercontent.com/22321743/222057962-ea16f95b-75f8-4f50-bfaf-c386809452e4.PNG) 报的错比较难定位，最好有个没匹配到的提示
