### ISSUE TITLE
工单完成后工单信息内容为空

### ISSUE THREAD

**Issue by WeiYingZhe** [blackholll/loonflow#412]
![image](https://user-images.githubusercontent.com/98902853/221502904-6f5ab0c5-c1ab-4409-9d0c-186280f65571.png)
![image](https://user-images.githubusercontent.com/98902853/221503006-14563409-3641-45b3-8649-ee4891baec6f.png)

**Comment by WeiYingZhe** [comment]
是我没有配置对吗

**Comment by blackholll** [comment]
处理完后 当前用户只有查看权限 即展现表单  配置在工作流级别  不在状态里面

**Comment by WeiYingZhe** [comment]
是要在“展现表单”里面加入内容才能在结束后还能看到内容吗

**Comment by WeiYingZhe** [comment]
> 处理完成后当前用户只有查看权限即展开现表单配置在工作流级别不在状态里面

是要在“展示单”里面加入内容才能在绑定后还能看到内容吗

**Comment by blackholll** [comment]
对  当用户有处理权限 根据工单当前所处状态的表单字段设置来确定显示那些字段 以及每个字段的只读 可选 编辑权限。 当用户只有查看权限睡衣根据工作流的展现表单来确定显示哪些字段

**Comment by WeiYingZhe** [comment]
> 对 当用户有处理权限 根据工单当前所处状态的表单字段设置来确定显示那些字段 以及每个字段的只读 可选 编辑权限。 当用户只有查看权限睡衣根据工作流的展现表单来确定显示哪些字段

好的，谢谢
