### ISSUE TITLE
定义日期表单字段的时候，选择日期，工单被打回初始状态或者工单主动撤回初始状态都会报错，date.clone is not a function

### ISSUE THREAD

**Issue by zhiming429438709** [blackholll/loonflow#413]

**Comment by blackholll** [comment]
不支持回到初始状态   可以加个草稿状态 处理人类型用变量-工单创建人

**Comment by dong9205** [comment]
参考链接：https://blog.csdn.net/qq_40937541/article/details/115751044
**解决如下**
文件: frontend\src\pages\Ticket\TicketDetail\index.tsx:1148
![image](https://github.com/blackholll/loonflow/assets/40266166/fe10e4a7-4a68-4ce7-955a-6c53a415eb3f)
