### ISSUE TITLE
新增工作流时，WorkflowAdmin这张表是否要插入数据

### ISSUE THREAD

**Issue by splier** [blackholll/loonflow#421]
新增工作流时，业务逻辑里往WorkflowUserPermission表里插入了对应数据，但是通过api/v1.0/workflows获取工作流列表信息时，返回的字段workflow_admin信息是从WorkflowAdmin表里获取的。

**Comment by blackholll** [comment]
WorkflowAdmin是早期版本的逻辑。 应该从WorkflowUserPermission获取.
will be fixed in r2.0.16

**Comment by blackholll** [comment]
r2.0.16 released, and fixed it
