### ISSUE TITLE
工作流标题是否支持内置工单字段

### ISSUE THREAD

**Issue by splier** [blackholll/loonflow#423]
![image](https://user-images.githubusercontent.com/36869852/228785430-b29e77f7-fbbb-4b4b-81cb-541a943692cf.png)
![image](https://user-images.githubusercontent.com/36869852/228785558-e35707e7-6578-45d3-bf7b-dca99808d591.png)
经过测试和查看源码，发现工作标题不支持内置字段，这里是否有问题？

附：
查看源码，得知内置字段如下
![image](https://user-images.githubusercontent.com/36869852/228786192-cc2a3315-e18f-43c2-9409-cb6fbe1fa26e.png)

**Comment by blackholll** [comment]
will fixed in r2.0.16, about next week

**Comment by blackholll** [comment]
r2.0.16 released, and fixed it
