### ISSUE TITLE
会签功能问题咨询

### ISSUE THREAD

**Issue by splier** [blackholll/loonflow#426]
![image](https://user-images.githubusercontent.com/36869852/229017924-6c00e956-7948-4b9b-83bd-89fd902cf216.png)
![image](https://user-images.githubusercontent.com/36869852/229019485-1daccddb-f047-4606-ae05-2fdfe70f915f.png)

根据截图所示，当我在审批中状态设置页面时，设置
参与人类型：多人
参与人：admin,zhouwei
分配方式时：全部处理
此时，审批的方式应该是会签的形式，如果admin和zhangsan都选择同意，则当前工单会正常流转到下个状态，但是当zhangsan选择驳回，工单的状态应当返回只上一状态【创建中（开始状态）】，但是结果还是审批中，且admin账号下工单详情页面也没有任何审批功能（同意，驳回）。

请问这是设计上的缺陷吗？

**Comment by blackholll** [comment]
现实需求并不一定都是希望多人拒绝就回退。 所以当前的处理是停在当前状态。 配置通知hook，被拒绝后发起人可以收到拒绝通知，由发起人根据工单后续状态。  管理员也可以工单界面中的“管理员操作”来干预工单
