### ISSUE TITLE
hook使用方法介绍

### ISSUE THREAD

**Issue by AndrewChung-GitHub** [blackholll/loonflow#429]
仔细查阅了所有issue和文档介绍，对于hook的使用方法没怎么详细介绍，能否提供一些文档或者demo帮助快速上手，谢谢。

**Comment by blackholll** [comment]
https://github.com/blackholll/loonflow_hook_demo

**Comment by AndrewChung-GitHub** [comment]
也就是说先在loonflow/service目录下创建Hook NoticeService script，譬如说短信/Email提醒服务
<img width="821" alt="截屏2023-04-07 11 31 13" src="https://user-images.githubusercontent.com/40729655/230535811-d777667c-71f7-4a9d-bd73-117bd0f952a2.png">
 那请问，前端页面又该怎么配置呢？
<img width="513" alt="截屏2023-04-07 11 33 08" src="https://user-images.githubusercontent.com/40729655/230536004-20860436-6b0b-4c3c-8eb2-b16e8b2584f9.png">

还请大佬进一步明示，非常感谢！

**Comment by blackholll** [comment]
hook服务需要你自己实现（自己写一个单独的项目，或者将功能加在一个已有项目里），暴露一个http的post API， 供loonfow调用。 loonflow里面配置的是你新提供的服务单位地址。 demo描述的是你如何写这个新的服务

**Comment by AndrewChung-GitHub** [comment]
懂了，感谢大佬明示！
