### ISSUE TITLE
新增工单后，调用接口查询工单详情，其中创建者信息creator_info在何时写入的？

### ISSUE THREAD

**Issue by lovefox666** [blackholll/loonflow#43]
1、’提交表单的时候，并没有提交创建者信息creator_info相关信息，是何时写入的？
2、用headers里的username？
3、如果同名同姓的人，如何正确获取工单相关信息。如何用id的，同步个人信息时如何确保人员能对应更新？
比如：在外部系统里，【userid=1000，username='张三'】【userid=1001，username='张三'】。同步到这个工作流引擎里，id是自动的，只同步了username字段。那更新时，同名同姓的如何同步更新？

**Comment by blackholll** [comment]
1.调用方前端提交工单到调用方的后端，调用方后端会请求loonflow的接口来创建工单。在请求的header里面有用户信息username
2.是的
3。.username不要重名。 那就吧userid同步到loonflow的username.   username同步到loonflow的alias字段

**Comment by lovefox666** [comment]
1、userid一般是能唯一区分一个人的，比如企业的工号。
但是，展示给用户工单详情时，一般都是用姓名来显示。
按此思路，用你的工作流，就会处理不了显示姓名的情况，只能用alias？感觉别扭。

**Comment by blackholll** [comment]
工单详情等接口返回的内容中有participant_info，这个对象里面有alias，前端显示的时候显示participan_info.alias（当前处理人）。 creator_info.alias(创建人的姓名)

**Comment by lovefox666** [comment]
谢谢解答。
希望用userid和username规范一下。

**Comment by blackholll** [comment]
username大多数都是用拼音(或者工号)的，user_id一般是用数据库中中的id的
