### ISSUE TITLE
调用权限配置后工单前缀仍未生效

### ISSUE THREAD

**Issue by AndrewChung-GitHub** [blackholll/loonflow#430]
## 调用权限配置后工单前缀仍未生效 

使用的版本: r2.0.15

问题详细描述: 调用权限配置后工单前缀仍未生效

是否搜索过历史issue: 是

- 调用权限配置 请假 前缀改为‘leave’
![Snipaste_2023-04-07_12-20-31](https://user-images.githubusercontent.com/40729655/230540212-b112d908-74ec-4c34-8f5e-5b987dff6fe2.png)
- 工作流 基础信息配置
![Snipaste_2023-04-07_12-21-20](https://user-images.githubusercontent.com/40729655/230540323-15382cb5-ba7e-4f90-a5fb-7c81e93f030b.png)
- 工单信息 流水号前缀并未变更为‘leave’
![Snipaste_2023-04-07_12-23-42](https://user-images.githubusercontent.com/40729655/230540502-676dcb63-3769-49da-9a8b-80298f7f8d50.png)

**Comment by blackholll** [comment]
此配置只针对以请假这个应用身份通过api调用创建工单的流水。    自带前端里面创建工单是以loonflow身份调用的

**Comment by AndrewChung-GitHub** [comment]
明白了，感谢大佬答疑解惑。
