### ISSUE TITLE
字段下拉列表调接口获取

### ISSUE THREAD

**Issue by zhiming429438709** [blackholll/loonflow#431]
大佬，动态获取下拉列表有没有和demo，这个太常用了，依靠配置受限很大

**Comment by AndrewChung-GitHub** [comment]
+1
在[issue 135](https://github.com/blackholll/loonflow/issues/135)中有讨论可以使用【标签】来实现，能否具体介绍一下，能否给出具体实践demo？

**Comment by blackholll** [comment]
自定义标签的方式适合是有自己的系统，自己系统的前端调用自己后端， 然后自己的后端调用loonflow的api.  自己的前后端可以根据标签来做一些特殊处理。 配置侧, 给字段加个标签，如 “{"get_data":"from_external","external_url":"http://www.baidu.com"}”， 可以认为是该字段比较特殊，从外部获取数据， 然后获取地址是http://www.baidu.com.  可以不指定url.前端用户选择一个选项后，出发请求给自己的后端，带上一个特殊的参数来获取需要的数据.
<img width="1901" alt="image" src="https://user-images.githubusercontent.com/6269605/230919814-8c2ce5c6-6ae7-4313-9385-7cc7f8498cc9.png">
在展示侧新建工单或处理工单的时候通过接口可以获取字段的label信息，前端根据这个信息来返回处理展示逻辑。这个标签中内容前后端约定好就行。 
<img width="1889" alt="image" src="https://user-images.githubusercontent.com/6269605/230919932-d38b9000-24de-454f-8534-b840c14c01ed.png">
