### ISSUE TITLE
 普通状态中“字段类型”为"日期"的字段若设置为2(必填)则报e.clone is not a function

### ISSUE THREAD

**Issue by AndrewChung-GitHub** [blackholll/loonflow#432]
## 普通状态中“字段类型”为"日期"的字段若设置为2(必填)则报e.clone is not a function

- 日期字段
![image](https://user-images.githubusercontent.com/40729655/230876232-e7b5d08d-e652-4bfb-8f7b-6334574169a5.png)

- 基本流程图
![image](https://user-images.githubusercontent.com/40729655/230874870-e3064d37-6138-4e3d-9df2-632f29f24058.png)

- 新建中【初始状态】， query_date 为必填项
![image](https://user-images.githubusercontent.com/40729655/230874407-98f5d23f-b6cd-4bee-8ee3-3ed8e83cfb8e.png)

- 编辑中【普通状态】，
    - query_date为只读（1），则不报错
   
![image](https://user-images.githubusercontent.com/40729655/230876140-051bc5fc-f416-4538-aa0e-ac217df873be.png)

![image](https://user-images.githubusercontent.com/40729655/230875837-f622f24b-3bed-4999-a80c-e8bf31aae4d1.png)

    - query_date为必填（2），则报错
   
![image](https://user-images.githubusercontent.com/40729655/230875716-2f7fb029-c8a1-424f-b561-3249d7103c01.png)

**Comment by blackholll** [comment]
问题已复现， 下个版本修复，计划两周内

**Comment by blackholll** [comment]
欢迎自己解决并提交PR

**Comment by blackholll** [comment]
r2.0.17中已修复

**Comment by AndrewChung-GitHub** [comment]
亲测已修复，感谢大佬的更新。
