### ISSUE TITLE
脚本触发如何触发的咋配置

### ISSUE THREAD

**Issue by quguoqiang** [blackholll/loonflow#433]
## ISSUE TEMPLATE

使用的版本: 2.0.12

问题详细描述: 装态中的脚本配置 2.0.12 是在那个页面配置的

是否查看了系统日志(默认在启动用户家目录下loonflow.log):
![image](https://user-images.githubusercontent.com/37200588/231042662-7ab2e7e2-088a-415a-ba83-b8e3579aff54.png)

是否搜索过历史issue: 老版本看过，新版本在哪配置

做过哪些尝试:

**Comment by blackholll** [comment]
脚本功能已移除， 因为脚本中如果包含大量长时间轮询逻辑 会影响loonflow主进程的功能。 请使用hook功能替代

**Comment by quguoqiang** [comment]
hook方式咋们是那块代码触发调用执行hook的，一直报错 File "/opt/workflow/loonflow/service/ticket/ticket_base_service.py", line 880, in get_ticket_format_participant_info
    script_obj = WorkflowScript.objects.filter(id=int(participant), is_deleted=0).first()  这个是触发脚本，我工作流修改了为hook方式了，咋还走script方式
是需要别的操作吗？

**Comment by blackholll** [comment]
该状态的配置界面发出来看下

**Comment by quguoqiang** [comment]
![image](https://user-images.githubusercontent.com/37200588/231412644-d22a883c-267d-4bba-a90b-50bfe6c5035f.png)
数据库是上面的
![image](https://user-images.githubusercontent.com/37200588/231412844-0c720f83-89ee-4436-b100-663d6ef74782.png)
这个是配置页面

**Comment by blackholll** [comment]
这个错误是重置状态触发的么？ 新建工单看下。修改状态配置 只会对后续变更为此状态的工单生效。 历史处于此状态的工单处理人信息已经确定

**Comment by quguoqiang** [comment]
我这没启动celery   起来后
![Uploading image.png…]()
这属于是url不对吗？

**Comment by quguoqiang** [comment]
![Uploading image.png…]()

**Comment by quguoqiang** [comment]
原来是没启动了celery hook不执行
