### ISSUE TITLE
未配置HOOK_HOST_ALLOWED，但仍报‘hook host is not allowed'

### ISSUE THREAD

**Issue by AndrewChung-GitHub** [blackholll/loonflow#436]
## 未配置HOOK_HOST_ALLOWED，但仍报‘hook host is not allowed'

实际上未配置HOOK_HOST_ALLOWED，但仍报‘hook host is not allowed, please contact the administrator to alter the configure’错误
![image](https://user-images.githubusercontent.com/40729655/231415349-21c77139-d52c-4ed2-9899-7447711dcd92.png)
![image](https://user-images.githubusercontent.com/40729655/231415692-ac893f9c-4c9d-4fa4-8377-7e420c58de74.png)
![image](https://user-images.githubusercontent.com/40729655/231415915-fadb30c1-59f4-4392-9161-1b215457497b.png)

**Comment by blackholll** [comment]
未配置不会触发校验失败。 这两条错误 不是一个事务吧。有其他人在这期间加了配置？

**Comment by AndrewChung-GitHub** [comment]
考虑到HOOK_HOST_ALLOWED可以为空列表[], 源码需要稍微改一下即可
![image](https://user-images.githubusercontent.com/40729655/231523033-304da3b7-eab7-455e-ab59-411ad226e1d3.png)

**Comment by blackholll** [comment]
为[]的意思是不允许任何host， 所以return False
为["10.0.0.1","x.x.com"]表示允许10.0.0.1和x.x.com
不配置表示允许所有

**Comment by AndrewChung-GitHub** [comment]
好的，谢谢。
