### ISSUE TITLE
报错：Cannot read properties of null (reading 'startsWith')

### ISSUE THREAD

**Issue by AndrewChung-GitHub** [blackholll/loonflow#438]
工单ticket处于中间环节时，creator本人查看详情报错，但是后面审批人查看详情正常

![image](https://user-images.githubusercontent.com/40729655/233301331-266291c9-ae52-47cd-9654-b89dae0bd498.png)

- 中间审批环节（LSP审阅），creator查看详情出错
![image](https://user-images.githubusercontent.com/40729655/233300720-a08f0b13-35de-4a99-9af0-b8f3fdd69945.png)
- 中间审批环节（LSP审阅），LSP审批人查看详情正常
![image](https://user-images.githubusercontent.com/40729655/233302213-4132f363-25ee-40d1-8876-286e3a6e1698.png)

- 审批结束（结束），creator查看详情正常
![image](https://user-images.githubusercontent.com/40729655/233301540-f2425f26-218e-4b79-8e89-3581c962ac64.png)

但有的workflow并没有发现这个问题，有点迷糊

**Comment by blackholll** [comment]
最好能复现问题， 然后看下控制台中ticket详情的api中返回的数据。  然后结合代码中用到startswith的地方判断是哪里的问题。

**Comment by AndrewChung-GitHub** [comment]
亲测已修复，感谢大佬的更新。
