### ISSUE TITLE
关于teamleader审批人的认定

### ISSUE THREAD

**Issue by lovefox666** [blackholll/loonflow#44]
比如总部时组织结构的根节点，下级部门A，还有子部门A1/A2，形如：
总部
    部门A
        部门A1
            部门A11
        部门A2
            部门A21
有员工张三，隶属A11，那teamleader是哪个？是A11还是A1?
如果我设置A1有leader，A11没有leader可以么？是否此时，张三发起的审批teamleader就是A1的leader？

**Comment by blackholll** [comment]
teamleader指的是直属部门的teamleader。 loonflow中如果设置处理人类型为变量，处理人为creator_tl. 那么先去获取这个创建人的所在部门，然后这个所在部门的审批人信息，如果没有审批人信息，那么取这个部门的leader信息。如果都没有那么工单的处理人会为空

**Comment by lovefox666** [comment]
问题1：设置A1有leader，A11没有leader可以么？
问题2：可以设置张三创建的工单，处理人类型为变量，处理人为cretor_tl，由所在的部门A的leader，行不？

**Comment by blackholll** [comment]
1: 这么设置不会报错。但是A11提交的工单，下个状态如果是creator_tl.那么处理人将为空，无人再可处理(leader和approver都未设置的情况)
2. 你可以把A11的leader或者approver也设置成和A部门相同的leader或者approver

**Comment by lovefox666** [comment]
谢谢解答。
建议可以设置增设变量（上一级部门leader）为处理人，否则一旦更换了部门Leader，下属的各分支机构，都要修改一遍。

**Comment by blackholll** [comment]
一般审批人场景较多的是直属上级的tl。   
部门tl换了，这个你的同步脚本应该可以感知到。 定时同步的时候就批量更新掉了
