### ISSUE TITLE
接单报错了

### ISSUE THREAD

**Issue by quguoqiang** [blackholll/loonflow#440]
## ISSUE TEMPLATE

使用的版本: 2.0

问题详细描述:  点击接单报错
{code: 201, data: {…}, msg: 'error', status: 'error'}
code: 201
data:
code: -1
data: null
msg: "参数不合法,请提供username，transition_id"
[[Prototype]]: Object
msg: "error"
status: "error"
[[Prototype]]: Object
是否查看了系统日志(默认在启动用户家目录下loonflow.log):
        suggestion = request_data_dict.get('suggestion', '')
        print("transition_id: %s username: %s"%(transition_id,username))
        if not (transition_id and username):
            return False, '参数不合法,请提供username，transition_id'

日志
test++++++ {'transition_id': 0, 'suggestion': '接单', 'username': 'lihong'}
transition_id: 0 username: lihong

是不是这个判断有问题？？
做过哪些尝试:

**Comment by blackholll** [comment]
接单是有个接单的接口。不是调用处理工单的接口。 获取工单可执行的操作的接口会返回该操作的属性 是普通流转操作还是接单操作

**Comment by quguoqiang** [comment]
已经ok了 已经写好了 调用接单接口就行了 
![image](https://user-images.githubusercontent.com/37200588/233968524-f216a81a-f29d-4af4-a9a2-1528a55cfaaa.png)

**Comment by quguoqiang** [comment]
感谢
