### ISSUE TITLE
转交操作条件

### ISSUE THREAD

**Issue by quguoqiang** [blackholll/loonflow#441]
## ISSUE TEMPLATE

使用的版本: 2.0

问题详细描述:
      转交操作这个from_admin 这个参数指定是否是管理员强转
    那我咋判断普通用户是否有转交权限  （这个操作在可操作的接口也没有体现）（转交一般当前节点的人可操作）
是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:

做过哪些尝试:

**Comment by blackholll** [comment]
有当前工单的处理权限就有转交权限 即tickets/xx/transitions接口返回内容中data.value不为空

**Comment by quguoqiang** [comment]
了解了，感谢大佬
