### ISSUE TITLE
新建工单提示业务流程未初始化配置

### ISSUE THREAD

**Issue by admi2u** [blackholll/loonflow#442]
## ISSUE TEMPLATE

使用的版本: r2.0.3

问题详细描述: 搭配shutongflow使用时，新建工单提示业务流程未初始化配置

是否查看了系统日志(默认在启动用户家目录下loonflow.log): 是

是否搜索过历史issue: 是

做过哪些尝试:

![image](https://user-images.githubusercontent.com/36391186/236138246-f30afe60-f3d8-499f-89ed-74e09ccce7e0.png)

**Comment by blackholll** [comment]
https://github.com/youshutong2080/shutongFlow/blob/master/apps/apps/settings.py里面 最后两行有shutongflow调用loonflow所用的appname和token   需要在loonflow的 用户及权限--调用权限中配置该appname 并授予工作流的权限

**Comment by admi2u** [comment]
谢谢，已经解决。是因为在工作流的状态设置中，参与人类型没有设置正确。
