### ISSUE TITLE
bugs:【部门管理】[上级部门]下拉框可选字段只限于当前页面出现的部门名称

### ISSUE THREAD

**Issue by AndrewChung-GitHub** [blackholll/loonflow#443]
## 【部门管理】[上级部门]下拉框可选字段只限于当前页面出现的部门名称

使用的版本: r2.0.17

譬如你在page 2页面进行操作，page 1页面中的部门名称就不会出现。

**Comment by blackholll** [comment]
r2.0.18将修复

**Comment by blackholll** [comment]
r2.0.18已修复
