### ISSUE TITLE
关于docker方式部署一些问题请教

### ISSUE THREAD

**Issue by ghost** [blackholll/loonflow#448]
## ISSUE TEMPLATE

使用的版本:2.0.17

问题详细描述:想咨询下 我用docker部署的loonflow 想配置钉钉消息通知 应该怎么配置 ？
另外 工单附件我看了下应该没有映射到本地，可能传到容器内了 如何映射到本地 ？
docker-compose方式部署需要映射哪些目录到本地？

是否查看了系统日志(默认在启动用户家目录下loonflow.log):否

是否搜索过历史issue:是

做过哪些尝试:查看dockerfile相关配置

**Comment by blackholll** [comment]
通知：配置通知hook， 自己实现一个hook服务（可以参考github.com/blackholll/loonfow_hook_demo） 
附件：可以参考nginx配置文件docker_compose_deploy/loonflow-web/nginx.conf。 实际有用的只有opt/loonflow/media目录

**Comment by blackholll** [comment]
docker_compose_deploy下建个目录。然后mount这个目录，并且吧nginx配置文件中把location media的alias改成这个路径就好

**Comment by blackholll** [comment]
r2.0.18 docker compose部署已添加media目录配置
