### ISSUE TITLE
接单问题

### ISSUE THREAD

**Issue by ykchen12** [blackholll/loonflow#45]
当工单到工作组，组内所有成员都可以看到，A接单了，待处理人就是A，B接单了，待处理人就是B，那么后台进行设计的时候，这个字段是选个人还是变量？接单人的变量是什么？

**Comment by blackholll** [comment]
处理人类型书部门， 处理人用部门id。 
处理人和类型和处理人的设置 不受处理方式(主动接单、直接处理、随机分配)影响。 
主动接单： 当发现当前状态的处理人是多人(多人、部门id、角色 都可能对于多个人)时，需要其中的人接单后，才可以继续处理
直接处理：当前处理人随便谁都可以直接处理(直接处理指的是按照流程设计点击相应的操作：同意、拒绝、完成等等)
随机分配: 系统会将工单的当前处理人设置为有权限的其中一人

**Comment by ykchen12** [comment]
[图片]  我接单了  我同事也可以处理

**Comment by blackholll** [comment]
图片在哪？
接单操作的逻辑是直接将工单的当前处理人类型改成个人，处理人改成操作人。 你可以检查下工单表中这两个属性是否正常改变了
