### ISSUE TITLE
自定义字段创建工单时不显示

### ISSUE THREAD

**Issue by ssrshz** [blackholll/loonflow#450]
## ISSUE TEMPLATE

使用的版本:
loonflow 2.0.17

问题详细描述:
在工作流管理中，配置了自定义字段，但是在工作台创建工单时，字段不显示

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:
没有发现
做过哪些尝试:
在已有的流程样例中添加自定义字段，也不显示，如下图
<img width="1389" alt="WechatIMG70" src="https://github.com/blackholll/loonflow/assets/19809226/4d8f623b-93cc-421d-8bfc-d4bc7a664605">

![WX20230523-143456@2x](https://github.com/blackholll/loonflow/assets/19809226/ae1341ff-2b97-4741-8ad7-d1cbcfb77d09)

**Comment by blackholll** [comment]
github.com/blackholll/loonflow/issues/37

**Comment by ssrshz** [comment]
> github.com/[/issues/37](https://github.com/blackholll/loonflow/issues/37)

感谢大佬的及时回复
