### ISSUE TITLE
docker-compose部署的web项目静态资源问题

### ISSUE THREAD

**Issue by ghost** [blackholll/loonflow#451]
## ISSUE TEMPLATE

使用的版本:2.0.17

问题详细描述:docker-compose部署的web项目静态资源，登录页面有个背景图：
引用了此地址：https://gw.alipayobjects.com/zos/rmsportal/TVYTbAXWheQpRcWDaDMu.svg
内网环境下无法连接外网会导致资源加载异常，能否将此资源本地化。谢谢~

是否查看了系统日志(默认在启动用户家目录下loonflow.log):是

是否搜索过历史issue:是

做过哪些尝试:否

**Comment by blackholll** [comment]
r2.0.18 修改

**Comment by blackholll** [comment]
r2.0.18已优化
