### ISSUE TITLE
在loonflow web中，主动接单与直接处理的区别？

### ISSUE THREAD

**Issue by ssrshz** [blackholll/loonflow#452]
## ISSUE TEMPLATE

使用的版本:
loonflow 2.0.17

问题详细描述:
在测试过程，没有看到主动接单与直接处理这两种分配方式有什么差异，用在什么场景？
没看到在哪里有主动接单的动作

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:
搜索过

做过哪些尝试:
尝试改过这两种状态，然后再web中没看到区别
![WX20230523-183635@2x](https://github.com/blackholll/loonflow/assets/19809226/a0f99a2a-4ed7-44e1-8836-85c6f70d4cae)

**Comment by blackholll** [comment]
接单是指配置了多人处理时， 需要先接单操作  然后再处理。  你这里“发布中”虽然配置的多人， 但是参与人实际只有一个（ 多个人用逗号隔开username）

**Comment by ssrshz** [comment]
感谢作者的快速反馈！
