### ISSUE TITLE
bug-附件字段为必填时，如果附件为空，同时校验必填项打开，流程也能正常流转

### ISSUE THREAD

**Issue by ssrshz** [blackholll/loonflow#454]
使用的版本:
r2.0.17

问题详细描述:

表单字段配置：{"release_upload":2}

![WX20230526-125102@2x](https://github.com/blackholll/loonflow/assets/19809226/ad35270b-997a-4331-abb0-57427a9f40e9)

**Comment by blackholll** [comment]
r2.0.18已修复
