### ISSUE TITLE
调用权限当中的工单前缀不生效

### ISSUE THREAD

**Issue by ghost** [blackholll/loonflow#455]
## ISSUE TEMPLATE

使用的版本:2.0.18

问题详细描述:调用权限当中配置的工单前缀不生效，在对应应用关联的工作流生成工单的时候，工单前缀默认为loonflow_开头，实际配置的工单前缀未生效。

是否查看了系统日志(默认在启动用户家目录下loonflow.log):docker-compose部署，不存在问题

是否搜索过历史issue:是

做过哪些尝试:尝试重新配置，仍然无效
![image](https://github.com/blackholll/loonflow/assets/97371434/55c40b53-9bad-4aae-a5f5-da0a0f01ebae)
![image](https://github.com/blackholll/loonflow/assets/97371434/016669fd-b2b6-462b-9447-c68585fdbbe2)

**Comment by blackholll** [comment]
工单前缀 仅针对通过该app身份 通过api调用来创建的工单

**Comment by blackholll** [comment]
其实我在考虑要不要3.0中将这个sn的功能去掉， 有id就够了。sn没啥用。 大家可以评论下sn使用的场景
