### ISSUE TITLE
流程hook触发问题

### ISSUE THREAD

**Issue by dangaoxia** [blackholll/loonflow#456]
哈喽
解答一下流程里面的hook是怎么触发和配置的，想自动执行一些任务，好像并不能用，只有通知的hook是能用的

**Comment by blackholll** [comment]
贴下你的hook配置 以及检查是否有报错日志，。 流程中的hook是在工单状态发生变化就会触发，

**Comment by dangaoxia** [comment]
[2023-07-04 14:27:26,712: INFO/ForkPoolWorker-2] Task tasks.flow_hook_task[3aff1652-3d77-421d-b18b-5f50f228fccf] succeeded in 0.013718262780457735s: None
参与人：
{"hook_url":"http://192.168.4.220:8000/flow/hook/loonflow/", "hook_token":"ee5e2356-1a1b-4aed-839f-b57979a465eb", "wait":false, "extra_info":""}

**Comment by blackholll** [comment]
这表示hook已经触发了

**Comment by dangaoxia** [comment]
但是http://192.168.4.220:8000/flow/hook/loonflow/这个没有收到请求

**Comment by blackholll** [comment]
看下你的配置中 是否有这个配置 有的话 配置的是什么值。 HOOK_HOST_ALLOWED

**Comment by dangaoxia** [comment]
是空的，但是我修改为HOOK_HOST_ALLOWED = ['*']依旧不能发起请求

**Comment by blackholll** [comment]
允许所有 就去掉这行配置

**Comment by dangaoxia** [comment]
183	64	0	hook host is not allowed, please contact the administrator to alter the configure	10	hook 我在数据库看到的信息，即便去掉HOOK_HOST_ALLOWED这个配置依然是会出现这个信息

**Comment by blackholll** [comment]
去掉后需要重启celery

**Comment by dangaoxia** [comment]
感谢，解决了🙏

**Comment by dangaoxia** [comment]
还有一个问题啊，就是我在hook请求中没有看到hook_token，这个参数好像没有起到作用

**Comment by blackholll** [comment]
token用于身份验证的 计算签名后作为header中的signature。 你的服务端需要对此校验。参考 github.com/blackholll/loonflow_hook_demo

**Comment by dangaoxia** [comment]
再次感谢🙏
