### ISSUE TITLE
状态流转问题

### ISSUE THREAD

**Issue by dangaoxia** [blackholll/loonflow#458]
使用默认测试的vpn流程，发现不能正常流转
<img width="1037" alt="截屏2023-07-10 12 01 58" src="https://github.com/blackholll/loonflow/assets/57345969/d564e0ce-d04c-4bf4-a500-4a364db962b3">

**Comment by blackholll** [comment]
提供下以下信息：
1.这个截图中 操作记录tab下的信息截图。 
2.ticketuser表中 ticketid=77的记录
3.loonflow的日志 如果有错误信息的话 发出来

**Comment by dangaoxia** [comment]
INSERT INTO `loonflownew`.`ticket_ticketuser` (`id`, `creator`, `gmt_created`, `gmt_modified`, `is_deleted`, `username`, `in_process`, `worked`, `ticket_id`) VALUES (133, '', '2023-07-10 11:53:38', '2023-07-10 11:53:38', 0, 'it', 1, 0, 77);

**Comment by dangaoxia** [comment]
<img width="983" alt="截屏2023-07-10 13 48 14" src="https://github.com/blackholll/loonflow/assets/57345969/072471be-b50e-48c4-a11f-2b444c8a34c9">

**Comment by blackholll** [comment]
提供下：
1.流程图
2. 运维人员审批中 这个状态的编辑窗口信息

**Comment by dangaoxia** [comment]
搞错了，第二个流程是要全部人同意才会流转，我以为随便一个人同意就会流转了
