### ISSUE TITLE
请问在用户管理如果不需要email和电话需要在哪些地方进行删改？

### ISSUE THREAD

**Issue by kkkzhonghaiwei** [blackholll/loonflow#462]
使用的版本:r2.0.14

问题详细描述:我在frontend/src/pages/User/User/UserList/index.tsx和apps\account\models.py下分别修改了email的相关代码，当创建一个新用户时，提示missing key: email

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:

做过哪些尝试:

**Comment by blackholll** [comment]
这个地方有定义参数必填：https://github.com/blackholll/loonflow/blob/master/apps/account/views.py#L22
但是应该报”alias is needed“ 而不是miss key :email.    你看下loonflow的日志  会有详细的错误堆栈信息

**Comment by kkkzhonghaiwei** [comment]
谢谢，已解决，还需要修改service下的basemodel和ticket下的相关代码。另外自定义字段里面，字段类型选择的是用户或者多选用户的时候，在工单详情里面显示的是username而不是alias，需要怎么改才能让前端直接显示alias而不是username
![2023-08-08 09_07_06-pcm_h5_msg](https://github.com/blackholll/loonflow/assets/53913399/ce2bfa2b-d24a-4c6e-8dfa-64d97618449a)

**Comment by blackholll** [comment]
frontend/src/pages/Ticket/TicketDetail/index.tsx
![image](https://github.com/blackholll/loonflow/assets/6269605/994c55ee-4ebb-4d3a-b2d7-06d70c5b105d) 
方案1:可参考工作流编辑页面
![image](https://github.com/blackholll/loonflow/assets/6269605/084eef4a-9ee3-43e8-957a-05b27ff41f6a)实现选择的只读状态展示效果。 方案2:或者新增一个根据username查询用户详情的接口，前端判断是用户或者用户多选的时候 请求该API获取用户信息 来展示。  方案3:后端在返回这工单详情时针对用户类型字段额外返回alias信息 方便前端处理展示。 推荐方案3 简单些

**Comment by kkkzhonghaiwei** [comment]
能麻烦你就方案一或者方案三写个简单的示例吗？

**Comment by blackholll** [comment]
给你参考页面了 还要我写啊。 自己尝试下吧。    或者付个费？

**Comment by kkkzhonghaiwei** [comment]
大佬，付费渠道在哪？还有很多问题要请教你

**Comment by blackholll** [comment]
> 大佬，付费渠道在哪？还有很多问题要请教你
项目readme 里面有二维码
