### ISSUE TITLE
大佬，一层层领导审批怎么做

### ISSUE THREAD

**Issue by zhiming429438709** [blackholll/loonflow#463]
我看了变量只有creator_tl，领导的领导要审批怎么办~
还有我们想调接口的方式集成，但是一个审批里面有多个相同类型的参数，这种是要走父子工单吗？

**Comment by blackholll** [comment]
之前有个讨论 https://github.com/blackholll/loonflow/issues/82。本来打算支持的，后来遗漏了。  当前已经支持了外部获取， 你可以配置一个外部获取处理人的类型， 通过配置不同的参数来实现 比如level=1&order=desc，从上到下第一级
