### ISSUE TITLE
兄弟们，工作流状态数据怎么支持列表

### ISSUE THREAD

**Issue by baqmxdsny** [blackholll/loonflow#464]
## ISSUE TEMPLATE

问题详细描述:
现在表单数据中有个列表，不知道怎么支持
<img width="1170" alt="image" src="https://github.com/blackholll/loonflow/assets/30679656/c25a5376-aa64-4239-8ff8-4259a71379d9">

**Comment by blackholll** [comment]
你可以新增一个自定义字段， 然后在标签中填入个性化的内容如“detail_list”。 工单详情页面中展示的时候根据这个label的内容做个性化展示。 提交或处理工单的时候用json描述填写的内容， 并提交到后端保存 。  3.x版本会考虑支持这个类型的字段。  估计3.1或者3.2   3.0.0版本 可能不一定有时间支持
