### ISSUE TITLE
审批后，获得某些资源的权限，这个怎么做

### ISSUE THREAD

**Issue by zhiming429438709** [blackholll/loonflow#467]

**Comment by blackholll** [comment]
是要做权限申请么？ 状态可以这么设置： 发起人新建中--经理审批中--自动授权中---结束。  自己实现一个hook服务，用于执行授权操作，并开放api。 其中“自动授权中” 配置处理人类型为“hook”。 处理人参考配置界面提示配置相应参数。   工单到达处理人为hook的状态时 会触发post请求到你配置的hook服务 并附带工单的所有信息。 你的hook服务收到请求，根据工单信息执行相应的授权操作

**Comment by blackholll** [comment]
hook服务可参考 https://github.com/blackholll/loonflow_hook_demo/blob/main/hook/views.py。另外 文档中有hook详细的说明 https://loonflow.readthedocs.io/zh_CN/r2.0.18/manage/workflow_config/#id4
