### ISSUE TITLE
一个部门下分管流程的领导不一样要怎么来设置流程

### ISSUE THREAD

**Issue by kkkzhonghaiwei** [blackholll/loonflow#469]
比如：
某个部门A流程归领导a审批；
B流程归领导b审批。
另外一个部门A流程归领导aa审批；
B流程归领导bb审批。
如果选择部门的话，那么所有该部门的领导都能审批，显然不符合常理。
如果选择角色，那么所有不同部门的角色都能审批，显然也不符合需求。
这种应该怎么来设置？
![2023-09-05 16_18_35-pcm_h5_msg](https://github.com/blackholll/loonflow/assets/53913399/9a80291f-88b1-4497-b500-d52997234fe2)

**Comment by blackholll** [comment]
配置处理人类型”外部获取“， 然后处理人部分根据提示配置一个hook_url。你提供一个hook服务，工单状态到达此状态时候调用你的服务获取处理人。
