### ISSUE TITLE
工单流转

### ISSUE THREAD

**Issue by adoyyoda** [blackholll/loonflow#471]
## ISSUE TEMPLATE

使用的版本: 2.0.18

问题详细描述: 普通用户建立一个工单vpn申请，admin用户同意后，工单并没有走到下一步，还是留在发起人tl-审批中

是否查看了系统日志(默认在启动用户家目录下loonflow.log): 是，无错误

是否搜索过历史issue: 是

做过哪些尝试: 用工作流管理员登录还是不能把工单送到下一步。

**Comment by adoyyoda** [comment]
![image](https://github.com/blackholll/loonflow/assets/95363438/2725805e-ba09-4480-8233-c45a55247d5c)

**Comment by adoyyoda** [comment]
如果是我理解不对，工单怎么才能去下一步运维人员审批中呢？

**Comment by blackholll** [comment]
检查下 运维人员审批中 这个状态的处理人配置看是否配置错误。比如配置了部门 以及部门id 但是该部门id不存在
