### ISSUE TITLE
分配方式为全部处理，a,b,c 三人怎么实现处理意见为不同字段

### ISSUE THREAD

**Issue by baqmxdsny** [blackholll/loonflow#472]
![image](https://github.com/blackholll/loonflow/assets/30679656/ffb0e6d3-d765-4dc1-b5ad-df27429873bf)
表单字段 该如何配置
a,b,c三人的处理意见互相不可修改 和看见

**Comment by blackholll** [comment]
处理意见 不同于自定义字段  每个人处理工单时填写的处理意见都是独立的。    如果你指的是你新建了一个自定义字段名称叫处理意见 那需要吧状态拆分成多个 每个状态配置单独的处理人 里面的表单配置对应的处理意见字段可选或者必填
