### ISSUE TITLE
前端小白关于页面的几个问题向请教一下怎么改？

### ISSUE THREAD

**Issue by kkkzhonghaiwei** [blackholll/loonflow#476]
1.选择字段类型是用户名的时候在填写表单时，输入关键字后怎么调整显示的条目数量？现在默认是10条
![2](https://github.com/blackholll/loonflow/assets/53913399/0c52e5c2-806b-48b4-b775-d736159b9f4e)

2.字段类型是附件的时候怎么在表单里点击如何设置在新窗口打开？当附件是office文件时如何设置点击时可以预览
![1](https://github.com/blackholll/loonflow/assets/53913399/5b2181dc-f0d3-40c4-9a57-29b825efa416)

3.新建工单里面有个默认的标题是在哪里删除的？
![3](https://github.com/blackholll/loonflow/assets/53913399/c5216b9d-d5e2-4967-a590-ea0e4c92f2ad)

**Comment by blackholll** [comment]
1.https://github.com/blackholll/loonflow/blob/master/frontend/src/pages/Ticket/TicketDetail/index.tsx  queryUserSimple方法里面传个per_page参数 。 或者 https://github.com/blackholll/loonflow/blob/master/apps/account/views.py#L710 修改per_page的默认值
2.https://github.com/blackholll/loonflow/blob/master/frontend/src/pages/Ticket/TicketDetail/index.tsx 附件字段改下属性。 需要点击直接打开，可以浏览器安装下office的插件。 不装插件也支持打开的话会有点麻烦， 可能要改后端代码。 自己网上搜下吧
3. 状态列表中 初始状态的表单配置里面把title去掉

**Comment by kkkzhonghaiwei** [comment]
第二个问题的附件字段是指这一段吗？改哪个属性？ANTD文档里面好像没说
![sss](https://github.com/blackholll/loonflow/assets/53913399/8dd33bcf-9bcf-4306-be09-1b2acde0bea1)

第三个问题的话，自定义的字段也有title，前端有没有办法隐藏掉默认的title显示

**Comment by blackholll** [comment]
1.   https://github.com/blackholll/loonflow/blob/b0e236b314286c5f6cc6959622c9c8505e776443/frontend/src/pages/Ticket/TicketDetail/index.tsx#L530  新增个属性。target="_blank。 2.自定义字段不要用title，换个标识符
