### ISSUE TITLE
当部门有多个leader时，如何配置creator_tl如何复选某种角色？

### ISSUE THREAD

**Issue by kkkzhonghaiwei** [blackholll/loonflow#477]
也就是说推送给部门Leader中的某种角色的leader，或者外部怎么去实现？求教逻辑
![2023-12-14 18_44_03-创新工作协作平台](https://github.com/blackholll/loonflow/assets/53913399/37fa47b7-6dc9-4bb3-b2e8-236d9b26055e)
另外，捐赠后如何加微信？

**Comment by blackholll** [comment]
多个leader可以将多个人配置在审批人信息里面。 然后使用变量+creator_tl作为审批人。 但是这种方式会将根据“分配方式” 分配给某一个人或全部处理。  无法实现你所谓的另一层属性。 
方案1：将多个tl及tl的属性信息作为json保存在部门表的label字段中。 定制开发新增一个处理人类型。 我的vip付费视频教程中有如何定制新增处理人类型
方案2： 处理人类型使用“外部获取”， 处理人信息中配置外部服务的地址信息（详见配置界面提示）。 当工单状态到达此状态时loonflow会请求你的获取对应的处理人。 处理人逻辑由你的hook服务自己实现。  

捐赠后可留言 你的微信号（但是我可能不会很及时看见）， 你可以再qq私聊我，或者邮件 blackholll@163.com
