### ISSUE TITLE
工单详情接口返回的json格式，key是否可以用规范双引号而不是单引号

### ISSUE THREAD

**Issue by lovefox666** [blackholll/loonflow#48]
工单详情接口返回的json格式，key是否可以用规范双引号而不是单引号

**Comment by blackholll** [comment]
json格式的key是没有引号的，哪来的单引号？
![image](https://user-images.githubusercontent.com/6269605/59970758-c55ca580-95a0-11e9-9218-1ad315d4694b.png)
