### ISSUE TITLE
流程配置了通知，新建工单后celery看不到发送的通知日志

### ISSUE THREAD

**Issue by sendtion** [blackholll/loonflow#480]
## ISSUE TEMPLATE

使用的版本: 2.0.18

问题详细描述: 配置了通知地址，工作流管理也选择了通知，celery服务已启动。但是收不到通知，celery看不到通知的日志。redis里面也能看到数据。

是否查看了系统日志(默认在启动用户家目录下loonflow.log):  查了loonflow日志，能看到触发通知日志。但是celery日志没有显示。

是否搜索过历史issue: 搜过，没解决问题。

做过哪些尝试: 更换celery版本，重启服务等。

这是通知配置
![image](https://github.com/blackholll/loonflow/assets/9346618/fe260c84-6479-4a6b-af5d-8b832357e86f)
这是流程配置
![image](https://github.com/blackholll/loonflow/assets/9346618/4b74174a-931b-4cd8-80ca-ba6731e88d33)
这是loonflow日志
![image](https://github.com/blackholll/loonflow/assets/9346618/e2085dfb-0180-4a94-8e49-d1c09756b4b2)
这是celery日志
![image](https://github.com/blackholll/loonflow/assets/9346618/339e971b-e868-4966-9730-043808874975)
这是redis数据
![image](https://github.com/blackholll/loonflow/assets/9346618/edadbe1b-1e73-48af-bdaf-486608eccfbb)

**Comment by maczyt** [comment]
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by blackholll** [comment]
celery 启动的时候需要加个参数   -Q loonflow

**Comment by sendtion** [comment]
感谢解答，困扰了我大半天，确实是这个问题！
