### ISSUE TITLE
如何将工单提交到回退上次的回退节点

### ISSUE THREAD

**Issue by quguoqiang** [blackholll/loonflow#483]
## ISSUE TEMPLATE

使用的版本:

问题详细描述:

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:

做过哪些尝试:

**Comment by blackholll** [comment]
没看明白你的问题， 把描述清楚点

**Comment by quguoqiang** [comment]
就是一个工单申请人提交后审批到一半，被中间某个审批人退回到申请人了，申请人修改工单后直接提交到某个审批人退回节点（防止重新再审批）
