### ISSUE TITLE
 'str' object has no attribute 'type_id'

### ISSUE THREAD

**Issue by wtxhai** [blackholll/loonflow#484]
## ISSUE TEMPLATE

使用的版本:2.0.19

问题详细描述:
![image](https://github.com/blackholll/loonflow/assets/49899065/e70e3886-2c1f-42fd-aa61-478e1aeab471)

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:搜索过

做过哪些尝试:更改表达试还是不合适[ {"expression": "{issue_notify} == '采购部'", "target_state_id": 40}, {"expression": "{issue_notify} == '计划部'", "target_state_id": 41} ]

**Comment by wtxhai** [comment]
![image](https://github.com/blackholll/loonflow/assets/49899065/f0cb8171-2859-4462-93f6-d41b083060ff)
自定义字段也添加了！

**Comment by blackholll** [comment]
1.条件写的有问题， 条件表达式里面==后面的值应该是配置字段选项时的key。比如｛“aa”：“中国”｝。需要用==“aa” 而不是中国 。
2.标题中错误 不太详细， 把完整的错误堆栈发出来

**Comment by wtxhai** [comment]
完整报错信息：
{"code": -1, "data": {}, "msg": "'str' object has no attribute 'type_id'"}

**Comment by blackholll** [comment]
这个错误是哪个页面 怎么操作报出来的？ 另外这个是api的返回，详细的错误日志去日志文件中找。 进程启动用户的家目录下 loonflow.log

**Comment by wtxhai** [comment]
{issue_suggestion: "1213", issue_department: "2", issue_notify: "2", transition_id: 30}
issue_department: "2"
issue_notify: "2"
issue_suggestion: "1213"
transition_id: 30

**Comment by wtxhai** [comment]
错误日志：
2024-06-03 15:53:51,428 D:\nlpflow\service\common\log_service.py process-11316 thread-26708 20 [ERROR]: Traceback (most recent call last):
  File "D:\nlpflow\service\common\log_service.py", line 17, in _deco
    real_func = func(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^
  File "D:\nlpflow\service\ticket\ticket_base_service.py", line 1971, in get_ticket_state_participant_info
    if state_obj.type_id == constant_service_ins.STATE_TYPE_START:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'type_id'

2024-06-03 15:53:51,428 D:\Python\Lib\site-packages\django\core\servers\basehttp.py process-11316 thread-26708 187 [INFO]: "PATCH /api/v1.0/tickets/64 HTTP/1.1" 200 74

**Comment by wtxhai** [comment]
![image](https://github.com/blackholll/loonflow/assets/49899065/633aaf71-b7d6-46cb-a4b6-9c7f249465cd)

**Comment by blackholll** [comment]
应该就是你表达式写错了。匹配不到任何一个分支， 目标节点未获取到 然后代码里面要获取state_obj.type_id 就报错了

**Comment by wtxhai** [comment]
> 1.条件写的有问题， 条件表达式里面==后面的值应该是配置字段选项时的key。比如｛“aa”：“中国”｝。需要用==“aa” 而不是中国 。 2.标题中错误 不太详细， 把完整的错误堆栈发出来

我要判断的是aa是否等于中国，如果等于中国，则进行A流程，反之则进行B流程，“中国”这个值的判断，我放到哪里？

**Comment by wtxhai** [comment]
> 应该就是你表达式写错了。匹配不到任何一个分支， 目标节点未获取到 然后代码里面要获取state_obj.type_id 就报错了

表达式：[ {"expression": "{issue_notify} == '采购部'", "target_state_id": 40}, {"expression": "{issue_notify} == '计划部'", "target_state_id": 41} ]
请教一下该如何修正一下

**Comment by blackholll** [comment]
[{"expression": "{issue_notify} == '采购部'", "target_state_id": 40}, {"expression": "{issue_notify} == '计划部'", "target_state_id": 41} ]
如果你自定义字段 issue_notify配置里面 选项的内容为 ｛“caigou”：“采购部”，“jihua”：“计划部”｝。  那么你的表达式应该 [{"expression": "{issue_notify} == 'caigou'", "target_state_id": 40}, {"expression": "{issue_notify} == 'jihua'", "target_state_id": 41} ]

**Comment by wtxhai** [comment]
明白了。非常感谢！
