### ISSUE TITLE
状态设置问题

### ISSUE THREAD

**Issue by dragonhackking** [blackholll/loonflow#486]
## ISSUE TEMPLATE

使用的版本:2.0.18

问题详细描述:设置状态时，我这边最后一个状态是【申请人确认】，那需要怎么设置才能实现：当倒数第二个状态通过时，默认会流程到申请的人那里？毕竟没有一个角色叫申请人，没法指定给申请人

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:

做过哪些尝试:

**Comment by blackholll** [comment]
处理人类型选择 变量。处理人填写creator
