### ISSUE TITLE
部门邮件功能实现

### ISSUE THREAD

**Issue by wtxhai** [blackholll/loonflow#489]
## ISSUE TEMPLATE

使用的版本:v2.0.19

问题详细描述:流程里面如果参与人类型设置成了部门，如何给部门审批人发送一份邮件，这个功能我需要写到哪个模块下面？

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:已检索，未发现合适的解决方案。

做过哪些尝试:

**Comment by wtxhai** [comment]
> ## ISSUE TEMPLATE
> 使用的版本:v2.0.19
> 
> 问题详细描述:流程里面如果参与人类型设置成了部门，如何给部门审批人发送一份邮件，这个功能我需要写到哪个模块下面？
> 
> 是否查看了系统日志(默认在启动用户家目录下loonflow.log):
> 
> 是否搜索过历史issue:已检索，未发现合适的解决方案。
> 
> 做过哪些尝试:

![image](https://github.com/blackholll/loonflow/assets/49899065/18600e26-a248-412f-951d-890394600c08)

**Comment by blackholll** [comment]
设置为部门 在工单流转的时候就会转化成部门下的所有人（因为如果工单当前处理人直接记录部门，那么在查询待办工单的时候 如果工单记录多 就会非常慢）。 所以无需额外处理

**Comment by wtxhai** [comment]
我想额外增加一个调用第三方发送邮件的功能，流转到部门的时候，系统可以发送一份邮件到部门审批人，通过Outlook，网易等第三方邮件服务器。这样做可以避免单据流转到部门时，不登录系统就发现不了单据，能够及时提醒处理。这个功能代码，我怎么实现好一点，请教一下！

**Comment by wtxhai** [comment]
懂了，合适了。
