### ISSUE TITLE
一个流程，如果当发起人是本部门的TL，此时需要本部门的另外一个TL审核时，如何处理

### ISSUE THREAD

**Issue by lovefox666** [blackholll/loonflow#49]
一个流程，如果当发起人是本部门的TL，此时需要本部门的另外一个TL审核时，如何处理

**Comment by blackholll** [comment]
本部门还有好几个TL?   审批人设置为creator_tl的话，处理人会是这个创建人所在部门记录中的approver.如果approver设置了多人，那么该工单的审批人就是多人。
如果所在部门approver为空，那么就以 leader为准。如果都没有，那么工单处理人为空，无人可以再处理

**Comment by blackholll** [comment]
你的情况， 可以把approver设置为多人，即逗号隔开的多个username

**Comment by lovefox666** [comment]
从管理角度需要，
1、比如部门主任自己要发起某个审批，那么需要部门书记审批。
2、部门书记发起的，需要部门主任审批。
3、部门其他人员发起的，部门主任审批

**Comment by lovefox666** [comment]
approver多人的话，是会签（每个人都同意），还是或签（有一个同意即可）？

**Comment by blackholll** [comment]
这个根据这个状态分配方式： 直接处理，主动接单，全部处理，随机分配
