### ISSUE TITLE
通知模板中如何放入审批流当前状态？

### ISSUE THREAD

**Issue by wtxhai** [blackholll/loonflow#491]
## ISSUE TEMPLATE

使用的版本:v2.0.19

问题详细描述:想把当前审批流的当前状态放到通知模板中去，state_name放了报错。应该放哪个字段

错误信息：\nKeyError: \'state_name\'\n', 'args': '[191]', 'kwargs': '{}', 'description': 'raised unexpected', 'internal': False}

![image](https://github.com/blackholll/loonflow/assets/49899065/589dedcb-dd4f-461e-9d4c-5b1bc71064ab)

**Comment by wtxhai** [comment]
大佬请教一下,怎么在通知内容模板里面获取审批流当前状态？

**Comment by blackholll** [comment]
当前发送通知生成内容模板时 仅支持基础字段: 即工单基础表中的字段如sn,title,gmt_created, creator,state_id  等 + 工单自定义字段（这里仅支持自定义字段的原始值，比如是一个选项类型字段country{"1":"中国", "2":"美国"}， 实际的值是“1”那么生成的通知标题或者通知内容 就是1，而不是中国）。  当前需要拿到状态的名称的话 需要自己修改下taks.send_ticket_notice方法 https://github.com/blackholll/loonflow/blob/r2.0.18/tasks.py#L159
