### ISSUE TITLE
生产环境docker compose方式部署 执行 docker compose -f docker-compose.yml up -d 后报错

### ISSUE THREAD

**Issue by Nickdong123** [blackholll/loonflow#492]
## ISSUE TEMPLATE

使用的版本: r2.0.18

问题详细描述:
生产环境docker compose方式部署方式 ，执行 docker compose -f docker-compose.yml up -d 后报错，报错信息如下：
“Error response from daemon: pull access denied for loonflow-web, repository does not exist or may require 'docker login': denied: requested access to the resource is denied”

是否查看了系统日志(默认在启动用户家目录下loonflow.log): 否

是否搜索过历史issue:   是

做过哪些尝试:
1、登录docker id 后执行命令
2、手动拉取镜像：
  执行docker-compose -f docker-compose.yml pull  终端信息显示如下：
       Pulling loonflow-redis ... done
       Pulling loonflow-mysql ... done
       Pulling loonflow-web   ... retrying in 1 second
       Pulling loonflow-task  ... retrying in 1 second
  执行 docker pull blackholll/loonflow-web:latest  终端信息显示如下：
       2d473b07cdd5: Pulling fs layer
       2d473b07cdd5: Retrying in 1 second
       f454ba3ac68a: Retrying in 1 second
       4f4fb700ef54: Retrying in 1 second
       b232db65e856: Waiting
       a0b56cc50e58: Waiting
       ......
       error pulling image configuration: download failed after attempts=6: dial tcp 108.160.169.185:443: i/o timeout

**Comment by blackholll** [comment]
你需要个VPN. 或者你本地 build image.  docker_compose_deploy目录下有每个image对应的dockerfile
