### ISSUE TITLE
新建自定义字段（附件类型）表单中不显示 click to upload 按钮

### ISSUE THREAD

**Issue by Nickdong123** [blackholll/loonflow#493]
## ISSUE TEMPLATE

使用的版本:r2.0.18

问题详细描述:工作流中新建自定义字段为附件类型，在状态的展示字段中添加后，在新建工单后的表单中不显示 click to upload 按钮，无法上传附件

是否查看了系统日志(默认在启动用户家目录下loonflow.log):no

是否搜索过历史issue:yes

做过哪些尝试: 在自带的请假申请工作流中新建附件类型自定义字段也不显示，但已有工单中的附件类型却显示click to upload按钮并且可以上传

**Comment by blackholll** [comment]
需要在工作流配置和 状态里面配置需要展示的字段 具体逻辑见 https://github.com/blackholll/loonflow/issues/37

**Comment by Nickdong123** [comment]
> 需要在工作流配置和 状态里面配置需要展示的字段 具体逻辑见 #37

不是这个问题。我已经在状态的表单展示字段中设置了该字段(该字段是附件类型)，在新建表单后该字段仅显示了字段名称，但没有出现附件类型字段该有的click to upload按钮。我重新尝试将展示字段中该字段是否必填项由1改成了2，发现表单中upload按钮正常显示了出来。或许这是个bug

**Comment by blackholll** [comment]
1是只读，2 是必填，
<img width="1443" alt="image" src="https://github.com/blackholll/loonflow/assets/6269605/5f354721-790f-424d-abdd-521cfceef164">
