### ISSUE TITLE
单选下拉框字段没有值

### ISSUE THREAD

**Issue by dragonhackking** [blackholll/loonflow#494]
## ISSUE TEMPLATE

使用的版本:2.0.18

问题详细描述:使用代码调用【新建工单】，生成的工单到下一个节点，处理页面中，下拉框是没有值，查了下数据库ticketcustomfield表，这2个字段的char_value列也是空的值。
![666](https://github.com/blackholll/loonflow/assets/22230548/6f9f6c2c-2a4a-48a3-ac28-6e284985609a)

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:

做过哪些尝试:

**Comment by blackholll** [comment]
调用自己工单时传参传错了，例如你的下拉选择的字段选项是｛“a”：“中国”，“b”：“美国”｝  传 a或者b 而不是 中国 或美国。  另外 注意初始状态的表单配置中将该字段设置为可选或者必填 否则会忽略这个字段
