### ISSUE TITLE
日志问题

### ISSUE THREAD

**Issue by dragonhackking** [blackholll/loonflow#496]
## ISSUE TEMPLATE

使用的版本:2.0.18

问题详细描述:目前来看，好像部署到服务器中的程序，日志没法打印，是因为这个原因吗。
<img width="558" alt="999" src="https://github.com/blackholll/loonflow/assets/22230548/49f34426-6527-45c6-bdc5-cdc335fe8952">

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:

做过哪些尝试:

**Comment by blackholll** [comment]
是的， 先看uwgi日志吧.   或者你有时间可以帮忙排查下原因

**Comment by blackholll** [comment]
docker compose方式部署 日志在/var/log/loonflow/目录下
