### ISSUE TITLE
获取工单详情的问题-delimiter

### ISSUE THREAD

**Issue by dragonhackking** [blackholll/loonflow#498]
## ISSUE TEMPLATE

使用的版本:2.0.18

问题详细描述:突然出现的问题，回过头发现只要是这个流程，获取工单详情时，都有这个问题。。。我怀疑是字段值导致的，大佬们帮忙看看
<img width="413" alt="微信图片_111" src="https://github.com/blackholll/loonflow/assets/22230548/e0c811a7-3119-43ab-bffd-995e866e1e49">
<img width="605" alt="微信图片_222" src="https://github.com/blackholll/loonflow/assets/22230548/26e53629-de29-4d7a-a209-b85be16c4f75">

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:

做过哪些尝试:

**Comment by blackholll** [comment]
看下日志， uwsgi启动的话 看下uwsgi日志 。 里面会有详细的错误堆栈信息

**Comment by dragonhackking** [comment]
> 看下日志， uwsgi启动的话 看下uwsgi日志 。 里面会有详细的错误堆栈信息

<img width="872" alt="微信图片_666" src="https://github.com/blackholll/loonflow/assets/22230548/b7c8f165-ded0-4148-bc61-139a128bcb43">
貌似是正常的访问诶

**Comment by dragonhackking** [comment]
cacacaca！！居然是一个工作流的展现表单的格式问题。【工作流管理】->【详情】->【基础信息】->【展现表单】
把列表[  ]，不小心粘贴成了中括号 {  }，shit！！！

**Comment by dragonhackking** [comment]
cacacaca！！居然是一个工作流的展现表单的格式问题。【工作流管理】->【详情】->【基础信息】->【展现表单】
把列表[  ]，不小心粘贴成了中括号 {  }，shit！！！
