### ISSUE TITLE
docker-compse up启动项目时，loonflow-mysql服务报错启动失败

### ISSUE THREAD

**Issue by cyh26** [blackholll/loonflow#499]
## ISSUE TEMPLATE

使用的版本:
v3.0.1
问题详细描述:
根据指导文档中的方法，使用docker-compose up启动整个项目，镜像build后，启动服务时其它服务均能够正常启动，但mysql对应的服务启动失败，报错：
loonflow-mysql_1  | 2024-07-31T09:33:59.432782Z 0 [Note] InnoDB: Buffer pool(s) load completed at 240731  9:33:59
loonflow-mysql_1  | 2024-07-31T09:33:59.438006Z 0 [Note] Plugin 'FEDERATED' is disabled.
loonflow-mysql_1  | mysqld: Table 'mysql.plugin' doesn't exist
loonflow-mysql_1  | 2024-07-31T09:33:59.438167Z 0 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
loonflow-mysql_1  | 2024-07-31T09:33:59.439005Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
loonflow-mysql_1  | 2024-07-31T09:33:59.440487Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
loonflow-mysql_1  | 2024-07-31T09:33:59.440500Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
loonflow-mysql_1  | 2024-07-31T09:33:59.440504Z 0 [Warning] A deprecated TLS version TLSv1 is enabled. Please use TLSv1.2 or higher.
loonflow-mysql_1  | 2024-07-31T09:33:59.440506Z 0 [Warning] A deprecated TLS version TLSv1.1 is enabled. Please use TLSv1.2 or higher.
loonflow-mysql_1  | 2024-07-31T09:33:59.441723Z 0 [Warning] CA certificate ca.pem is self signed.
loonflow-mysql_1  | 2024-07-31T09:33:59.441791Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
loonflow-mysql_1  | 2024-07-31T09:33:59.442056Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
loonflow-mysql_1  | 2024-07-31T09:33:59.442096Z 0 [Note] IPv6 is available.
loonflow-mysql_1  | 2024-07-31T09:33:59.442108Z 0 [Note]   - '::' resolves to '::';
loonflow-mysql_1  | 2024-07-31T09:33:59.442130Z 0 [Note] Server socket created on IP: '::'.
loonflow-mysql_1  | 2024-07-31T09:33:59.492352Z 0 [Warning] Failed to open optimizer cost constant tables
loonflow-mysql_1  | 
loonflow-mysql_1  | 2024-07-31T09:33:59.492480Z 0 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.user' doesn't exist
loonflow-mysql_1  | 2024-07-31T09:33:59.492489Z 0 [ERROR] Fatal error: Failed to initialize ACL/grant/time zones structures or failed to remove temporary table files.
loonflow-mysql_1  | 2024-07-31T09:33:59.492555Z 0 [ERROR] Aborting

可以看出缺失mysql.plugin、mysql.user等。
这应该不是该项目的问题，而是mysql5.7的问题，但也想知道如何解决。

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

没有启动成功，应该没什么日志

是否搜索过历史issue:
是
做过哪些尝试:

删除mysql5.7镜像重新拉取并启动，问题依旧

**Comment by cyh26** [comment]
本地基于mysql:5.7镜像启动一个mysql容器是OK的，命令：docker run  --name my-mysql -e MYSQL_ROOT_PASSWORD=cyhtest -d  mysql:5.7

**Comment by cyh26** [comment]
解决办法：清除/loonflow-mysql/data下面的所有文件。
猜测原因为：一开始使用的是最新版本的mysql镜像（我本人修改过docker-compose.yml中loonflow-mysql的参数image）；但是最新版的mysql镜像可以启动项目，但是登录的时候会报错缺失一个包（忘了），查了原因是mysql版本过高的问题；此时切换到5.7，但原来的/loonflow-mysql/data下面任然有数据残留，此时启动项目，因为mysql版本不一致，导致/loonflow-mysql/data下的数据存在兼容性问题。
个人猜测如上。

**Comment by blackholll** [comment]
你在用v3.0.1分支？ 该版本还在开发中， 请使用当前最新的release版本 r2.0.18

**Comment by cyh26** [comment]
> 你在用v3.0.1分支？ 该版本还在开发中， 请使用当前最新的release版本 r2.0.18

已经切换了。谢谢！
