### ISSUE TITLE
处理工单后无法将当前处理人加入到关系人中

### ISSUE THREAD

**Issue by Jayden-he** [blackholll/loonflow#5]
使用cls.add_ticket_relation(ticket_id, add_relation)更新工单联系人，但后续使用了之前的工单查询记录ticket_obj，保存后会覆盖cls.add_ticket_relation(ticket_id, add_relation)保存的值，需要在cls.add_ticket_relation(ticket_id, add_relation)更新工单联系人后，重新查询ticket表记录，然后更新其它的数据
![image](https://user-images.githubusercontent.com/31341179/42146645-9ed67840-7dfb-11e8-9779-69393fcb84bd.png)

**Comment by blackholll** [comment]
fixed
https://github.com/blackholll/loonflow/releases/tag/v0.1.3
