### ISSUE TITLE
想在显示工单详情页，同时显示该类型工单的流程情况和相关审批人

### ISSUE THREAD

**Issue by lovefox666** [blackholll/loonflow#50]
1、显示该工单流程情况——完成了哪些，目前处于哪个状态，哪些为完成。
由于工单详情接口返回了当前工单的状态id（state_id），未返回状态的排序order。在使用flask模板的时候，由于for循环的作用域问题，很难区分完成了哪些，未完成哪些。需要用order值进一步加以判断。希望能提供order
2、希望显示工作流的当前状态以及每个状态的处理人。已处理的显示时间，未处理的显示处理人。应该调用哪个接口？

**Comment by blackholll** [comment]
1.flow_step接口中 会返回这个工单有哪些状态，哪些状态有过处理记录。 你根据这个有处理记录的就可以知道这个状态是否处理过了
2.因为工单的不同状态下的处理人是动态的。比如工单字段，需要等这个字段已经设置后 才有。 所以不提供获取每个状态处理人的接口。本状态处理完成后  工单状态就变成下一状态了。 重新获取工单详情接口，就可以知道新的处理人了

**Comment by lovefox666** [comment]
通过调用steps接口，无法获取当前处理流程的人员信息。
