### ISSUE TITLE
如何在转交提交的时候实现邮件发送功能，

### ISSUE THREAD

**Issue by wtxhai** [blackholll/loonflow#500]
## ISSUE TEMPLATE

使用的版本:2.0.19

问题详细描述:
1、如何在转交提交的时候实现邮件发送功能，可以给点思路吗？
2、可以转交给多个人在哪里修改一下配置？
![2024-08-16 10_33_04-Window](https://github.com/user-attachments/assets/3f067ea3-0684-4227-8815-12d70fb6a268)

**Comment by maczyt** [comment]
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by blackholll** [comment]
配置通知hook。然后你转交的时候就会触发hook。  关于转交多人： 你这个前端是自己写的吗？ 当前转交api不支持转给多人，代码在service.ticket.deliver_ticket.py 可以自己改下

**Comment by wtxhai** [comment]
一个workflow下面可以配置多个hook吗？现在已经配置了一个邮件通知的hook

**Comment by blackholll** [comment]
一个workflow不支持配置多个通知hook. 你可以在你配置的hook聚合下需要实现的功能

**Comment by wtxhai** [comment]
转交的那个事件在哪里触发的？

**Comment by wtxhai** [comment]
请教一下，转交的那个事件按钮是在哪一块触发的？

**Comment by wtxhai** [comment]
> 配置通知hook。然后你转交的时候就会触发hook。 关于转交多人： 你这个前端是自己写的吗？ 当前转交api不支持转给多人，代码在service.ticket.deliver_ticket.py 可以自己改下

没有找到service.ticket.deliver_ticket.py 这个文件

**Comment by wtxhai** [comment]
转交的前端是在哪个文件下面？

**Comment by blackholll** [comment]
这个你在代码里全文搜索下不就找到了

**Comment by wtxhai** [comment]
前端设置好了转交多人，在后端也接收到了，“与我相关”可以看到相关转交的审批流，可是在“我的待办”里面为何没有？请教一下是哪出漏了吗？
![2024-08-20 17_37_47-Window](https://github.com/user-attachments/assets/8e249816-029e-44a6-9331-8d1696e05d2d)

**Comment by blackholll** [comment]
你这样改动 只是允许前端调用api的时候传list。 实际并没有对这个list的数据类型做实际的处理。   转交给多人的功能目前没有支持是因为 给多人实际需要考虑这多人要怎么分配：随机分配、主动接单、全部处理。

**Comment by wtxhai** [comment]
> 你这样改动 只是允许前端调用api的时候传list。 实际并没有对这个list的数据类型做实际的处理。 转交给多人的功能目前没有支持是因为 给多人实际需要考虑这多人要怎么分配：随机分配、主动接单、全部处理。

应该是主动接单，上一个流程的人会分配这个流程会流入到指定的人员手中，这样会不会好一点？

**Comment by blackholll** [comment]
这个不同场景会有不同的需求，所以如果要做成转给多人 ，就需要支持选择分配方式。  刚才看了下代码当前转交的逻辑好像有点问题, 好像没有写到用于查询待办工单的那个表中， 然后好像没有触发hook.   我这几天抽空检查下

**Comment by blackholll** [comment]
转交工单 未触发通知hook问题已经修复 请使用最新版本r2.0.20

**Comment by wtxhai** [comment]
请教一下，我如何在转交的时候获取框中的那一部分数据值？（Hook邮件通知的时候可以获取去到，我想在转交的时候也能获取到这一部分值）
![image](https://github.com/user-attachments/assets/6cb11aa0-be25-45a5-89d5-324f13cb9e35)

**Comment by blackholll** [comment]
hook请求的时候会将工单所有值都带上
