### ISSUE TITLE
工作台，请假申请，新建后不能提交

### ISSUE THREAD

**Issue by littleforce163** [blackholll/loonflow#501]
## ISSUE TEMPLATE

使用的版本: r2.0.18

问题详细描述:

工作台，请假申请，新建后不能提交。

<img width="942" alt="bug图" src="https://github.com/user-attachments/assets/c17f6487-e57a-410a-a3ed-bf174776d246">

**此工单的必填字段为:attachment_field,multi_user_field,user_fleld,text_field,multi_select_field,select_field,leave_start,leave_end,leave_type,leave_reason,bool_field,checkbox_field,multi_checkbox_field**

是否查看了系统日志(默认在启动用户家目录下loonflow.log):

是否搜索过历史issue:

做过哪些尝试:

**Comment by blackholll** [comment]
打开浏览器控制台 点提交 看下有什么报错

**Comment by littleforce163** [comment]
<img width="1916" alt="bug图2" src="https://github.com/user-attachments/assets/54ce8f65-9bd9-4807-95db-bc2d95da9c0f">

**Comment by blackholll** [comment]
有正常触发提交的网络请求么？  另外检查下后台日志，如果是uwsgi启动的 看下uwsgi日志

**Comment by littleforce163** [comment]
1. 没有成功过，发送的网络请求payload：{"bool_field":1,"checkbox_field":"1","multi_checkbox_field":"1,2","select_field":"1","multi_select_field":"1","text_field":"aaa","user_fleld":"admin","multi_user_field":"admin","attachment_field":"[{\"url\":\"/media/ticket_file/55324a6a-6228-11ef-a200-b56a0247e735.png\",\"file_name\":\"1710959456204.png\"}]","leave_end":"2024-08-25 22:56:27","leave_type":"2","leave_reason":1,"transition_id":1,"workflow_id":1}
2. uwsgi日志：{address space usage: 181092352 bytes/172MB} {rss usage: 48472064 bytes/46MB} [pid: 15|app: 0|req: 153/472] 114.92.124.187 () {48 vars in 1563 bytes} [Sat Aug 24 23:03:15 2024] POST /api/v1.0/tickets => generated 270 bytes in 24 msecs (HTTP/1.1 200) 7 headers in 213 bytes (1 switches on core 0)

**Comment by littleforce163** [comment]
楼主可以贴一个试验成功的案例吗，我照着学习

**Comment by blackholll** [comment]
这个是后端已经收到请求了， network里面看不到请求的response么?  另外前端没有别的错误信息么？ 比如提示你redis没启动？

**Comment by blackholll** [comment]
你应该说清楚报错的信息就是：attachment_field,multi_user_field,user_fleld,text_field,multi_select_field,select_field,leave_start,leave_end,leave_type,leave_reason,bool_field,checkbox_field,multi_checkbox_field


我用docker compose启动后找到原因了，初始化的sql里面的数据有些问题，之前测试功能的时候把数据忘了改回来。   我这几天会发布哥新版本修复下。 或者你手工修改下:

![QQ_1724570914592](https://github.com/user-attachments/assets/46cee0b5-aca3-4f13-ae06-a40ee70b0ebb)
![QQ_1724570948583](https://github.com/user-attachments/assets/955b08bc-26aa-4511-b2f7-4aa87b6126b7)
