### ISSUE TITLE
如何在所有工单页面显示工单信息中的其他字段

### ISSUE THREAD

**Issue by wtxhai** [blackholll/loonflow#504]
## ISSUE TEMPLATE

使用的版本:2.0.19

问题详细描述 : 如何在所有工单页面显示工单信息中的其他字段

**Comment by blackholll** [comment]
分两种情况：1.用户只有查看权限时 的表单是根据工作流基础信息的配置里面的展现表单来展示 2.用户作为工单当前处理人时（即有处理权限） 根据对应工作流配置中当前状态配置里面的 表单字段 来展示。 如果是需要展示自定义字段就根据提示格式来配置对应字段标识。 非自定义字段可根据工单基础表ticket_ticketrecord中的字段的列名来配置 如title，sn，gmt_created等

**Comment by wtxhai** [comment]
举个例子：我现在有个自定义字段：field_a,我怎么把他展示出来，就和title，sn一样

**Comment by blackholll** [comment]
那就filed_a啊 和配置title一样。  上条回复不是说了嘛

**Comment by wtxhai** [comment]
菜单控制现在能不能实现，比如A菜单，甲可以看到，B菜单，乙可以看到

**Comment by blackholll** [comment]
目前菜单权限提供简单的控制，  即根据用户类型： 超级管理员、普通用户、工作流管理员 来确定不同权限:
普通用户：工作台、工单管理（我的待办，我的申请，与我相关，工单查看）
工作流管理员： 工作台、工单管理（我的待办，我的申请，与我相关，工单查看，工单干预）、工作流管理
超级管理员：所有菜单

**Comment by blackholll** [comment]
前端的菜单显示是根据用户登录后的jwt token中信息来获取用户权限的。 是否是因为之前非普通用户，现在改成普通用户了？ 因为jwt 是保存在本地的，需要用户登录状态过期 重新登陆 才会生效。 当前默认的jwt有效期是24小时。  前端判断权限的代码在frontend/src/access.ts中

**Comment by wtxhai** [comment]
用户属性没有变更过，就是感觉权限没有生效，我在哪里可以检查一下？在frontend/src/access.ts添加了打印好像没有执行

**Comment by blackholll** [comment]
浏览器控制台中 找到jwt的cookie。然后找个在线的jwt parser工具 看下解析出来的用户信息中的typeid
