### ISSUE TITLE
Redis  data question

### ISSUE THREAD

**Issue by EFX1SZH** [blackholll/loonflow#506]
使用的版本:2.18

问题详细描述: 
redis 里面的数据除了流水号，我找到了相关的代码，如下redis Key是（loonflow）json数据是从哪段代码写入的，告知一下非常感谢
{
  "body": "W1s1NzZdLCB7fSwgeyJjYWxsYmFja3MiOiBudWxsLCAiZXJyYmFja3MiOiBudWxsLCAiY2hhaW4iOiBudWxsLCAiY2hvcmQiOiBudWxsfV0=",
  "content-encoding": "utf-8",
  "content-type": "application/json",
  "headers": {
    "lang": "py",
    "task": "tasks.send_ticket_notice",
    "id": "532ad415-334e-4f7c-ab9d-6a3113bd8c72",
    "shadow": null,
    "eta": null,
    "expires": null,
    "group": null,
    "group_index": null,
    "retries": 0,
    "timelimit": [
      null,
      null
    ],
    "root_id": "532ad415-334e-4f7c-ab9d-6a3113bd8c72",
    "parent_id": null,
    "argsrepr": "[576]",
    "kwargsrepr": "{}",
    "origin": "gen8292@szhmesvma597",
    "ignore_result": false
  },
  "properties": {
    "correlation_id": "532ad415-334e-4f7c-ab9d-6a3113bd8c72",
    "reply_to": "e45ed4ee-2e46-3ffc-b420-7eb033ca3306",
    "delivery_mode": 2,
    "delivery_info": {
      "exchange": "",
      "routing_key": "loonflow"
    },
    "priority": 0,
    "body_encoding": "base64",
    "delivery_tag": "8aced58b-0b97-4abb-ba70-f5b37fde6d3c"
  }
}

 @auto_log
    def gen_ticket_sn(cls, app_name: str='')->tuple:
        redis_conn = redis.Redis(connection_pool=POOL)
        ticket_day_count_key = 'ticket_day_count_{}'.format(str(datetime.datetime.now())[:10])
        try:
            ticket_day_count = redis_conn.get(ticket_day_count_key)
        except redis.exceptions.ConnectionError:
            return False, 'Redis连接失败，请确认Redis已启动并配置正确'
        except Exception as e:
            raise Exception(e.__str__())

        if ticket_day_count is not None:
            new_ticket_day_count = redis_conn.incr(ticket_day_count_key)
        else:
            # 查询数据库中个数
            # 今天和明天
            today = str(datetime.datetime.now())[:10] + " 00:00:00"
            next_day = str(datetime.datetime.now() + datetime.timedelta(days=1))[:10] + " 00:00:00"
            # 包括is_deleted=1的数据
            ticket_day_count = TicketRecord.objects.filter(gmt_created__gte=today, gmt_created__lt=next_day).count()
            new_ticket_day_count = int(ticket_day_count) + 1
            redis_conn.set(ticket_day_count_key, new_ticket_day_count, 86400)

**Comment by blackholll** [comment]
处理异步任务，如通知hook的执行 使用了celery。 celery使用redis作为消息队列， tasks.py里面有相关逻辑
