### ISSUE TITLE
如何判断一个审批已完成

### ISSUE THREAD

**Issue by lovefox666** [blackholll/loonflow#52]
1、当一个流程到“结束状态”的时候，是否就结束了？
2、如何知道一个流程已经结束了。判断steps？
3、trainsition里如果该流程是结束状态，则返回code=-1。我怎么判断这个-1是结束状态的-1，还是异常返回的？

**Comment by blackholll** [comment]
1，2 ：设置状态的时候，有个属性状态类型(type_id).表示了开始、普通、结束。 当工单当前处于的状态的属性是结束的是。 工单基础表中is_end的值会为True（工单详情接口中有体现）。
3，工单已经处理结束的话，transition接口获取到的code不会是-1. data中是[]

**Comment by lovefox666** [comment]
url = 'http://127.0.0.1:8888/api/v1.0/tickets'

1、我是调用这个接口，获取工单列表。如果完成了，我想标记一下颜色。但断点调试了一下，返回的value值里的state并没有is_end信息。
2、工单到了结束状态，如果我调用transition确实返回了code=-1

**Comment by blackholll** [comment]
1.工单列表接口中已新增is_end字段
2.问题已经修复[r0.3.13](https://github.com/blackholll/loonflow/releases/tag/r0.3.13)

**Comment by lovefox666** [comment]
谢谢！
