### ISSUE TITLE
工单创建，或者发生改变，有没有事件通知

### ISSUE THREAD

**Issue by bennyliu-lexin** [blackholll/loonflow#53]
工单的所有变化，希望能将事件推送到某个IP某个端口，方便做定制化；

比如推送到192.168.1.2:8000端口
，我会在192.168.1.2上监听8000，获取到推送的事件，解析后判断，做自动化执行脚本，或者推送微信消息，或者等等

**Comment by blackholll** [comment]
loonflow支持通知脚本，状态发生变化的时候就会调用通知脚本。 通知脚本的执行需要启动celery。
#46

**Comment by bennyliu-lexin** [comment]
celery 是在哪里启动，我通过什么可以验证celery 可以正常工作了

**Comment by blackholll** [comment]
看文档: https://github.com/blackholll/loonflow/blob/master/docs/index.md
