### ISSUE TITLE
执行工单时，领导能否选择下一步的执行人？

### ISSUE THREAD

**Issue by libaibuaidufu** [blackholll/loonflow#54]
rt

**Comment by libaibuaidufu** [comment]
就是选择下一步 的 工单处理人。。。

**Comment by blackholll** [comment]
添加一个自定义字段，字段的类型是用户。 然后设置这个状态下这个字段是可选或者必填的。 工单处理的时候在表单中填写这个字段(前端根据字段的类型是用户，则显示一个用户选择的下拉框，数据源从调用方自己的后端获取)。 下个状态设置参与人类型是工单字段，参与人设置为这个自定义字段的字段标识。这样工单流转到下个状态的时候处理人就是前一个状态设置的处理人了

**Comment by libaibuaidufu** [comment]
> 然后设置这个状态下这个字段是可选或者必填的。工单处理的时候在表单中填写这个字段（前端根据字段的类型是用户，则显示一个用户选择的下拉框，数据源从调用方自己的后端获取）。下个状态设置参与人类型是工单字段，参与人设置为这个自定义字段的字段标识。这样工单流转到下个状态的时候处理人就是前一个状态设置的处理人了

感谢解答  已完成

**Comment by libaibuaidufu** [comment]
> > 然后设置这个状态下这个字段是可选或者必填的。工单处理的时候在表单中填写这个字段（前端根据字段的类型是用户，则显示一个用户选择的下拉框，数据源从调用方自己的后端获取）。下个状态设置参与人类型是工单字段，参与人设置为这个自定义字段的字段标识。这样工单流转到下个状态的时候处理人就是前一个状态设置的处理人了
> 
> 感谢解答已完成

测试一下看看
