### ISSUE TITLE
如何应用内置字段

### ISSUE THREAD

**Issue by lovefox666** [blackholll/loonflow#55]
![image](https://user-images.githubusercontent.com/34913809/60348441-1d0c6e00-99f2-11e9-814c-94179c407abb.png)
如何理解和正确应用内置字段？在模板里，可以直接调用么？在返回的工单详情里并没有这个信息。还是需要在后台配置工作流的状态里的表单字段？

烦请指点一下。

**Comment by blackholll** [comment]
participant_info.participant_name目前只支持表单配置。通知模板中不支持
表单字段配置中支持的字段为:    https://github.com/blackholll/loonflow/blob/cbbc724b4258e06333ce3c5479d9df91fb43669d/service/ticket/ticket_base_service.py#L652    + 你自定义字段的key
