### ISSUE TITLE
发送给第三方应用的消息，是否支持transition的操作

### ISSUE THREAD

**Issue by lovefox666** [blackholll/loonflow#56]
![image](https://user-images.githubusercontent.com/34913809/60379053-79a57280-9a5e-11e9-93b7-204fc079acce.png)

企业微信的消息，可以实现这种任务卡片的形式。loonflow是否支持任务卡片上的操作？

**Comment by blackholll** [comment]
loonflow通知脚本的功能，你可以在通知脚本中发送这个卡片消息。然后批准和驳回按钮这些你在你的自己的调用端后端实现接口以支持在卡片中直接处理
