### ISSUE TITLE
分管领导的审批，如何实现？

### ISSUE THREAD

**Issue by lovefox666** [blackholll/loonflow#58]
![image](https://user-images.githubusercontent.com/34913809/60386274-6d083500-9ac5-11e9-873e-7b0ed219bbdb.png)
比如A/B/C部门分管领导是张三，D/E/F部门的分管领导是李四。

**Comment by blackholll** [comment]
当前不支持。 计划在下个大版本中支持。 
目前你可以二次开发loonflow：
1.apps.account.models中新增一个表用于部门id和分管领导username的关联
2.新增一个变量，名字如:分管领导
3.自己实现一下对这个变量的处理。 获取创建人的分管领导信息
