### ISSUE TITLE
self.FIELD_TYPE_BOOL = 20  # 布尔类型 引起的错误

### ISSUE THREAD

**Issue by smilesmall** [blackholll/loonflow#60]
当设置一个bool类型的字段, 前端传否的时候, 数据库存的是False, 创建工单的时候就会报错"bool' object has no attribute 'items", 是因为在这个字段存的值就是False...现在不能使用id = 20字段了.,..

**Comment by blackholll** [comment]
把loonflow日志中的报错截图贴下吧， 方便我找到出错的地方。
日志路径在当前启动用户的根目录下的loonflow.log(如果你没有修改过日志路径的话)

**Comment by smilesmall** [comment]
service/ticket/ticket_base_service.py中, 397行左右, 你之前有标记过这个问题
![image](https://user-images.githubusercontent.com/39799758/60654198-1791a680-9e7e-11e9-95ac-3cb67b9f4f90.png)
就是因为这个问题的存在不能使用布尔类型

**Comment by blackholll** [comment]
你是否不是最新的代码？ 这个问题在v0.3.7已经修过了
https://github.com/blackholll/loonflow/releases/tag/v0.3.7

https://github.com/blackholll/loonflow/commit/cbbc724b4258e06333ce3c5479d9df91fb43669d

**Comment by smilesmall** [comment]
.....多谢楼主
