### ISSUE TITLE
工单 请求下一页出错

### ISSUE THREAD

**Issue by libaibuaidufu** [blackholll/loonflow#61]
# 接口：http://ip:8000/api/v1.0/tickets
## 第一页
请求参数：{'category': u'all', 'per_page': 20, 'page': 1}
返回结果：{u'msg':u'',u'code':0,u'data':{u'per_page':20,u'total':34,u'page':1,u'value':[]}}
可以返回正常结果
## 第二页
请求参数：{'category': u'all', 'per_page': 20, 'page': 2}
返回结果：{u'msg': u"'bool' object has no attribute 'username'", u'code': -1, u'data': u''}
## 请求 每页 30条
请求参数：{'category': u'all', 'per_page': 30, 'page': 1}
返回结果：{u'msg': u"'bool' object has no attribute 'username'", u'code': -1, u'data': u''}

## loonflow 接口一致
GET /api/v1.0/tickets?category=all&per_page=20&page=1 => generated 28546 bytes in 681 msecs (HTTP/1.1 200)
GET /api/v1.0/tickets?category=all&per_page=20&page=2 => generated 76 bytes in 67 msecs (HTTP/1.1 200)
## page 不能超过20
测试似乎 page不能超过20
## per_page 和 page 不能超过total
请求参数：{'category': u'all', 'per_page': 10, 'page': 2}
返回结果：{u'msg':u'',u'code':0,u'data':{u'per_page':10,u'total':34,u'page':2,u'value':[]}}

**Comment by blackholll** [comment]
看错误应该 获取第二页(per_page=10)和 第一页(per_page=30) 时，也就是第20-30条记录中某个工单的创建人账户在loonflow的用户表中不存在导致报错。  loonflow的日志应该也有相关信息

**Comment by libaibuaidufu** [comment]
错误日志
>2019-07-08 10:41:16,292 ./service/common/log_service.py process-32 thread-139839584990976 20 [ERROR]: Traceback (most recent call last):
  File "./service/common/log_service.py", line 17, in _deco
    real_func = func(*args, **kwargs)
  File "./service/ticket/ticket_base_service.py", line 177, in get_ticket_list
    creator_info = dict(username=creator_obj.username, alias='', is_active=False, email='', phone='', dept_info={})
AttributeError: 'bool' object has no attribute 'username'

>2019-07-08 10:41:59,885 ./service/common/log_service.py process-30 thread-139839768953216 20 [ERROR]: Traceback (most recent call last):
  File "./service/common/log_service.py", line 17, in _deco
    real_func = func(*args, **kwargs)
  File "./service/ticket/ticket_base_service.py", line 811, in get_ticket_format_participant_info
    script_obj = WorkflowScript.objects.filter(id=int(participant), is_deleted=0).first()
ValueError: invalid literal for int() with base 10: ''

**Comment by libaibuaidufu** [comment]
## 路径：service/ticket/ticket_base_service.py line 27
```
    @classmethod
    @auto_log
    def get_user_by_username(cls, username):
        """
        获取用户信息
        :return:
        """
        result = LoonUser.objects.filter(username=username, is_deleted=0).first()
        if result:
            return result, ''
        else:
            return False, '用户不存在'
```
## service/ticket/ticket_base_service.py line 166
creator_obj is False ,所以没有username 
```
creator_obj, msg = AccountBaseService.get_user_by_username(ticket_result_object.creator)
if creator_obj:
    creator_info = dict(username=creator_obj.username, alias=creator_obj.alias,
                        is_active=creator_obj.is_active, email=creator_obj.email, phone=creator_obj.phone)
else:
    creator_info = dict(username=creator_obj.username, alias='', is_active=False, email='', phone='')
```
是不是还是用上面的ticket_result_object.creator 代替 else 中的creator_obj.username

**Comment by blackholll** [comment]
嗯，是的。这块逻辑优化下 是可以不报错的。 后续我优化下
 
不过你这里的工单记录中确实存在创建人在loonflow用户表中不存在的。 你现在的解决方案如下：
1.删除这些创建人在loonflow不存在的工单
2.不存在的用户，同步到loonflow的用户表

**Comment by libaibuaidufu** [comment]
> 嗯，是的。这块逻辑优化下 是可以不报错的。 后续我优化下
> 
> 不过你这里的工单记录中确实存在创建人在loonflow用户表中不存在的。 你现在的解决方案如下：
> 1.删除这些创建人在loonflow不存在的工单
> 2.不存在的用户，同步到loonflow的用户表

感谢，我把数据库导过几次，导致用户和工单有些乱。我把他们删除重新测试一下。

**Comment by blackholll** [comment]
已优化   r0.3.15
