### ISSUE TITLE
驳回之后再次提交数据保存失败

### ISSUE THREAD

**Issue by smilesmall** [blackholll/loonflow#62]
驳回之后, 添加数据 ,提交数据, 经常出现保存不上新增的数据
打断点调试之后,发现  service/ticket/ticket_base_service中:
怀疑 :update_ticket_custom_field  方法有问题

**Comment by blackholll** [comment]
被退回的状态， 表单字段配置中是否包含你新增的那个字段？

**Comment by smilesmall** [comment]
1-包含该字段
2-驳回之后 旧数据修改,很大概率出现保存不上的现象,刚才又试了很多次

**Comment by smilesmall** [comment]
service/ticket/ticket_base_service中update_ticket_custom_field 方法含有一个for循环,
这个for循环遍历到某个元素, 会直接返回,跳出for循环

**Comment by smilesmall** [comment]
知道了...因为数据格式问题,这个方法执行到一半出错了.  
但是被日志捕获了, 而且调用这个方法的时候,,没有判断返回值,,直接return了,
调用方法的时候, 建议判断一下返回值再return

**Comment by blackholll** [comment]
好的  下个版本我优化下
