### ISSUE TITLE
适配后端数据库Postgres所做的修改

### ISSUE THREAD

**Issue by boldmanQ** [blackholll/loonflow#63]
因此需修改文件service/ticket/ticket_base_service.py适配
由133行：
>    ticket_query_set1 = TicketRecord.objects.filter(query_params).extra(where=['FIND_IN_SET("{}", participant)'.format(username), 'participant_type_id in ({}, {})'.format(CONSTANT_SERVICE.PARTICIPANT_TYPE_MULTI, CONSTANT_SERVICE.PARTICIPANT_TYPE_MULTI_ALL)])
修改为：
>  ticket_query_set1 = TicketRecord.objects.filter(query_params, participant__icontains=username).extra(where=['participant_type_id in ({}, {})'.format(CONSTANT_SERVICE.PARTICIPANT_TYPE_MULTI, CONSTANT_SERVICE.PARTICIPANT_TYPE_MULTI_ALL)])

TicketRecord模型participant字段存的是ID或者用逗号分隔的username
由于Postgres数据库没有FIND_IN_SET函数，所以用__contains处理判断participant字段是否包含username

不知这样修改是否符合查询相关工单的设计思路以或引起什么问题

**Comment by blackholll** [comment]
__contains 明显不行。 比如当前处理人类型是多人，处理人是”zhangsan3,lisi“.那么你用contains这条工单也会出现在zhangsan的待办工单列表中

**Comment by blackholll** [comment]
https://www.google.com/search?q=postgresql+FIND_IN_SET
