### ISSUE TITLE
在执行脚本时，如何获取上一次状态，如果执行失败，就修改工单状态为上一状态？

### ISSUE THREAD

**Issue by libaibuaidufu** [blackholll/loonflow#64]
在执行脚本时，如何获取上一次状态，如果执行失败，就修改工单状态为上一状态？
有没有这样一个接口，或者方法呢？

**Comment by blackholll** [comment]
可以这样:
1.新增一个自定义字段来标识脚本是否执行成功
2.脚本执行过程中根据执行结果， 调用loonflow中的service方法: TicketBaseService().update_ticket_field_value() 修改这个工单字段的值
3.新建一个流转，流转的初始状态是这个脚本执行的状态， 流转中设置为条件流转，流转表达式根据这个自定义字段的值来流转到不同状态

**Comment by libaibuaidufu** [comment]
> 可以这样:
> 1.新增一个自定义字段来标识脚本是否执行成功
> 2.脚本执行过程中根据执行结果， 调用loonflow中的service方法: TicketBaseService().update_ticket_field_value() 修改这个工单字段的值
> 3.新建一个流转，流转的初始状态是这个脚本执行的状态， 流转中设置为条件流转，流转表达式根据这个自定义字段的值来流转到不同状态

主要是 我们 因为在脚本执行中 我们把信息 通过redis 发送到另一个服务端 去处理了。
因此 在执行脚本时，是会成功的 ，然后在另一个服务端执行报错，然后想 利用上一状态 ，然后回退回去。

目前 我使用 工单步骤记录，来循环，上一阶段的 state_id.
但总感觉不咋好。。。

**Comment by libaibuaidufu** [comment]
同时 我们也做了 展示 所有工单，加上一个 回到某一个状态的页面。
保证能正常回退。只不过要手动。
这种方法 就比较保险。。。

**Comment by blackholll** [comment]
方案一:
基于上面的方案，你的脚本中发出任务后，轮询查询任务执行的结果，等获取到执行结果后，修改自定义字段。 
方案二:
需要状态处理人类型支持hook的方式(此类型计划中，但是还没支持。 就是到达这个状态后，将请求hook配置的接口地址。 然后被调用方任务执行后再回调loonflow)。 在hook端执行任务期间可以先修改自定义字段的值。   回调loonflow通过条件流转根据自定义字段的值来确定下个状态。
此方案的好处是不用在loonflow执行轮询脚本

**Comment by libaibuaidufu** [comment]
感谢 ，方案一 是个不错的主意。

**Comment by blackholll** [comment]
方案一可以临时用。 轮询脚本 特别是轮询时间比较长时，可能会导致loonflow的celery任务堆积。
我周末 如果有空的话，支持下hook方式

**Comment by libaibuaidufu** [comment]
就是轮询 有点麻烦，我想在另一服务端进行 修改 字段值 ，如果脚本已经执行完成了，这样应该就不会回退过去了吧。

**Comment by blackholll** [comment]
脚本执行完成后 后面的条件流转就立即执行了，条件已经判断过了。  后续字段修改不会导致流转的

**Comment by blackholll** [comment]
hook方式已支持 https://github.com/blackholll/loonflow/releases/tag/r0.3.17

**Comment by libaibuaidufu** [comment]
> hook方式已支持 https://github.com/blackholll/loonflow/releases/tag/r0.3.17

有没有文档 介绍如何使用，我没找到入口。

**Comment by blackholll** [comment]
https://github.com/blackholll/loonflow/wiki
“新建状态”  和 工单接口中的“工单hook回调”
