### ISSUE TITLE
请问 ticket_ticketcustomfield 这张表 中 字段is_delete 是如何被控制？

### ISSUE THREAD

**Issue by libaibuaidufu** [blackholll/loonflow#65]
自定义字段：script_is_end
数据库查询结果：ticket_ticketcustomfield 表中
```
id    name               is_delete
385	脚本执行状态	1
```
今天 我在运行脚本 ，这个字段不知为何 变成了 is_delete=1状态，导致无法使用。
但是 我无法看到或者知道他是不是删除状态，除了在数据库中查询，同时他会因为什么操作，变成is_deletel=1的状态呢？从而我好避免这样的操作。

**Comment by blackholll** [comment]
比如某个状态的表单设置里面有字段a, 且设置了可选或者必填。 然后调用处理工单的时候 传了个None， 那么这个字段的值将在ticket_ticketcustomfield 表中被删除

**Comment by libaibuaidufu** [comment]
> 比如某个状态的表单设置里面有字段a, 且设置了可选或者必填。 然后调用处理工单的时候 传了个None， 那么这个字段的值将在ticket_ticketcustomfield 表中被删除

好的。我今天是使用了           ` result, msg = TicketBaseService().update_ticket_field_value(ticket_id, update_dict)` 来更新字段，并传了None,以后注意了。。。。

**Comment by blackholll** [comment]
补充下：update_ticket_field_value这个方法是不校验 当前状态是否配置了该字段的， 只要提供了就直接更新， 是None的话就删除。
如果是通过处理工单这个api操作的，传了参数里面， 会根据状态的表单配置来校验。

**Comment by libaibuaidufu** [comment]
update_ticket_field_value 确实没有验证，但我也没有把这个字段设为必选或者可填。仅设置了可读，刚刚我测试了设置可选，传数据过去也只是空字符串`""`,也没有复现上面的问题,is_delete依然为0，同时该字段值也没有更新。可能是我误操作了。
