### ISSUE TITLE
需求收集(new requirement)

### ISSUE THREAD

**Issue by blackholll** [blackholll/loonflow#67]
新的需求请提交这里，我会考虑在后续版本支持
if you want some new functions. you can comment here

**Comment by lovefox666** [comment]
1、完善后台管理功能。可后台配置用户权限。
2、完善工作流配置-》状态-》表单字段可选，否则很容易写错。也无法交付给业主。

**Comment by yinhuanyi** [comment]
一个工作流中只支持10个状态，添加11个状态的时候，在流转中就无法选择到，只有将状态列表的分页改成每次取50个， 然后切回到添加流转的页面在选择，就可以选择到。

**Comment by blackholll** [comment]
@yinhuanyi    fixed in  [r0.3.23](https://github.com/blackholll/loonflow/releases/tag/r0.3.23)

**Comment by children1987** [comment]
支持工作流变更时，不影响已经创建的工单。即，无论工作流如何变化，变化前已被创建的工单的字段、状态、流转等，都按照工单创建时工作流的配置进行流转。

**Comment by blackholll** [comment]
@children1987   业内有些工作流定义保存为xml文件，这种方式比较好实现这个需求。目前loonflow保存到数据库中的。 变化后按照之前的定义来流转，实现起来比较复杂。   loonflow1.0发布并比较成熟后，开始考虑下这个需求

**Comment by children1987** [comment]
@blackholll 建议开一个issue专门讨论这个问题。或许有高人能提出巧妙的解决办法呢？

**Comment by children1987** [comment]
建议新增工单的“回退”功能，类似“转交”，作为系统的一个“内置功能”。退回支持退回到工单中，任意一个已经处理过的用户，状态切换到这个用户处理的相应状态。

**Comment by blackholll** [comment]
> 建议新增工单的“回退”功能，类似“转交”，作为系统的一个“内置功能”。退回支持退回到工单中，任意一个已经处理过的用户，状态切换到这个用户处理的相应状态。

回退时 系统需要知道将工单退回到哪个状态。 所以现在设计是需要自己新增个流转，自己来设定哪些状态需要支持退回，并且退回到哪个状态

**Comment by blackholll** [comment]
> @blackholll 建议开一个issue专门讨论这个问题。或许有高人能提出巧妙的解决办法呢？

你新建个issue呗

**Comment by children1987** [comment]
> > 建议新增工单的“回退”功能，类似“转交”，作为系统的一个“内置功能”。退回支持退回到工单中，任意一个已经处理过的用户，状态切换到这个用户处理的相应状态。
> 
> 回退时 系统需要知道将工单退回到哪个状态。 所以现在设计是需要自己新增个流转，自己来设定哪些状态需要支持退回，并且退回到哪个状态

由于工单已经被哪些人处理过了是可以知道的。在用户点“回退”后，列出这些人及对应的状态，由用户自己选择退回给谁，同时也就知道了应该退回到哪儿状态。

**Comment by blackholll** [comment]
> > > 建议新增工单的“回退”功能，类似“转交”，作为系统的一个“内置功能”。退回支持退回到工单中，任意一个已经处理过的用户，状态切换到这个用户处理的相应状态。
> > 
> > 
> > 回退时 系统需要知道将工单退回到哪个状态。 所以现在设计是需要自己新增个流转，自己来设定哪些状态需要支持退回，并且退回到哪个状态
> 
> 由于工单已经被哪些人处理过了是可以知道的。在用户点“回退”后，列出这些人及对应的状态，由用户自己选择退回给谁，同时也就知道了应该退回到哪儿状态。

工作流设计中 流程是规范的， 有些状态是不应该允许退回的，如果这个放开了，那么用户在处理工单的时候 就可以任意修改状态了。  但是通过新增流转来退回 就可以很好的控制那些状态可以退回，而且只退回给特定的状态

**Comment by blackholll** [comment]
test webhook

**Comment by blackholll** [comment]
test webhook2

**Comment by children1987** [comment]
建议新增“撤销工单”功能：工单创建人可在任意允许撤销的状态撤销工单。
具体的：
1. 状态 新增 “是否可撤销” 属性，默认“是”
2. 工单创建人点“撤销”后，工单流转到“初始状态”

**Comment by blackholll** [comment]
> 建议新增“撤销工单”功能：工单创建人可在任意允许撤销的状态撤销工单。
> 具体的：
> 
> 1. 状态 新增 “是否可撤销” 属性，默认“是”
> 2. 工单创建人点“撤销”后，工单流转到“初始状态”

初始状态是工单还没创建时候的状态，所以不可以回退到初始状态的。  目前我公司在用版本，有实现一个功能: 状态配置时支持配置一个标签，工单创建人可以在配置了标签的状态下强制关闭工单。如果要做撤回的话也可以这个思路， 在标签中注明撤回到哪个状态(你需要建个如”发起人-编辑中状态“)

**Comment by blackholll** [comment]
> > 建议新增“撤销工单”功能：工单创建人可在任意允许撤销的状态撤销工单。
> > 具体的：
> > 
> > 1. 状态 新增 “是否可撤销” 属性，默认“是”
> > 2. 工单创建人点“撤销”后，工单流转到“初始状态”
> 
> 初始状态是工单还没创建时候的状态，所以不可以回退到初始状态的。 目前我公司在用版本，有实现一个功能: 状态配置时支持配置一个标签，工单创建人可以在配置了标签的状态下强制关闭工单。如果要做撤回的话也可以这个思路， 在标签中注明撤回到哪个状态(你需要建个如”发起人-编辑中状态“)

当然 这个是可以做成通用功能的，1.x中会后续考虑支持下

**Comment by blackholll** [comment]
test qq hook

**Comment by children1987** [comment]
@blackholll 请问下是否有计划支持一个用户属于多个部门的场景？当前是只支持一个部门。

**Comment by blackholll** [comment]
> @blackholll 请问下是否有计划支持一个用户属于多个部门的场景？当前是只支持一个部门。

目前我见到的 一个用户属于多个部门的都是不合理的场景。你这是怎样的场景？

**Comment by children1987** [comment]
> > @blackholll 请问下是否有计划支持一个用户属于多个部门的场景？当前是只支持一个部门。
> 
> 目前我见到的 一个用户属于多个部门的都是不合理的场景。你这是怎样的场景？

某个员工，由于工作量不饱满、处于交接期、负责2大部门等原因，一个人被复用负责2份工作，即属于2个部门

**Comment by blackholll** [comment]
> > > @blackholll 请问下是否有计划支持一个用户属于多个部门的场景？当前是只支持一个部门。
> > 
> > 
> > 目前我见到的 一个用户属于多个部门的都是不合理的场景。你这是怎样的场景？
> 
> 某个员工，由于工作量不饱满、处于交接期、负责2大部门等原因，一个人被复用负责2份工作，即属于2个部门

目前大多数系统的用户部门管理里面一般都是不支持一个人属于多个部门的。你这个负责两个部门的工作 是否应该是这两个部门的leader? 如果是这样的话 就给两个部门的leader都配置为他。  
如果实在就是要支持一个人多个部门会有个麻烦的地方：
一个人属于多个部门的话  他提交的工单需要部门tl审批的话，应该哪个部门的tl来审批呢

**Comment by children1987** [comment]
test webhook3

**Comment by children1987** [comment]
test webhook4

**Comment by children1987** [comment]
test webhook5

**Comment by children1987** [comment]
> > > > @blackholll 请问下是否有计划支持一个用户属于多个部门的场景？当前是只支持一个部门。
> > > 
> > > 
> > > 目前我见到的 一个用户属于多个部门的都是不合理的场景。你这是怎样的场景？
> > 
> > 
> > 某个员工，由于工作量不饱满、处于交接期、负责2大部门等原因，一个人被复用负责2份工作，即属于2个部门
> 
> 目前大多数系统的用户部门管理里面一般都是不支持一个人属于多个部门的。你这个负责两个部门的工作 是否应该是这两个部门的leader? 如果是这样的话 就给两个部门的leader都配置为他。
> 如果实在就是要支持一个人多个部门会有个麻烦的地方：
> 一个人属于多个部门的话 他提交的工单需要部门tl审批的话，应该哪个部门的tl来审批呢

当前，钉钉是支持一个人属于多个部门的。
当一个人属于多个部门，需要tl审批的话，表单最后会自动增加一个必填项：所在部门。

**Comment by blackholll** [comment]
发现需求放在一起 不好跟进状态，新需求还是单独提issue吧
