### ISSUE TITLE
希望增加工单评论功能

### ISSUE THREAD

**Issue by cdz620** [blackholll/loonflow#7]
## 场景

工单在操作过程中，有些中间过程的结果需要添加到工单的评论中，工单相关的人可以查阅。

## 可能的实现方案

- 预留 ticket_flow_log 的 intervene_type_id 4为评论
- 还需要提供一个评论接口

**Comment by blackholll** [comment]
intervene_type_id为4已经使用了。 
评论类型设定为5了
功能已经实现见develop分支

**Comment by blackholll** [comment]
v0.2版本已经发布，包含此功能
