### ISSUE TITLE
工作流配置状态列表界面，状态处理人选择hook时，列表显示为“未知”

### ISSUE THREAD

**Issue by lovefox666** [blackholll/loonflow#71]
工作流配置状态列表界面，状态处理人选择hook时，列表显示为“未知”
![image](https://user-images.githubusercontent.com/34913809/69111582-f4783400-0ab8-11ea-8e53-7107d01330ad.png)

**Comment by blackholll** [comment]
fixed   https://github.com/blackholll/loonflow/releases/tag/r0.3.22
