### ISSUE TITLE
后台采用netcore可好

### ISSUE THREAD

**Issue by masterchen** [blackholll/loonflow#73]
有没有计划支持netcore后端版本？

**Comment by blackholll** [comment]
loonflow是http api的，你的应用通过http调用就好了

**Comment by masterchen** [comment]
我主要是对数据库该怎么设计不熟悉 有没有对工单数据库设计思想进行介绍一下

**Comment by blackholll** [comment]
@masterchen 
http://loonapp.com/blog/27/
