### ISSUE TITLE
文字错误

### ISSUE THREAD

**Issue by Rgcsh** [blackholll/loonflow#74]
工作流自定义字段 页面
布尔显示定义 字段
注释内容如下：

> 当为布尔类型时候，可以支持自定义显示形式。{"1":"是",0:"否"}或{"1":"需要","0":"不需要"}，注意数字也需要引号

错误为: {"1":"是",0:"否"} 中 的 0 没有加 双引号

**Comment by blackholll** [comment]
看的这么仔细  👍

**Comment by Rgcsh** [comment]
正在尝试中

**Comment by blackholll** [comment]
fixed in  [r0.3.23](https://github.com/blackholll/loonflow/releases/tag/r0.3.23)
