### ISSUE TITLE
支持工作流变更时，不影响已经创建的工单。

### ISSUE THREAD

**Issue by children1987** [blackholll/loonflow#78]
支持工作流变更时，不影响已经创建的工单。即，无论工作流如何变化，变化前已被创建的工单的字段、状态、流转等，都按照工单创建时工作流的配置进行流转。

_Originally posted by @children1987 in https://github.com/blackholll/loonflow/issues/67#issuecomment-594011133_

**Comment by blackholll** [comment]
业内有些工作流定义保存为xml文件，这种方式比较好实现这个需求。目前loonflow保存到数据库中的。 变化后按照之前的定义来流转，实现起来比较复杂。 loonflow1.0发布并比较成熟后，开始考虑下这个需求。
欢迎大家提相关意见，一起讨论

**Comment by children1987** [comment]
抛砖引玉：
1. 工作流的每次发布，都保存新的一族记录。（一族记录 = 1条Workflow记录 + n条State记录 + n条Transition记录 + n条CustomField记录）
2. 工单创建时，使其关联当前页面的工作流id

**Comment by blackholll** [comment]
> 抛砖引玉：
> 
> 1. 工作流的每次发布，都保存新的一族记录。（一族记录 = 1条Workflow记录 + n条State记录 + n条Transition记录 + n条CustomField记录）
> 2. 工单创建时，使其关联当前页面的工作流id

这种方案  引入版本的概念需要在workflow 和state+transition+customfield等之间再抽象一层(直接新增一条workflow记录的话  比较难维护)， workflow记录中保存一个版本号 这个版本号 与抽象层关联。  可以实现  但是成本比较大， 大改

**Comment by children1987** [comment]
是否可以先实现一个“工作流复制”的功能，作为临时解决方案？

**Comment by blackholll** [comment]
> 是否可以先实现一个“工作流复制”的功能，作为临时解决方案？

to  #79

**Comment by children1987** [comment]
有2个实现方案：
1. 工单创建时，把工作流相关信息序列化后保存在工单中。
2. 工作流相关信息，变化时就copy一套(无非关闭工单时直接修改)，这套工作流信息对应一个版本号，工单创建时保存这个版本号
`
加锁
    if 已存在不处于“已完成”状态的工单:
        copy 一套
    else:
        直接修改
`

**Comment by children1987** [comment]
可以在“workflow”表中，新增字段“version”，“id”和“version”作为联合主键。第三方应用的创建页面，始终会去找指定工作流id的最新版本的这一条记录来获取工作流相关信息。

**Comment by children1987** [comment]
目前可通过一些技巧规避此问题：
1. 仅新增状态，不会有问题
2. 若需要删除某状态A，则将其设为隐藏状态，并将所有目的状态为A的流转，改为其它目的状态。
