### ISSUE TITLE
关于工单定制流程状态定制流程的改进建议

### ISSUE THREAD

**Issue by cpu8802667** [blackholll/loonflow#79]
最近有一个开源定制流程的组件https://gitee.com/xiaoka2017/easy-flow，可以做拖拽生成工单流程，这个功能是否能集成到现有loonflow的状态定制页面。抱歉我实在是不会贴图，您直接看那个链接吧。

**Comment by blackholll** [comment]
拖拽生成工作流 这个优先级比较低，原因有二：
1.完全拖拽只能完成比较简单的工作流的配置，复杂点的配置如添加定制相关的 添加标签、添加选择类型字段的可选项目等无法直接拖拽生成，就算支持，操作起来也不比目前modal中填写方便
2.拖拽生成工作流面向应该应该小白用户。如商业化可能会优先考虑这样的需求
所以loonflow短期内不会支持，至少1.x版本不会支持。2.x时可能会考虑。 当然如果有人有意愿提交pr来支持的话，我会非常感谢

**Comment by blackholll** [comment]
"是否可以先实现一个“工作流复制”的功能，作为临时解决方案？"

复制的话， 需要之前对接的 调用方前端有些地方需要修改，因为workflow_id变了，  创建工单时的 transition_id也变了
