### ISSUE TITLE
custom field 支持附件类型

### ISSUE THREAD

**Issue by cdz620** [blackholll/loonflow#8]
## 场景

工单应用场景中，经常需要上传一些附件，就像jira。上传附件是工单共有的功能。

## 实现方案

- custom field 增加支持附件类型： FIELD_TYPE_ATTACHMENT = 80
- 调用方负责上件的文件的存储， loonflow只保存路径
- 代码中对FIELD_TYPE_ATTACHMENT的处理与富文本一致，有多个附件时，用逗号区分。

**Comment by blackholll** [comment]
v0.2版本已经支持，目前代码在develop分支

**Comment by blackholll** [comment]
v0.2版本已经发布
