### ISSUE TITLE
> > 建议新增“撤销工单”功能：工单创建人可在任意允许撤销的状态撤销工单。——v1.x考虑支持

### ISSUE THREAD

**Issue by children1987** [blackholll/loonflow#80]
> > 建议新增“撤销工单”功能：工单创建人可在任意允许撤销的状态撤销工单。
> > 具体的：
> > 
> > 1. 状态 新增 “是否可撤销” 属性，默认“是”
> > 2. 工单创建人点“撤销”后，工单流转到“初始状态”
> 
> 初始状态是工单还没创建时候的状态，所以不可以回退到初始状态的。 目前我公司在用版本，有实现一个功能: 状态配置时支持配置一个标签，工单创建人可以在配置了标签的状态下强制关闭工单。如果要做撤回的话也可以这个思路， 在标签中注明撤回到哪个状态(你需要建个如”发起人-编辑中状态“)

当然 这个是可以做成通用功能的，1.x中会后续考虑支持下

_Originally posted by @blackholll in https://github.com/blackholll/loonflow/issues/67#issuecomment-597116559_

**Comment by children1987** [comment]
如果我们贡献代码的话，是合入v1.0.0 分支吗？

**Comment by blackholll** [comment]
可以的你fork一份 1.0.0分支的代码，改完提pr.   改之前和我确认下方案

**Comment by children1987** [comment]
ok

**Comment by children1987** [comment]
ok




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JD Godchaux"<notifications@github.com&gt;; 
发送时间: 2020年3月11日(星期三) 下午2:55
收件人: "blackholll/loonflow"<loonflow@noreply.github.com&gt;; 
抄送: "Zhou Zhipeng"<39188043@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [blackholll/loonflow] &gt; &gt; 建议新增“撤销工单”功能：工单创建人可在任意允许撤销的状态撤销工单。——v1.x考虑支持 (#80)




可以的你fork一份 1.0.0分支的代码，改完提pr.   改之前和我确认下方案

**Comment by blackholll** [comment]
已经支持   [r1.0.0beta](https://github.com/blackholll/loonflow/releases/tag/r1.0.0beta)
