### ISSUE TITLE
建立 工作流状态时，参与人类型为部门时，是否代表这个部门所有的人都能处理？

### ISSUE THREAD

**Issue by winvip8** [blackholll/loonflow#81]
处理人类型及处理人
    3.部门
当选择类型为部门时，处理人输入框中请填写对应的部门的id(loonflow部门表中的主键id)

**Comment by children1987** [comment]
![image](https://user-images.githubusercontent.com/9018733/76402208-0d855780-63be-11ea-88f8-eb39a02e162b.png)
如图，有几种选择
