### ISSUE TITLE
请问两级部门审批（工单创建人->1级领导->2级领导）这种流程怎么设定？

### ISSUE THREAD

**Issue by winvip8** [blackholll/loonflow#82]
部级（2级领导）
    |——科级 （1级领导）
                   |——发起人

**Comment by blackholll** [comment]
目前loonflow的处理人类型有变量， 变量支持的类型有工单创建人、工单创建人leader 你可以新增一个变量类型。 涉及改动:   service/ticket/ticket_base_service.py中的  get_ticket_state_participant_info方法

**Comment by winvip8** [comment]
新添加了一种变量类型：创建人的上两级领导
在 ticket_base_service文件增加了对这种变量类型的判断。
![image](https://user-images.githubusercontent.com/10652628/76737123-32554280-67a3-11ea-8f6b-530529348181.png)
但在下图显示 未能显示 新加要的变量内容，请问还有什么地方要修改的？
![image](https://user-images.githubusercontent.com/10652628/76737360-97a93380-67a3-11ea-93e4-065bbfced522.png)

**Comment by winvip8** [comment]
没图的

**Comment by winvip8** [comment]
![image](https://user-images.githubusercontent.com/10652628/76740166-667f3200-67a8-11ea-9ee9-6a51b509c4d7.png)
还有这个文件要改

**Comment by children1987** [comment]
其实这是个挺常见的需求。 @blackholll 考虑下是否计划直接支持

**Comment by blackholll** [comment]
可以吧， 不过到时候是不是又有人要支持三级tl审批 😂

**Comment by winvip8** [comment]
那就做到4 -5级

**Comment by children1987** [comment]
> 那就做到4 -5级

这是个悖论，那6级的需求来了怎么办？
我看钉钉目前是支持到20级主管 -_-

**Comment by blackholll** [comment]
群里提的 “creator_tlN” 确实是个办法😄。 mark一下

**Comment by winvip8** [comment]
workflow_state_service：
           
 elif participant_name == 'creator_tl2':
                participant_alias = '工单创建人的2级tl'

**Comment by blackholll** [comment]
1.1版本中支持
