### ISSUE TITLE
关于支持一个用户属于多个部门的讨论

### ISSUE THREAD

**Issue by children1987** [blackholll/loonflow#83]
> > > > @blackholll 请问下是否有计划支持一个用户属于多个部门的场景？当前是只支持一个部门。
> > > 
> > > 
> > > 目前我见到的 一个用户属于多个部门的都是不合理的场景。你这是怎样的场景？
> > 
> > 
> > 某个员工，由于工作量不饱满、处于交接期、负责2大部门等原因，一个人被复用负责2份工作，即属于2个部门
> 
> 目前大多数系统的用户部门管理里面一般都是不支持一个人属于多个部门的。你这个负责两个部门的工作 是否应该是这两个部门的leader? 如果是这样的话 就给两个部门的leader都配置为他。
> 如果实在就是要支持一个人多个部门会有个麻烦的地方：
> 一个人属于多个部门的话 他提交的工单需要部门tl审批的话，应该哪个部门的tl来审批呢

当前，钉钉是支持一个人属于多个部门的。
当一个人属于多个部门，需要tl审批的话，表单最后会自动增加一个必填项：所在部门。

_Originally posted by @children1987 in https://github.com/blackholll/loonflow/issues/67#issuecomment-598012496_

我单独启了个issue，抛砖引玉，希望大家共同输出良策。

**Comment by blackholll** [comment]
自动增加一个必填项：所在部门 。 这个是配置工作流的时候？   配置工作流的时候并不知道后续创建工单的用户属于哪个部门，如何选择所在部门

**Comment by children1987** [comment]
https://wj.qq.com/s2/5651297/0ef0/

**Comment by children1987** [comment]
> 自动增加一个必填项：所在部门 。 这个是配置工作流的时候？ 配置工作流的时候并不知道后续创建工单的用户属于哪个部门，如何选择所在部门

不是。与创建无关。在工单创建页，符合如下几个条件时，自动增加一个必填项：所在部门：
1. 当前用户（即，工单创建者）属于多个部门；
2. 工作流存在按部门找处理人的状态。

**Comment by blackholll** [comment]
这个 创建的时候选择自己所在部门， 感觉不是很好啊。  
这样如何？ 如果创建人属于多个部门，那么遇到部门tl审批的情况就多个部门的tl共同审批

**Comment by children1987** [comment]
我理解，一个工单少不了要有一个“发起者部门”属性，因为，有可能，某个流转，需要根据“发起者部门”进入不同的目的状态。

**Comment by blackholll** [comment]
> 我理解，一个工单少不了要有一个“发起者部门”属性，因为，有可能，某个流转，需要根据“发起者部门”进入不同的目的状态。
这样处理感觉好奇怪， 有别的方案么

**Comment by children1987** [comment]
远程视频沟通结论：计划 v1.1.x 实现
