### ISSUE TITLE
请问建好的工作流，没能显示出流程图出来的？

### ISSUE THREAD

**Issue by winvip8** [blackholll/loonflow#84]
![image](https://user-images.githubusercontent.com/10652628/76593302-e7cc8f80-6530-11ea-9eae-27d453488261.png)
已授与权限
![image](https://user-images.githubusercontent.com/10652628/76593342-0b8fd580-6531-11ea-8117-95195aecb82c.png)

**Comment by blackholll** [comment]
在工作流列表界面中添加工作流，只是配置工作流的基本信息。 添加完成后你需要点击这条记录右侧的”配置“按钮， 进入工作流的配置界面。 
一个工作流是由”自定义字段“（可以没有）、状态、流转几个部分组成的。你流程图里面没有信息，应该是连状态都没有添加过

**Comment by winvip8** [comment]
已经添加了
![image](https://user-images.githubusercontent.com/10652628/76593851-637b0c00-6532-11ea-8bc7-ae0f20f78235.png)
![image](https://user-images.githubusercontent.com/10652628/76593885-7d1c5380-6532-11ea-8d4f-88e49b859e39.png)
![image](https://user-images.githubusercontent.com/10652628/76593917-93c2aa80-6532-11ea-8b87-a88a2034b569.png)

**Comment by winvip8** [comment]
![image](https://user-images.githubusercontent.com/10652628/76594312-c28d5080-6533-11ea-8e40-3ffb4649ae47.png)

**Comment by blackholll** [comment]
看下浏览器控制台看下是否有报错。 这个页面会引入cdn的静态文件，你是否在内部部署无法访问cdn资源<script src="https://d3js.org/d3.v4.min.js" charset="utf-8"></script>

**Comment by winvip8** [comment]
![image](https://user-images.githubusercontent.com/10652628/76594835-15b3d300-6535-11ea-81c0-1166256f1815.png)
![image](https://user-images.githubusercontent.com/10652628/76594874-31b77480-6535-11ea-85ff-c9e50dd25035.png)

可以加载到这个JS的，没有问题。

**Comment by blackholll** [comment]
看下这个界面的ajax请求    以及每个请求返回的内容是否有问题

**Comment by winvip8** [comment]
![image](https://user-images.githubusercontent.com/10652628/76595963-f66a7500-6537-11ea-81c6-f27ad9b077a9.png)
有一个错误
render.js:98 Uncaught TypeError: Cannot set property 'label' of undefined
    at render.js:98
    at Array.forEach (<anonymous>)
    at preProcessGraph (render.js:96)
    at fn (render.js:19)
    at Object.success (3:154)
    at u (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at k (jquery.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2)

**Comment by winvip8** [comment]
把所有流转删除重建。一步一步调查

**Comment by blackholll** [comment]
怀疑是数据有问题 导致渲染图片出错。 贴下这个页面每个ajax get请求 返回的内容。

**Comment by winvip8** [comment]
![image](https://user-images.githubusercontent.com/10652628/76728051-8e629b80-6790-11ea-8a52-0bfcf4a8895a.png)
问题找到原因，条件表达式写错了。漏写了红色部分

**Comment by blackholll** [comment]
多个条件用一个transtions哦。 比如在一个流转里面配置[{"expression":"{cost}>1000", "target_state_id":18},{"expression":"{cost}<1000", "target_state_id":17}]，而不是两个流转分别是[{"expression":"{cost}>1000", "target_state_id":18}], [{"expression":"{cost}<1000", "target_state_id":17}]

**Comment by winvip8** [comment]
好的。
