### ISSUE TITLE
是否有计划支持抄送？

### ISSUE THREAD

**Issue by children1987** [blackholll/loonflow#89]
当前是否是以如下2种方式代替抄送：
1. 流转hook自行实现；
2. 被抄送人独立安排在一个状态，并设置一个较短的超时时间。

**Comment by blackholll** [comment]
对齐一下“抄送”的概念。  我理解的抄送是： 提交工单的时候选择一个抄送人， 这个人不在流程审批节点里面。 在工单状态发生变化的时候 都会通知这个人，且这个人可以查看这个工单的详情。 是否有别的需求？如只是需要在创建的时候或者结束的时候收到通知？

**Comment by children1987** [comment]
可能是惯性思维吧，我理解钉钉当前的“抄送”功能是合理且灵活的。
它允许在任何2个状态之间，插入1~n个抄送节点。只有到了这个节点，才会抄送。
顺便提一下，关于谁可以只读打开工单的问题：我认为，可以不限制。这样，任何人都可以直接打开“转发”过来的工单。
而被抄送者，一方面是获取了一个通知，另一方面，能够无需别人转发就能在自己的抄送列表中看到这个工单。

**Comment by blackholll** [comment]
钉钉的抄送是在工作流配置的时候就 添加好了抄送对象， 然后到达这个节点发送通知给被抄送的人么

**Comment by children1987** [comment]
是的。可以配置为固定 或 由发起人自己选。https://oa.dingtalk.com/ 建议登上去看下，我已给你在测试企业加了权限。

**Comment by children1987** [comment]
补充下：钉钉当前的处理是：前期被抄送到的用户，后续工单做了任何同意、评论操作后，都会收到通知消息。这个我是觉得没太大必要。我认为只是到抄送这一步时，发通知消息就够了。

**Comment by blackholll** [comment]
我在之前的一家公司有做过抄送的功能， 当工单创建的时候会通知， 然后工单结束的时候会通知，结束的时候会将历史处理记录也展示出来通知(html格式的邮件)。   这个抄送的什么时候通知  不同公司可能有不同需求，不太好统一满足

**Comment by children1987** [comment]
是的。不仅不同公司会有不同要求，即使同一公司内，不同工作流的要求也可能不同。所以需要支持灵活配置：可以允许在任意工作流流转中，配置抄送人，抄送触发的时机即为流转触发的时机。

**Comment by children1987** [comment]
钉钉审批目前已经支持上述抄送，且支持工单参与人在工单创建(创建时由创建人选择)或流转中设置抄送人(取表单字段的值)

**Comment by children1987** [comment]
远程视频沟通结论：此功能暂不合入主干。
我们将在应用方系统实现此功能。
