### ISSUE TITLE
sn 支持配置前缀

### ISSUE THREAD

**Issue by cdz620** [blackholll/loonflow#9]
sn 支持配置前缀

**Comment by blackholll** [comment]
v0.2版本已经支持，目前代码在develop分支

**Comment by blackholll** [comment]
v0.2版本已经发布

**Comment by yslhzj** [comment]
在管理后面 权限下配置
![image](https://user-images.githubusercontent.com/29890756/59415880-f39af200-8df6-11e9-8cd3-0d9a48a6d0e9.png)
