### ISSUE TITLE
是否有支持工单评论的计划？

### ISSUE THREAD

**Issue by children1987** [blackholll/loonflow#90]
工单评论功能：任何能看到工单的人，都可以发文本、图片，作为评论。评论的内容，作为一条工单log，与其它的处理一起，按时间序显示。

**Comment by blackholll** [comment]
目前有评论的接口，评论历史会在flowlog中查看到，不过只支持文本。  评论支持富文本这个需求不大普遍吧

**Comment by children1987** [comment]
从我们实际使用情况来看，评论中发图片，确实是一个比较普遍的需求。因为有时候，确实文字很难说清楚，相反，截图，再框一下，问题直接就讲明白了。
BTY，富文本评论倒是真没啥必要。

**Comment by blackholll** [comment]
附件可以掉用方后端自己处理，然后吧附件的路径提交给suggestion字段就好了，显示的时候 调用方前端处理好附件的显示

**Comment by children1987** [comment]
"suggestion" : {
    "text": "评论文本",
    "imgs":["url1", "url2"]
}
类似这样？

**Comment by blackholll** [comment]
suggestion保存json格式，里面包含处理意见和图片地址， 和调用方约定好特定的格式就可以了

**Comment by children1987** [comment]
ok  3Q!
