### ISSUE TITLE
工单到达leader审批,leader审批将工单派发给多人,多人派发主动接单在loonflow里面是怎么配置的

### ISSUE THREAD

**Issue by zengshuaishuai** [blackholll/loonflow#91]
如果处理人接单后 发现处理不了 ，这个时候工单可以怎么处理

**Comment by blackholll** [comment]
1.你需要改成多选用户名类型， 然后前端根据这个类型 显示一个选择用户的下拉框，支持多选。
2.状态设置里面设置为“主动接单”， 然后只要实际的处理人大于1，那么获取工单可以做的操作的接口 就会返回 接单的操作。 具体看下接单接口。
