### ISSUE TITLE
通过第三方平台的脚本调用创建工单的接口，loonflow能否支持直接将脚本创建的工单派发给多人

### ISSUE THREAD

**Issue by zengshuaishuai** [blackholll/loonflow#92]

**Comment by blackholll** [comment]
1.工作流设置里面第二个状态的处理人设置为多人，那么工单创建完成后就是多人处理了
2.新增一个自定义字段，字段类型是多选用户。  状态的处理人设置为这个工单字段， 创建的时候指定这个字段的值(uername逗号隔开，如果zhangsan,lisi)。 注意初始状态需要设置这个字段为必填或者可选(不然loonflow保存这个字段的值)
