### ISSUE TITLE
关于调用方的用户信息和loonflow数据库同步的问题

### ISSUE THREAD

**Issue by zengshuaishuai** [blackholll/loonflow#93]
我用的是workflowdemo作为第三方调用方，用户信息怎么同步到loonflow，目前我的方案是 在workflowdemo后台创建用户的账户和密码，然后通过触发器将用户名同步到loonflow数据库，再去loonflow里面给用户分配部门和部门领导

**Comment by blackholll** [comment]
调用方可以自己手动管理用户，也可以对接公司的ldap(如果公司有ldap的话)， 也可以不保存用户信息，直接调用公司内部的用户体系完成登录、获取用户信息等。
loonflow中的用户及部门信息可以通过定时任务脚本、触发器(如从oa的用户部门表设置触发器，不过不建议用触发器，dba估计也不会允许你用)，nsq消息（如果你们公司有消息的基础设置，监听好oa系统里面用户部门变动消息，然后修改loonflow中的用户部门记录，建议用此方法），定时任务获取公司oa等管理组织架构信息的系统里面的用户信息操作loonflow的数据库完成用户同步。loonflow中只需要管理员和工单管理员登录管理后台，其他用户在插入数据的时候密码随便设置(也就是不允许登录系统)
