### ISSUE TITLE
loonflow的权限部分是怎么设计的

### ISSUE THREAD

**Issue by zengshuaishuai** [blackholll/loonflow#94]

**Comment by blackholll** [comment]
工单的处理权限： 根据工单的当前处理人来确定是否有处理权限
工单的查看权限:  如何对应工作流设置启用可查看权限校验，那么需要工单关系人(创建人、曾经需要他处理的人) 有权限查看工单，其他人无权限查看工单(表现形式是获取工单详情接口会返回无权限查看详情)
管理后台的权限: 1.0之前管理后台只分为超级管理员 和非管理员(无法登录管理后台，无配置工作流的权限)   1.0开始管理后台分为超级管理员和工作流管理员，工作流管理员可以创建工作流，编辑自己有权限的工作流(自己创建的+工作流设置里面被设置为管理员的工作流)，总览中工单统计只可以查看自己有权限的类型的工单数据， 工单干预中只可以干预自己作为工作流管理员的工单。 超级管理员可以编辑所有的工作流、编辑自定义通知、编辑执行脚本等管理后台的所有功能

**Comment by children1987** [comment]
工单的查看权限 —— 这块目前 loonflow 是不关心的吧，具体还是落在第三方应用自己决定的吧？我们实际的使用场景，是希望工单只要被转发，接受者就能看到。只是不能操作而已。换言之，只要是登录用户，能拿到第三方应用的工单链接，就能查看工单。

**Comment by blackholll** [comment]
工作配置的时候 有个工单查看权限校验。 不想控制的话就不开启这个选项好了

**Comment by children1987** [comment]
ok. 3Q! 我看到了
