### ISSUE TITLE
loonflow里面是否可以设置观察者角色

### ISSUE THREAD

**Issue by zengshuaishuai** [blackholll/loonflow#97]
我所说的观察者相当于领导，和管理员是区分开的，管理员对工单有所有的操作权限，而观察者(领导)对所有工单只有查看权限，观察者不作为工单的实际参与人

**Comment by blackholll** [comment]
领导的话 为何要限制他没有干预权限呢？  领导一般也不会干预， 直接给他管理员，让他看有什么问题么

**Comment by zengshuaishuai** [comment]
我这边是三种角色，领导(只能查看所有工单)，管理员(可以干预工单和编辑工作流),工程师(创建工单和查看与自己相关的工单)

**Comment by blackholll** [comment]
那就自己定制下吧， 我认为这个不是通用需求
