### ISSUE TITLE
希望可以新增“退回”功能api。

### ISSUE THREAD

**Issue by children1987** [blackholll/loonflow#98]
背景：
由于业务决定，我们第三方应用的“退回”按钮具有普遍存在性，所以，不希望在loonflow中配置一堆名叫“退回”的流转。
我们第三方前端判断满足如下条件时，呈现"退回"按钮：当前用户在当前工单状态的participant中。
点击“退回”后，我们会让用户选择回退的目的状态。做如下操作：
（1）新增一个ticketflowlog
（2）调用 api/v1.0/tickets/{ticket_id}/state ，使 工单.state_id = 用户选择的状态
（3）工单.act_state_id = 2被退回（此条，我们需要一个api）

**Comment by blackholll** [comment]
这样有安全风险的。  比如流程是: 发起人新建中-tl审批中-总监审批中-授权任务执行中-结束。 那么tl审批中状态可以选择退回，然后目标状态选择“授权任务执行中” 那么就跳过了总监审批的状态了。 可能你会加个限制比如目标状态id或者目标状态的顺序id比当前状态小，但是实际情况比如流程图复杂的情况（存在网状的情况）下这个限制就不一定合理了

**Comment by children1987** [comment]
确实需要加个限制，但不是“目标状态id或顺序id比当前状态小”，而是，只能选择已通过的状态。—— 这样ok吗？

**Comment by blackholll** [comment]
已经通过的状态也会有问题。 比如流程是: 发起人新建中-tl审批中-总监审批中-安全审核中-授权任务执行中-结束。 在安全审核的时候总结拒绝了，回到发起人新建中， 然后发起人新建的时候修改了很多信息(这些信息修改后理应需要早tl再次审批的)， 通过你的这种方案直接修改状态到总监审批中(因为总监审批中之前是同意过的)，这样就跳过了tl审批了

**Comment by children1987** [comment]
通过你的这种方案直接修改状态到总监审批中(因为总监审批中之前是同意过的)，这样就跳过了tl审批了  ——  不会啊。我的方案中，直接修改状态(state_id 和 act_state_id)永远都是由后往前改。至于由前到后，永远是不能跳的，永远是必须一步一步走的，无论这一步先前是否被同意过。

**Comment by children1987** [comment]
简单总结下就是：
状态向终结方向推进：只能一步一步按流转走；
状态向起始方向退回：可以由退回人指定退回的目的状态(限定范围：已完成的状态)

**Comment by blackholll** [comment]
已完成的状态如何界定呢？  我上面的例子， 总监审批中 这个状态在第一轮顺序流转的时候经历过的(flow_log中存在的)。 我理解的你的是应该是第二轮顺序流转的时候要有经历过的状态，但是这个判断逻辑好像不是太好写

**Comment by children1987** [comment]
不，第二轮流转的逻辑很简单。就完全当做是在进行第一轮流转就够了。唯一区别是workflowlog的靠前部分多了几条记录而已。

**Comment by children1987** [comment]
已完成的状态如何界定呢？—— 这个应该可以做到吧？工单详情页的step进度图不是已经标了哪些节点是已完成的了么？

**Comment by blackholll** [comment]
flowstep中是有每个状态经历的所有操作。  比如第一轮总监审批中有操作，第二轮还没到达总监审批中。 所以你要根据每个状态下操作次数来定么？如tl审批中这个状态下有2条记录， 总监审批中这个状态下只有一次记录，来认定总监审批中在第二轮流转中还没完成么

**Comment by children1987** [comment]
哦，我貌似明白你的顾虑了，我再想一下。现在的主要问题就是无法判断“退回”时可以回到哪些状态，对吧？

**Comment by children1987** [comment]
可否这样，整个换一条思路：
1. 新增支持“退回”功能，类似“撤回”，暴露退回api，并在工作流状态页中可配置“是否可退回”；
2. 工单新增属性“已完成状态”，当工单参与者执行了“可执行的操作”后，把此流转的源状态append到“已完成状态”。用户点“退回”按钮后，呈现“已完成状态”，让用户选择退回的目的状态。
3. 同时满足如下条件时，显示“退回”按钮：
(1)工单当前状态.是否可退回 == 是；
(2)当前用户 in 工单.participant。

**Comment by blackholll** [comment]
1.0.0正式版中已支持。 见文档中”撤回工单“

**Comment by blackholll** [comment]
> 1.0.0正式版中已支持。 见文档中”撤回工单“

搞错了，支持了撤回 不是退回。。。。。

**Comment by children1987** [comment]
> 可否这样，整个换一条思路：
> 
> 1. 新增支持“退回”功能，类似“撤回”，暴露退回api，并在工作流状态页中可配置“是否可退回”；
> 2. 工单新增属性“已完成状态”，当工单参与者执行了“可执行的操作”后，把此流转的源状态append到“已完成状态”。用户点“退回”按钮后，呈现“已完成状态”，让用户选择退回的目的状态。退回api响应后，在“已完成状态”中，把用户选择的退回目的状态之后的状态干掉。
> 3. 同时满足如下条件时，显示“退回”按钮：
>    (1)工单当前状态.是否可退回 == 是；
>    (2)当前用户 in 工单.participant。

这个是否可在v1.0.1中实现？允许合入的话，我可以提pr，或者我们就只能自己定制loonflow了

**Comment by blackholll** [comment]
"把用户选择的退回目的状态之后的状态干掉"  这个状态指的啥？ 清空“已完成状态”么  还是根据状态的顺序id吧大于目标状态顺序id的状态清掉？  这两种都不合适啊

**Comment by children1987** [comment]
是清空“已完成状态”。这个为什么不合适？这个状态是为了这个功能新增的，不显示在页面上，只是每次用户选退回目的状态时用到。

**Comment by blackholll** [comment]
比如流程是: 发起人新建中-tl审批中-总监审批中-授权任务执行中-结束。 总监审批的时候将工单退回到tl审批中，你上面的逻辑清空历史状态，那么tl审批中的状态如果想将工单退回到发起人新建中呢？因为被清空了 选择范围为空了

**Comment by children1987** [comment]
“总监审批的时候将工单退回到tl审批中，你上面的逻辑清空历史状态”  ——  这里不对。按我说的逻辑，这时不是“清空历史状态”，而是：在“已完成状态”中，删除“tl审批中”这一项

**Comment by children1987** [comment]
比如流程是: 发起人新建中-tl审批中-总监审批中-总经理审批中-结束。
如果总经理退回到了“tl审批中”，则在“已完成状态”中，删除 “总监审批中” 和 “tl审批中”这2项。
总之：退回到哪一步，就在“已完成状态”list中删除这一项级以后得所有项。

**Comment by blackholll** [comment]
对于流程是：流程是: 发起人新建中-tl审批中-二级领导审批中-三级领导审批中-总监审批中-授权任务执行中-结束。总监退回到tl审批中，  在已完成状态中删除’tl审批‘和’总监审批‘。 那么tl审批中这个状态就可以用退回的方式将工单状态直接到三级领导审批中，从而跳过了“二级领导审批”这个环节

**Comment by children1987** [comment]
对于流程是： 发起人新建中-tl审批中-二级领导审批中-三级领导审批中-总监审批中-授权任务执行中-结束。总监退回到tl审批中， 则：
在已完成状态中删除“三级领导审批中”、“二级领导审批中”、“tl审批中”。
注意：因为退到“tl审批中”，所以，要删“tl审批中”及其后所有。

**Comment by blackholll** [comment]
要删“tl审批中”及其后所有. 其后  根据什么来呢？ 根据状态的顺序id?   还是说根据“已完成状态”中历史的追加记录里面的顺序？   因为流程图是环状的，不能保证 每次历史处理状态的顺序是一致的(受条件流转、不同transiton的目标地址影响)。 也就是说有可能第一次流转的顺序是A-B-C-D-E. 第二次的流转顺序是A-B-D-E-C， 所以根据历史记录的顺序是不可靠的

**Comment by children1987** [comment]
要删“tl审批中”及其后所有. 其后 根据什么来呢？——工单新增的字段“已完成状态”是一个列表（具体存db可以用逗号分隔的字符串，也可用json）。 每完成一个流转后，对这个列表append(流转.源状态)。这样，就不会乱序了

**Comment by children1987** [comment]
远程视频沟通结论：此功能暂不合入主干。
