### ISSUE TITLE
请教下，TicketCustomField模型中，设计了多个冗余字段，包含 char_value、int_value等，目的是？

### ISSUE THREAD

**Issue by children1987** [blackholll/loonflow#99]
为什么不直接统一存一个char_value？

**Comment by blackholll** [comment]
为了可以直接查询就可以获取对应的值，而不需要获取到值后再根据类型进行类型转换。 另外公用一个字段只能是字符串类型的，如果要针对自定义字段的值做统计分析查询的时候性能就非常差了

**Comment by children1987** [comment]
懂了。谢谢！



---原始邮件---
发件人: "blackholll"<notifications@github.com&gt;
发送时间: 2020年3月20日(周五) 晚上9:17
收件人: "blackholll/loonflow"<loonflow@noreply.github.com&gt;;
抄送: "逆寒刀"<39188043@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [blackholll/loonflow] 请教下，TicketCustomField模型中，设计了多个冗余字段，包含 char_value、int_value等，目的是？ (#99)




 
为了可以直接查询就可以获取对应的值，而不需要获取到值后再根据类型进行类型转换。 另外公用一个字段只能是字符串类型的，如果要针对自定义字段的值做统计分析查询的时候性能就非常差了
